### PR TITLE
metrics: Add network memory PSS consumption

### LINKED ISSUE #604: Add network memory PSS consumption test
Measures network PSS memory consumption using smem tool while running a network workload with nuttcp.

### PR DESCRIPTION
**Pull request by GabyCT**
Measures network PSS memory consumption using smem tool while
running a network workload with nuttcp.

Fixes #604

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@klynnrif could you please check this?

**Comment by GabyCT** [comment]
@intelkevinputnam could you please take a look?

**Comment by GabyCT** [comment]
@intelkevinputnam changes applied

**Comment by GabyCT** [comment]
@intelkevinputnam changes applied

**Comment by GabyCT** [comment]
@intelkevinputnam done :) thanks

**Comment by amshinde** [comment]
Will wait for @grahamwhaley if he has any comments on this PR.

**Comment by GabyCT** [comment]
@grahamwhaley thanks for the feedback, changes applied

**Comment by amshinde** [comment]
@grahamwhaley PTAL

**Comment by chavafg** [comment]
lgtm

**Comment by devimc** [comment]
lgtm

**Pull request merged**
