### PR TITLE
ci: Fixes and improvements to the vfio job

### LINKED ISSUE #3263: setup: ninja-build package should be installed on Ubuntu for QEMU 5.2
The `.ci/install_qemu.sh`  script has a conditional where if
 1. `AGENT_INIT=false` then QEMU is built with statically linking. It uses the scripts in github.com/kata-containers/kata-containers/tools/packaging which are going to build it inside a container, so any build dependencies are already handled. 
 1. `AGENT_INIT=true` then QEMU is built with dynamically linking. Here it doesn't use the packaging scripts, and QEMU is built in the local host. Meaning that all build dependencies should be installed on the host.

The QEMU 5.2 requires the `ninja-build` package for Ubuntu. Thus, the CI setup script should be changed to handle the case 2) above.

Note: theoretically all setup scripts should be changed to get ninja-build installed. But in practice only one CI job test the `AGENT_INIT=true` and that is in Ubuntu.

### PR DESCRIPTION
**Pull request by wainersm**
The main goal of this PR was to fix the failure on vfio job due to missing ninja-build package on the ubuntu host. Then I noticed that the script was using code from the master branch. I changed it but that caused more failures, and more fixes were needed. Along the way I implemented changes to the vfio test script to increase its debuggability, this comes as a bonus commit.

### CODE REVIEW

**Comment by wainersm** [comment]
This PR fixes the problem of QEMU not being built, however the vfio test failed with:

```
15:12:42 + sudo -E kubectl wait --for=condition=Ready pod vfio
15:13:12 error: timed out waiting for the condition on pods/vfio
15:13:12 Failed at 123: sudo -E kubectl wait --for=condition=Ready pod "${pod_name}"
15:13:12 ++ handle_error 123
15:13:12 ++ local exit_code=1
15:13:12 ++ local line_number=123
15:13:12 ++ echo 'Failed at 123: sudo -E kubectl wait --for=condition=Ready pod "${pod_name}"'
```

**Review by chavafg — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
