### PR TITLE
# Kata Containers 1.13.0-alpha1

### PR DESCRIPTION
**Pull request by bergwolf**
- metrics: Define new memory footprint value for kata 1.x
- cri-o: Stop using devicemapper with CRI-O
- ci: Disable the `CPU constraints` docker tests for firecracker
- test: docker: Adjust the `cpuset-cpus test`
- ci: Move to stable virtiofs
- static_check: bypass license check for kernel configs

22c72e8 metrics: Define new memory footprint value for kata 1.x
cde3c0c cri-o: Stop using devicemapper with CRI-O
3d4a599 ci: Disable the `CPU constraints` docker tests for firecracker
3682e66 test: docker: Adjust the `cpuset-cpus test`
efb04dd metrics: virtiofs: Relax minval for mean boot time
1231e4a test: docker: Handle qemu for KATA_HYPERVISOR
399dd69 ci: virtiofs: Use default path for experimental binaries
20d7ca3 ci: Create stable VIRTIOFS job
ed81178 static_check: bypass license check for kernel configs

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Review by egernst — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Comment by GabyCT** [comment]
@jodh-intel the label Move issues to "In progress" in backlog project when referenced by a PR is not working properly

**Pull request merged**
