### PR TITLE
integration/pmem: don't build image from dockerhub

### LINKED ISSUE #3832: pmem: build-images: too many requests: You have reached your pull rate limit
```
9:28:32 Sending build context to Docker daemon  62.01MB
19:28:33 Step 1/48 : ARG LINUX_BASE=debian:buster-slim
19:28:33 Step 2/48 : FROM ${LINUX_BASE} AS build
19:28:33 toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
19:28:35 Makefile:98: recipe for target 'build-image' failed
19:28:35 make[1]: *** [build-image] Error 1
19:28:35 make[1]: Leaving directory '/home/jenkins/workspace/go/src/github.com/kata-containers/tests/pmem-csi'
19:28:35 [pmem_test.sh:77] ERROR: make build-images
```

### PR DESCRIPTION
**Pull request by devimc**
Fix  pull rate limit issue, don't build image from dockerhub

fixes #3832

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by wainersm — APPROVED** [review]
hi @devimc , my only concern is https://github.com/intel/pmem-csi/blob/devel/Dockerfile moving away of *debian:buster-slim* in the future and that breaking the build on our side. But since I know nothing about pmem-csi so I don't know whether the break probability is high or not.

Anyway, this change looks good to me.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @devimc!

Are there other images we're still using from dockerhub?

**Comment by wainersm** [comment]
> lgtm, thanks @devimc!
> 
> Are there other images we're still using from dockerhub?

It seems `integration/containerd/cri/integration-tests.sh` uses images from dockerhub.

**Comment by GabyCT** [comment]
@devimc is this PR will need to be `backport`? in case that yes could you please add the label

**Comment by devimc** [comment]
> hi @devimc , my only concern is https://github.com/intel/pmem-csi/blob/devel/Dockerfile moving away of debian:buster-slim in the future and that breaking the build on our side. But since I know nothing about pmem-csi so I don't know whether the break probability is high or not.

not a problem, @pohly can help us

> It seems integration/containerd/cri/integration-tests.sh uses images from dockerhub.

**Comment by devimc** [comment]
@GabyCT done, I've added backport label

**Comment by devimc** [comment]
my bad, this not needs backport, stable-2.1 has the old pmem test :sweat_smile:

**Comment by fidencio** [comment]
> my bad, this not needs backport, stable-2.1 has the old pmem test

Even better. :-)

**Pull request merged**
