### PR TITLE
ci: Enable complete kubernetes-e2e tests with CRI-O

### PR DESCRIPTION
**Pull request by fidencio**

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]

**Comment by jodh-intel** [comment]
@fidencio - ah - Travis failed as one of your commits ("ci: Enable complete kubernetes-e2e tests with CRI-O") only contains a SoB (missing explanatory text). Please could you tweak, rebase and re-push?

**Comment by fidencio** [comment]
@jodh-intel, I have to rebase and revisit this one. :-)
The problem I faced was that I never ever was able to get a full run completed because of a timeout happening.  It may be something I need to tweak on jenkins side and then I can actually open an issue and have it in a way it can be re-reviewed and hopefully merged.

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Comment by fidencio** [comment]
/cc @kata-containers/cri-o

I think we could have a weekly, if not daily job testing running the k8s-e2e with CRI-O.
The part in jenkins is not enabled yet, but I'd like to ask opinions on this one before someone starts playing with jenkins.

@chavafg, would this be too costly?

@jcvenegas, would you mind to take a look at the changes in the scripts?  :-)

**Comment by jcvenegas** [comment]
@fidencio  daily or every 2 days make sense for me.  I will merge this as the other changes are part of jenkins.

**Pull request merged**
