### PR TITLE
Lint fixes

### LINKED ISSUE #138: Fix lint errors
Fix issues found by `.ci/static-check.sh`.

### PR DESCRIPTION
**Pull request by jodh-intel**
Fix the issues found by `.ci/static-checks.sh` plus skip testing test packages which need special setup.

Fixes #138.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Related: #140.

**Comment by sboeuf** [comment]
LGTM

**Comment by chavafg** [comment]
lgtm

**Comment by GabyCT** [comment]
lgtm

**Pull request merged**
