### PR TITLE
docs: Remove UT advice doc

### PR DESCRIPTION
**Pull request by jodh-intel**
Remove the Unit Test Advice document as it has been moved to
the main rep.

See:

- https://github.com/kata-containers/kata-containers/pull/3100

Fixes: #4211.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by fgiudici — APPROVED** [review]
lgtm, thanks @jodh-intel !

**Comment by jodh-intel** [comment]
@GabyCT - how can I (re-)trigger the "test" CI jobs above?

**Comment by jodh-intel** [comment]
Err, I mean below ;)

**Comment by fidencio** [comment]
So, we have a problem here with the force-skip CI, which I sincerely thought I had solved in the past, but it seems I only did for the `kata-containers` repo :-/

**Pull request merged**
