### PR TITLE
ci: Remove CentOS setup script

### LINKED ISSUE #5041: remove setup_env_centos.sh script

### PR DESCRIPTION
**Pull request by GabyCT**
This PR removes the CentOS setup script as it is not longer being
used in the kata CI and it has been disabled the jenkins jobs
and the baseline due the EOL of CentOS.

Fixes #5041

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by cmaf — APPROVED** [review]

**Review by fidencio — CHANGES_REQUESTED** [review]
@GabyCT, this is used with CentOS Stream, and it works without issues.
Also, I think @wainersm uses this script as part of the OpenShift CI.

**Comment by GabyCT** [comment]
@wainersm are you using this to OpenShift CI?

**Comment by wainersm** [comment]
Hi @GabyCT ! Sorry for taking too long to respond... yes, that script is still used by openshift-ci (see https://github.com/kata-containers/tests/blob/main/.ci/openshift-ci/build_install.sh#L105)

**Pull request closed without merging**
