### PR TITLE
test: Improve stability test

### LINKED ISSUE #609: Docker stability test is failing
Currently we have issues in the CI mainly because the docker stability test is failing. I tried it to run it in an ubuntu machine by itself and is showing me the error that is been seen in our CI.

```
$ export ITERATIONS=2 && export MAX_CONTAINERS=20 && chronic ./soak_parallel_rm.sh
Checking Kata runtime kata-runtime
Start iteration 1 of 2
Running...
Checking 0 containers have all relevant components
Run kata-runtime: nginx:
f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad
Checking 1 containers have all relevant components
Wrong number of qemus running (1 != 0) - stopping
Showing system state:
 --Docker ps--
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS               NAMES
f35f28321624        nginx               "nginx -g 'daemon of…"   3 seconds ago       Up Less than a second   80/tcp              festive_allen
 --kata-runtime list--
ID                                                                 PID         STATUS      BUNDLE                                                                                                                               CREATED                          OWNER
f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad   7253        running     /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad   2018-08-14T20:07:27.998881292Z   #0
 --pgrep kata-proxy--
7207 /usr/libexec/kata-containers/kata-proxy -listen-socket unix:///run/vc/sbs/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/proxy.sock -mux-socket /run/vc/vm/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/kata.sock -sandbox f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad -log debug -agent-logs-socket /run/vc/vm/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/console.sock
 --pgrep kata-shim--
7253 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/proxy.sock -container f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad -exec-id f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad -terminal -log debug
 --pgrep kata-runtime--
 --pgrep qemu--
7193 /usr/local/bin/qemu-system-x86_64 -name sandbox-f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad -uuid 9550ee0c-4466-4c64-b06f-d3513314b4b1 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host,pmu=off -qmp unix:/run/vc/vm/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/qmp.sock,server,nowait -m 2048M,slots=2,maxmem=17065M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2 -device virtio-serial-pci,disable-modern=true,id=serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/usr/share/kata-containers/kata-containers-image_clearlinux_1.2.0_agent_fcfa054a757.img,size=536870912 -device virtio-scsi-pci,id=scsi0,disable-modern=true -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/kata.sock,server,nowait -device virtio-9p-pci,disable-modern=true,fsdev=extra-9p-kataShared,mount_tag=kataShared -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad,security_model=none -netdev tap,id=network-0,vhost=on,vhostfds=3:4:5:6:7:8:9:10,fds=11:12:13:14:15:16:17:18 -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:02,disable-modern=true,mq=on,vectors=18 -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -kernel /usr/share/kata-containers/vmlinuz-4.14.51.7-133.container -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug panic=1 nr_cpus=4 init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket agent.log=debug -smp 1,cores=1,threads=1,sockets=1,maxcpus=4
 --pgrep ksm-throttler--
ERROR: Got 1 errors, quitting
```

### PR DESCRIPTION
**Pull request by GabyCT**
Obtain from the configuration file the name for the hypervisor,
proxy, and shim.

Fixes #609

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @GabyCT - I'm a little confused as your "Fixes" references a closed PR?

**Comment by grahamwhaley** [comment]
@jodh-intel - yeah, that #610 was closed with an interim-fix. This is a better fix. I'm not overly bothered - we could just re-open #610 and have this close it again, or open a new Issue. Former is probably just cleaner and simpler tbh.

Code looks good to me - I don't have time to run it right now. I went to check the CI logs to ensure it had run OK (I'm pretty sure is has, or the CI should/would have failed ;-)) - but, when I go look at the console output for 16.04:
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-16-04-PR/283/console
It tells me the logs are `21,589 KB` - and what I see on the tail end of the logs looks to be kata journald log debug output. I thought that only came out if we failed the CI run??? @chavafg @GabyCT - can you check that for us? Both 'did we actually fail the run' and 'why did we get a full log if we passed?' ?

thx. I'll lgtm when we have some clarity on both the Issue and the logs ;-)

**Comment by chavafg** [comment]
we changed to run the `teardown.sh` script even if the CI job passes. The output seems to be from the `kata-log-parser` tool, which detected some errors, although I am not sure if it is ok to dump all that information.

**Comment by chavafg** [comment]
lgtm

**Comment by GabyCT** [comment]
@jodh-intel sorry, I got confused with the issue number but now I just correct the commit message.

**Comment by GabyCT** [comment]
@grahamwhaley the output of the logs is made by the tool of `kata-log-parser` (maybe @jodh-intel will have more information about this). As far I can see from other PRs this tool is bumping all this information. @jodh-intel is this behaviour expected? thank you

**Comment by amshinde** [comment]
lgtm.

**Pull request merged**
