### PR TITLE
ci: fix broken clean-up work for building up CI on aarch64

### PR DESCRIPTION
**Pull request by Pennyzct**
The former clean-up work was sort of broken by pr#732, here to fix
related codes.

Fixes: #816

Signed-off-by: Penny Zheng penny.zheng@arm.com

### CODE REVIEW

**Comment by marcov** [comment]
lgtm

hi @Pennyzct, I had a quick look at this file, and at line 59 and 69 the `done <<< "${...}"` should be changed to `done`. It would be nice if you fix those too.

**Comment by grahamwhaley** [comment]
Heh, you scared me a little with the title @Pennyzct , as it didn't mention aarch64 - maybe it should say aarch64 rather than baremetal machine :-)
so, yes, lgtm me too - but, please fold in that fix suggestion from @marcov. Thus, I'm going to add a DNM label to give you a chance to do that. thx!

**Comment by Pennyzct** [comment]
Hi~@marcov thanks for the reminding. mixed up with `while loop` and `for loop`. already updated. ptal. ;)

**Comment by Pennyzct** [comment]
Hi~ @grahamwhaley  my bad😝. refined the title and commit info. ptal.

**Comment by marcov** [comment]
Thanks @Pennyzct, it looks good now :)

**Comment by grahamwhaley** [comment]
metrics CI we can probably ignore for the minute - I need to go fixup some of that later.
The F27 CI fail looks odd, but I suspect unrelated, so I'll give it a nudge:
```
Ensure crio service is stopped before running the tests
Ensure docker service is stopped before running the tests
++ time bats --tap ctr.bats
1..32
ok 1 ctr not found correct error message
ok 2 ctr termination reason Completed
ok 3 ctr termination reason Error
ok 4 ctr remove
ok 5 ctr lifecycle
ok 6 ctr logging
not ok 7 ctr logging [tty=true]
# (in test file ctr.bats, line 239)
#   `grep --binary -P "^[^\n]+ stdout F here is some output\x0d$" "$logpath"' failed
# 0
```

I think that is the error - but the 22Mb log file is not helping me root cause ...

**Comment by marcov** [comment]
> I think that is the error - but the 22~Mb~MB log file is not helping me root cause ...

fixed it for you @grahamwhaley  :)

**Comment by chavafg** [comment]
lgtm

I'll go add an ARM job to the tests repo, so we know if we break the scripts.

**Pull request merged**
