### PR TITLE
CC | Revert #5048 as it exposed proxy issues with the kata-deploy builds

### PR DESCRIPTION
**Pull request by fidencio**
This is, unfortunately, needed as `make kata-tarball` (and similars) are
not currently working as expected behind a proxy.

See: https://github.com/kata-containers/kata-containers/issues/5077

Once that one is fixed, we can revert this commit.

### CODE REVIEW

**Comment by cmaf** [comment]
> See: [kata-containers/kata-containers#5077](https://github.com/kata-containers/kata-containers/issues/5077)
> 
> Once that one is fixed, we can revert this commit.

I'm approving, but to clarify, this is a temporary revert of a bunch of commits, which will be un-reverted (re-committed?) after https://github.com/kata-containers/kata-containers/issues/5077?

**Review by cmaf — APPROVED** [review]

**Comment by cmaf** [comment]
also adding DNM temporarily just to make sure the above is what you want

**Comment by fidencio** [comment]
> > See: [kata-containers/kata-containers#5077](https://github.com/kata-containers/kata-containers/issues/5077)
> > Once that one is fixed, we can revert this commit.
> 
> @fidencio I'm approving, but to clarify, this is a temporary revert of a bunch of commits, which will be un-reverted (re-committed?) after [kata-containers/kata-containers#5077](https://github.com/kata-containers/kata-containers/issues/5077)?

That's it, @cmaf.  I just won't have time to work on kata-containers/kata-containers#5077 any tie soon.  So it'll end up being left for October / Novemer.  And we need to revert this one as it exposed the issues reported in kata-containers/kata-containers#5077, making the TDX Ci unusable :-(

**Comment by cmaf** [comment]
@fidencio, understood, thanks for clarifying!

**Comment by fidencio** [comment]
I'm going ahead and merging this one to unblock the rest of the pending CC work.

@wainersm, please, let me know if something else should be addressed as part of a different PR.

**Pull request merged**
