### PR TITLE
CC: Switch SEV operator test to online sev kbc

### PR DESCRIPTION
**Pull request by Alex-Carter01**
Adding kbc url information to config's kernel parameters the at KBS startup.

Related to #5251

Fixes: #5298
Signed-off-by: Alex Carter <Alex.Carter@ibm.com>

### CODE REVIEW

**Comment by fitzthum** [comment]
Oh I guess I made all these changes when we were fixing up the CI for 0.3.0. I think this PR can be closed.

**Comment by wainersm** [comment]
hi @Alex-Carter01 , can we close this?

**Comment by stevenhorsman** [comment]
I'm going to close this, but if it's later decided it is needed then feel free to rebase and re-open

**Pull request closed without merging**
