### PR TITLE
CC | Improve and add the needed scripts and targets for the TDX CIs

### PR DESCRIPTION
**Pull request by fidencio**
ci: Add `install_tvdf.sh`

Installing TDVF as part of the CI is needed in order to test QEMU + TDX
without depending on components internally provided by Intel.

Let's add a script to build and install tdvf into `/usr/share/tdvf`,
which takes advantage of the `cc-tdx-tdvf` target from the
`kata-deploy-binaries.sh`, which is the same one used for building the
binaries for the release, ensuring we're testing exactly what we're
shipping.

Fixes: #5061

---

ci: Add `install_td_shim.sh`

Installing TD-Shim as part of the CI is needed in order to test Cloud
Hypervisor + TDX.

Let's add a script to build and install TD-Shim into
`/usr/share/td-shim`, which takes advantage of the `cc-tdx-td-shim`
target from the `kata-deploy-binaries.sh`, which is the same one used
for building binaries for the release, ensuring we're testing exactly
whata we're shipping

Fixes: #5060

---

ci: Remove CCV0 flag

The CCV0 flag has been used in a few places and can be easily replaced
by the BUILD_KATA_CC flag.

With this in mind, let's drop the CCV0 flag and use the BUILD_KATA_CC
wherever CCV0 was used.

---

ci: Add new flags related to the CC work

The new flags added are useful for when running CC specific CI, and the
ones added are:
TEE_TYPE="tdx|sev", default as ""
KATA_BUILD_KERNEL_TYPE="vanilla|tdx|sev", default as "vanilla"
KATA_BUILD_QEMU_TYPE="vanilla|tdx|sev", default as "vanilla"
KATA_BUILD_CC="yes|no", default as "no"
SKOPEO="yes|no", default as "no"
UMOCI="yes|no", default as "no"

---

ci: Install TDVF when testing TDX using QEMU

As TDVF is needed for running a TDVM when using QEMU, let's make sure
this is installed as part of our CI scripts.

Fixes: #5064

---

ci: Install TD-Shim when testing TDX using Cloud Hypervisor

As TD-Shim is needed for running a TDVM when using Cloud Hypervisor,
let's make sure this is installed as part of our CI scripts.

Fixes: #5059

---

ci: Adjust td-shim location

TD-Shim, as it's been built as part of our CI, will be installed in:
`/usr/share/td-shim/td-shim.bin`.

Let's adjust our scripts to point to that location.

Mind that in the near future we'll be able to drop those changes as
we'll be using a configuration file that's specific for TDX.

---

ci: Adjust TDVF location

TDVF, as it's been built as part of our CI, will be installed in:
`/usr/share/tdvf/`.

Let's adjust our scripts to point to that location.

Mind that in the near future we'll be able to drop those changes as
we'll be using a configuration file that's specific for TDX.

---

ci: Add CC_CRI_CONTAINERD_TDX_QEMU job

Let's add a new test, based on the existing `CC_CRI_CONTAINERD` one,
targetting TDX using QEMU as the Kata Containers VMM.

Fixes: #5062

---

ci: Add CC_CRI_CONTAINERD_TDX_CLOUD_HYPERVISOR job

Let's add a new test, based on the existing `CC_CRI_CONTAINERD` one,
targetting TDX uising Cloud Hypervisor as the Kata Containers VMM.

Fixes: #5063

---

ci: Use specific config for TDX capable VMMs

Let's ensure that, instead of hacking the current
`configuration-$vmm.toml`, we will the specific configuration created
for the $vmm-tdx.

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
@fidencio awesome work! Some changes I wanted to have implemented already, others I made in my PR  (https://github.com/kata-containers/tests/pull/5048). Let's merge this one first, I resolve the conflicts on mine.

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
