### PR TITLE
kernel: Always build the kernel version found locally for CI

### PR DESCRIPTION
**Pull request by ganeshmaharaj**
Fixes: #1441

Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>
(cherry picked from commit 16cf741ca60e3931f0b798ab035336694b76fbc5)

Depends-on: kata-containers/runtime#1578

### CODE REVIEW

**Comment by ganeshmaharaj** [comment]
@chavafg

**Comment by chavafg** [comment]
I see some errors when applying patches to the kernel.

```
08:34:45 INFO: Applying patch /tmp/jenkins/workspace/kata-containers-tests-ubuntu-18-04-PR/go/src/github.com/kata-containers/packaging/kernel/patches/0003-arm64-backport-Arm64-KVM-Dynamic-IPA-and-52bit-IPA-s.patch
08:34:45 patching file Documentation/admin-guide/kernel-parameters.txt
08:34:45 Hunk #1 succeeded at 2637 (offset -121 lines).
08:34:45 patching file arch/arm/include/asm/kvm_arm.h
08:34:45 patching file arch/arm/include/asm/kvm_host.h
08:34:45 Hunk #1 succeeded at 267 (offset -6 lines).
08:34:45 Hunk #2 succeeded at 324 with fuzz 2 (offset -30 lines).
08:34:45 patching file arch/arm/include/asm/kvm_mmu.h
08:34:45 Hunk #1 FAILED at 35.
...
```

**Comment by grahamwhaley** [comment]
@chavafg @ganeshmaharaj - we know (some/all of) the arm patches do not (need to be) apply to the kernel >=v5.x - I wonder if this is somehow building a more recent kernel?

**Comment by ganeshmaharaj** [comment]
Is there a reason the CI is picking up 4.14 kernel for this build? @chavafg 
```
INFO: Current Kernel version 4.14.102.33
INFO: Get packaged kernel version
INFO: Packaged Kernel version 
INFO: Install kernel from sources
INFO: Clone config and patches
INFO: Config version: 33
INFO: Kernel version: 4.14.102
```

**Comment by chavafg** [comment]
versions.yaml on stable-1.5 still specifies kernel 4.14: https://github.com/kata-containers/runtime/blob/stable-1.5/versions.yaml#L136

**Comment by grahamwhaley** [comment]
spinning nemu CI to see if that was transient

**Pull request merged**
