### PR TITLE
integration/docker: Add test to check agent logs if there is no proxy

### LINKED ISSUE #1509: integration/docker: add test to check agent log in the shim journal
agent logs should be in the shim journal when there is no proxy

### PR DESCRIPTION
**Pull request by devimc**
Agent logs should be in the shim journal when `use_vsock` and
shim debug are enabled.

Depends-on: github.com/kata-containers/runtime#1597

fixes #1509

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
adding dnm label until https://github.com/kata-containers/runtime/pull/1597 lands

**Comment by grahamwhaley** [comment]
@chavafg - looks like 1597 has landed - would you like to un-DNM and merge?

**Comment by chavafg** [comment]
yes, lets merge this.

**Pull request merged**
