### PR TITLE
CC | ci: Remove skopeo based tests

### PR DESCRIPTION
**Pull request by stevenhorsman**
Remove the job flags, tests code and fixtures just used by the skopeo variant of CoCo

### CODE REVIEW

**Comment by stevenhorsman** [comment]
`do-not-merge` whilst we are in code freeze

**Review by fidencio — APPROVED** [review]
Finally! :-)

lgtm, thanks @stevenhorsman!

**Review by wainersm — APPROVED** [review]
I'm trying to remember what else should be remove but I can't. So probably this does the job :)

Thanks @stevenhorsman !

**Pull request merged**
