### PR TITLE
Fix yq package download for macOS

### LINKED ISSUE #558: OSX CI failure: missing /Users/travis/gopath/bin/yq
I'm constantly getting this on travis-ci osx build for kata-proxy. E.g., https://travis-ci.org/kata-containers/proxy/jobs/411225835

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     52      0 --:--:-- --:--:-- --:--:--    52
/Users/travis/gopath/bin/yq: line 1: Not: command not found
INFO: Forcing gometalinter version 
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
```

It seems osx does not have the required command?

### PR DESCRIPTION
**Pull request by marcov**
Update yq package download function to support all combinations of {GOOS, GOARCH}.

Fixes #558

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Hi @marcov thanks for that! Did you test on OSX? I think @raravena80 says that the binary on OSX ends up called `yq.v2` for instance...

Hmm, F27 CI failed in a funny way @chavafg 
```
Retrieve repository github.com/kata-containers/agent
.ci/lib.sh: line 29: go: command not found
```

**Comment by chavafg** [comment]
We didn't use `go` in `install_yq` because at the time the function is called, we still don't have it installed. 
Later, you can see in the log file, we install go using `install_go.sh` but we need yq to get the correct version of go that we use.
```
/tmp/install-go-tmp.19HP1PjZje /tmp/jenkins/workspace/kata-containers-tests-centos-7-4-PR/go/src/github.com/kata-containers/tests
/tmp/jenkins/workspace/kata-containers-tests-centos-7-4-PR/go/src/github.com/kata-containers/tests/.ci/lib.sh: line 61: go: command not found
/tmp/jenkins/workspace/kata-containers-tests-centos-7-4-PR/go/src/github.com/kata-containers/tests/.ci/lib.sh: line 62: go: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9    0     9    0     0     36      0 --:--:-- --:--:-- --:--:--    36
/tmp/jenkins/workspace/kata-containers-tests-centos-7-4-PR/go/bin/yq: line 1: Not: command not found
Missing go version or -p option
Usage:

install_go.sh [options] <args>
```

I think that is why we need the `$(arch)` case

**Comment by marcov** [comment]
@grahamwhaley: yea I tested on macOS. 
The message:
```
/tmp/jenkins/workspace/kata-containers-tests-centos-7-4-PR/go/bin/yq: line 1: Not: command not found
```
is returned because curl actually creates the yq file at the right place, but it's just an ASCII text file with content `Not found` (that what github http server should return).

@chavafg: fair enough :-) I'll restore the switch case then.

**Comment by chavafg** [comment]
lgtm

restarded ubuntu job, failure is unrelated.

**Pull request merged**
