### PR TITLE
k8s: enable memroy tests

### PR DESCRIPTION
**Pull request by bergwolf**
Increase the memory size to allow testing.

Depends-on: github.com/kata-containers/kata-containers#910
Fixes: #2942

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @bergwolf !

**Comment by jodh-intel** [comment]
The confusingly named `jenkins-vfio-host:ubuntu18-04-vm:fedora32` CI is failing:

```
09:41:28 Using context: jenkins-vfio-host:ubuntu18-04-vm:fedora32

    :

09:43:28 +++ ID=fedora

    :

09:43:28 ++ '[' ubuntu = fedora ']'
09:43:28 ++ echo '.ci/vfio_jenkins_job_build.sh only supports Fedora'
09:43:28 .ci/vfio_jenkins_job_build.sh only supports Fedora
09:43:28 ++ exit 1
```

/cc @devimc as this code changes in https://github.com/kata-containers/tests/issues/2917.

**Comment by bergwolf** [comment]
Please do not merge it until kata-containers/kata-containers#910 is merged

**Comment by bergwolf** [comment]
kata-containers/kata-containers#910 has been merged. We can merge this one as well.

**Pull request merged**
