### PR TITLE
ci: Update obs repos to master.

### PR DESCRIPTION
**Pull request by jcvenegas**
"release" is not longer maintained.

Fixes: #1106

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@jcvenegas all the CI is failing with `.ci/lib.sh/kata-arch.sh: Not a directory`

**Comment by jcvenegas** [comment]
@GabyCT  another round, lets see if now all works.

**Comment by jodh-intel** [comment]
lgtm

**Comment by grahamwhaley** [comment]
@jodh-intel - when you 'l g t m' - are you just posting that as a comment item, rather than doing it through the github 'review changes' dialog. I'm afraid the github ack counting only sees the latter, whereas I think pullapprove noticed both... so, sorry, but can you re-ack using the github process pls :-)

**Comment by jodh-intel** [comment]
@grahamwhaley - yes I am. That sounds like a bit of a pita and should be communicated to others I think.

I can't even see how to add another approval now I've already ack'ed it?!?

**Comment by grahamwhaley** [comment]
Now we are using the github approval workflow, then using the review/approve button/dialog is the github way.

To communicate the change I'll:
- see if we have it in our docs
- send an update to the mailing list

tbh, I thought pullapprove had stopped looking at comment fields a long time ago, and only looked at the approval dialogs.
If you go to the 'files changed' tab, under the 'review changes' button, can you not click the 'approve' and add an 'lgtm' to it then? It looks like I can, even though I have already...

**Pull request merged**
