### PR TITLE
integration/docker: save container ID to check kata components status

### LINKED ISSUE #598: ExistDockerContainer must use container ID not container name
`ExistDockerContainer` checks if the kata components (proxy, agent, qemu) are still running, the functions used to check this, are `HypervisorRunning` , `ProxyRunning` and `ShimRunning` https://github.com/kata-containers/tests/blob/master/integration/docker/docker.go#L210-L219, these functions need the container ID to check the commandline of all the running processes at `/proc` https://github.com/kata-containers/tests/blob/master/process.go#L55-L85 ,
the problem is that `ExistDockerContainer` is using the container name not the container ID, hence `ExistDockerContainer` always returns `false`. 

**Note: container's name can't be used since it's not present in the process command line**

### PR DESCRIPTION
**Pull request by devimc**
Use --cidfile to save container ID and use it later to check if kata
components are still running.

Container's name can't be used since it's not present in the process
command line.

fixes #598

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@devimc Can you address @grahamwhaley comments on the issue for this PR?
Name should be unique as well, so I would like to understand the reasoning for this change.

**Comment by devimc** [comment]
@amshinde  done

**Comment by amshinde** [comment]
Thanks @devimc 
lgtm

**Comment by chavafg** [comment]
lgtm

**Comment by GabyCT** [comment]
lgtm

**Comment by GabyCT** [comment]
lgtm

**Pull request merged**
