### PR TITLE
k8s: enable skipped bats for kata 2.0

### PR DESCRIPTION
**Pull request by bergwolf**
We should already support it.

Fixes: #2806

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]

**Comment by jodh-intel** [comment]
@bergwolf - Travis failed due to what looks like a network issue, but I can't restart the job. Also, the Jenkins CI's seem to be "stuck".  Could you do a force-push to re-trigger the CI's?

**Comment by bergwolf** [comment]
@jodh-intel I've restarted both travis and jenkins, the latter seems stuck yesterday as well.

**Comment by jodh-intel** [comment]
Thanks @bergwolf. Yes, I've raised https://github.com/kata-containers/ci/issues/328 on the Jenkins issue.

**Pull request merged**
