### PR TITLE
unskip tests in openshift to match kubernetes

### PR DESCRIPTION
**Pull request by cpmeadors**
PR https://github.com/kata-containers/tests/pull/943 unskipped tests related to initrd issue in kubernetes/run_kubernetes_test.sh.  This PR makes the same changes in the openshift/run_openshift_tests.sh for the same reason.

Signed-off-by: Cameron Meadors cmeadors@redhat.com

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @cpmeadors

**Comment by devimc** [comment]
please fix your commit message

**Review by GabyCT — APPROVED** [review]

**Comment by GabyCT** [comment]
Here it is the guide for the commit message https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

**Review by wainersm — APPROVED** [review]
This change looks good to me.

**Comment by jodh-intel** [comment]
Thanks for the contribution @cpmeadors, but we do need the commit in the standard format Gaby mentions above.

**Comment by fidencio** [comment]
@cpmeadors, you'll need to:
`git commit --amend --signoff` in order to add the tag and have the DCO check happy.

That may also solve the travis check.

**Comment by cpmeadors** [comment]
@fidencio I added the Signed-off-by line (CONTRIBUTING doc says the --sign-off is a convenience feature that adds that).  I think the real problem is that the jobs never reran after I updated the PR and amended the commit to have the correct commit message.  How do I trigger the jobs to run again?

**Comment by fidencio** [comment]
> @fidencio I added the Signed-off-by line (CONTRIBUTING doc says the --sign-off is a convenience feature that adds that).
 
I can see you added that to the first message, but not to the commit itself: https://github.com/kata-containers/tests/pull/2889/commits/28779a6bc0db7ccae74985bbe27034a68fb71df3

> I think the real problem is that the jobs never reran after I updated the PR and amended the commit to have the correct commit message. How do I trigger the jobs to run again?

We can re-run the ci by using the /test command, but you need special powers to do that. As the CI has to be re-run after a force-push, I'd recommend we fix DCO and travis-ci as the first thing, then we run the CI against the patch in order to avoid re-running it.

Does this make sense?

**Comment by fidencio** [comment]
```
ERROR: No "Fixes" found
ERROR: checkcommits failed. See the document below for help on formatting
commits for the project.
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
```

@cpmeadors, is this PR still needed? If so, mind to add the Fixes: #NN to the commit message?

**Comment by fidencio** [comment]
@cpmeadors, we're seeing a bunch of CI failures that are not related to your patch.
For future cases, please, always remember to rebase your patch atop of the the current status of the repo (considering the branch you're submitting the patch to).

If you have the cycles, would be nice to have it rebased now just to be more than sure about the issues, but I'll leave it up to you.

**Comment by fidencio** [comment]
* **jenkins-ci-centos-8**:
```
15:35:58 Error: 
15:35:58  Problem 1: cannot install the best update candidate for package authselect-compat-1.1-2.el8.x86_64
15:35:58   - nothing provides authselect(x86-64) = 1.2.1-2.el8 needed by authselect-compat-1.2.1-2.el8.x86_64
15:35:58  Problem 2: cannot install the best update candidate for package python3-pip-9.0.3-16.el8.noarch
15:35:58   - nothing provides platform-python-pip = 9.0.3-18.el8 needed by python3-pip-9.0.3-18.el8.noarch
15:35:58 (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
15:35:58 Failed at 41: sudo -E yum -y update
```
This is due to the release that rebuilt RHEL-8.3 and pieces are yet not properly working. Please, see: https://github.com/kata-containers/tests/issues/3098 as a suggestion.

**Comment by fidencio** [comment]
* **jenkins-ci-podman-clh-fedora-31**:
```
16:01:10 ./scripts/dev_cli.sh: line 122: docker: command not found
16:01:10 [Cloud Hypervisor] Error pulling container image. Aborting.
16:01:10 Failed at 41: "${GOPATH}/src/${packaging_repo}/static-build/cloud-hypervisor/build-static-clh.sh"
16:01:10 Failed at 54: "${cidir}/install_cloud_hypervisor.sh"
```
This is the known issue about clh hardcoding a check for docker, while podman should be used in this CI.

**Comment by fidencio** [comment]
* **jenkins-ci-ubuntu-18-04**:
```
16:40:03 not ok 2 initContainer with shared volume
16:40:03 # (in test file k8s-shared-volume.bats, line 44)
16:40:03 #   `kubectl exec "$pod_name" -c "$last_container" -- sh -c "$cmd"' failed
16:40:03 # INFO: k8s configured to use runtimeclass
16:40:03 # pod/initcontainer-shared-volume created
16:40:03 # pod/initcontainer-shared-volume condition met
16:40:03 # I1208 15:39:48.313167   28868 log.go:172] (0xc00089a160) (0xc000454500) Create stream
16:40:03 # I1208 15:39:48.313210   28868 log.go:172] (0xc00089a160) (0xc000454500) Stream added, broadcasting: 1
16:40:03 # I1208 15:39:48.314201   28868 log.go:172] (0xc00089a160) Reply frame received for 1
16:40:03 # I1208 15:39:48.314231   28868 log.go:172] (0xc00089a160) (0xc000714000) Create stream
16:40:03 # I1208 15:39:48.314238   28868 log.go:172] (0xc00089a160) (0xc000714000) Stream added, broadcasting: 3
16:40:03 # I1208 15:39:48.314875   28868 log.go:172] (0xc00089a160) Reply frame received for 3
16:40:03 # I1208 15:39:48.314893   28868 log.go:172] (0xc00089a160) (0xc00068e0a0) Create stream
16:40:03 # I1208 15:39:48.314900   28868 log.go:172] (0xc00089a160) (0xc00068e0a0) Stream added, broadcasting: 5
16:40:03 # I1208 15:39:48.315440   28868 log.go:172] (0xc00089a160) Reply frame received for 5
16:40:03 # I1208 15:39:48.490489   28868 log.go:172] (0xc00089a160) Data frame received for 1
16:40:03 # I1208 15:39:48.490512   28868 log.go:172] (0xc000454500) (1) Data frame handling
16:40:03 # I1208 15:39:48.490523   28868 log.go:172] (0xc000454500) (1) Data frame sent
16:40:03 # I1208 15:39:48.490534   28868 log.go:172] (0xc00089a160) (0xc000454500) Stream removed, broadcasting: 1
16:40:03 # I1208 15:39:48.491022   28868 log.go:172] (0xc00089a160) (0xc000714000) Stream removed, broadcasting: 3
16:40:03 # I1208 15:39:48.491044   28868 log.go:172] (0xc00089a160) (0xc00068e0a0) Stream removed, broadcasting: 5
16:40:03 # I1208 15:39:48.491060   28868 log.go:172] (0xc00089a160) (0xc000454500) Stream removed, broadcasting: 1
16:40:03 # I1208 15:39:48.491069   28868 log.go:172] (0xc00089a160) (0xc000714000) Stream removed, broadcasting: 3
16:40:03 # I1208 15:39:48.491075   28868 log.go:172] (0xc00089a160) (0xc00068e0a0) Stream removed, broadcasting: 5
16:40:03 # command terminated with exit code 1
16:40:03 # pod "initcontainer-shared-volume" deleted
16:40:03 Failed at 82: bats "${K8S_TEST_ENTRY}"
```
This looks genuinely bad.  @kata-containers/runtime, @kata-containers/tests, have we seen this before?

**Comment by fidencio** [comment]
* **jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd**:
```
16:32:47 not ok 1 Check PID namespaces
16:32:47 # (in test file k8s-pid-ns.bats, line 28)
16:32:47 #   `kubectl wait --for=condition=Ready pod "$pod_name"' failed
16:32:47 # INFO: k8s configured to use runtimeclass
16:32:47 # pod/busybox created
16:32:47 # error: timed out waiting for the condition on pods/busybox
16:32:47 # pod "busybox" deleted
16:32:47 Failed at 82: bats "${K8S_TEST_ENTRY}"
```
Seems a legit failure, @kata-containers/runtime, @kata-containers/tests, have we seen this before?

**Comment by fidencio** [comment]
* **jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-e2e-* **:
All the issues seem to be related to sonobouy timing out.  Not sure what to do in those cases.
@kata-containers/tests, ideas?

**Pull request merged**
