### PR TITLE
Test latest CRI-O

### PR DESCRIPTION
**Pull request by liubin**
Signed-off-by: bin liu <bin@hyper.sh>

### CODE REVIEW

**Comment by liubin** [comment]
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: time="2020-08-11T03:41:24.204393474Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/e1bb5027099f5844e1054ba3d69e531052b308acb0a617398570e99a50c9c683/console.sock pid=99783 sandbox=e1bb5027099f5844e1054ba3d69e531052b308acb0a617398570e99a50c9c683 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"updating e1bb5027099f5844e1054ba3d69e531052b308acb0a617398570e99a50c9c683\",\"level\":\"INFO\",\"ts\":\"2020-08-11T03:41:24.186490446+00:00\",\"subsystem\":\"sandbox\",\"version\":\"0.1.0\",\"source\":\"agent\",\"pid\":\"50\",\"name\":\"kata-agent\"}"
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: panic: protobuf tag not enough fields in Status.state:
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: goroutine 4882 [running]:
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: github.com/gogo/protobuf/proto.(*unmarshalInfo).computeUnmarshalInfo(0xc00096b0e0)
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]:         /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR/go/src/github.com/cri-o/cri-o/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:341 +0x1834
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: github.com/gogo/protobuf/proto.(*unmarshalInfo).unmarshal(0xc00096b0e0, 0xc0007d5d40, 0xc00084f4f2, 0x0, 0x6, 0x0, 0x2378700)
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]:         /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR/go/src/github.com/cri-o/cri-o/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:138 +0xe02
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: github.com/gogo/protobuf/proto.makeUnmarshalMessagePtr.func1(0xc00084f4f2, 0x6, 0x7, 0xc0004b4ac0, 0x2, 0x0, 0x0, 0x203000, 0xc000809b20, 0x413b46)
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]:         /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR/go/src/github.com/cri-o/cri-o/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:1826 +0x12b
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: github.com/gogo/protobuf/proto.(*unmarshalInfo).unmarshal(0xc00096b040, 0xc0004b4ac0, 0xc00084f4f0, 0x8, 0x8, 0x4143b8, 0x20)
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]:         /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR/go/src/github.com/cri-o/cri-o/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:175 +0x79e
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: github.com/gogo/protobuf/proto.(*InternalMessageInfo).Unmarshal(0xc00067db80, 0x2325f40, 0xc0004b4ac0, 0xc00084f4f0, 0x8, 0x8, 0x1, 0x0)
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]:         /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR/go/src/github.com/cri-o/cri-o/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:63 +0x66
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: github.com/gogo/protobuf/proto.(*Buffer).Unmarshal(0xc000cffcf0, 0x2325f40, 0xc0004b4ac0, 0x0, 0x0)
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]:         /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR/go/src/github.com/cri-o/cri-o/vendor/github.com/gogo/protobuf/proto/decode.go:424 +0x1ec
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: github.com/gogo/protobuf/proto.Unmarshal(0xc00084f4f0, 0x8, 0x8, 0x2325f40, 0xc0004b4ac0, 0xc0009537b8, 0xc000809f40)
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]:         /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR/go/src/github.com/cri-o/cri-o/vendor/github.com/gogo/protobuf/proto/decode.go:342 +0x170
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: github.com/containerd/ttrpc.(*Client).recv(0xc001282e00, 0xc0004b4ac0, 0xc001004180, 0x0, 0x0)
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]:         /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR/go/src/github.com/cri-o/cri-o/vendor/github.com/containerd/ttrpc/client.go:323 +0x14f
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: github.com/containerd/ttrpc.(*Client).run(0xc001282e00)
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]:         /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR/go/src/github.com/cri-o/cri-o/vendor/github.com/containerd/ttrpc/client.go:273 +0x471
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]: created by github.com/containerd/ttrpc.NewClient
Aug 11 03:41:24 fedoradocker32-1dc8f0 crio[97726]:         /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR/go/src/github.com/cri-o/cri-o/vendor/github.com/containerd/ttrpc/client.go:92 +0x17e
Aug 11 03:41:24 fedoradocker32-1dc8f0 systemd[1]: crio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by liubin** [comment]
Blocked on https://github.com/cri-o/cri-o/issues/3991

**Comment by fidencio** [comment]
So, just to be clear here. cri-o is broken but, IIUC, the breakage is coming from containerd vendored code: https://github.com/containerd/ttrpc/issues/62 (and we may also face issues with any other github/gogo/protobuf usage).

**Comment by liubin** [comment]
> So, just to be clear here. cri-o is broken but, IIUC, the breakage is coming from containerd vendored code: [containerd/ttrpc#62](https://github.com/containerd/ttrpc/issues/62) (and we may also face issues with any other github/gogo/protobuf usage).

Ok, thanks for your clarification

**Comment by liubin** [comment]
https://github.com/kata-containers/runtime/pull/2954 is doing the same thing

**Pull request closed without merging**
