### PR TITLE
tests: Remove leftover code handling cmake

### LINKED ISSUE #3199: tests contain obsolete code to install cmake
# Description of problem

`cmake` used to be a dependency for Kata, but isn't any longer.  Since https://github.com/kata-containers/kata-containers/pull/1306 all remaining requirement for it has been removed, but there remains some codes in the tests repo to install it which is now obsolete.

### PR DESCRIPTION
**Pull request by dgibson**
cmake used to be a dependency for Kata, but isn't any longer.  Since
https://github.com/kata-containers/kata-containers/pull/1306 all remaining
requirement for it has been removed.  So remove the code to install it from
the tests as well.

fixes #3199

Signed-off-by: David Gibson <david@gibson.dropbear.id.au>

### CODE REVIEW

**Comment by snir911** [comment]
Thanks!, this also redundant i suppose:
https://github.com/kata-containers/tests/blob/ac8a2c8c5d09c7527522a6cfe07f467c93e7aabd/.ci/setup_env_ubuntu.sh#L55

**Review by wainersm — APPROVED** [review]
LGTM

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
