### PR TITLE
# Kata Containers 2.5.1

### PR DESCRIPTION
**Pull request by amshinde**
Version bump no changes

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @amshinde!

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
https://github.com/kata-containers/tests/pull/5093 needs to be merged.

**Comment by fidencio** [comment]
> #5093 needs to be merged.

It's dependencies are too intrusive, we better rollback to using the Ubuntu 20.04 CI as part of the stable-2.5 branch.

**Pull request merged**
