### PR TITLE
docker: fix cpu tests

### PR DESCRIPTION
**Pull request by bergwolf**
We should take the initial cpu count when setting cpu constraints.
IOW, if there is already enough cpu in the vm for a container, we
should not hotplug more CPUs.

Depends-on: kata-containers/runtime#696
Fixes: #705

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

But looking at the CI logs suggests the depends-on is broken:

```
This PR depends on repository: kata-containers/runtime and pull request: 696
package kata-containers/runtime: unrecognized import path "kata-containers/runtime" (import path does not begin with hostname)
```

**Comment by chavafg** [comment]
@bergwolf can you rebase your PR with latest changes? There is a fix that solves the Depends-on issue.

**Comment by jcvenegas** [comment]
@devimc ping

**Comment by jcvenegas** [comment]
```

Summarizing 15 Failures:

[Fail] Update number of CPUs Update CPU period and quota [It] should have 2 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:287

[Fail] Update number of CPUs Update CPU period and quota [It] should have 3 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:287

[Fail] Update number of CPUs Update CPU period and quota [It] should have 1 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:287

[Fail] Update number of CPUs Update CPU constraint [It] should have 1 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:309

[Fail] Update number of CPUs Update CPU constraint [It] should have 2 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:309

[Fail] Update number of CPUs Update CPU constraint [It] should have 2 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:309

[Fail] Update number of CPUs Update CPU constraint [It] should have 3 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:309

[Fail] Update number of CPUs Update CPU constraint [It] should have 3 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:309

[Fail] Hot plug CPUs container with CPU period and quota [It] should have 2 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:96

[Fail] Hot plug CPUs container with CPU period and quota [It] should have 3 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:96

[Fail] Hot plug CPUs container with CPU period and quota [It] should have 1 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:96

[Fail] Hot plug CPUs container with CPU constraint [It] should have 1 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:115

[Fail] Hot plug CPUs container with CPU constraint [It] should have 2 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:115

[Fail] Hot plug CPUs container with CPU constraint [It] should have 2 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:115

[Fail] Hot plug CPUs container with CPU constraint [It] should have 3 CPUs 
/tmp/jenkins/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:115

Ran 200 of 211 Specs in 992.647 seconds
FAIL! -- 185 Passed | 15 Failed | 0 Pending | 11 Skipped --- FAIL: TestIntegration (1018.22s)
```

**Comment by bergwolf** [comment]
I'll drop this one for now since @devimc has a valid use case and we might introduce a new option to control the behavior.

**Pull request closed without merging**
