### PR TITLE
docs: Fix typos and formatting

### PR DESCRIPTION
**Pull request by jodh-intel**
Correct spelling and formatting.

Fixes: #1632.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Travis static check doc fail:

```
ERROR: Document metrics/density/README.md is not referenced
```

You up for fixing that in this PR as well?

**Comment by jodh-intel** [comment]
Huh?

/retest

**Comment by grahamwhaley** [comment]
heh - still some funny travis fails - but, they feel a little sporadic?
```
ERROR: Invalid URL 'https://godoc.org/github.com/sirupsen/logrus' found in the following files:
cmd/log-parser/README.md
The command "bash .ci/static-checks.sh github.com/kata-containers/tests" exited with 1.
```

**Comment by jodh-intel** [comment]
Yup - restarted...

**Comment by jodh-intel** [comment]
That error is odd as it's valid as you say. But Travis repeatedly fails on that URL. I've reworked the URL checker to hopefully be more reliable on https://github.com/kata-containers/tests/pull/1643.

**Comment by jodh-intel** [comment]
You guessed it, yet-another-doc-only PR. I think the travis URL check might be failing as we still haven't landed https://github.com/kata-containers/tests/pull/1643. Merging anyway as that URL check is a known issue and all other CI's are green...

**Pull request merged**
