### PR TITLE
Revert "ci: Fix missing line so that codecov works"

### LINKED ISSUE #2790: Tests on pull requests are failing with make[1]: cargo: Command not found
After [2782](https://github.com/kata-containers/tests/pull/2782) was merged, which adds `make test` to the jenkins script with the intention of creating a golang coverage report, ubuntu (and other) tests are failing with an error related to `make test` also calling the rust build. We should revert this change until we can go further debugging on the rust build so that tests on the 2.0-dev branch don't consistently fail.

### PR DESCRIPTION
**Pull request by cmaf**
This reverts commit d2e77d29bb79727aaf64dac75da97c28b1b3f370.

Fixes #2790

Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>

### CODE REVIEW

**Comment by cmaf** [comment]
`make test` was added to the jenkins script with the intention of creating a golang coverage report, ubuntu (and other) tests are failing with an error related to make test also calling the rust build. We should revert this change until we can go further debugging on the rust build so that tests on the 2.0-dev branch don't consistently fail.

**Comment by chavafg** [comment]
thanks @cmaf

**Comment by chavafg** [comment]
I see error format on the commit message, can you please amend it?
something like: `ci: Revert Fix missing line so that codecov works` should work

**Comment by jongwu** [comment]
thanks @cmaf , "make test" will lead to Arm ci failing as it will make agent in host, see http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/149/console

**Pull request merged**
