### PR TITLE
CC | ci: replace $TRAVIS with $GITHUB_ACTION in setup

### PR DESCRIPTION
**Pull request by jepio**
Cherry-pick of
- #5518

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jepio!

**Comment by stevenhorsman** [comment]
SEV test failed with:
```
16:07:42 Install Kubernetes components
16:07:42 Warning: apt-key output should not be parsed (stdout is not a terminal)
16:07:42 gpg: no valid OpenPGP data found.
16:07:42 [install_kubernetes.sh:32] ERROR: sudo apt-key add -
16:07:42 [jenkins_job_build.sh:251] ERROR: .ci/setup.sh
16:07:42 ++ handle_error 93
16:07:42 ++ local exit_code=2
16:07:42 ++ local line_number=93
16:07:42 ++ echo 'Failed at /home/jenkins/workspace/tests-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S-PR/ci_entry_point.sh +93: .ci/jenkins_job_build.sh "${repo_to_test}" -t "${TEST_TYPE}"'
16:07:42 Failed at /home/jenkins/workspace/tests-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S-PR/ci_entry_point.sh +93: .ci/jenkins_job_build.sh "${repo_to_test}" -t "${TEST_TYPE}"
16:07:42 ++ exit 2
```
/test-sev

**Comment by jepio** [comment]
That must have been a packages.cloud.google.com outage again, because I had already restarted a run before that, that failed with:
> 15:58:33 Err:5 https://packages.cloud.google.com/apt kubernetes-xenial-unstable Release
15:58:33   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 142.250.188.14 443]

Rerunning.

**Comment by stevenhorsman** [comment]
Only TDX is failing, which is a known issue, so we can merge this. Thanks @jepio!

**Pull request merged**
