### PR TITLE
integration: pmem: fix test

### LINKED ISSUE #3652: integration: pmem: data/lib.sh: No such file or directory
```
18:06:48 + ./integration/pmem/pmem_test.sh
18:06:48 ./integration/pmem/pmem_test.sh: line 16: ./integration/pmem/data/lib.sh: No such file or directory
18:06:48 Build step 'Execute shell' marked build as failure
```

### PR DESCRIPTION
**Pull request by devimc**
Fix Pmem test.
data/lib.sh was removed in a previous commit, hece source it
is an error.

fixes #3652

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @devimc!

**Review by jodh-intel — APPROVED** [review]
lgtm

**Comment by fidencio** [comment]
Howdy!

I'd like to ask you to rebase your PR atop of current main, as #3668 has been merged and it has a fix that unblocks the CI.

Please, do the rebase and feel free to `@fidencio` in case you do not have the powers to run `/test`.

Sorry for the inconvenience and happy hacking!

**Pull request merged**
