### PR TITLE
# Kata Containers 2.4.0-alpha1

### PR DESCRIPTION
**Pull request by snir911**
- ci: exclude the SPDX-License check for some proto files
- Static checks: adds a checker for dockerfiles
- k8s: Add seccomp support test
- ci: Always install newest Rust version
- kubernetes: strengthen the init.sh and misc refactors
- env: install runc before podman
- ci: skip unit tests on ppc64le
- tests: Remove leftovers of the docker integration tests
- spell: Add AppArmor to dictionary
- openshift-ci: adapt scripts to test like OpenShift Sandboxed Containers - respin
- spell: Fix hypervisor entry in dictionary
- metrics: Update report metrics documentation
- docs: fix check-markdown test
- workflows: Bump golang to 1.17
- ci: fix CI entry point for cri-o PRs
- docs: Remove UT advice doc
- static-checks: Check for the `force-skip-ci` label on each step
- metrics: Remove kata-fc from memory usage script
- integration/kubernetes: volume tests for nested configmap and secret
- k8s: cleanup environment before retry
- tests: update API version of RuntimeClass resource
- docs: Moving from EOT to EOF
- spell-checker: Add new words for DinD docs
- ci: Remove debian installation

b496afbb ci: exclude the SPDX-License check for some proto files
00b133ff ci/static-checks: skip dockerfiles checker if not in x86_64
6341f955 ci/static-checks: update dockerfiles checker for the kata-containers repo
da64ef2e ci/static-checks: handle hadolint install
37e3637f ci/static-checks: add a checker for dockerfiles
e2019f10 ci/openshift-ci: delint dockerfiles
323928d4 conformance/posixfs: delint dockerfiles
2075b6dd metrics: delint dockerfiles
c946d070 integration/kubernetes: delint dockerfiles
6c26d09d kata-webhook: delint the Dockerfile
64240397 ci: Always install newest Rust version
e3bb5637 k8s: replace "echo" in init.sh and cleanup_env.sh
e380e87a k8s: add the main() in cleanup_env.sh
d19a1501 k8s: retry the test environment initialization
505fa6e4 k8s: add the main() in init.sh
8de661e5 k8s: add the configure_network() in init.sh
96b3f7bd k8s: add the start_kubernetes() in init.sh
79f6562b k8s: add the start_cri_runtime_service() in init.sh
92f8b2da k8s: add the save_iptables() in init.sh
5141a31e ci: skip unit tests on ppc64le
2cc8d97b env: install runc before podman
f382cf88 tests: Remove leftovers of the docker integration tests
05e49be2 k8s: add the cleanup_cni_configuration() in init.sh
ba85666d k8s: add debug information to wait_pods_ready() in init.sh
454d8d2f k8s: add the untaint_node() in init.sh
0ab446fd spell: Add AppArmor to dictionary
82536a92 spell: Fix hypervisor entry in dictionary
ebc73380 metrics: Update report metrics documentation
a1a457b2 docs: fix check-markdown test
7e359ac9 ci/openshift-ci: add updater for kernel modules in the initrd
6853e457 ci/openshift-ci: test.sh return error when the smoke test fail
e95699db metrics: Remove kata-fc from memory usage script
f8219c88 ci: fix CI entry point for cri-o PRs
a8b6e4aa static-checks: Check for the `force-skip-ci` label on each step
9bf37b01 workflows: Bump golang to 1.17
5b573173 integration/kubernetes: volume tests for nested configmap and secret
e400f12a ci: turn off zram swap
70265caf ci: add backoff sleep
1effcb1a tests: update API version of RuntimeClass resource
90b95857 docs: Moving from EOT to EOF
8463b7d6 ci: Remove debian installation
67a36876 spell-checker: Add new words for DinD docs
a9e1a667 docs: Remove UT advice doc
51227705 k8s: cleanup environment before retrying init.sh
d8f673d2 k8s: Add Seccomp support test

### CODE REVIEW

**Comment by c3d** [comment]
@snir911 Thanks for the update. Just curious why you add a manual bullet point list of topics when there is also a commit list following it?

**Comment by snir911** [comment]
@c3d it's done automatically by the release script, I suppose it would be more helpful when many PRs has multiple commits

**Review by GabyCT — APPROVED** [review]

**Review by wainersm — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @snir911!

**Pull request merged**
