### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by stevenhorsman**
Merge remote-tracking branch 'upstream/main' into CCv0

Fixes: https://github.com/kata-containers/tests/issues/5645
Depends-on: github.com/https://github.com/kata-containers/kata-containers/pull/6885

Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by fidencio** [comment]
```
11:41:31 ERROR: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests focal]: 503 Service Unavailable
```

We've been consistently failing on things like this.
I'll give it some time and re-run later Today, with the hope this is just infra related issues.

**Comment by fidencio** [comment]
Failure on TDX is legit:
```
15:27:48 # May 25 21:26:54 tdx-ci kata[2130160]: time="2023-05-25T21:26:54.431582822+08:00" level=error msg="Create new sandbox failed" error="Missing image and initrd path" name=containerd-shim-v2 pid=2130160 sandbox=e7d9016c31f786aa6475f2e54ecb1519b8b95e6d7d6967049eb7a746f35eb823 source=virtcontainers subsystem=sandbox
```

**Comment by stevenhorsman** [comment]
@arronwy - if you get the chance, would you be able to check the tdx tests to see if the problem is not reporting/network issues, or if there is a genuine issue in the merge PRs please. Thank you!

**Comment by stevenhorsman** [comment]
FYI @UnmeshDeodhar - the SEV tests failed with
```
Err:6 https://packages.cloud.google.com/apt kubernetes-xenial-unstable Release
20:35:02   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 142.251.46.206 443]
```
I've re-queued it, but I wanted to let you know in case that's an issue that need some manual intervention.

**Comment by UnmeshDeodhar** [comment]
Thanks @stevenhorsman i think this is the networking issue and should go away automatically in the next run!

**Comment by fidencio** [comment]
Cloud Hypervisor TDX passed but didn't report back: http://10.112.240.208:8080/job/tests-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/512/

We're still running the QEMU ones.

**Comment by fidencio** [comment]
QEMU TDX test is now passing, now that the image for TDX has been re-added to the Makefile. http://10.112.240.208:8080/job/tests-CCv0-qemu-TDX-CRI_CONTAINERD_K8S-PR/556/

**Pull request merged**
