### PR TITLE
K8s: Re-enable replication controller tests and improvements

### PR DESCRIPTION
**Pull request by wainersm**
Actually while I was working on the improvements to the e2e tests, tried the replication controller many times and it passed always. Thus I thought on re-enable it and  run a couple of times on CI to check if it is stable (or not).

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by snir911 — APPROVED** [review]

**Comment by wainersm** [comment]
I triggered the CI jobs 3x, some of them ran the replication controller test, it always passed. Plus got the reviews, so this PR is ready for merge.

**Pull request merged**
