### PR TITLE
# Kata Containers 2.2.3

### PR DESCRIPTION
**Pull request by bergwolf**
ac28e5bd integration/k8s: Disable caps test on s390x
64fb1dc7 k8s: add test to check capabilities of pod

### CODE REVIEW

**Comment by fidencio** [comment]
@bergwolf, the bump doesn't look correct, as it's bringing a non-related-to-the-bump commit.

**Comment by fidencio** [comment]
> @fidencio `integration/k8s: Disable caps test on s390x` is needed otherwise CI always fails on `s390x`.

Nice, thanks for bringing this is as well then.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Comment by bergwolf** [comment]
`jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd` failed due to disk pressure.
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd/356/console

```
18:05:17 # Events:
18:05:17 #   Type     Reason     Age   From               Message
18:05:17 #   ----     ------     ----  ----               -------
18:05:17 #   Normal   Scheduled  90s   default-scheduler  Successfully assigned default/initcontainer-shared-volume to ubuntu1804-azure249dd0
18:05:17 #   Warning  Evicted    90s   kubelet            The node had condition: [DiskPressure].
```

**Comment by bergwolf** [comment]
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-PR-cloud-hypeprvisor-k8s-containerd/
is just very much unstable. In the last 9 runs, it passed only twice, one for releasing `2.2.2` and the other one is the first run of this PR.

**Review by jodh-intel — APPROVED** [review]
Thanks @bergwolf.

lgtm

**Comment by jodh-intel** [comment]
@GabyCT, @likebreath ^

**Pull request merged**
