### PR TITLE
integration/docker:modify test of memory hotplug when create container

### LINKED ISSUE #812: Fix test fail cause by memory hotplug when create container
Fix test fail cause by memory hotplug when create container

### PR DESCRIPTION
**Pull request by clarecch**
Modify test of memory hotplug when create container.

Depends-on:github.com/kata-containers/runtime#786

Fixes #812

Signed-off-by: Clare Chen <clare.chenhui@huawei.com>

### CODE REVIEW

**Comment by caoruidong** [comment]
lgtm

**Comment by clarecch** [comment]
@bergwolf @jodh-intel @jcvenegas Please take a look.

**Comment by jodh-intel** [comment]
CI still failing due to no nested support @chavafg, @mnaser:

```
time="2018-10-15T07:07:19Z" level=error msg="open /sys/module/kvm_intel/parameters/nested: no such file or directory" arch=amd64 name=kata-runtime pid=15586 source=runtime
```

/cc @egernst.

Re-starting...

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
Hi @clarecch - I've restarted them again, but I suspect they are going to fail again...

We've had a problem recently where for reasons I don't understand a high proportion of the jobs have been scheduled on systems that do not support nested kvm. This is a recent change and currently causes all tests to fail. I believe that @mnaser is investigating.

/cc @chavafg, @egernst.

**Comment by grahamwhaley** [comment]
Ignoring known metrics CI fail - merging.

**Comment by clarecch** [comment]
Thanks @grahamwhaley

**Pull request merged**
