### PR TITLE
ci: Add installation RHEL scripts.

### LINKED ISSUE #1359: Add ci installation scripts for RHEL
Add setup scripts for RHEL

### PR DESCRIPTION
**Pull request by GabyCT**
This will setup all kata dependencies and install the kata components.

Fixes #1359

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
can you check if enabling the epel repository provides the missing packages? 
https://github.com/kata-containers/ci/issues/129#issuecomment-477050990

**Comment by GabyCT** [comment]
@chavafg changes applied

**Comment by jodh-intel** [comment]
@GabyCT, @chavafg: another instance of the opensuse CI failing due to a missing `git` command I think:

```
04:02:34 Caused by: java.io.IOException: Cannot run program "git" (in directory "/tmp/jenkins/workspace/kata-containers-tests-opensuse-15-PR"): error=2, No such file or directory
```

**Pull request merged**
