### PR TITLE
# Kata Containers 2.4.0-alpha2

### PR DESCRIPTION
**Pull request by snir911**
- versions: Remove alpine reference
- Adapt to centos stream
- spell: Add new terms to spell checker dictionary
- ci: Run static checks --only-arch
- ci: Use tests directory for setting 9p
- Switch to virtio-9p on s390x
- tests: Removed unused e2e k8s tests flags
- ci: Remove unused ci job flags for kata 2.0
- k8s: fix a problem on flannel installation
- versions: Remove elasticsearch
- ci: crio: Bump CRI-O latest release
- ci: Remove unused ci job flags
- Vagrantfile: Add support to Fedora 35
- ci: force-skip-ci check before static checks
- integration: add the agent namespace test cases
- kubernetes: bring up kubelet with '--v 4' by default and misc improvement
- versions: Remove kibana information
- ci: Remove unused variable at install kata script
- ci: fix install_rom_aarch64.sh on non-ubuntu/debian os
- ci: Improve `--rebase-merges` compatibility
- vagrant: Use the default distro with osbuilder
- test: Remove docker integration pentest
- ci: do not fail if no PR number is given
- k8s: add firecracker limitation issue link
- ci: Remove variable TEST_CGROUPSV2 from install runtime script
- kubernetes tests framework improvements
- k8s: add more test cases in k8s-env.bats
- Makefile: add static-checks target
- k8s: give more time to kubelet restart
- Makefile: Remove unused podman tests
- ci: Add static checks for anchor
- ci: "local" can only be used in functions
- ci: Use different rebase flag for ubuntu 18.04
- ci: do not drop merge commits when rebasing
- ci: exclude the SPDX-License check for some test materials
- k8s: ensure capability test container logs are available before checking

2b1ff802 versions: Remove alpine reference
434ea8df docs: update README.md running CI locally
8ee0b2e5 ci: Use tests directory for setting 9p
66dd969a spell: Add new terms to spell checker dictionary
73be1c45 ci: Switch to virtio-9p on s390x
e03ad89c tests: Removed unused e2e k8s tests flags
3fd2578e ci: Run static checks --only-arch
0069f8d7 ci: Remove unused ci job flag for kata 2.0
90d7421e ci: Remove unused CI jobs for the run.sh script
3a5335f5 ci: adapt scripts to work with centos stream
6b3aeffd versions: Remove elasticsearch
942419f1 k8s: restart CRI-O after the flannel deployment
88a06d78 k8s: check that flannel pods are ready
283fb4ad ci: Remove unused ci job flags
878b59de ci: force-skip-ci check before static checks
6f809156 Vagrantfile: Add support to Fedora 35
f180432b ci: crio: Bump CRI-O latest release
f90154eb versions: Remove kibana information
2f43a7b7 k8s: allow to skip the cleanup routine
44c5398b k8s: bring up kubelet with '--v 4' by default
83e370d8 integration: add the agent namespace test cases
33dad932 ci: Remove unused variable at install kata script
a70e5c93 test: Remove docker integration pentest
cbcbb4fd ci: Remove variable TEST_CGROUPSV2 from install runtime script
0610d875 k8s: add firecracker limitation issue link
57d8127a vagrant: Use the default distro with osbuilder
c1ed6c64 ci: fix install_rom_aarch64.sh on non-ubuntu/debian os
aa3e6af9 k8s: move KUBECONFIG boilerplate to tests_common
4a3fe28f k8s: allow running a sub-set of tests
076f6273 k8s: add more test cases in k8s-env.bats
d51186a8 k8s: give more time to kubelet restart
8d0d1010 Makefile: Remove unused podman tests
3242e2f8 ci: Improve `--rebase-merges` compatibility
c0a82fa2 ci: do not fail if no PR number is given
3d531954 ci: "local" can only be used in functions
aa479434 Makefile: add static-checks target
bb62f1b4 ci: Use different rebase flag for ubuntu 18.04
57be9294 ci: do not drop merge commits when rebasing
608b7b94 ci: exclude the SPDX-License check for some test materials
c0f2f829 k8s: ensure capability test container logs are available before checking
60f19eb8 ci: Add static checks for anchor

### CODE REVIEW

**Comment by fidencio** [comment]
Let's add the do-not-merge label so we avoid it being merged before we run `/test_kata_deploy` on its counterpart on `main`.

**Review by fidencio — APPROVED** [review]
lgtm, @snir911!

**Review by wainersm — APPROVED** [review]
Great!

**Pull request merged**
