### PR TITLE
tests: Update checkcommits README

### PR DESCRIPTION
**Pull request by nitkon**
Fixes: #377

Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
@jodh-intel - is/was it Travis where we hit the sporadic 'cannot find commit' issue? If so, I think maybe we should show @nitkon the open Issue etc., just in case it becomes an annoyance again.

**Comment by nitkon** [comment]
typo
Need Advice: How do we treat single typos in a README, like the one above. "legth" instead of "length". Raising a PR for this seems to be a "heavy" operation and not that significant too.

**Comment by chavafg** [comment]
I think you can fix it in this PR, just adding a new commit. No need of a new issue.

**Comment by nitkon** [comment]
@chavafg : Done..

**Comment by chavafg** [comment]
Thanks @nitkon, I am investigating the issues on the CI that are not related with your changes.

**Comment by jodh-intel** [comment]
@grahamwhaley - do you mean https://github.com/travis-ci/travis-ci/issues/7830? An example of the error we used to see a lot of is https://github.com/clearcontainers/tests/pull/101#issuecomment-312821994.

**Comment by jodh-intel** [comment]
lgtm

@klynnrif - ptal.

**Comment by grahamwhaley** [comment]
@jodh-intel yes, exactly that old Jenkins commit sha issue - thx. Let's keep an eye out for that with this new Jenkins setup... fingers crossed we never see it again!

**Comment by nitkon** [comment]
I see ``` ctr oom ``` error in the logs. Are the CI failing because of Out Of Memory issue?

**Comment by chavafg** [comment]
@nitkon no, `ctr oom` test is actually skipped. It failed on another `cri-o` test. 
The other failure seems from `kata-collect-data.sh`:

```
INFO: Checking Kata data collection script
/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1: `<!DOCTYPE html>'
```

I have restarted the jobs.

**Comment by jodh-intel** [comment]
That is one weird error - no idea what would cause that at this point.

**Pull request merged**
