### PR TITLE
tests: Add k8s test for kubectl patch

### LINKED ISSUE #2011: Add a test for kubectl patch

### PR DESCRIPTION
**Pull request by GabyCT**
This adds a K8s test for kubectl patch command.

Fixes #2011

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
typo in commit title: `s/path/patch`

**Comment by GabyCT** [comment]
@chavafg changes applied

**Pull request closed without merging**
