### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by GeorginaKin**
Merge remote-tracking branch 'upstream/main' into CCv0

Fixes: #5349
Depends-on: github.com/kata-containers/kata-containers#5933

Signed-off-by: Georgina Kinge <georgina.kinge@ibm.com>

### CODE REVIEW

**Comment by GeorginaKin** [comment]
```
git diff --stat upstream/main -- . ':!*/vendor/*'
 .ci/ci_job_flags.sh                                                                       |  78 ++++++++++-
 .ci/install_cloud_hypervisor.sh                                                           |  15 +-
 .ci/install_cni_plugins.sh                                                                |   2 +-
 .ci/install_kata.sh                                                                       |   8 ++
 .ci/install_kata_image.sh                                                                 |  42 +++++-
 .ci/install_kata_kernel.sh                                                                |  37 ++++-
 .ci/install_ovmf_sev.sh                                                                   |  28 ++++
 .ci/install_qemu.sh                                                                       |  34 ++++-
 .ci/install_runtime.sh                                                                    |  51 ++++---
 .ci/install_td_shim.sh                                                                    |  25 ++++
 .ci/install_tdvf.sh                                                                       |  24 ++++
 .ci/install_virtiofsd.sh                                                                  |  12 +-
 .ci/jenkins_job_build.sh                                                                  |  10 ++
 .ci/lib.sh                                                                                |  42 +++++-
 .ci/resolve-kata-dependencies.sh                                                          |  44 +++---
 .ci/run.sh                                                                                |  24 +++-
 .ci/setup.sh                                                                              |   1 +
 .ci/setup_env_ubuntu.sh                                                                   |   4 +-
 .ci/static-checks.sh                                                                      |  10 +-
 .github/workflows/commit-message-check.yaml                                               |   4 +-
 Makefile                                                                                  |  19 ++-
 README.md                                                                                 |  10 +-
 cmd/check-spelling/data/projects.txt                                                      |   1 +
 cmd/github-labels/labels.yaml.in                                                          |   4 +-
 cmd/pmemctl/pmemctl.sh                                                                    |   2 +-
 functional/kata-monitor/run.sh                                                            |   1 +
 functional/sev/fixtures/agent-config.toml                                                 |  44 ++++++
 functional/sev/run.sh                                                                     | 233 +++++++++++++++++++++++++++++++
 integration/confidential/fixtures/cosign/offline-fs-kbc/aa-offline_fs_kbc-resources.json  |   4 +
 integration/confidential/fixtures/offline-fs-kbc/aa-offline_fs_kbc-resources.json.in      |   7 +
 integration/confidential/fixtures/offline-fs-kbc/auth.json.in                             |   7 +
 integration/confidential/fixtures/offline-fs-kbc/s390x/aa-offline_fs_kbc-resources.json   |   5 +
 integration/confidential/fixtures/offline-fs-kbc/x86_64/aa-offline_fs_kbc-resources.json  |   5 +
 integration/confidential/fixtures/quay_verification/s390x/public.gpg                      |  41 ++++++
 integration/confidential/fixtures/quay_verification/s390x/quay_policy.json                |  18 +++
 integration/confidential/fixtures/quay_verification/s390x/signatures.tar                  | Bin 0 -> 1930 bytes
 integration/confidential/fixtures/quay_verification/x86_64/public.gpg                     |  30 ++++
 integration/confidential/fixtures/quay_verification/x86_64/quay_policy.json               |  18 +++
 integration/confidential/fixtures/quay_verification/x86_64/signatures.tar                 | Bin 0 -> 2157 bytes
 integration/confidential/fixtures/registries.d/quay.io.yaml                               |   4 +
 integration/confidential/lib.sh                                                           | 354 +++++++++++++++++++++++++++++++++++++++++++++++
 integration/containerd/confidential/agent_api.bats                                        |  82 +++++++++++
 integration/containerd/confidential/agent_image.bats                                      | 176 ++++++++++++++++++++++++
 integration/containerd/confidential/asserts.sh                                            |  77 +++++++++++
 integration/containerd/confidential/fixtures/agent-configuration-no-exec.toml             |  46 +++++++
 integration/containerd/confidential/fixtures/container-config.yaml                        |  11 ++
 integration/containerd/confidential/fixtures/container-config_authenticated.yaml          |   9 ++
 integration/containerd/confidential/fixtures/container-config_cosigned-other.yaml         |  11 ++
 integration/containerd/confidential/fixtures/container-config_cosigned.yaml               |  11 ++
 integration/containerd/confidential/fixtures/container-config_signed-protected-other.yaml |  11 ++
 integration/containerd/confidential/fixtures/container-config_unsigned-protected.yaml     |  11 ++
 integration/containerd/confidential/fixtures/container-config_unsigned-unprotected.yaml   |  11 ++
 integration/containerd/confidential/fixtures/pod-config.yaml.in                           |  12 ++
 integration/containerd/confidential/lib.sh                                                | 163 ++++++++++++++++++++++
 integration/containerd/confidential/run_tests.sh                                          |  21 +++
 integration/containerd/confidential/tests_common.sh                                       | 106 ++++++++++++++
 integration/containerd/cri/integration-tests.sh                                           |  12 +-
 integration/kubernetes/confidential/agent_image.bats                                      | 255 ++++++++++++++++++++++++++++++++++
 integration/kubernetes/confidential/agent_image_encrypted.bats                            |  79 +++++++++++
 integration/kubernetes/confidential/fixtures/encrypted-image-tests.yaml                   |  28 ++++
 integration/kubernetes/confidential/fixtures/pod-config.yaml.in                           |  14 ++
 integration/kubernetes/confidential/fixtures/unencrypted-image-tests.yaml                 |  28 ++++
 integration/kubernetes/confidential/lib.sh                                                | 125 +++++++++++++++++
 integration/kubernetes/confidential/sev.bats                                              | 447 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 integration/kubernetes/e2e_conformance/setup.sh                                           |   2 +-
 integration/nydus/nydus-sandbox.yaml                                                      |   1 +
 integration/nydus/nydus_tests.sh                                                          |   2 +
 lib/common.bash                                                                           | 127 +++++++++++++++++
 versions.yaml                                                                             |   7 +-
 69 files changed, 3083 insertions(+), 104 deletions(-)
```

**Comment by stevenhorsman** [comment]
@UnmeshDeodhar - this is failing

```
09:44:29 Set up environment (default)
09:44:29 Update apt repositories
09:44:29 
09:44:29 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
09:44:29 
09:44:29 Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
09:44:29 Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease
09:44:29 Get:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
09:44:29 Ign:4 https://packages.cloud.google.com/apt kubernetes-xenial-unstable InRelease
09:44:29 Err:5 https://packages.cloud.google.com/apt kubernetes-xenial-unstable Release
09:44:29   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 142.251.214.142 443]
09:44:30 Get:6 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
09:44:30 Get:7 http://us.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
09:44:30 Reading package lists...
09:44:31 E: The repository 'http://apt.kubernetes.io/ kubernetes-xenial-unstable Release' no longer has a Release file.
```
Are you able to check this PR to see if there are likely to be problems again? Thanks

**Comment by stevenhorsman** [comment]
@arronwy - can you check the TDX qemu test please to see if the job failed with an infrastructure issues, or if it is related to the code change. Thanks!

**Review by stevenhorsman — APPROVED** [review]

**Comment by stevenhorsman** [comment]
Only s390x tests failing, which is a known error, so merging this now

**Pull request merged**
