### PR TITLE
Jenkins call static checks

### LINKED ISSUE #102: Update jenkins script to call checkcommits
At some point, we'll be dropping Travis and switching entirely to Jenkins so add back the logic from the Clear Containers jenkins script to call [checkcommits](https://github.com/kata-containers/tests/tree/master/cmd/checkcommits).

### PR DESCRIPTION
**Pull request by jodh-intel**
Ensure Jenkins jobs call the static checks before running setup and the
tests.

Fixes #102.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
What's not immediately obvious about this change is that once it lands the main repos will be calling the static checks *twice*:

- once under Travis.
- once under Jenkins.

Once this lands, I don't see why we can't go around removing the static check call from all the `.travis.yml` files.

wdyt @chavafg?

**Comment by chavafg** [comment]
Well, I think we still need to add the unit tests execution on the `.ci/run.sh` scripts, right? and `codecov.io` also?

**Comment by chavafg** [comment]
lgtm

**Comment by grahamwhaley** [comment]
Right, so, just so we are clear - we now have a single unified static check method (hooray!), as compared to say https://github.com/clearcontainers/runtime/blob/master/Makefile#L506 where we had a slightly different method and call coded into each individual repo...

And thus, we are unifying the single static call into the CI main level script - yes?

**Comment by jodh-intel** [comment]
@grahamwhaley - that's right. Currently the kata components all call that static script themselves (via Travis), but the ideal is for them to just call a single script (the jenkins setup script) and have that call the static checks so that we centralise the CI logic in this repo.

**Pull request merged**
