### PR TITLE
metrics: CI: enable percentage reporting

### PR DESCRIPTION
**Pull request by grahamwhaley**
Enable checkmetrics percentage reporting mode in the
metrics CI run script.

Fixes: #517

Signed-off-by: Graham Whaley <graham.whaley@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Relies on #504 being merged.

**Comment by grahamwhaley** [comment]
Rebased and pushed to kick a CI rebuild, as although this change does not actually get run in the QA CI, they had all failed due to I believe the now worked-around/fixed crio issues...

**Comment by grahamwhaley** [comment]
Yeah, best to wait for #504, or the metrics CI will start failing (not that that will block anything, but me...).
Looks like we need one more ack as well here...

**Comment by sboeuf** [comment]
I just put the DNM label so that it does not get merged by mistake!

**Comment by egernst** [comment]
merged 504.  should be good now.

**Pull request merged**
