### PR TITLE
tests: test for leaking processes

### LINKED ISSUE #546: Testcase for processes(proxy/shim) left behind
Test case:

```
Terminal 1:
$ docker run -ti -v /tmp/a/hello:/hello --runtime kata busybox sh
/

Terminal 2:
$ rm -fv /tmp/a/hello

Terminal 1: exit the container
/ exit
```

We can observe that there's proxy and shim left.

### PR DESCRIPTION
**Pull request by WeiZhang555**
Fixes #546

This test case addresses this situation:

```
Terminal 1:
$ docker run -ti -v /tmp/a/hello:/hello --runtime kata busybox sh
/

Terminal 2:
$ rm -fv /tmp/a/hello

Terminal 1: exit the container
/ exit
```

Even we removed the volume source file, there shouldn't be any kata-proxy
or kata-shim or qemu process left behind.

Signed-off-by: Wei Zhang <zhangwei555@huawei.com>

### CODE REVIEW

**Comment by WeiZhang555** [comment]
Related: https://github.com/kata-containers/runtime/pull/531

**Comment by WeiZhang555** [comment]
The test case failure is exposed in K8S cleanup script:

https://github.com/kata-containers/tests/blob/master/integration/kubernetes/cleanup_env.sh#L11-L21

This is a workaround and initial problem is fixed in latest kube-adm, not sure if we can remove this or not. I can remove that if we are sure it's already ok without the workaround

**Comment by jodh-intel** [comment]
I'm not seeing a testcase failure here so maybe that was from a previous CI run?

lgtm

**Comment by GabyCT** [comment]
lgtm

**Pull request merged**
