### PR TITLE
ci: run runtime's unit tests in centos

### LINKED ISSUE #1413: ci: run runtime's unit tests in centos

### PR DESCRIPTION
**Pull request by devimc**
run runtime's unit tests in centos

fixes #1413

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
We need the PR runtime to be first merged

**Comment by jodh-intel** [comment]
@devimc:

- See my question on https://github.com/kata-containers/runtime/issues/1517.

- fwics on https://github.com/kata-containers/runtime/issues/1517, the only test failing on RHEL is `TestHostNetworkingRequested`. So rather like the idea on https://github.com/kata-containers/tests/issues/59, why don't we simply skip that single test on RHEL? Something like:

```go
if kata.Distro("rhel") {
    Skip("Issue: ...")
}
```

That way, we'd still be testing most of the code on RHEL.

/cc @amshinde.

**Comment by jodh-intel** [comment]
@devimc - we could land this "as-is" - I've got some code that might do what we want later to just run this test: https://github.com/kata-containers/tests/issues/1496.

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/runtime/pull/1587.

**Pull request merged**
