### PR TITLE
tests: Enable e2e k8s tests with containerd-shim-kata-v2

### LINKED ISSUE #2843: crio: Run the kubernetes e2e_conformance tests using `containerd-shim-kata-v2`
Currently we run the kubernetes e2e_conformance tests using only the `kata-runtime` runtime, which used the OCI runtime type from CRI-O. As we'd like to ensure `containerd-shim-kata-v2` and the VM runtime type are also working as expected (and catch regressions as soon as possible), we should extend those tests to also run with `containerd-shim-kata-v2`.

For the future me, or whoever will implement this, you must look at: https://github.com/kata-containers/tests/blob/a5a7c59c3f9c9ac6050350f4ecf297961ba13e74/integration/kubernetes/e2e_conformance/run.sh#L26

### PR DESCRIPTION
**Pull request by GabyCT**
This PR enables the e2e k8s minimal tests with the containerd-shim-kata-v2.

Fixes #2843

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
\o/

**Review by devimc — APPROVED** [review]
lgtm - thanks @GabyCT

**Pull request merged**
