### PR TITLE
ci: Add haveged to generate entropy in CI.

### PR DESCRIPTION
**Pull request by jcvenegas**
Add haveged will allow have entropy for PR.

https://github.com/kata-containers/runtime/pull/676

Fixes: #712

### CODE REVIEW

**Comment by chavafg** [comment]
lgtm

**Comment by jodh-intel** [comment]
lgtm

**Comment by caoruidong** [comment]
lgtm
BTW looks like today pullapprove  dislike @jodh-intel

**Comment by jodh-intel** [comment]
:cry:

**Pull request merged**
