### PR TITLE
github: Enable github actions

### LINKED ISSUE #3127: enable github actions
Enable github actions for test repository

### PR DESCRIPTION
**Pull request by GabyCT**
This PR enables the github actions for test repository.

Fixes #3127

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
I am having an error in the `static-checks.sh`
```
Run test_repo=$(go env GOPATH)/src/github.com/kata-containers/tests
~/go/src/github.com/kata-containers/tests ~/work/tests/tests
INFO: Running 'static_check_commits' function
INFO: adding '\[Serial Test\]' to 'SKIP_GINKGO_PARALLEL'
INFO: adding '\[Serial Test\]' to 'FOCUS_GINKGO_SERIAL'
make -C cmd/checkcommits
make[1]: Entering directory '/home/runner/work/tests/tests/cmd/checkcommits'
go test .
checkcommits.go:18:2: cannot find package "github.com/urfave/cli" in any of:
	/opt/hostedtoolcache/go/1.13.15/x64/src/github.com/urfave/cli (from $GOROOT)
	/home/runner/go/src/github.com/urfave/cli (from $GOPATH)
Makefile:15: recipe for target 'checkcommits' failed
make[1]: *** [checkcommits] Error 1
make[1]: Leaving directory '/home/runner/work/tests/tests/cmd/checkcommits'
Makefile:98: recipe for target 'checkcommits' failed
make: *** [checkcommits] Error 2
Error: Process completed with exit code 2.
```
any idea @jodh-intel @amshinde @chavafg ?

**Comment by amshinde** [comment]
@GabyCT The workflow is now passing. 
I think the issue here was that the checkcommits tool present under cmd/checkcommits had its dependencies in the parent vendor directory. From what I have read, this works as long as the  repo itself is under $GOPATH. Although you created a symlink for the location where the code is checked out by actions@checkout, this does not seem to work. 
Copying the vendor directory manually to the subdirectories also does not work. 

One option would be to install dependencies using go install, but I did not want to go down that path.
I saw that the actions@checkout cannot really checkout code under any predefined directory in this case under $GOPATH. It can checkout code relative to the {{github.workspace}}. So I have redefined the $GOPATH instead in the go setup and subsequent steps. This wasnt as starightforward as I had expected. 
But with this change, the checkcommits code now looks for dependencies in its parent directory since the repository is now under $GOPATH. Please take a look.

**Comment by GabyCT** [comment]
@amshinde thanks

**Review by chavafg — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Pull request merged**
