### PR TITLE
metrics: nest json results in unique subsections

### PR DESCRIPTION
**Pull request by grahamwhaley**
To avoid any JSON name space/value type clashes, we nest each different tests
results into a section named by the test name.

This also then needs any code or examples that reference that data to be updated.

### CODE REVIEW

**Comment by grahamwhaley** [comment]
This is related to how we store our data into elasticsearch over on https://github.com/kata-containers/ci/issues/60

Note, marked as DNM right now, because as soon as this lands the metrics CI configs will need updating to take into account the new data format - so we will potentially have a few metrics glitches.

As I'm landing this on a Friday evening (yay, that old :chestnut: @jodh-intel ;-) ), I thought I'd go for DNM until it gets a bit of review, and then we can do the fast-hand land/fix in a sync'd manner to reduce the fallout.

@GabyCT - have a look. The final results (such as the genreport output) do not change, just the internal structure of the final JSON files. Nobody should notice - apart from anybody 'looking' in the data, which is mostly you and I ;-)

**Comment by jodh-intel** [comment]
lgtm

It might be interesting if you could paste an example of the "before" and "after" formats here inside ` ```json ` blocks :)

**Comment by grahamwhaley** [comment]
Will do Monday with some real data. Basically, it goes from...

```json
generic system stuff here....
,
"Results" : {
 blah specific to the test in question
}
```

to 
```json
generic system stuff here....
,
"test-name" : {
  "Results" : {
   blah specific to the test in question
  }
}
```

**Comment by GabyCT** [comment]
@grahamwhaley , let me take a look :)

**Comment by GabyCT** [comment]
@jodh-intel , here it is `json` example

Before this PR
```
...
        "Config": [
                        {
                "containers": 20,
                "ksm": 0,
                "auto": "",
                "waittime": 5,
                "image": "busybox",
                "command": "sh"
        }
        ],
        "Results": [
                        {
                "average": {
                        "Result": 139772.58,
                        "Units" : "KB"
                },
                "qemus": {
                        "Result": 135491.70,
                        "Units" : "KB"
                },
                "shims": {
                        "Result": 4105.15,
                        "Units" : "KB"
                },
                "proxys": {
                        "Result": 175.73,
                        "Units" : "KB"
                }
        }
...
```

After this PR

```
...
"memory-footprint" : {
        "Config": [
                        {
                "containers": 20,
                "ksm": 0,
                "auto": "",
                "waittime": 5,
                "image": "busybox",
                "command": "sh"
        }
        ],
        "Results": [
                        {
                "average": {
                        "Result": 153275.35,
                        "Units" : "KB"
                },
                "qemus": {
                        "Result": 145836.85,
                        "Units" : "KB"
                },
                "shims": {
                        "Result": 7039.75,
                        "Units" : "KB"
                },
                "proxys": {
                        "Result": 398.75,
                        "Units" : "KB"
                }
        }
        ],
...
```

I did not paste the full `json` but just the part that @grahamwhaley is adding, I hope it helps to give you an idea :)

**Comment by jodh-intel** [comment]
Thanks @grahamwhaley and @GabyCT.

**Comment by grahamwhaley** [comment]
dropping the DNM. The nesting works (I see it in elastic), and I believe is necessary.

**Comment by grahamwhaley** [comment]
even though I don't believe the tests will run this code.... I'm going to fire them so we get a nice clear BIG GREEN BUTTON ;-)

**Pull request merged**
