### PR TITLE
CC | Merge from `main`  to `CCv0` -  July 25th.

### PR DESCRIPTION
**Pull request by fidencio**
This is the weekly's merge from `main` to `CCv0`, and this is a special
"Steve's vacation" edition.

Considering Steve is off, enjoying his well deserved PTO, I'm here to
bring this merge (and hey, expect this to be messier than usual).

There were **no** conflicts on this.

### CODE REVIEW

**Comment by fidencio** [comment]
http://10.112.240.228:8080/job/tests-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/572/ passed but didn't report back
http://10.112.240.228:8080/job/tests-CCv0-qemu-TDX-CRI_CONTAINERD_K8S-PR/584/ passed but didn't report back

**Review by sameo — APPROVED** [review]

**Comment by fidencio** [comment]
I will go ahead an merge this one, as it will help with the static check failures from its Kata Containers counterpart.

**Pull request merged**
