### PR TITLE
ci: vfio: bump fedora version

### LINKED ISSUE #3073: vfio: ci: 1.x: waiting for VM to start
Unable to login the VM 

```
09:28:09 INFO: waiting for VM to start
09:28:09 + sleep 5
09:28:14 + for i in $(seq 1 30)
09:28:14 + ssh_vm true
09:28:14 + cmd=true
09:28:14 + ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i /home/jenkins/vfio-test/key -p 10022 jenkins@127.0.15.1 true
09:28:14 + info 'waiting for VM to start'
09:28:14 + echo -e 'INFO: waiting for VM to start'
09:28:14 INFO: waiting for VM to start
```

### PR DESCRIPTION
**Pull request by devimc**
fixes #3073

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @devimc!

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
