### PR TITLE
tests: Docker integration tests for export, diff, env and exit code.

### LINKED ISSUE #44: Docker integration tests for export, diff, env and exit code.
This will test docker integration functionality for export, diff, env and exit code.

### PR DESCRIPTION
**Pull request by GabyCT**
This will test docker integration functionality for export, diff, env and
exit code.

Fixes #44

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks @GabyCT.

lgtm

**Comment by jodh-intel** [comment]
ping @kata-containers/tests.

**Comment by chavafg** [comment]
lgtm

**Comment by jcvenegas** [comment]
lgtm

**Pull request merged**
