### PR TITLE
install: Setup docker runtime in config json

### PR DESCRIPTION
**Pull request by jcvenegas**
If kata-deploy is installed along with kata from CI scripts,
docker config will have conflicts. Instead use config with 
daemon.json to avoid dockerd config conflicts. 

Fixes: #2991

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]

**Comment by fidencio** [comment]
@jcvenegas, do we still want to have this one merged for the final 1.13.0 release?

**Comment by fidencio** [comment]
@jcvenegas, can you try to rebase this one atop of current `master`?  I think this is valid and should be part of the final release.

**Comment by jcvenegas** [comment]
closing this PR, we can rework  for main branch.

**Pull request closed without merging**
