### PR TITLE
scripts: Remove go-test.sh script

### LINKED ISSUE #4753: Remove go-test.sh
# Description of problem

https://github.com/kata-containers/kata-containers/pull/4191 imports the `go-test.sh` script from the tests repository before simplifying it.  Since the script is now in the main repository, it doesn't need to be in the test repository any more.

### PR DESCRIPTION
**Pull request by dgibson**
This script has been moved into the main source repository by
https://github.com/kata-containers/kata-containers/pull/4191, so it can
now be removed from the tests repository.

fixes #4753

Depends-on: https://github.com/kata-containers/kata-containers/pull/4191

Signed-off-by: David Gibson <david@gibson.dropbear.id.au>

### CODE REVIEW

**Review by snir911 — APPROVED** [review]
LTGM thanks

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @dgibson !

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
