### PR TITLE
integration/docker: Add ulimit tests

### LINKED ISSUE #986: Add tests to check resource limits
add test to check rlimits, see https://github.com/kata-containers/agent/pull/431

### PR DESCRIPTION
**Pull request by devimc**
Ulimit tests are to check resource limits in the container

fixes #986

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by GabyCT** [comment]
lgtm

**Comment by chavafg** [comment]
@devimc ulimits tests failed on ARM and ubuntu initrd jobs, can you check?

**Comment by devimc** [comment]
@chavafg I don't know what is the problem with ARM CI

```
Stderr: time="2018-12-11T22:16:21+08:00" level=error msg="open /tmp/bundle422560944/log: no such file or directory" arch=arm64 name=kata-runtime pid=67650 source=runtime
open /tmp/bundle422560944/log: no such file or directory
```

**Comment by devimc** [comment]
ohh I see the error

```
Running command '/usr/bin/docker [docker run --cidfile /tmp/cid860034542/tGu5KEkRwSHelH6o33QBq1gPPVxIty --runtime kata-runtime --name tGu5KEkRwSHelH6o33QBq1gPPVxIty --rm --ulimit data=512000:665600 centos bash -c echo $(ulimit -d -S):$(ulimit -d -H)]'
command failed error 'exit status 125'
[docker run --cidfile /tmp/cid860034542/tGu5KEkRwSHelH6o33QBq1gPPVxIty --runtime kata-runtime --name tGu5KEkRwSHelH6o33QBq1gPPVxIty --rm --ulimit data=512000:665600 centos bash -c echo $(ulimit -d -S):$(ulimit -d -H)]
Timeout: 60 seconds
Exit Code: 125
Stdout: 
Stderr: runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7fbf3de97c m=3 sigcode=18446744073709551610
```

**Comment by Pennyzct** [comment]
Hi~ @devimc if you want to skip one docker intergration test on aarch64, you can modify the [configuration_aarch64.yaml ](https://github.com/kata-containers/tests/blob/master/.ci/aarch64/configuration_aarch64.yaml). you could add one new item `- check ulimits` under `Describe` to skip ulimit test. This file keep arch-related code out of generic test code. 
```
docker:

  Describe:

    - CPUs and CPU set

    - Update number of CPUs

    - Hot plug CPUs

    - Update CPU constraints

    - memory constraints

    - Hotplug memory when create containers

    - run container and update its memory constraints

    - check ulimits
```

**Comment by devimc** [comment]
thanks @Pennyzct

**Pull request merged**
