### PR TITLE
ci: Add user agent back into curl request

### PR DESCRIPTION
**Pull request by stevenhorsman**
Add user agent back into curl request after it was removed in #4883

Fixes: #5185
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
I have a test PR I used to reproduce this: https://github.com/kata-containers/kata-containers/pull/5371. I'm not 100% sure how we test it before it is merged though as I think we need to trigger the static checks on the kata-containers repo and the static-checks don't use the Depends-on IIRC.

**Comment by liubin** [comment]
Thank you @stevenhorsman.

I manually tested it with `curl` command, and this should work.

So I'd like to merge this one asap and fix it if it does not work.

**Review by liubin — APPROVED** [review]

**Pull request merged**
