### PR TITLE
 Reorganize the tests - part 4 (new functional/confidential-guest directory) 

### LINKED ISSUE #4645: Re-think the organization of our tests
### Background

Our tests are spread over the `integration`, `functional`, `metrics`, and `tracing` directories so that they can be grouped by type of test.

I wasn't here when those directories were created so I can only take some assumptions. And I assume they were created with the following purposes:

 * integration: to hold tests that assert the integration with external entities. For example, runtimes (containerd, CRI-O,...), engines (docker, podman), systems (Kubernetes). Very often the tests consist of running the external entity suites of tests with Kata Containers configured as the default runtime, so asserting the entity work fine. 
 * functional: contain tests that assert a specific feature . For example, the ability run a rootless VMM (see https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-run-rootless-vmm.md).
 * metrics: to hold tests that ensure no performance regressions are introduced. This is the home of the metrics CI.
 * tracing: I don't know why it exists, maybe it belongs to functional.

### The problem

We didn't document the purpose of those directories nor provide clear guidelines about where new tests better fit in. As a result, over the time we end up with most of the tests landing in the `integration` directory although many are actually functional tests. Also what seems to be new categories (the stability tests) also ended up in `integration`.  

### Proposing a reorganization

Here I propose two things:

1. that we re-organize the tests
1. that we document the new organization and provide guidelines for the developers

As for 1), I propose that we:
 * [ ] create a new directory `stability` out of `integration` to hold the stability tests
 * [ ] move `tracing` to `functional` as it is actually a functional test
 * [ ] move `agent`, `ksm`,  `pmem`, `rootless`,  `sandbox_cgroup`, `vcpus` from `integration` to `functional`
 * keep `containerd`, `cri-o`, `kubernetes`, **`nydus`, **`qat`  in `integration`
 * [ ] rename `functional/tdx` to `functional/confidential_guest` as likely soon there will be tests for other technologies like AMD SEV.

(**) I still don't have a strong option about `integration/nydus` and `integration/qat` but maybe they logically belong to integration.

Regarding 2), I propose that we:
 * create a new advice-style document for the non-unit tests. For unit tests we already have advises: https://github.com/kata-containers/kata-containers/blob/main/docs/Unit-Test-Advice.md

### PR DESCRIPTION
**Pull request by wainersm**
Continuing part 1 (https://github.com/kata-containers/tests/pull/4751), 2 (https://github.com/kata-containers/tests/pull/4752) and 3(https://github.com/kata-containers/tests/pull/4758)...

Created the directory `functional/confidential-guest` to hold tests for the confidential guest feature. Currently we only have tests for Intel TDX but in the future it is likely we will have for AMD SEV and more, so this prepare the ground.

While here I created an entry point `run.sh` script which calls tests specific for the `$TEE_TYPE`, as well as a new makefile target (`confidential-guest`).

Fixes #4645

### CODE REVIEW

**Comment by wainersm** [comment]
I set the `wip` label because I don't have access to a TDX machine to test this PR. I believe that @kata-containers/intel team maintain a CI for TDX and this change is going to break it. So I will remove the label after proper testing.

@devimc @GabyCT could you please help with testing? :)

**Comment by wainersm** [comment]
Also, I am using the variable `TEE_TYPE` to switch between the implementations (tdx, sev, etc...) because it is already the variable used on scripts (e.g. `.ci/install_kata.sh`) to handle installation for TDX testing.  However I don't know for sure whether TDX is conceptually a TEE type or not.

**Review by amshinde — APPROVED** [review]

**Comment by amshinde** [comment]
> Also, I am using the variable `TEE_TYPE` to switch between the implementations (tdx, sev, etc...) because it is already the variable used on scripts (e.g. `.ci/install_kata.sh`) to handle installation for TDX testing. However I don't know for sure whether TDX is conceptually a TEE type or not.

@wainersm TDX should fall under as another type of TEE.

**Review by jodh-intel — APPROVED** [review]

**Comment by fidencio** [comment]
As we're in the process (a still long process) of moving tests from this repo to the kata-containers one, we're closing PRs that are either stale for too long.

Please, if you think this has been mistakenly closed, open it agains the `kata-containers` repo as in the coming months this repo will be archived.

**Pull request closed without merging**
