### PR TITLE
metrics: Support sync engine configuration for FIO tests

### LINKED ISSUE #4930: Support sync engine configuration for FIO tests

### PR DESCRIPTION
**Pull request by GabyCT**
This PR adds the support for sync engine configuration to gathered synchronous
FIO test results.

Fixes #4930

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Review by dborquez — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
