### PR TITLE
containerd: Skip using the config provided by cri

### LINKED ISSUE #2002: Try to enable ipv6 in CI to see if container 1.3.0 CI passes.
The script to install sample CNI config in the CRI repo now
expplicitly installs ipv6 routes for containerd 1.3.0.
So enable sysctl settingg for ipv6.

### PR DESCRIPTION
**Pull request by amshinde**
The cni config used for tests from the cri repo has ipv6 routes.
Skip this and use a cni config used for crio as well.

Depends-on: github.com/kata-containers/runtime#2100

Fixes #2002

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
I see the next failure on the containerd job:

```
19:54:59 [init] Using Kubernetes version: v1.15.3
19:54:59 [preflight] Running pre-flight checks
19:54:59 error execution phase preflight: [preflight] Some fatal errors occurred:
19:54:59 	[ERROR CRI]: container runtime is not running: output: time="2019-10-31T01:54:59Z" level=fatal msg="getting status of runtime failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
19:54:59 , error: exit status 1
```

**Comment by amshinde** [comment]
@lifupan Seeing the CRI validation suite failing here with containerd 1.3.0:
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-18-04-PR-initrd/2289/consoleFull

Any inputs?

**Comment by lifupan** [comment]
> @lifupan Seeing the CRI validation suite failing here with containerd 1.3.0:
> http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-18-04-PR-initrd/2289/consoleFull
> 
> Any inputs?

Hi @amshinde 

I had took a look and found the failure was related with vm template, but I couldn't reproduce it and I tried relaunch this CI successfully. I will keep an eye on this issue to see would it be appear again.

**Comment by amshinde** [comment]
@jcvenegas Can you take a look. 
I see that you had touched the code prior to this introducing logic to switch to cni config provided by cri.

**Comment by amshinde** [comment]
Finally green!
@chavafg Can you merge this one and the runtime one as well.

**Pull request merged**
