### PR TITLE
stable-2.4 | Second round of backports for the 2.4.1 release

### PR DESCRIPTION
**Pull request by fidencio**
This round includes fixes for the following issues:
* #4732

### CODE REVIEW

**Comment by fidencio** [comment]
The `clh-devmapper` failure happened here as the https://github.com/kata-containers/kata-containers/pull/4202 has backport that's needed.

**Review by snir911 — APPROVED** [review]
LGTM thanks

**Comment by fidencio** [comment]
@BbolroC, s390x failing: http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-s390x-PR/847/

**Review by chavafg — APPROVED** [review]

**Comment by fidencio** [comment]
/retest-devmapper-clh

As the kata-containers PR has been merged.

**Review by fgiudici — APPROVED** [review]
Well, I just realized we already have 2 approvals here... anyway, for what is worthLGTM too, thanks!

**Pull request merged**
