### PR TITLE
Merge `main` branch into `CCv0`

### PR DESCRIPTION
**Pull request by stevenhorsman**
Weekly merge of `main` into `CCv0` to keep it up to date

Fixes: #4225

### CODE REVIEW

**Comment by stevenhorsman** [comment]
```
$ git diff --stat upstream/main -- . ':!*/vendor/*'
 .ci/configure_cni.sh                            |  2 +-
 .ci/install_cri_containerd.sh                   | 31 +++++++++++++++++++++++++++----
 .ci/install_kata_image.sh                       | 12 +++++++++---
 .ci/jenkins_job_build.sh                        |  6 ++++++
 .ci/lib.sh                                      |  8 ++++++++
 .ci/static-checks.sh                            | 13 ++++++++++---
 README.md                                       | 12 ++++++------
 cmd/github-labels/labels.yaml.in                |  4 ++--
 cmd/pmemctl/pmemctl.sh                          |  2 +-
 integration/containerd/cri/integration-tests.sh |  2 ++
 integration/kubernetes/e2e_conformance/setup.sh |  2 +-
 versions.yaml                                   |  2 +-
 12 files changed, 74 insertions(+), 22 deletions(-)
```

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Comment by fidencio** [comment]
Ouch:
```
12:39:26 Rebasing (1/9)
Rebasing (2/9)
Rebasing (3/9)
Rebasing (4/9)
error: could not apply d2fcba00... integration: containerd cri integration tests using containerd repo
12:39:26 Resolve all conflicts manually, mark them as resolved with
12:39:26 "git add/rm <conflicted_files>", then run "git rebase --continue".
12:39:26 You can instead skip this commit: run "git rebase --skip".
12:39:26 To abort and get back to the state before "git rebase", run "git rebase --abort".
12:39:26 Could not apply d2fcba00... integration: containerd cri integration tests using containerd repo
12:39:26 Auto-merging integration/containerd/cri/integration-tests.sh
12:39:26 CONFLICT (content): Merge conflict in integration/containerd/cri/integration-tests.sh
12:39:26 Auto-merging .ci/lib.sh
12:39:26 Auto-merging .ci/install_cri_containerd.sh
12:39:26 ++ handle_error 77
12:39:26 ++ local exit_code=1
12:39:26 ++ local line_number=77
12:39:26 ++ echo 'Failed at /tmp/jenkins/workspace/kata-containers-CCv0-tests-fedora-PR/ci_entry_point.sh +77: git rebase "origin/${ghprbTargetBranch}"'
12:39:26 Failed at /tmp/jenkins/workspace/kata-containers-CCv0-tests-fedora-PR/ci_entry_point.sh +77: git rebase "origin/${ghprbTargetBranch}"
12:39:26 ++ exit 1
12:39:26 Build step 'Execute shell' marked build as failure
```

**Comment by stevenhorsman** [comment]
> Ouch

Any ideas how I can fix this except for a rebase that will mess up the history and result in a force push, which we wanted to avoid here?

**Comment by stevenhorsman** [comment]
@fidencio - do you think this is just a limitation with the way that the CI works by doing the rebase?
Is there a another approach than just doing the `tests` repo push and backing out if it goes wrong?

**Comment by stevenhorsman** [comment]
My new idea on this (which might not be a good one), is that I've created https://github.com/kata-containers/tests/pull/4228 as a copy of this branch, but I have run the rebase on that one. This has resulted in identical branches, with no code differences:
```
$ git branch
  CCv0
* ccv0-rebased
 ...
Stevens-MacBook-Pro-2019:tests stevenh$ git diff --stat origin/CCv0
Stevens-MacBook-Pro-2019:tests stevenh$ 
```
But the commit history is different due to the rebase.
My theory is that I can run the CI on #4228 and confirm that it works allowing this to be merged even though the CI code's rebase process is not compatible. Happy to hear opinions if this is an adequate work around, or other people have better ideas

**Comment by stevenhorsman** [comment]
@fidencio - I'd like your opinion on this PR. I have created a [PR with identical code](https://github.com/kata-containers/tests/pull/4228), but different commit history and that passes all the tests and https://github.com/kata-containers/kata-containers/pull/3133 which depends on this PR now passes all its tests too. Do you think that is sufficient for us to override the jenkins jobs checks and merge this (along with the matching kata-containers PR)?

**Comment by sameo** [comment]
> @fidencio - I'd like your opinion on this PR. I have created a [PR with identical code](https://github.com/kata-containers/tests/pull/4228), but different commit history and that passes all the tests and [kata-containers/kata-containers#3133](https://github.com/kata-containers/kata-containers/pull/3133) which depends on this PR now passes all its tests too. Do you think that is sufficient for us to override the jenkins jobs checks and merge this (along with the matching kata-containers PR)?

We should merge that one. @stevenhorsman Thanks a lot for the effort of putting #4228 to show that this one can be merged.

@fidencio, unless you have objections I will go ahead and merge that PR.

**Comment by fidencio** [comment]
@stevenhorsman, @sameo, I am really sorry I missed this message here, and thanks for the gentle poke at the #confidential-containes channel.  For the future, please, do not hesitate in pinging me if I don't reply in half-day or so.

I have one light objection on merging thus, mainly considering https://github.com/kata-containers/tests/pull/4228, as I think our CI may be broken forever from now on.

What I'd recommend to do, sincerely, is try to get rid of all in-flight PRs for this branch (which right now is none: https://github.com/kata-containers/tests/pulls?q=is%3Apr+is%3Aopen+CCv0) and then force-push into this branch (as in, go for https://github.com/kata-containers/tests/pull/4228 rather than going for this one), as long as we have the agreement from @bpradipt and @jodh-intel on doing this, as they were the ones who raised the preference on going for the merge approach.

Does this sound reasonable?

**Comment by stevenhorsman** [comment]
> I have one light objection on merging this one, mainly considering #4228, as I think our CI may be broken forever from now on.

So my (limited) understanding based on the code is that it only does a rebase of the PR branch on the target branch, meaning once it is merged in the rebase will never be attempted?

> What I'd recommend to do, sincerely, is try to get rid of all in-flight PRs for this branch (which right now is none: https://github.com/kata-containers/tests/pulls?q=is%3Apr+is%3Aopen+CCv0) and then force-push into this branch (as in, go for #4228 rather than going for this one), as long as we have the agreement from @bpradipt and @jodh-intel on doing this, as they were the ones who raised the preference on going for the merge approach.
> 
> Does this sound reasonable?

If we want to take the force push approach then #4228 isn't the right branch as it is effectively the delta of `main` and `CCv0` rebased on `CCv0` which will cause any commits into main in the last week to have their history re-done which will probably be a mess if we ever want to merge CCv0 contents into `main`. However I can create a branch which is `CCv0` rebased on `main` and force push this, if that is the choice made.

**Comment by sameo** [comment]
@stevenhorsman @fidencio @jodh-intel @bpradipt 
> However I can create a branch which is CCv0 rebased on main and force push this, if that is the choice made.

I would definitely prefer going with that.

**Comment by fidencio** [comment]
> @stevenhorsman @fidencio @jodh-intel @bpradipt
> 
> > However I can create a branch which is CCv0 rebased on main and force push this, if that is the choice made.
> 
> I would definitely prefer going with that.

+1 here.

**Comment by fidencio** [comment]
> > I have one light objection on merging this one, mainly considering #4228, as I think our CI may be broken forever from now on.
> 
> So my (limited) understanding based on the code is that it only does a rebase of the PR branch on the target branch, meaning once it is merged in the rebase will never be attempted?

Hmm. I'm not sure how CI would behave on a commit after this one, sincerely.
Maybe it's a matter of trying and if something goes wrong we roll back to another approach?

**Comment by stevenhorsman** [comment]
I guess the other approach is I try deleting the [rebase line](https://github.com/kata-containers/tests/blob/1ff30ebd9aa45969e9e16f50a707a30eaa881ad1/.ci/ci_entry_point.sh#L77) in the `CCv0` branch and see if there are any issues, but I'm not quite sure what it is for other than to catch this issue.

**Comment by stevenhorsman** [comment]
Based on the slack conversation we decided to force push `CCv0` rebased on `main` instead

**Comment by sameo** [comment]
Thanks @stevenhorsman !

**Pull request merged**
