### PR TITLE
metrics report update series

### PR DESCRIPTION
**Pull request by grahamwhaley**
A series of metrics report related updates, including:

- Add stats tables to fio pages
- Improve colour usage on system density graph
- Enable system info tables for `runc`
- A couple of other minor related bug/warn fixes

### CODE REVIEW

**Comment by grahamwhaley** [comment]
@mcastelino, this series includes the fio stats tables we discussed.
@eadamsintel, this improves the colour and point type usage on the system scaling graph, which you might be interested in.

**Comment by GabyCT** [comment]
@grahamwhaley , is there a reason why fio is not included at  `grabdata.sh`?

**Comment by grahamwhaley** [comment]
ping @kata-containers/tests - just in case anybody wants to review, or give it a quick spin?

**Comment by caoruidong** [comment]
lgtm, but not very familiar with R language :)

**Comment by grahamwhaley** [comment]
;-) me neither ;-) I had to choose between basically gnuplot, matplotlib or R. I'm sure my R is horrible to an R programmer - but it is currently functional :-)

**Comment by chavafg** [comment]
lgtm

**Pull request merged**
