### PR TITLE
Add test for translation of PCIDEVICE_ environment variables

### PR DESCRIPTION
**Pull request by dgibson**
Addresses the problem described in #4432, and makes a couple of other small improvements along the way.

### CODE REVIEW

**Comment by dgibson** [comment]
Draft for now, since it *should* fail CI until we fix https://github.com/kata-containers/kata-containers/issues/3634

**Review by jodh-intel — APPROVED** [review]
Thanks @dgibson.

lgtm

**Review by devimc — APPROVED** [review]

**Pull request merged**
