### PR TITLE
ci: Remove debian installation

### LINKED ISSUE #4231: remove debian installation

### PR DESCRIPTION
**Pull request by GabyCT**
Currently for kata 2.0 CI we do not have a debian job and we are
not going to supported it as we do not have a maintainer. This PR
removes debian installation scripts in order to have a more cleaner
setup script with only the distros that we are supporting on the CI.

Fixes #4231

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @GabyCT

**Review by jodh-intel — APPROVED** [review]
Thanks @GabyCT.

This is a shame, but we've been looking for someone to help with Debian [for a very long time now](https://github.com/kata-containers/packaging/issues/6#issuecomment-453940053), so this is a sensible solution until we find one.

/cc @zhsj, @zeigerpuppy in case they know of anyone who can help with Kata+Debian?

---

@GabyCT - We should also remove https://github.com/kata-containers/kata-containers/tree/main/tools/osbuilder/rootfs-builder/debian if we're no longer testing that.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

Please, wait till the 2.4.0-alpha0 release is made before merging this one.

**Comment by fidencio** [comment]
```sh
18:43:54 Init cluster using /var/run/crio/crio.sock
18:43:54 [init] Using Kubernetes version: v1.22.0
18:43:54 [preflight] Running pre-flight checks
18:43:54 error execution phase preflight: [preflight] Some fatal errors occurred:
18:43:54 	[ERROR Port-6443]: Port 6443 is in use
18:43:54 	[ERROR Port-10259]: Port 10259 is in use
18:43:54 	[ERROR Port-10257]: Port 10257 is in use
18:43:54 	[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
18:43:54 	[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
18:43:54 	[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
18:43:54 	[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
18:43:54 	[ERROR Port-10250]: Port 10250 is in use
18:43:54 	[ERROR Port-2379]: Port 2379 is in use
18:43:54 	[ERROR Port-2380]: Port 2380 is in use
18:43:54 	[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
18:43:54 [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
18:43:54 To see the stack trace of this error execute with --v=5 or higher
18:43:54 [init.sh:153] ERROR: sudo -E kubeadm init --config /tmp/kubeadm_config.eJrl1I.yaml
18:43:54 [setup.sh:29] ERROR: bash ./init.sh
18:43:54 make: *** [Makefile:67: kubernetes-e2e] Error 1
18:43:54 [run.sh:80] ERROR: sudo -E PATH=/tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR-crio-k8s-e2e-minimal/go/bin:/usr/local/go/bin:/usr/sbin:/sbin:/home/jenkins/.local/bin:/home/jenkins/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin bash -c make kubernetes-e2e
18:43:54 [jenkins_job_build.sh:215] ERROR: .ci/run.sh
18:43:54 ++ handle_error 84
18:43:54 ++ local exit_code=2
18:43:54 ++ local line_number=84
18:43:54 ++ echo 'Failed at /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR-crio-k8s-e2e-minimal/ci_entry_point.sh +84: .ci/jenkins_job_build.sh "${repo_to_test}"'
18:43:54 Failed at /tmp/jenkins/workspace/kata-containers-2.0-tests-fedora-PR-crio-k8s-e2e-minimal/ci_entry_point.sh +84: .ci/jenkins_job_build.sh "${repo_to_test}"
18:43:54 ++ exit 2
18:43:54 Build step 'Execute shell' marked build as failure
18:43:54 Performing Post build task...
18:43:55 Match found for :.* : True
18:43:55 Logical operation result is TRUE
18:43:55 Running script  : #!/bin/bash
```

This is happening with high frequency. @snir911, @c3d, @ariel-adam, what's the action plan on this?

**Comment by fidencio** [comment]
> This is happening with high frequency. @snir911, @c3d, @ariel-adam, what's the action plan on this?

I've opened https://github.com/kata-containers/tests/issues/4235 to track this one.

**Comment by fidencio** [comment]
@GabyCT, just one thing, do you prefer to treat the removal of https://github.com/kata-containers/tests/blob/main/.ci/setup_env_debian.sh as part of this one or on a follow-up PR?

**Comment by fidencio** [comment]
> @GabyCT, just one thing, do you prefer to treat the removal of https://github.com/kata-containers/tests/blob/main/.ci/setup_env_debian.sh as part of this one or on a follow-up PR?

Oh, nevermind, it's removed here, sorry for the noise.

**Pull request merged**
