### PR TITLE
k8s: Enable k8s footloose integration test

### LINKED ISSUE #4773: enable k8s footloose integration test

### PR DESCRIPTION
**Pull request by GabyCT**
This PR enables k8s footloose integration test.

Fixes #4773

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by cmaf — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Pull request merged**
