### PR TITLE
kata-webhook: update dependencies

### PR DESCRIPTION
**Pull request by arc9693**
**Summary**
- This change was required because an outdated dependency of `katawebhook` removes gRPC handler from spec during mutation review, intended to only add runtimeClass name to spec
- This commit aims at updating `katawebhook` dependency from v2.1.0 -> v2.5.0, to support newer versions of k8s, which in turn updates other dependencies.
- The go version in go.mod of kata-webhook is updated from v1.16 -> v1.21, and there is a corresponding change in Dockerfile.

Fixes: https://github.com/kata-containers/kata-containers/issues/7565

Signed-off-by: Archana Choudhary <archana1@microsoft.com>

### CODE REVIEW

**Review by Redent0r — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @arc9693!

**Comment by fidencio** [comment]
@arc9693, you're missing the `Signed-off-by` in your commit and our CI is not happy about that.
https://wiki.linuxfoundation.org/dco

**Comment by arc9693** [comment]
> @arc9693, you're missing the `Signed-off-by` in your commit and our CI is not happy about that. https://wiki.linuxfoundation.org/dco

Updated.

**Review by danmihai1 — APPROVED** [review]

**Comment by ldoktor** [comment]
@arc9693 thank you, I have tested this by pushing this image to `docker.io/ldoktor/kata-webhook-example:latest` and it does address this image. @fidencio could you please push this image to quay (or do you know who has the write access there?)

**Pull request merged**
