### PR TITLE
remove files that for different golang versions

### PR DESCRIPTION
**Pull request by liubin**
We have two files:

- cmd/checkmetrics/round_post9_test.go
- cmd/checkmetrics/round_pre10_test.go

which are used to provide a Round method.

After golang 1.10, we can use  math.Round directly.

Fixes: #5283

Signed-off-by: Bin Liu <bin@hyper.sh>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by cmaf — APPROVED** [review]
thanks @liubin

**Pull request merged**
