### PR TITLE
ci: fix install failure for the webhook

### PR DESCRIPTION
**Pull request by littlejawa**
Update the webhook reference to stop using the deprecated reference.

Fixes: #3996

Signed-off-by: Julien Ropé <jrope@redhat.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@littlejawa, this is quite similar to https://github.com/kata-containers/tests/pull/3809/files, which may contain other important bits, see: https://github.com/kata-containers/tests/pull/3775/files#diff-729b88502c5710ab3ef9cd7cb0580edc95b6731f9925cc3aed21e986d28b3517R14-R16

Considering @dmaizel started the work, I wonder if it's not worth it to also give him credit to it.

**Comment by fidencio** [comment]
Now, the elephant in the room, can we easily build the new image?  IIRC Daniel faced some issues building it that lead to opening a can of worms, which would require moving, for instance, from the `dep` tool to `go mod`, which seems something not so straightforward to do.

**Comment by littlejawa** [comment]
> @littlejawa, this is quite similar to https://github.com/kata-containers/tests/pull/3809/files, which may contain other important bits, see: https://github.com/kata-containers/tests/pull/3775/files#diff-729b88502c5710ab3ef9cd7cb0580edc95b6731f9925cc3aed21e986d28b3517R14-R16
> 
> Considering @dmaizel started the work, I wonder if it's not worth it to also give him credit to it.

Sure. I'll update my patch and reference his. Unless you prefer to merge his PR?

**Comment by littlejawa** [comment]
> Now, the elephant in the room, can we easily build the new image? IIRC Daniel faced some issues building it that lead to opening a can of worms, which would require moving, for instance, from the `dep` tool to `go mod`, which seems something not so straightforward to do.

Ok, I didn't even see the elephant :( 
I'll have to look into that.

**Comment by fidencio** [comment]
> > @littlejawa, this is quite similar to https://github.com/kata-containers/tests/pull/3809/files, which may contain other important bits, see: https://github.com/kata-containers/tests/pull/3775/files#diff-729b88502c5710ab3ef9cd7cb0580edc95b6731f9925cc3aed21e986d28b3517R14-R16
> > Considering @dmaizel started the work, I wonder if it's not worth it to also give him credit to it.
> 
> Sure. I'll update my patch and reference his. Unless you prefer to merge his PR?

I´d rather have yours, with his signed-off-by, as yours is way less intrusive for what we need now.

**Comment by wainersm** [comment]
This fix is very important to https://github.com/kata-containers/tests/issues/3639 as well. It will also unlock a old PR of mine: https://github.com/kata-containers/tests/pull/3647

@littlejawa , please let me know when this PR is ready so I can give it a try.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @littlejawa!

**Comment by littlejawa** [comment]
> This fix is very important to https://github.com/kata-containers/tests/issues/3639 as well. It will also unlock a old PR of mine: https://github.com/kata-containers/tests/pull/3647
> 
> @littlejawa , please let me know when this PR is ready so I can give it a try.

Hey @wainersm, I think you can try it now.

**Review by fgiudici — APPROVED** [review]
LGTM!

**Comment by wainersm** [comment]
> > This fix is very important to #3639 as well. It will also unlock a old PR of mine: #3647
> > @littlejawa , please let me know when this PR is ready so I can give it a try.
> 
> Hey @wainersm, I think you can try it now.

I will give it a try still today and post the results here. thanks @littlejawa !

**Comment by wainersm** [comment]
@littlejawa hi Julien, I installed this PR on top of my changes from https://github.com/kata-containers/tests/pull/3647 then I run the job locally. Unfortunately the webhook is still not working (please see very last message in below snippet). I am trying to debug it; to certify I did not make any mistake :)  

```
Create kata RuntimeClass resource
runtimeclass.node.k8s.io/kata created
node/localhost.localdomain untainted
crictl version v1.21.0
NAME   HANDLER   AGE
kata   kata      1s
Warning: resource runtimeclasses/kata is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
runtimeclass.node.k8s.io/kata configured
NAMESPACE     NAME                                            READY   STATUS    RESTARTS   AGE
kube-system   coredns-558bd4d5db-b5dtp                        1/1     Running   0          35s
kube-system   coredns-558bd4d5db-vjzrg                        1/1     Running   0          35s
kube-system   etcd-localhost.localdomain                      1/1     Running   0          25s
kube-system   kube-apiserver-localhost.localdomain            1/1     Running   0          50s
kube-system   kube-controller-manager-localhost.localdomain   1/1     Running   0          25s
kube-system   kube-flannel-ds-794nk                           1/1     Running   0          35s
kube-system   kube-proxy-lfknh                                1/1     Running   0          36s
kube-system   kube-scheduler-localhost.localdomain            1/1     Running   0          50s
Generating RSA private key, 2048 bit long modulus (2 primes)
....................+++++
........+++++
e is 65537 (0x010001)
Signature ok
subject=CN = pod-annotate-webhook.default.svc
Getting Private key
secret/pod-annotate-webhook-certs created
mutatingwebhookconfiguration.admissionregistration.k8s.io/pod-annotate-webhook created
deployment.apps/pod-annotate-webhook created
service/pod-annotate-webhook created
[webhook-check.sh:70] INFO: Going to check the kata-webhook installation
pod/hello-kata-webhook created
[webhook-check.sh:64] WARNING: RuntimeClassName expected kata, got 
[webhook-check.sh:65] ERROR: kata-webhook is not working
```

**Comment by wainersm** [comment]
yeah, it seems I didn't make any mistake. I believe I should not rebuild the kata-deploy-example image, should I?

Here is a little more information:
```
[vagrant@localhost kata-webhook]$ export KUBECONFIG=/etc/kubernetes/admin.conf 
[vagrant@localhost kata-webhook]$ kubectl get nodes
error: error loading config file "/etc/kubernetes/admin.conf": open /etc/kubernetes/admin.conf: permission denied
[vagrant@localhost kata-webhook]$ sudo kubectl get nodes
NAME                    STATUS   ROLES                  AGE   VERSION
localhost.localdomain   Ready    control-plane,master   17m   v1.21.1
[vagrant@localhost kata-webhook]$ sudo kubectl get deployments
NAME                   READY   UP-TO-DATE   AVAILABLE   AGE
pod-annotate-webhook   1/1     1            1           16m
[vagrant@localhost kata-webhook]$ sudo kubectl logs deployment/pod-annotate-webhook
2021/09/27 20:04:10 [WARN] no metrics recorder active
2021/09/27 20:04:10 [WARN] no tracer active
2021/09/27 20:04:10 [INFO] Listening on :8080
2021/09/27 20:04:10 http: TLS handshake error from 10.244.0.1:35317: remote error: tls: bad certificate
[vagrant@localhost kata-webhook]$ sudo kubectl get pods
NAME                                    READY   STATUS    RESTARTS   AGE
pod-annotate-webhook-55bfb9f7dd-hjm9g   1/1     Running   0          17m
[vagrant@localhost kata-webhook]$ sudo kubectl logs pod/pod-annotate-webhook-55bfb9f7dd-hjm9g
2021/09/27 20:04:10 [WARN] no metrics recorder active
2021/09/27 20:04:10 [WARN] no tracer active
2021/09/27 20:04:10 [INFO] Listening on :8080
2021/09/27 20:04:10 http: TLS handshake error from 10.244.0.1:35317: remote error: tls: bad certificate
[vagrant@localhost kata-webhook]$ ./webhook-check.sh 
[webhook-check.sh:72] INFO: Going to check the kata-webhook installation
[webhook-check.sh:34] ERROR: The pod-annotate-webhook deployment does not exist
[vagrant@localhost kata-webhook]$ vi webhook-check.sh 
[vagrant@localhost kata-webhook]$ sudo ./webhook-check.sh 
[webhook-check.sh:72] INFO: Going to check the kata-webhook installation
[webhook-check.sh:73] ERROR: KUBECONFIG should be exported
[vagrant@localhost kata-webhook]$ sudo -E ./webhook-check.sh 
[webhook-check.sh:72] INFO: Going to check the kata-webhook installation
NAME   HANDLER   AGE
kata   kata      19m
pod/hello-kata-webhook created
[webhook-check.sh:66] WARNING: RuntimeClassName expected kata, got 
[webhook-check.sh:67] ERROR: kata-webhook is not working
[vagrant@localhost kata-webhook]$ vi webhook-check.sh 
[vagrant@localhost kata-webhook]$ sudo kubectl logs pod/pod-annotate-webhook-55bfb9f7dd-hjm9g
2021/09/27 20:04:10 [WARN] no metrics recorder active
2021/09/27 20:04:10 [WARN] no tracer active
2021/09/27 20:04:10 [INFO] Listening on :8080
2021/09/27 20:04:10 http: TLS handshake error from 10.244.0.1:35317: remote error: tls: bad certificate
2021/09/27 20:23:24 http: TLS handshake error from 10.244.0.1:8184: remote error: tls: bad certificate
```

**Comment by littlejawa** [comment]
@wainersm 
Hey Wainer,
My fix was to make the webhook installable again, and it seems you've installed it successfully.
Then I need to update the webhook image on quay.io, but I'll do that when the PR is merged.
For reference, I've been using an updated image for testing, from here: quay.io/littlejawa/kata-webhook:latest

**Comment by wainersm** [comment]
> @wainersm Hey Wainer, My fix was to make the webhook installable again, and it seems you've installed it successfully. Then I need to update the webhook image on quay.io, but I'll do that when the PR is merged. For reference, I've been using an updated image for testing, from here: quay.io/littlejawa/kata-webhook:latest

Hi @littlejawa , true, now the webhook can be at least installed. I'm okay to merge it, I will give my review.

Regarding the image, I tried with yours but it didn't work either. Then I tried to rebuild my own image (see the logs below) and... failed :( 

BTW, I still don't understand why it needs a new image. Is the vendor that was updated?

```
[vagrant@localhost kata-webhook]$ podman build -t quay.io/kata-containers/kata-webhook-example:latest -f Dockerfile ..
STEP 1: FROM golang:latest AS builder
STEP 2: WORKDIR /go/src/kata-pod-annotate
--> Using cache aaf682fb38bb02736184bffb4846cb77f8141a5627a40a254d05e77f614dda59
--> aaf682fb38b
STEP 3: COPY vendor/ ./vendor
--> Using cache ac2356a473d2c542db6734b96d2b26de25e5f9efc207e2b0634a0fdf4beaf5d3
--> ac2356a473d
STEP 4: COPY kata-webhook/* ./
--> e70281e28ca
STEP 5: RUN CGO_ENABLED=0 go build -o /go/bin/kata-pod-annotate
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
STEP 6: FROM alpine:latest
Resolved short name "alpine" to a recorded short-name alias (origin: /etc/containers/registries.conf.d/shortnames.conf)
Error: error building at STEP "RUN CGO_ENABLED=0 go build -o /go/bin/kata-pod-annotate": error while running runtime: exit status 1

```

**Review by wainersm — APPROVED** [review]

**Comment by littlejawa** [comment]
@wainersm - hey Wainer, sorry, I actually forgot a file.
You should be able to build the image now at least.

I've run the test with my image, and now they are passing again without, so... I'm not sure what's needed in it to be honest.

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
