### PR TITLE
DNM: ci: debug CI for CLH

### PR DESCRIPTION
**Pull request by jcvenegas**
debug for kill bug

Fixes: #666

### CODE REVIEW

**Comment by jodh-intel** [comment]
NDM is the new DNM... :smile:

**Comment by jodh-intel** [comment]
NDM => DNM => NTDWS => DWSNT ("Do We Still Need This")? :wink:

**Comment by likebreath** [comment]
@jodh-intel Let’s keep this PR for few more days and will close it with another Debug PR from the runtime repo. Thanks.

**Pull request closed without merging**
