### PR TITLE
CI: DNM Trigger build on s390x Jenkins CI

### PR DESCRIPTION
**Pull request by jschintag**
Just to trigger it.

Fixes: #12345
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>

### CODE REVIEW

**Comment by ganeshmaharaj** [comment]
@jschintag i see s390x job is passing, but i have a feeling the change in README.md is not the one we need to make this part of the default CI run. What should be the next steps here?

/cc @chavafg

**Comment by chavafg** [comment]
@ganeshmaharaj you are right, as this is only changing an MD, we are not running full validation... @jschintag I think you could change another type of file (bats, sh or go), so that full validation is triggered. That way we can see what other issues appear.

**Comment by jschintag** [comment]
@ganeshmaharaj @chavafg Yeah i know, i just wanted to see if there would be any problems with the job in general, before i run the whole job.

**Comment by jschintag** [comment]
/test-s390x

Lets see if that runs the whole job.

**Comment by jschintag** [comment]
The Problem with the CI here #1877 comes from qemu. Here is the related Issue in the Runtime https://github.com/kata-containers/runtime/issues/1153#issuecomment-518129592.
The related PR for govmm is https://github.com/intel/govmm/pull/99.

@grahamwhaley Until this is fixed the s390x CI will keep failing.

````
08:57:21 Stderr: qemu-system-s390x: warning: 'apqci' requires 'ap'.
08:57:21 qemu-system-s390x: warning: 'apft' requires 'ap'.
08:57:21 qemu-system-s390x: -device virtio-serial-ccw,id=serial0,devno=: Property 'virtio-serial-ccw.devno' doesn't take value ''
````

**Comment by jschintag** [comment]
Can i get an DNM Label for this PR?

**Comment by grahamwhaley** [comment]
done @jschintag - are you not able to apply those yourself? You can also add a DNM to your PR subject line..

**Comment by jschintag** [comment]
@grahamwhaley no, i can't assign labels.

**Comment by grahamwhaley** [comment]
@jschintag - ah, I see, it is a github perms thing. You have to be in the 'team' for each repo to gain write powers.... you were only in the ci and jenkins repo teams. sadly I cannot find a github UI that lets me add you to multiple teams in a single click... I have added you to the tests repo team (so you should be able to set labels here now) - just request access to more repo/teams as required (which, I think you can do via the github UI...?)

**Comment by grahamwhaley** [comment]
@jschintag - if the CI is all happy and done now, can we close this?
We can always open another if/when needed - leaving it here not only skews our stats a fraction, but the weekly herders probably have to read/scan over it once a week just to refresh and check what it is and where it is at :-)
thx

**Comment by jschintag** [comment]
@grahamwhaley Since we currently don't have a s390x VM, we aren't really done. But i agree that we could just open a new one when we need it.

**Pull request closed without merging**
