### PR TITLE
Switch to virtio-9p on s390x

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
until leftover shims under virtio-fs (#3998) are resolved.

Fixes: #4406
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
needed another GOPATH-related fix, /test-s390x

**Comment by Jakob-Naucke** [comment]
no, just need `sudo -E` of course... /test-s390x

**Comment by Jakob-Naucke** [comment]
`Wrong number of qemu running (0 != 1) - stopping` /retest-s390x

**Comment by Jakob-Naucke** [comment]
some leftover k8s apparently /retest-s390x

**Comment by Jakob-Naucke** [comment]
at last. /test

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Jakob-Naucke!

I am sad to see the witch back to 9p, though.

**Comment by Jakob-Naucke** [comment]
@fidencio yes, and investigating is far up on my list. But right now it's better to unblock the s390x CI this way rather than disabling it entirely or ignoring failures for another week.

**Pull request merged**
