### PR TITLE
integration/docker: don't use sh to check vCPUs

### LINKED ISSUE #291: random failure runnig CPU tests
```
------------------------------
Hot plug CPUs container with CPU constraint 
  should have 3 CPUs
  /home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-17-10-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
Running command '/usr/bin/docker [docker run --runtime kata-runtime --rm --name xCvv00pByO4rCQLwlgJNlwRHMwDF3r --cpus 2 busybox sh -c c=0; while [[ "$(cat "/sys/fs/cgroup/cpuset/cpuset.cpus")" != "0-2" ]] && [[ $c < 5 ]]; do sleep 5; ((c++)); done; nproc]'
[docker run --runtime kata-runtime --rm --name xCvv00pByO4rCQLwlgJNlwRHMwDF3r --cpus 2 busybox sh -c c=0; while [[ "$(cat "/sys/fs/cgroup/cpuset/cpuset.cpus")" != "0-2" ]] && [[ $c < 5 ]]; do sleep 5; ((c++)); done; nproc]
Timeout: 60 seconds
Exit Code: 0
Stdout: 2

Stderr: sh: can't open 5: no such file
```

and

```
------------------------------
Hot plug CPUs container with CPU constraint 
  should have 2 CPUs
  /home/jenkins/jenkins_slave/workspace/kata-containers-tests-centos-7-4-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
Running command '/usr/bin/docker [docker run --runtime kata-runtime --rm --name YPR7jS4Oeg7HJQJ8nFEjRRDPylLpG6 --cpus 1 debian bash -c for c in $(seq 1 5); do [ -d /sys/devices/system/cpu/cpu1 ] && exit 0; sleep 5; done; exit 1]'
command failed error 'exit status 126'
[docker run --runtime kata-runtime --rm --name YPR7jS4Oeg7HJQJ8nFEjRRDPylLpG6 --cpus 1 debian bash -c for c in $(seq 1 5); do [ -d /sys/devices/system/cpu/cpu1 ] && exit 0; sleep 5; done; exit 1]
Timeout: 60 seconds
Exit Code: 126
Stdout: 
Stderr: docker: Error response from daemon: OCI runtime create failed: rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"failed to write 0-1 to cpuset.cpus: write /sys/fs/cgroup/cpuset/docker/49f2ed7d1f726ceee3bc460155d065d8024593b2c20d3556202b6f80745b40cc/cpuset.cpus: permission denied\"": unknown.

Running command '/usr/bin/docker [docker ps -a -f name=YPR7jS4Oeg7HJQJ8nFEjRRDPylLpG6 --format {{.Status}}]'
[docker ps -a -f name=YPR7jS4Oeg7HJQJ8nFEjRRDPylLpG6 --format {{.Status}}]
Timeout: 60 seconds
Exit Code: 0
Stdout: 
Stderr: 

• Failure [3.222 seconds]
Hot plug CPUs
/home/jenkins/jenkins_slave/workspace/kata-containers-tests-centos-7-4-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:62
  container with CPU constraint
  /home/jenkins/jenkins_slave/workspace/kata-containers-tests-centos-7-4-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
    should have 2 CPUs [It]
    /home/jenkins/jenkins_slave/workspace/kata-containers-tests-centos-7-4-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

    Expected
        <int>: 126
    to be zero-valued

    /home/jenkins/jenkins_slave/workspace/kata-containers-tests-centos-7-4-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:115
```

### PR DESCRIPTION
**Pull request by devimc**
next condition is used to wait until all vCPUs are visible in the container

```
while [[ "$(cat "/sys/fs/cgroup/cpuset/cpuset.cpus")" != "2" ]] && [[ $c < 5 ]]

```

and that condition fail in sh

```
Stderr: sh: can't open 5: no such file
```

to avoid random failures when CPU tests are running, this patch change the container image
to debian + bash and the command to check the number of vCPUs.

fixes #291

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
I am seeing the CI failure for ubuntu 17.10, I dont understand why the CI passes on the other distros since they use the same container image. Lets wait for the CI on this one.

**Comment by chavafg** [comment]
sadly, this is still failing...

Summarizing 1 Failure:

[Fail] Hot plug CPUs container with CPU period and quota [It] should have 2 CPUs 
/home/jenkins/jenkins_slave/workspace/kata-containers-tests-fedora-27-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:98

Ran 102 of 164 Specs in 492.864 seconds
FAIL! -- 101 Passed | 1 Failed | 0 Pending | 62 Skipped --- FAIL: TestIntegration (542.43s)
FAIL

http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-tests-ubuntu-17-10-PR/217/console
and
http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-tests-fedora-27-PR/113/console


should we disable the test?

**Comment by jodh-intel** [comment]
I don't know why this is random as it looks like a quoting issue:

```
$ busybox sh -c 'c=0; [[ $c < 5 ]] && echo ok'
sh: can't open 5: no such file
$ busybox sh -c 'c=0; [[ $c \< 5 ]] && echo ok'
ok
```

But I'd write it like this to avoid the problem entirely:

```
$ busybox sh -c 'c=0; [ $c -lt 5 ] && echo ok'
ok
```

**Comment by devimc** [comment]
crio is broken :cry: 

```
not ok 23 run ctr with image with Config.Volumes
# (from function `crictl' in file helpers.bash, line 163,
#  from function `start_crio' in file helpers.bash, line 256,
#  in test file ctr.bats, line 811)
#   `start_crio' failed
```

**Comment by devimc** [comment]
I ran this test 100 times in an azure VM, and I didn't get any error.
CI is green, @chavafg feel free to restart the jobs to ensure this test is ok.

**Comment by chavafg** [comment]
thanks @devimc. I 'll give them another run and merge if everything goes well.

**Comment by chavafg** [comment]
lgtm

**Comment by jodh-intel** [comment]
lgtm

**Pull request merged**
