### PR TITLE
test: Add retries to get entropy level

### LINKED ISSUE #1546: improve entropy test
We need to wait a couple of seconds in order to get the
entropy level https://github.com/kata-containers/packaging/pull/482.

### PR DESCRIPTION
**Pull request by GabyCT**
We need to wait a couple of seconds in order to get the
entropy level https://github.com/kata-containers/packaging/pull/482.

Fixes #1546

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@ganeshmaharaj @jcvenegas @grahamwhaley @mcastelino this can be a temporary solution of the problem seen at kata-containers/packaging#482. This can help until we have this set of test https://github.com/kata-containers/tests/issues/1543

**Comment by grahamwhaley** [comment]
/test
Indeed, I think this is a bit of a flaky sticky plaster - this *might* work, today, with our current kernel, config, and CI machines - but, as noted on the other items/issues, I think checking the entropy level is probably not the right test - we probably need to check how much 'randomness' is available, and at what rate. Let's see how it flies in the CI for now though...

**Comment by jcvenegas** [comment]
@grahamwhaley  I think it is still value on check the entropy level at container startup at at least to ensure that we provide it in a low time after the container has boot.

Correct me if I am wrong but just dumping some megabytes from /dev/random does not tell us the quality of the entropy if this is low (less that 1000) our level is not good as we want for users.

**Comment by jcvenegas** [comment]
@grahamwhaley  the other option is to force the agent finish the boot until finds the entropy level is good but will result in the same issue @mcastelino is trying to solve (reduce boot time).

I agree that we should add an additional test to see how fast we provide random numbers `/dev/random` should be the one we pick as this is a blocking device (not use pool as urandom).

**Comment by grahamwhaley** [comment]
afaict, reading from `/dev/random` does block until entropy is good enough. Reading from `/dev/urandom` does not block, and will continue to provide *potentially* less random numbers if entropy runs out...
Best document I found to read was at https://www.2uo.de/myths-about-urandom

What concerns me most I guess about us measuring `entropy >= 1000` is, do we know how long it will, or should, take to achieve that level of entropy inside a kata container? How is it getting filled up - is there a rate limit to it filling, is it via `virtio-rng`, or ??? I think we have shown it is not instant already, by failing the test just by modifying the kernel config and thus the PRNG init sequence and boot time... on my local system for instance I think I was seeing an extra 30s was not enough, but an extra 60s was - but, this probably comes down to 'lack of activity' happening inside the container post-boot etc.

Reading from `/dev/random` I think will maybe force the Kata kernel to go access the `virtio-rng` device to get more entropy, and thus really test that we can provide entropy, post boot, at a good enough rate.

**Comment by jcvenegas** [comment]
@GabyCT  after talk with @grahamwhaley and you  in slack, lets not run this test for now until we can find if we can have a reliable that we agree that gives value to our test suite.

**Comment by GabyCT** [comment]
@jcvenegas ok I will close this PR thanks

**Pull request closed without merging**
