### PR TITLE
ci: vfio: fix VFIO CI

### LINKED ISSUE #2940: ci: vfio: .ci/vfio_jenkins_job_build.sh only supports Fedora
```
13:43:44 ++ '[' ubuntu = fedora ']'
13:43:44 ++ echo '.ci/vfio_jenkins_job_build.sh only supports Fedora'
13:43:44 .ci/vfio_jenkins_job_build.sh only supports Fedora
13:43:44 ++ exit 1
13:43:44 ++ handle_error 280
13:43:44 ++ local exit_code=1
13:43:44 ++ local line_number=280
13:43:44 ++ echo 'Failed at 280: ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i "${ssh_key_file}" -p "${vm_port}" "${USER}@${vm_ip}" "${cmd}"'
13:43:44 Failed at 280: ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i "${ssh_key_file}" -p "${vm_port}" "${USER}@${vm_ip}" "${cmd}"
13:43:44 ++ exit 1
```

### PR DESCRIPTION
**Pull request by devimc**
escape ID variable since it shouldn't be expanded in the host

fixes #2940

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @devimc.

lgtm

**Pull request merged**
