### PR TITLE
stable-3.0: update links to stable-3.0

### PR DESCRIPTION
**Pull request by bergwolf**
So that we run tests with the correct stable branch.

### CODE REVIEW

**Comment by bergwolf** [comment]
Hi @GabyCT, does the CI require special setup for the stable-3.0 branch as well? No tests were started by `/test` for this PR.

**Comment by snir911** [comment]
Probably, it also seems like it can be merged with no acks

**Comment by GabyCT** [comment]
@bergwolf, I did the changes to the CI to be triggered in stable-3

**Comment by bergwolf** [comment]
Thanks a lot @GabyCT !

**Review by liubin — APPROVED** [review]

**Review by snir911 — APPROVED** [review]

**Pull request merged**
