### PR TITLE
vfio-ap: Add e2e test for vfio-ap cold-plugin

### PR DESCRIPTION
**Pull request by BbolroC**
This PR is to add a new e2e test for vfio-ap cold-plugin and supplement logging.

Fixes: #5732

Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

### CODE REVIEW

**Review by zvonkok — APPROVED** [review]
LGTM, excellent, cold and hot-plug testing of AP devices!

**Comment by BbolroC** [comment]
Test result: http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-20.04-s390x-VFIO-AP-daily/204/consoleText

**Review by fidencio — APPROVED** [review]
lgtm, thanks @BbolroC!

**Pull request merged**
