### PR TITLE
ci: docker: update scripts to work with latest docker (19.03)

### PR DESCRIPTION
**Pull request by chavafg**
container-manager: Use specific version for ppc64le
Seems that docker hasn't released v19.03 on ppc64le,
so we need to specify a different version for this.

ci: Ensure docker is running before containerd-cri tests run
containerd-cri integration tests need docker as some tests
need to download images.

Fixes: #2118.

Depends-on: github.com/kata-containers/runtime#1715

### CODE REVIEW

**Comment by chavafg** [comment]
I see that the [`hypervisor_stability_kill_test`](https://github.com/kata-containers/tests/blob/master/integration/stability/hypervisor_stability_kill_test.sh) is leaving the container information under `/run/vc/sbs`, only when running with docker 19.03.
```
fuentess@newdocker:~$ sudo docker run --runtime kata-runtime -tid ubuntu bash
a4ddc2808ed7acf4883397024251fd122990025cf6a7e400a9c166958c010092
fuentess@newdocker:~$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
a4ddc2808ed7        ubuntu              "bash"              20 seconds ago      Up 16 seconds                           dreamy_williamson
fuentess@newdocker:~$ pidof qemu-system-x86_64
865
fuentess@newdocker:~$ sudo kill -KILL 865
fuentess@newdocker:~$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
fuentess@newdocker:~$ sudo kata-runtime list 
WARNING: failed to get container a4ddc2808ed7acf4883397024251fd122990025cf6a7e400a9c166958c010092 rootfs: stat /var/lib/docker/overlay2/f9314de2f862faf78cb3011921c7124d2af6e3e1e4d23c28c5aae791056f96d4/merged: no such file or directory
ID          PID         STATUS      BUNDLE      CREATED     OWNER
fuentess@newdocker:~$ sudo ls /run/vc/sbs
a4ddc2808ed7acf4883397024251fd122990025cf6a7e400a9c166958c010092
```

Any idea of this @bergwolf ?

**Comment by jodh-intel** [comment]
Any update on these PRs?

**Comment by chavafg** [comment]
not really, seems that kill behavior changes when using 19.03, so we are blocked by https://github.com/kata-containers/runtime/issues/2314, unless we want to skip the `hypervisor_stability__kill_test.sh`

**Comment by wainersm** [comment]
@chavafg allow me to hijack this PR.

Currently the `install_runtime.sh` configures kata as a runtime for docker if `TEST_CGROUPSV2==false` (line 113). I *do not* want to configure docker at all, and by using a combination of variables I thought that step could be simply skipped, so I thought in run the configuration step only and only if `TEST_CGROUPV2 == false AND TEST_DOCKER == true`. Looking at this PR I realized my idea has a flaw:  containerd-cri also need such as configuration (I suppose on context of containerd-cri tests `TEST_DOCKER` is set to `false`).

So could you advise me how can I possible solve this puzzle?

**Comment by jodh-intel** [comment]
@wainersm - Please can you raise a separate issue for this query, explaining what you would like that script to do.

**Comment by wainersm** [comment]
> @wainersm - Please can you raise a separate issue for this query, explaining what you would like that script to do.

@jodh-intel yes, I will do that. thanks!

**Pull request closed without merging**
