### PR TITLE
metrics: Enable metrics CI for clh for kata 2.0

### LINKED ISSUE #3265: enable clh metrics ci for kata 2.0

### PR DESCRIPTION
**Pull request by GabyCT**
This PR enables the metrics CI for clh on kata 2.0

Fixes #3265

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
Thanks @GabyCT - lgtm

**Review by chavafg — APPROVED** [review]

**Pull request merged**
