### PR TITLE
CI: install flex

### PR DESCRIPTION
**Pull request by chavafg**
flex package is needed by the 4.19.10 kernel

Fixes: #1031.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
lgtm

**Comment by jcvenegas** [comment]
ARM ci failing needed to add arm config for new kernel ERROR: failed to find default config /home/jenkins/workspace/kata-containers-tests-ARM-18.04-PR/go/src/github.com/kata-containers/packaging/kernel/configs/arm64_kata_kvm_4.19.x

**Comment by jcvenegas** [comment]
I see a performance degradation probably due to the new kernel

**Comment by chavafg** [comment]
should we instead revert https://github.com/kata-containers/runtime/pull/1030? 
@egernst @jcvenegas

**Comment by grahamwhaley** [comment]
@jcvenegas - any details on the performance drop you see - was that on the metrics CI logs?

**Comment by grahamwhaley** [comment]
@jcvenegas @chavafg - ah, I see maybe https://github.com/kata-containers/runtime/issues/1100 is related.
I'll comment over there...

**Pull request merged**
