### PR TITLE
backport for stable 1.11

### PR DESCRIPTION
**Pull request by GabyCT**
1484beac ci: support QEMU 5.0.0

### CODE REVIEW

**Comment by amshinde** [comment]
@GabyCT Why is this required? As far as I see, we supported qemu 4.1.1 for the stable 1.11 branch:
https://github.com/kata-containers/runtime/blob/stable-1.11/versions.yaml

I feel we are not checking out the right repo versions in our CI.
@devimc WDYT?

**Comment by devimc** [comment]
@amshinde the compatibility test checks if is possible to remove a container started with the latest (master branch -> QEMU 5) kata-runtime using the current (Pull Request) kata-runtime, having said we have two options:
1. Backport this patch
or
2. Disable the compatibility tests on stable branches

**Comment by amshinde** [comment]
@devimc Ok, thanks for the info. Makes sense to backport this patch then, I do not want to get rid of the compatibility test.

**Comment by GabyCT** [comment]
any idea of this failure?
```
10:36:41 Auto-merging CODE_OF_CONDUCT.md
10:36:41 CONFLICT (add/add): Merge conflict in CODE_OF_CONDUCT.md
10:36:41 error: Failed to merge in the changes.
10:36:41 Patch failed at 0003 CoC: Add Code of Conduct
10:36:41 Use 'git am --show-current-patch' to see the failed patch
10:36:41 
10:36:41 Resolve all conflicts manually, mark them as resolved with
10:36:41 "git add/rm <conflicted_files>", then run "git rebase --continue".
```

**Comment by amshinde** [comment]
@GabyCT Not sure about the error. Looks like you are getting the error as you have a
`Depends-on: github.com/kata-containers/kata-containers#371`.
Do you need that? I think you can submit this patch without that.

cc @jodh-intel @chavafg for any comments they have for the error seen.

**Comment by chavafg** [comment]
yeah, it seems that the issue comes from the `Depends-on`. @GabyCT please remove that line from the commit.

**Pull request merged**
