### PR TITLE
ci: Add metrics cloud hypervisor job

### LINKED ISSUE #5463: add metrics cloud hypervisor job

### PR DESCRIPTION
**Pull request by GabyCT**
This PR adds metrics cloud hypervisor job so it only installs cloud hypervisor and run only cloud hypervisor metrics benchmarks.

Fixes #5463

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Review by dborquez — APPROVED** [review]
LGTM, thanks @GabyCT

**Pull request merged**
