### PR TITLE
kubernetes: Reenable "Setting sysctl" test with CRI-O"

### PR DESCRIPTION
**Pull request by fidencio**
This reverts commit 1e89be5d9f1b25395dd9b4e5c227f8a089abf6d0.

Depends-on: github.com/kata-containers/kata-containers#1844

Fixes: #3523

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
mmm how stable is this test? I see that previously it failed in CentOS and other CIs
```
07:22:32 1..1
07:22:32 not ok 1 Setting sysctl
07:24:03 # (in test file k8s-sysctls.bats, line 22)
07:24:03 #   `kubectl wait --for=condition=Ready --timeout=$timeout pod $pod_name' failed
07:24:03 # INFO: k8s configured to use runtimeclass
```

**Comment by GabyCT** [comment]
mmm how stable is this test? I see that previously it failed in CentOS and other CIs
```
07:22:32 1..1
07:22:32 not ok 1 Setting sysctl
07:24:03 # (in test file k8s-sysctls.bats, line 22)
07:24:03 #   `kubectl wait --for=condition=Ready --timeout=$timeout pod $pod_name' failed
07:24:03 # INFO: k8s configured to use runtimeclass
```

**Comment by fidencio** [comment]
> mmm how stable is this test? I see that previously it failed in CentOS and other CIs
> 
> ```
> 07:22:32 1..1
> 07:22:32 not ok 1 Setting sysctl
> 07:24:03 # (in test file k8s-sysctls.bats, line 22)
> 07:24:03 #   `kubectl wait --for=condition=Ready --timeout=$timeout pod $pod_name' failed
> 07:24:03 # INFO: k8s configured to use runtimeclass
> ```

@GabyCT, the test is stable, the fix was not :-)
@lifupan was debugging and trying different solutions as part of https://github.com/kata-containers/kata-containers/pull/1844.

In any case this one should only be merged after https://github.com/kata-containers/kata-containers/pull/1844 is approved & merged.

**Comment by GabyCT** [comment]
@fidencio ok

**Comment by fidencio** [comment]
Adding the `do-not-merge` label just to ensure it'll only be merged after https://github.com/kata-containers/tests/pull/3524 gets merged.

**Review by lifupan — APPROVED** [review]

**Review by bergwolf — APPROVED** [review]

**Pull request merged**
