### PR TITLE
metrics: Add metric selection function

### LINKED ISSUE #5132: metrics: add metric selection function
**Which feature do you think can be improved?**
run_metrics_PR_ci.sh script 

Specify the feature you think could be made better.
run( ) function can define a condition to run specific metrics or all metrics.

**How can it be improved?**
By adding a _**TEST_SELECTOR**_ variable

### PR DESCRIPTION
**Pull request by dborquez**
Enables the selective execution of metrics.

Fixes #5132

Signed-off-by: David Esparza <david.esparza.borquez@intel.com>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by cmaf — APPROVED** [review]

**Comment by GabyCT** [comment]
@dborquez , we do not have the info that if a certain metric failed or passed as an output which is something that we need

**Pull request merged**
