### PR TITLE
# Kata Containers 2.2.0-alpha1

### PR DESCRIPTION
**Pull request by fidencio**
- metrics: Update memory-footprint-ksm midval
- docs: Update readme for metrics
- tests: do retry for running wget command in pod
- docs: Update density README
- tests: Add more tests to skip in k8s e2e conformance for clh+containerd
- tests: run wget after service is ready
- tests: Set --default-toolchain when installing rustup
- CI: Add ability to skip CI run in fast-return script
- ci: Add containerd+k8s+initrd CI job
- tests: get deploy/pod details for debugging
- tests: fix wrong runtime name
- ci: Temporarily disable govet checks
- containerd: disable memory update test on s390x
- ci: Add support for forked repo in ci scripts
- ci: add golang 1.16 to the CI
- integration: pmem: fix test
- metrics: Update metrics ksm value
- CI: Add mounts and pids to teardown
- containerd: fix the issue of getting cri version
- docs: Fix URLs in unit test doc
- integration/pmem: reimplement pmem test
- integration/cri-o: do not edit ctr.bats
- ci: Skip memory-related tests on s390x
- ci: Minor script fixes
- ci: Remove X86 pc machine related tests
- integration: Fix off-by-one in KSM comparison
- tests: Strengthen the vcpus integration tests
- metrics: Fix blogbench and bootime baseline
- CI: Show HTTP error code in static check script
- Fix packages & build arguments for RHEL and (mostly) s390x
- Disable virtio-fs for KSM
- integration/cri-o: add integration tests kata 2.x ready
- Clean up architecture-specific code
- ci: Install k8s containerd config if required
- ci: Enable AGENT_INIT if TEST_INITRD == yes

4bd99890 metrics: Update memory-footprint-ksm midval
afdd4898 docs: Update readme for metrics
3824e3a3 tests: do retry for running wget command in pod
8c2208f6 docs: Update density README
2972ff14 tests: Add more tests to skip in k8s e2e conformance for clh+containerd
f44a48e0 tests: run wget after service is ready
9ecc657a ci: Add containerd+k8s+initrd CI job
b4fee25e ci: Temporarily disable govet checks
930a9631 tests: get deploy/pod details for debugging
eb7aa7bb tests: fix wrong runtime name
2329b4db ci: Add support for forked repo in ci scripts
eef0c6d9 containerd: disable memory update test on s390x
61a69cb3 docker: fix govet fieldalignment
09ea7613 metrics/storage: fix govet fieldalignment
b1f0d033 integration/docker: fix govet fieldalignment
03f221d9 cmd/checkmetrics: fix govet fieldalignment
7679f716 cmd/log-parser: fix govet fieldalignment
9d0f6055 cmd/checkcommits: fix govet fieldalignment
9797f15d cmd/check-markdown: fix govet fieldalignment
91f101eb ci: update golangci-lint to 1.41.1
188c129f ci: support golang 1.16.x
43d0e0b5 ci: add 1.16 to the list of golang versions to test
a2268f44 ci: pmem: containerd: allow image pulling from localhost registry
2927ba9d integration: pmem: don't source data/lib.sh
5088af7c docs: Document the fast return script
3a5b413f CI: Default to main branch
4321c03c CI: Add ability to skip CI run in fast-return script
749eaedb CI: Refactor fast-return script
fc4fe441 CI: only try to install jq if not installed
961f4765 metrics: Update metrics ksm value
7eb985bd CI: Make collect script succeed in teardown
2f402b1a tests: Set --default-toolchain when installing rustup
a8d281ed CI: Add mounts and pids to teardown
231d4632 docs: Fix URLs in unit test doc
cc0e3987 integration/pmem: reimplement pmem test
d5e9dcab containerd: fix the issue of getting cri version
467e333e metrics: Fix boot times metrics baseline
ebd42776 ci: Skip memory-related tests on s390x
912087fa integration: Fix off-by-one in KSM comparison
170e76ed ci: Remove X86 pc machine related tests
1a518b29 metrics: Fix blogbench and bootimes baseline
19c1427b ci: Minor script fixes
21712a21 integration/cri-o: simplify path to bats file
83d78350 integration/cri-o: do not edit ctr.bats
e08cecf6 tests: Strengthen the vcpus integration tests
5aef325f CI: Show HTTP error code in static check script
a33e7f66 ci: Install distro Docker on Ubuntu s390x
697f6a44 ci: Install k8s on RHEL
d4c16935 ci: Fix btrfs for CentOS/RHEL
d18bf932 ci: Export CC=gcc on s390x Fedora-likes
f91b565a ci: Gear up for RHEL 8
cd1490ff ci: Fix packages in Ubuntu env setup
2325c2a2 ci: Fix packages in RHEL env setup
fb3dcc20 ci: Fix packages in Fedora env setup
e59530aa integration/cri-o: drop unused vars
621e387e integration/cri-o: ensure cri-o binaries are the expected ones
184280d2 integration/cri-o: make integration tests shimv2 ready
6642b558 integration/cri-o: fix cri-o version retrieval
6d664d0a integration/cri-o: update comment on skipped tests
48aaef31 integration/cri-o: update list of tests to skip
0fc60c8b integration/cri-o: revert "integration: Remove old CRI-O tests"
e4cfa445 ci: Install k8s containerd config if required
912c32dc ci: Use kata-arch for getting golang arch
ad1f674f ci: Remove install_packaged_qemu
c08786e5 ci: Remove s390x/lib_setup_s390x.sh
e5ea38e2 ci: Consolidate clean_up scripts
8fcd3996 ci: Remove lib_kata_image scripts
4350cf51 test: Revert "test: Skip KSM tests on ARM CI"
232be376 integration: Wait for KSM to kick in
83d8d96a integration: Disable virtio-fs for KSM test
9dca7e73 ci: Generalize toggle_sandbox_cgroup_only.sh
caa75863 ci: Enable AGENT_INIT if TEST_INITRD == yes

### CODE REVIEW

**Review by jcvenegas — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

lgtm

**Pull request merged**
