### PR TITLE
docs: Include metrics tests in the README

### LINKED ISSUE #3219: include metrics tests in README for kata 2.0

### PR DESCRIPTION
**Pull request by GabyCT**
Now that we have a metrics CI in kata 2.0, we should include that we
are supporting metrics in the README documentation.

Fixes #3219

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]

**Review by devimc — APPROVED** [review]
thanks @GabyCT

**Pull request merged**
