### PR TITLE
ci/vfio:  checkout the right tests target branch

### LINKED ISSUE #3948: VFIO CI is not honouring target branch
in https://github.com/kata-containers/kata-containers/pull/2588, VFIO CI is failing with the following error:

```
13:18:54 + sudo driverctl set-override 0000:00:03.0 vfio-pci
13:18:54 sudo: driverctl: command not found
13:18:54 ++ handle_error 213
13:18:54 ++ local exit_code=1
13:18:54 ++ local line_number=213
13:18:54 +++ basename functional/vfio/run.sh
13:18:54 +++ eval echo 'sudo driverctl set-override "${addr}" vfio-pci'
13:18:54 ++++ echo sudo driverctl set-override 0000:00:03.0 vfio-pci
13:18:54 [run.sh:213] ERROR: sudo driverctl set-override 0000:00:03.0 vfio-pci
13:18:54 ++ echo -e '[run.sh:213] ERROR: sudo driverctl set-override 0000:00:03.0 vfio-pci'
13:18:54 ++ exit 1
```

`driverctl` is used only in the main branch, this means VFIO CI is not checking out the right target branch to test PRs

### PR DESCRIPTION
**Pull request by devimc**
checkout the right tests target branch

fixes #3948

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by amshinde — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
thanks, @devimc!

**Pull request merged**
