### PR TITLE
fix ARM CI

### PR DESCRIPTION
**Pull request by bergwolf**

### CODE REVIEW

**Comment by bergwolf** [comment]
With k8s 1.17.3, ARM CI can pass. See http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-ARM-PR/217/console

**Comment by bergwolf** [comment]
k8s on waiting `coredns` pod to be running, causing k8s cluster setup failure:
```
00:21:36 + eval 'kubectl get pods --all-namespaces | grep coredns.*1/1.*Running'
00:21:36 ++ kubectl get pods --all-namespaces
00:21:36 ++ grep 'coredns.*1/1.*Running'
00:21:37 + sleep 5
00:21:42 + wait_time=0
00:21:42 + '[' 0 -gt 0 ']'
00:21:42 + return 1
00:21:42 + sudo -E sh -c 'rm -r /tmp/kubeadm_config.lljSTy.yaml'
00:21:42 Failed at 85: ./init.sh
```

master node is not ready:
```
00:19:17 + kubectl get nodes
00:19:18 NAME            STATUS     ROLES    AGE   VERSION
00:19:18 arm-testing-2   NotReady   master   5s    v1.18.9
```

pod cannot be scheduled:
```
00:19:36 Events:
00:19:36   Type     Reason            Age              From               Message
00:19:36   ----     ------            ----             ----               -------
00:19:36   Warning  FailedScheduling  2s (x3 over 4s)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
```

node has disk pressure:
```
00:21:42 Lease:
00:21:42   HolderIdentity:  arm-testing-2
00:21:42   AcquireTime:     <unset>
00:21:42   RenewTime:       Sun, 18 Oct 2020 16:21:34 +0000
00:21:42 Conditions:
00:21:42   Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
00:21:42   ----                 ------  -----------------                 ------------------                ------                       -------
00:21:42   NetworkUnavailable   False   Sun, 18 Oct 2020 16:20:02 +0000   Sun, 18 Oct 2020 16:20:02 +0000   FlannelIsUp                  Flannel is running on this node
00:21:42   MemoryPressure       False   Sun, 18 Oct 2020 16:20:04 +0000   Sun, 18 Oct 2020 16:19:12 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
00:21:42   DiskPressure         True    Sun, 18 Oct 2020 16:20:04 +0000   Sun, 18 Oct 2020 16:19:32 +0000   KubeletHasDiskPressure       kubelet has disk pressure
00:21:42   PIDPressure          False   Sun, 18 Oct 2020 16:20:04 +0000   Sun, 18 Oct 2020 16:19:12 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
00:21:42   Ready                True    Sun, 18 Oct 2020 16:20:04 +0000   Sun, 18 Oct 2020 16:20:04 +0000   KubeletReady                 kubelet is posting ready status. AppArmor enabled
```

So the problem is that ARM CI machine disk is almost full.

**Comment by jongwu** [comment]
thanks @bergwolf. I have cleaned the arm ci server. 
by the way, what's the meaning of the first commit named "wip". Will it be merged?

**Comment by bergwolf** [comment]
@jongwu no, wip means it is `work in progress`. So it won't be merged as is.

**Review by liubin — APPROVED** [review]
It's happy to see call checks are in green.

**Review by lifupan — APPROVED** [review]

**Comment by bergwolf** [comment]
@jongwu Thanks for your help! To prevent it from happening again in future, can you help a bit more to ensure that:
1. ARM CI VM is shut down every time when a CI job finishes.
2. Run the ARM CI in a dedicated directory, and remove all the artifacts created during CI to avoid disk space exhaustion.

Once done, we can set ARM CI as `required` as well to prevent unexpected breakage.

**Comment by jongwu** [comment]
Thanks @bergwolf.  It's helpful to make ARM CI more stable.
ARM CI run on bare metal. So  I can do "remove workspace op" in post action of jenkins to avoid that issue. 
I will add this "clean op" in every ARM CI job's configuration then I will ping you after verification.

**Comment by jongwu** [comment]
Hello @bergwolf - I have done these fixes. There are lots of ARM CI, but the most important one is kata-containers-2.0-ubuntu-ARM-PR. So maybe we can set it to required first.

**Pull request merged**
