### PR TITLE
backports stable-1.11

### PR DESCRIPTION
**Pull request by chavafg**
backports for stable-1.11 branch:

- .ci/install_runtime: Configure docker only if installed
- .ci/setup_env_centos.sh: Ensure yum-config-manager is installed
- .ci/setup_env_centos.sh: Install bc package
- .ci/setup_env_centos.sh: Install packaged GNU Parallel
- integration: fix cpuset test
- integration: remove, update cpuset tests
- ci: compress virtiofsd logs
- ci: Fix docker installation centos 8
- ci: Fix docker installation for rhel 8
- tests: Skip netmon test on CentOS 8
- ci: Remove utilities repository for SLES 15 SP2

### CODE REVIEW

**Comment by fidencio** [comment]
@chavafg, we'll also need this one: https://github.com/kata-containers/tests/commit/0188404fd32af99ffff4ddc263396a0e14afe066

**Comment by fidencio** [comment]
@devimc, I see some failures related to pmem. Sorry for bothering you, but IIRC you had some patches pushed about that. Is there something that should be backported here?

**Comment by fidencio** [comment]
> @chavafg, we'll also need this one: [0188404](https://github.com/kata-containers/tests/commit/0188404fd32af99ffff4ddc263396a0e14afe066)

Let me take it back for now.

So, rhel-8-q35 and centos-8 CIs are failing for the same reason:
```
03:26:52 docker: Error response from daemon: OCI runtime create failed: rpc error: code = Internal desc = Could not mount /dev/pmem1 to /run/kata-containers/sandbox/storage/a6509947-4a3e-42aa-bb89-e1110edb6b7a-test_pmem1: invalid argument: unknown.
03:26:52 Failed at 55: docker run -d --name "${container_name}" --runtime kata-runtime -v "${test_directory}:/${test_directory_name}" "${image}" sh -c "${payload}"
03:26:53 make: *** [Makefile:310: pmem] Error 125
```

debian-10 is failing because of a timeout:
```
02:31:05 Build timed out (after 5 minutes). Marking the build as aborted.
02:31:05 Build was aborted
```

**Comment by fidencio** [comment]
@chavafg. the pmem issue seems to be the same as https://github.com/kata-containers/tests/issues/2437 and we may just need to backport https://github.com/kata-containers/tests/pull/2533

**Comment by jcvenegas** [comment]
@fidencio, I will continue with the release process this,  I can follow-up in next commits to backport.

On this backports I see:
ARM 
```
19:19:36 Job for docker.service failed because the control process exited with error code.
19:19:36 See "systemctl status docker.service" and "journalctl -xe" for details.
19:19:36 Build step 'Execute shell' marked build as failure
```
that does not seems to be related with the current PR chagnes

centos:
```
19:51:14 57ddb754d67b5397d33114000e945c49297906bfee4a3135c51c6fb97e887d36
19:51:16 docker: Error response from daemon: OCI runtime create failed: rpc error: code = Internal desc = Could not mount /dev/pmem1 to /run/kata-containers/sandbox/storage/525c808d-b227-421d-9c71-3cbb758434c3-test_pmem1: invalid argument: unknown.
19:51:16 Failed at 55: docker run -d --name "${container_name}" --runtime kata-runtime -v "${test_directory}:/${test_directory_name}" "${image}" sh -c "${payload}"
19:51:17 make: *** [Makefile:310: pmem] Error 125
19:51:17 Failed at 86: sudo -E PATH="$PATH" bash -c "make test"
19:51:17 Build step 'Execute shell' marked build as failure
19:51:26 Performing Post build task...
```

Lets try to restart  and then merge.

**Review by fidencio — APPROVED** [review]
lgtm, considering happy tests!

Thanks @chavafg and @jcvenegas!

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
