### PR TITLE
metrics: Add sysbench memory test

### LINKED ISSUE #5279: metrics: Add sysbench memory test

### PR DESCRIPTION
**Pull request by GabyCT**
This PR adds the sysbench memory test.

Fixes #5279

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by BbolroC** [comment]
Please skip the test for s390x. At the moment, the package is not supported via the Ubuntu package manager. (See an issue https://github.com/akopytov/sysbench/issues/258) A progress for the issue has been stalled since 2018.

cc: @hbrueckner

**Comment by GabyCT** [comment]
@BbolroC thanks I will

**Comment by GabyCT** [comment]
@hbrueckner I will skip the test for s390x and right now we want to use it to measure memory and cpu usage and I/O

**Comment by GabyCT** [comment]
@chavafg changes applied, thanks

**Review by chavafg — APPROVED** [review]
thanks @GabyCT

**Review by dborquez — APPROVED** [review]
@GabyCT thank you, LGTM

**Pull request merged**
