### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by Megan-Wright**
Merge remote-tracking branch 'upstream/main' into CCv0
    
Fixes: #5169
Depends-on: github.com/kata-containers/kata-containers#5328
    
Signed-off-by: Megan Wright <megan.wright@ibm.com>

### CODE REVIEW

**Comment by Megan-Wright** [comment]
```
git diff --stat upstream/main -- . ':!*/vendor/*'
 .ci/ci_job_flags.sh                                                                       |  70 +++++++++++++--
 .ci/configure_cni.sh                                                                      |   2 +-
 .ci/install_cri_containerd.sh                                                             |  26 +++++-
 .ci/install_kata.sh                                                                       |   8 ++
 .ci/install_kata_image.sh                                                                 |  15 ++--
 .ci/install_kata_kernel.sh                                                                |   4 +-
 .ci/install_ovmf_sev.sh                                                                   |  28 ++++++
 .ci/install_runtime.sh                                                                    |  31 +++----
 .ci/install_td_shim.sh                                                                    |  29 +++++++
 .ci/install_tdvf.sh                                                                       |  29 +++++++
 .ci/jenkins_job_build.sh                                                                  |   6 ++
 .ci/lib.sh                                                                                |  10 ++-
 .ci/resolve-kata-dependencies.sh                                                          |  42 +++++----
 .ci/run.sh                                                                                |  24 +++--
 .ci/setup_env_ubuntu.sh                                                                   |   4 +-
 .ci/static-checks.sh                                                                      |   8 +-
 .github/workflows/commit-message-check.yaml                                               |   4 +-
 Makefile                                                                                  |  19 ++--
 README.md                                                                                 |  10 +--
 cmd/check-spelling/data/projects.txt                                                      |   1 +
 cmd/github-labels/labels.yaml.in                                                          |   4 +-
 cmd/pmemctl/pmemctl.sh                                                                    |   2 +-
 functional/kata-monitor/run.sh                                                            |   1 +
 functional/sev/fixtures/agent-config.toml                                                 |  44 ++++++++++
 functional/sev/run.sh                                                                     | 231 +++++++++++++++++++++++++++++++++++++++++++++++++
 integration/confidential/fixtures/offline-fs-kbc/aa-offline_fs_kbc-resources.json         |   5 ++
 integration/confidential/fixtures/quay_verification/public.gpg                            |  30 +++++++
 integration/confidential/fixtures/quay_verification/quay_policy.json                      |  18 ++++
 integration/confidential/fixtures/quay_verification/signatures.tar                        | Bin 0 -> 2157 bytes
 integration/confidential/fixtures/registries.d/quay.io.yaml                               |   4 +
 integration/confidential/lib.sh                                                           | 222 +++++++++++++++++++++++++++++++++++++++++++++++
 integration/containerd/confidential/agent_api.bats                                        |  82 ++++++++++++++++++
 integration/containerd/confidential/agent_image.bats                                      | 103 ++++++++++++++++++++++
 integration/containerd/confidential/asserts.sh                                            |  68 +++++++++++++++
 integration/containerd/confidential/fixtures/agent-configuration-no-exec.toml             |  46 ++++++++++
 integration/containerd/confidential/fixtures/container-config.yaml                        |  11 +++
 integration/containerd/confidential/fixtures/container-config_signed-protected-other.yaml |  11 +++
 integration/containerd/confidential/fixtures/container-config_unsigned-protected.yaml     |  11 +++
 integration/containerd/confidential/fixtures/container-config_unsigned-unprotected.yaml   |  11 +++
 integration/containerd/confidential/fixtures/pod-config.yaml.in                           |  12 +++
 integration/containerd/confidential/lib.sh                                                | 163 ++++++++++++++++++++++++++++++++++
 integration/containerd/confidential/run_tests.sh                                          |  21 +++++
 integration/containerd/confidential/tests_common.sh                                       | 105 ++++++++++++++++++++++
 integration/containerd/cri/integration-tests.sh                                           |  14 ++-
 integration/kubernetes/confidential/agent_image.bats                                      | 170 ++++++++++++++++++++++++++++++++++++
 integration/kubernetes/confidential/agent_image_encrypted.bats                            |  71 +++++++++++++++
 integration/kubernetes/confidential/fixtures/encrypted-image-tests.yaml                   |  28 ++++++
 integration/kubernetes/confidential/fixtures/pod-config.yaml.in                           |  14 +++
 integration/kubernetes/confidential/fixtures/unencrypted-image-tests.yaml                 |  28 ++++++
 integration/kubernetes/confidential/lib.sh                                                | 140 ++++++++++++++++++++++++++++++
 integration/kubernetes/confidential/sev.bats                                              | 447 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 integration/kubernetes/e2e_conformance/setup.sh                                           |   2 +-
 integration/nydus/nydus-sandbox.yaml                                                      |   1 +
 integration/nydus/nydus_tests.sh                                                          |   2 +
 lib/common.bash                                                                           | 127 +++++++++++++++++++++++++++
 versions.yaml                                                                             |   7 +-
 56 files changed, 2544 insertions(+), 82 deletions(-)
```

**Comment by fidencio** [comment]
/test

As @GeorginaKin added a commit fixing the errors being seen here.

**Comment by fidencio** [comment]
The TDX CIs are currently disabled due to https://github.com/kata-containers/kata-containers/issues/5326
The `skopeo` CIs are known to be failing since before the first CC release (and we should consider disabling them).

**Comment by stevenhorsman** [comment]
> /test-fedora

I wouldn't worry about the fedora test failing. It quite often times out, so we've marked it as not required

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Megan-Wright!

**Pull request merged**
