### PR TITLE
stable-2.3 | ci: force-skip-ci check before static checks

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
no point in forcing skip if we're still running those

Fixes: #4384
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

Backport of #4385

### CODE REVIEW

**Review by devimc — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Jakob-Naucke!

**Comment by bergwolf** [comment]
Why do we need `force-skip-ci` in the first place?

**Comment by fidencio** [comment]
> Why do we need `force-skip-ci` in the first place?

We need it in cases we actually have to force skip the CI, and those are quite extreme cases, but every now and then we have those.  The most recent one being moving GoVMM to the kata-containers repo.

On that specific PR, the CI would totally fail as we check for a subsystem being part of a commit message.  As we imported everything from GoVMM **keeping the history**, what they had there wouldn't match with our checks, hence we force skip the CI.

There are a few other situations where this is useful, such as simple fixes to unblock things here and there.

I know, we should have some written guideline on how and when to use those, but that's a different discussion.

Last but not least, if you ask me whether we could solve this just by changing the jobs from `Required` to `Non Required` as part of the GitHub configuration, that's also an option, but that ... IMHO, opens the possibility to have other PRs merged on the timeframe where the jobs are not marked as required (as that would be an action for the entire repo, while the `force-skip-ci` is an action for the current PR only), plus the time it takes to do such changes.

**Pull request merged**
