### PR TITLE
ci: Add make command for CentOS CI

### LINKED ISSUE #3316: Add make command for CentOS CI for kata 2.0
The CentOS CI is failing with this error
```
12:39:24 /tmp/jenkins/workspace/kata-containers-2.0-tests-centos-PR/go/src/github.com/kata-containers/kata-containers/tools/osbuilder /tmp/jenkins/workspace/kata-containers-2.0-tests-centos-PR/go/src/github.com/kata-containers/tests
12:39:24 INFO: Building image with AGENT_INIT=no
12:39:24 sudo: make: command not found
```
We need to add `make`

### PR DESCRIPTION
**Pull request by GabyCT**
This PR adds the make command for CentOS CI as currently is failing as
make command is not being found.

Fixes #3316

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@GabyCT, this is covered as part of @alicefr PR: https://github.com/kata-containers/tests/pull/3246

Seems we still have some k8s test specific failing with CentOS 8.  As @alicefr mentioned she can reproduce that easily, I guess we would better disabling the CentOS 8 Ci again.

**Comment by GabyCT** [comment]
@fidencio so CentOS is having a random k8s test failing? I ran the CentOS CI with this PR and it seems working

**Comment by fidencio** [comment]
> @fidencio so CentOS is having a random k8s test failing? I ran the CentOS CI with this PR and it seems working

@alicefr faced the following issue: http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-centos-PR/301/console, which is the "Check number of cpus" failing.

We can proceed with either yours or Alice's fix, and have the other one tracked.
/cc @kata-containers/redhat for random failures on tests using CentOS 8.

**Comment by GabyCT** [comment]
ok thanks @fidencio , we can proceed with Alice's PR

**Pull request closed without merging**
