### PR TITLE
metrics: Remove unused network metrics

### LINKED ISSUE #4449: remove unused network metrics

### PR DESCRIPTION
**Pull request by GabyCT**
This PR removes unused network metrics that were used for kata 1.x
but they are not longer being part of kata 2.0 metrics CI

Fixes #4449

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by dborquez — APPROVED** [review]
LGTM, thanks @GabyCT

**Review by devimc — APPROVED** [review]

**Pull request merged**
