### PR TITLE
test: Verify that mount points are removed after docker cp

### LINKED ISSUE #781: Add test to verify that mount points are removed after docker cp
While running a docker with volume and then performing a docker cp, we need to check that mount points are removed correctly (https://github.com/kata-containers/runtime/issues/794).

### PR DESCRIPTION
**Pull request by GabyCT**
While running a docker with volume and then performing a docker cp, we
need to check that mount points are removed correctly.

Fixes #781

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@devimc could you please take a look? thanks :)

**Comment by jodh-intel** [comment]
lgtm

**Comment by grahamwhaley** [comment]
This l g t m. Have added @devimc as a reviewer. Checking we have left no dangling mounts is good. Just want to ask if the original request was also to check the contents of the mount point ('/dev/') were still equal as well?

**Comment by devimc** [comment]
lgtm

**Comment by chavafg** [comment]
lgtm

**Pull request merged**
