### PR TITLE
integration/docker: Fix CPU hotplug tests

### LINKED ISSUE #250: CI failing due to hot plug CPUs
Summarizing 4 Failures:

[Fail] Hot plug CPUs container with CPU period and quota [It] should have 3 CPUs 
/home/jenkins/jenkins_slave/workspace/kata-containers-tests-ubuntu-17-10-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:91

[Fail] Hot plug CPUs container with CPU period and quota [It] should have 4 CPUs 
/home/jenkins/jenkins_slave/workspace/kata-containers-tests-ubuntu-17-10-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:91

[Fail] Hot plug CPUs container with CPU constraint [It] should have 3 CPUs 
/home/jenkins/jenkins_slave/workspace/kata-containers-tests-ubuntu-17-10-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:108

[Fail] Hot plug CPUs container with CPU constraint [It] should have 3 CPUs 
/home/jenkins/jenkins_slave/workspace/kata-containers-tests-ubuntu-17-10-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:108

Ran 98 of 159 Specs in 543.348 seconds
FAIL! -- 94 Passed | 4 Failed | 0 Pending | 61 Skipped --- FAIL: TestIntegration (567.07s)
FAIL

### PR DESCRIPTION
**Pull request by devimc**
once all vCPUs have been connected, the agent updates the cpuset cgroup
of each container allowing them to access to these resources

fixes #250

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@devimc Why is the CI passing for this PR ??? I would expect the CI to fail until you get github.com/kata-containers/agent/pull/220 merged. Especially based on the fact that you said it depends on it.

**Comment by devimc** [comment]
@sboeuf it is passing because of `Depends-on: github.com/kata-containers/agent#220` in the commit message

**Comment by sboeuf** [comment]
Ok, I have added `do-not-merge` label.

**Comment by devimc** [comment]
@kata-containers/tests please take a look

**Comment by GabyCT** [comment]
lgtm

**Comment by chavafg** [comment]
lgtm

**Pull request merged**
