### PR TITLE
ci: increase the timeou for clean_env_ctr

### LINKED ISSUE #3924: clean_ctr_env fails to terminate all running containers
The time out assigned to clean_env_ctr, requires to be increased to avoid failures.

### PR DESCRIPTION
**Pull request by dborquez**
For heavy workloads the time out assinged to clean_env_ctr
was increased up to 90 seconds.

Fixes #3924

Signed-off-by: David Esparza <david.esparza.borquez@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @dborquez.

lgtm

**Pull request merged**
