### PR TITLE
Clean up architecture-specific code

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
- ci: Remove lib_kata_image scripts (no longer used)
- ci: Consolidate clean_up scrips (most architectures identical)
- ci: Remove s390x/lib_setup_s390x.sh (no longer used)
- ci: Remove install_packaged_qemu (with our custom patches and recent versions, it isn't of much use)
- ci: Use kata-arch for getting golang arch (duplicate code)

@jongwu && (@Amulyam24 || @bpradipt || @clnperez) PTAL. If you strongly disagree with removing something in aarch64/ppc64le, I can keep the removals to s390x.

Fixes: #3600

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @Jakob-Naucke.

**Comment by fidencio** [comment]
Static checks are failing due to:
```
INFO: Installing xurls utility
curl: (22) The requested URL returned error: 502 
Failed at 32: curl -o "${yq_path}" -LSsf "${yq_url}"
/home/runner/work/tests/tests/src/github.com/kata-containers/tests/.ci/lib.sh: line 145: /home/runner/work/tests/tests/bin/yq: No such file or directory
curl: (22) The requested URL returned error: 502 
Failed at 32: curl -o "${yq_path}" -LSsf "${yq_url}"
/home/runner/work/tests/tests/src/github.com/kata-containers/tests/.ci/lib.sh: line 145: /home/runner/work/tests/tests/bin/yq: No such file or directory
go get .@: invalid module version syntax
```

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Jakob-Naucke!

I'm adding also a "do-not-merge" label as I would like to have an approval from a maintainer of each one of the specific arches before getting it merged.

**Comment by Amulyam24** [comment]
LGTM, Thanks a lot @Jakob-Naucke!

**Comment by Jakob-Naucke** [comment]
@jongwu ARM CI is indeed failing, but it doesn't really look like it's related to the suggested changes:
```
13:42:38 unpacking linux/arm64/v8 sha256:a56e11cce1c09f50a71290d65733ebe976adc8654395091d5379c7f294cc891e...
13:42:38 done
13:42:39 Running hypervisor stability test
13:42:41 Ending hypervisor stability test
13:42:43 INFO: Containerd checks
13:42:43 bash integration/containerd/cri/integration-tests.sh
13:42:43 INFO: Stop crio service
13:42:43 INFO: Stop containerd service
13:42:43 Job for containerd.service canceled.
13:42:44 ERROR: containerd log :
13:42:44 -------------------------------------
13:42:44 cat: /tmp/test-cri-containerd.acLU/containerd.log: No such file or directory
13:42:44 Makefile:134: recipe for target 'cri-containerd' failed
13:42:44 make: *** [cri-containerd] Error 1
13:42:44 Failed at 24: sudo -E PATH="$PATH" bash -c "make cri-containerd"
13:42:44 Build step 'Execute shell' marked build as failure
```

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @Jakob-Naucke

**Comment by jongwu** [comment]
> @jongwu ARM CI is indeed failing, but it doesn't really look like it's related to the suggested changes:
> 
> ```
> 13:42:38 unpacking linux/arm64/v8 sha256:a56e11cce1c09f50a71290d65733ebe976adc8654395091d5379c7f294cc891e...
> 13:42:38 done
> 13:42:39 Running hypervisor stability test
> 13:42:41 Ending hypervisor stability test
> 13:42:43 INFO: Containerd checks
> 13:42:43 bash integration/containerd/cri/integration-tests.sh
> 13:42:43 INFO: Stop crio service
> 13:42:43 INFO: Stop containerd service
> 13:42:43 Job for containerd.service canceled.
> 13:42:44 ERROR: containerd log :
> 13:42:44 -------------------------------------
> 13:42:44 cat: /tmp/test-cri-containerd.acLU/containerd.log: No such file or directory
> 13:42:44 Makefile:134: recipe for target 'cri-containerd' failed
> 13:42:44 make: *** [cri-containerd] Error 1
> 13:42:44 Failed at 24: sudo -E PATH="$PATH" bash -c "make cri-containerd"
> 13:42:44 Build step 'Execute shell' marked build as failure
> ```
> 
> e: yes, this is also over on #3599

Yeah, arm ci always that, the containerd doesn't work well randomly. I need try to find a workaround. thanks.

**Comment by Jakob-Naucke** [comment]
@jongwu but are you okay with the changes otherwise?

**Comment by jongwu** [comment]
Thanks @Jakob-Naucke -, I'm OK with the changes since the Arm ci is happy.

**Comment by fidencio** [comment]
I removed the "do-not-merge" label, as we got the confirmation from folks working on the other arches as well.

**Pull request merged**
