### PR TITLE
ci: Replace checkcommits with Github Action

### LINKED ISSUE #4596: Remove checkcommits
The [`checkcommits`](https://github.com/kata-containers/tests/tree/main/cmd/checkcommits) tool has served us well over the past five years to ensure that all commits comply with our documented [patch format](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format).

However, with the advent of the GitHub Actions, `checkcommits` has become redundant:

- https://github.com/kata-containers/tests/blob/main/.github/workflows/PR-wip-checks.yaml
- https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/PR-wip-checks.yaml

# Plan

- Review the functionality between the GHA and `checkcommits` to ensure the GHA does everything `checkcommits` does.
- Assuming the answer is yes:
  - Delete `checkcommits`.
  - Remove the `checkcommits` code from the [static checker](https://github.com/kata-containers/tests/blob/main/.ci/static-checks.sh).
  - Update [the contribution guide](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#verification) to mention the GHA's rather than `checkcommits`.

### PR DESCRIPTION
**Pull request by bookinabox**
The kata-container/kata-containers repo has been using Github Actions
rather than checkcommits. I have copied over the workflow from

 https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/commit-message-check.yaml

with minor modifications.
 1. The body length is now properly set at 72 rather than 149
 2. Now single-word lines such as urls should not be flagged for being
    too long.

Fixes #4596

Signed-off-by: Derek Lee derlee@redhat.com

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Comment by bookinabox** [comment]
Ironically, I think I made a mistake with my sign-off. I have it tested on my fork, so I think DCO/commit message check should pass now. https://github.com/bookinabox/kata-tests-testing/pull/15

**Comment by fidencio** [comment]
@bookinabox, ideally you'd like to make the same changes in the kata-containers repo (the ones you made here and mentioned as "minor modifications".

**Comment by bookinabox** [comment]
Thanks everyone! I realized I didn't name the file the same as the one in kata-containers, so I will probably rename it for the same consistency reasons. Sorry if that's a hassle.

I will update the kata-containers repo + the community docs as well. Should I raise a new issue in both for my Fixes label? I do see one old issue regarding checkcommits in the [kata-containers repo ](https://github.com/kata-containers/kata-containers/issues/3897)

**Comment by bookinabox** [comment]
kata-containers update: https://github.com/kata-containers/kata-containers/pull/4560
community docs update: https://github.com/kata-containers/community/pull/279

**Comment by bookinabox** [comment]
Late, but realized I forgot to say thanks to everyone, so uh. Thanks!

**Pull request merged**
