### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by stevenhorsman**
Weekly merge of new commits in `main` into `CCv0`

Fixes: #4281
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
```
$ git diff --stat upstream/main -- . ':!*/vendor/*'
 .ci/configure_cni.sh                            |  2 +-
 .ci/install_cri_containerd.sh                   | 31 +++++++++++++++++++++++++++----
 .ci/install_kata_image.sh                       | 12 +++++++++---
 .ci/jenkins_job_build.sh                        |  6 ++++++
 .ci/lib.sh                                      |  8 ++++++++
 .ci/static-checks.sh                            | 13 ++++++++++---
 README.md                                       | 12 ++++++------
 cmd/github-labels/labels.yaml.in                |  4 ++--
 cmd/pmemctl/pmemctl.sh                          |  2 +-
 integration/containerd/cri/integration-tests.sh | 12 +++++++++---
 integration/kubernetes/e2e_conformance/setup.sh |  2 +-
 versions.yaml                                   |  2 +-
 12 files changed, 81 insertions(+), 25 deletions(-)
 ```

**Comment by stevenhorsman** [comment]
There is a problem with this PR - commit https://github.com/kata-containers/tests/pull/4282/commits/a1a457b2841befe937694d4282491fa904a0f20b has a dependency on `Depends-on: github.com/kata-containers/kata-containers#3241`, which mean that we are picking up the incorrect version of code. The only way I can think to resolve this is to rebase and manually remove the depends-on from that commit, but that will involve changing the commit history and force pushing the tests repo. That is not ideal, but it doesn't look like there are any outstanding PRs based on `CCv0`, which is something.
I guess the other option is that I modify the depends-on check to process all of them and only pick up the last one, but in most scenarios when you are doing development on a branch, it's good to know if you have multiple conflicting dependencies.
@fidencio - sorry to bother you, but do you have any ideas on how to best proceed?

**Comment by fidencio** [comment]
> There is a problem with this PR - commit [a1a457b](https://github.com/kata-containers/tests/commit/a1a457b2841befe937694d4282491fa904a0f20b) has a dependency on `Depends-on: github.com/kata-containers/kata-containers#3241`, which mean that we are picking up the incorrect version of code. The only way I can think to resolve this is to rebase and manually remove the depends-on from that commit, but that will involve changing the commit history and force pushing the tests repo. That is not ideal, but it doesn't look like there are any outstanding PRs based on `CCv0`, which is something. I guess the other option is that I modify the depends-on check to process all of them and only pick up the last one, but in most scenarios when you are doing development on a branch, it's good to know if you have multiple conflicting dependencies. @fidencio - sorry to bother you, but do you have any ideas on how to best proceed?

Oh, man, we're hitting a lot of issues that we never thought we'd on keeping those branches rebased, aren´t we? :-)
I wonder if we could come up with a specific word (release?) that we could use to skip those tests? cc @jodh-intel

**Comment by stevenhorsman** [comment]
@sameo, @fidencio - Given that there weren't any merge conflicts (nothing has gone into the tests `CCv0` branch since the last merge up and we are heading towards me doing this weeks merge that might bring more complications), and the problem is just with the CI job, I think the best strategy for this PR, is to merge it (not force push) with the jobs failing, then I can re-run the tests in https://github.com/kata-containers/kata-containers/pull/3260 to make sure that they work. (sorry for the giant sentence!)
That way we can still review the code via this PR (we'll need an approver anyway), we don't mess up any commit history by changing commit messages and having to force push and in the chance that there is an issue with the `CCv0` branch after the merge I guess we can just back it out and re-evaluate.
What do you think about this approach? It's not ideal, but I think the closet we have without attempting to rewrite a bunch of CI job logic for this special case and risk the situation getting more complicated as more changes go into both branches in the meantime.

**Comment by fidencio** [comment]
There's a label called force-skip-ci, which should, theoretically just skip all the CIs.
Let me test whether it works here and we can go ahead and merge it sooner than later, to unblock you.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Comment by stevenhorsman** [comment]
> There's a label called force-skip-ci, which should, theoretically just skip all the CIs. Let me test whether it works here and we can go ahead and merge it sooner than later, to unblock you.

Yes, using that label is a better idea. Thanks!

**Comment by stevenhorsman** [comment]
Hmm, it looks like the label didn't work, or more likely that the merge issues caused by the early depends-on happen before the ci tests run.

**Comment by fidencio** [comment]
Yeah, but let's force it to get merged anyways and, in the worst case scenario, we can re-write the history of this branch,

**Comment by stevenhorsman** [comment]
Thanks, I'll re-run the tests on https://github.com/kata-containers/kata-containers/pull/3260 which will hopefully let us know if there are any issues.

**Comment by stevenhorsman** [comment]
All the tests passed, so I think we are good here!

**Pull request merged**
