### PR TITLE
CCv0: Merge main into CCv0 branch - 21st Feb

### PR DESCRIPTION
**Pull request by stevenhorsman**
Merge remote-tracking branch 'upstream/main' into CCv0

Fixes: https://github.com/kata-containers/tests/issues/4486
Depends-on: github.com/https://github.com/kata-containers/kata-containers/pull/3739

### CODE REVIEW

**Comment by stevenhorsman** [comment]
```
$ git diff --stat upstream/main -- . ':!*/vendor/*'
 .ci/configure_cni.sh                            |  2 +-
 .ci/install_cri_containerd.sh                   | 31 +++++++++++++++++++++++++++----
 .ci/install_kata_image.sh                       | 12 +++++++++---
 .ci/jenkins_job_build.sh                        |  6 ++++++
 .ci/lib.sh                                      |  8 ++++++++
 .ci/resolve-kata-dependencies.sh                | 42 +++++++++++++++++++++++-------------------
 .ci/static-checks.sh                            | 13 ++++++++++---
 README.md                                       | 12 ++++++------
 cmd/github-labels/labels.yaml.in                |  4 ++--
 cmd/pmemctl/pmemctl.sh                          |  2 +-
 integration/containerd/cri/integration-tests.sh | 12 +++++++++---
 integration/kubernetes/e2e_conformance/setup.sh |  2 +-
 versions.yaml                                   |  2 +-
 13 files changed, 104 insertions(+), 44 deletions(-)
 ```

**Comment by c3d** [comment]
Congratulations @stevenhorsman  :-)

**Comment by stevenhorsman** [comment]
The fedora CI `setup.sh` is failing with the following:
```
16:22:04 Error: 
16:22:04  Problem: conflicting requests
16:22:04   - package podman-docker-2:2.2.1-1.fc32.noarch conflicts with docker-ce provided by docker-ce-18.06.3.ce-3.fc28.x86_64
16:22:04   - package podman-docker-2:1.8.2-2.fc32.noarch conflicts with docker-ce provided by docker-ce-18.06.3.ce-3.fc28.x86_64
16:22:04   - problem with installed package docker-ce-18.06.3.ce-3.fc28.x86_64
```
so it looks like maybe now docker-ce is trying to be installed as well as podman?

**Comment by fidencio** [comment]
Okay, just to make it clear what happened here.

The bump to `fedora35` happened not so long ago, but this job was updated to use it.
And, by some reason not worth investigating, docker-ce from Fedora 28 (yep, from Fedora 28!!!) was there, most likely by default?, as part of the Fedora 32 image.

I've updated Jenkins to use the Fedora 35 image here as well, which is what `main` and `stable` branches are using, and it seems to be enough to allow @stevenhorsman  to proceed.
```
11:21:11 Installing:
11:21:11  podman-docker        noarch        3:3.4.4-1.fc35         updates        153 k
11:21:11 
11:21:11 Transaction Summary
11:21:11 ================================================================================
11:21:11 Install  1 Package
11:21:11 
11:21:11 Total download size: 153 k
11:21:11 Installed size: 6.8 k
11:21:11 Downloading Packages:

11:21:11 podman-docker-3.4.4-1.fc35.noarch.rpm           556 kB/s | 153 kB     00:00    
11:21:11 --------------------------------------------------------------------------------
11:21:11 Total                                           225 kB/s | 153 kB     00:00     
11:21:11 Running transaction check
11:21:11 Transaction check succeeded.
11:21:11 Running transaction test
11:21:11 Transaction test succeeded.
11:21:11 Running transaction
11:21:11   Preparing        :                                                        1/1 
11:21:12   Installing       : podman-docker-3:3.4.4-1.fc35.noarch                    1/1 
11:21:12   Running scriptlet: podman-docker-3:3.4.4-1.fc35.noarch                    1/1 
11:21:12 /usr/lib/tmpfiles.d/pam.conf:4: Duplicate line for path "/run/motd.d", ignoring.
11:21:12 /usr/lib/tmpfiles.d/setup.conf:2: Duplicate line for path "/run/motd.d", ignoring.
11:21:12 
11:21:12   Verifying        : podman-docker-3:3.4.4-1.fc35.noarch                    1/1 
11:21:12 
11:21:12 Installed:
11:21:12   podman-docker-3:3.4.4-1.fc35.noarch                                           
11:21:12 
11:21:12 Complete!
```

/cc @snir911 @wainersm, for visibility on the jobs using the Fedora image.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Pull request merged**
