### PR TITLE
test: Enable a kubernetes test for hugepages

### LINKED ISSUE #2070: Enable a kubernetes test for hugepages

### PR DESCRIPTION
**Pull request by GabyCT**
This will enable a kubernetes test for the hugepages configuration only.

Fixes #2070

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
I think we could add the test to https://github.com/kata-containers/tests/blob/master/integration/kubernetes/k8s-hugepages.bats ? so we can reuse the code there.

**Comment by GabyCT** [comment]
@chavafg changes applied

**Pull request merged**
