### PR TITLE
stable-2.1 | k8s: Set mininum timeout for tests and other improvements

### PR DESCRIPTION
**Pull request by fidencio**
Backport of #3503 to the stable-2.1 branch.

### CODE REVIEW

**Review by wainersm — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
@GabyCT, the ARM CI will fail here as it's not rebased atop of that.

**Comment by fidencio** [comment]
/test

Now it's rebased, and let's rerun everything.

**Comment by fidencio** [comment]
Error from the ARM CI (http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-ARM-PR/752/console):
```
20:46:20 ERROR: containerd log :
20:46:20 -------------------------------------
20:46:20 cat: /tmp/test-cri-containerd.iKkp/containerd.log: No such file or directory
20:46:20 Makefile:144: recipe for target 'cri-containerd' failed
20:46:20 make: *** [cri-containerd] Error 1
20:46:20 Failed at 24: sudo -E PATH="$PATH" bash -c "make cri-containerd"
20:46:20 Build step 'Execute shell' marked build as failure
```

**Comment by fidencio** [comment]
Fedora CI failure (http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-fedora-PR/738/console):
```
21:48:34 not ok 1 ConfigMap for a pod
21:48:42 # (in test file k8s-configmap.bats, line 35)
21:48:42 #   `kubectl exec $pod_name -- sh -c $cmd | grep "KUBE_CONFIG_2=value-2"' failed
21:48:42 # INFO: k8s configured to use runtimeclass
21:48:42 # configmap/test-configmap created
21:48:42 # pod/config-env-test-pod created
21:48:42 # pod/config-env-test-pod condition met
21:48:42 # I0512 19:48:42.393472  103407 log.go:184] (0xc000555ef0) (0xc0008a28c0) Create stream
21:48:42 # I0512 19:48:42.393648  103407 log.go:184] (0xc000555ef0) (0xc0008a28c0) Stream added, broadcasting: 1
21:48:42 # I0512 19:48:42.397568  103407 log.go:184] (0xc000555ef0) Reply frame received for 1
21:48:42 # I0512 19:48:42.397592  103407 log.go:184] (0xc000555ef0) (0xc00073c780) Create stream
21:48:42 # I0512 19:48:42.397599  103407 log.go:184] (0xc000555ef0) (0xc00073c780) Stream added, broadcasting: 3
21:48:42 # I0512 19:48:42.398173  103407 log.go:184] (0xc000555ef0) Reply frame received for 3
21:48:42 # I0512 19:48:42.398200  103407 log.go:184] (0xc000555ef0) (0xc0008a2000) Create stream
21:48:42 # I0512 19:48:42.398211  103407 log.go:184] (0xc000555ef0) (0xc0008a2000) Stream added, broadcasting: 5
21:48:42 # I0512 19:48:42.398938  103407 log.go:184] (0xc000555ef0) Reply frame received for 5
21:48:42 # I0512 19:48:42.443315  103407 log.go:184] (0xc000555ef0) Data frame received for 3
21:48:42 # I0512 19:48:42.443342  103407 log.go:184] (0xc00073c780) (3) Data frame handling
21:48:42 # I0512 19:48:42.443352  103407 log.go:184] (0xc00073c780) (3) Data frame sent
21:48:42 # I0512 19:48:42.444117  103407 log.go:184] (0xc000555ef0) Data frame received for 5
21:48:42 # I0512 19:48:42.444132  103407 log.go:184] (0xc0008a2000) (5) Data frame handling
21:48:42 # I0512 19:48:42.444439  103407 log.go:184] (0xc000555ef0) Data frame received for 3
21:48:42 # I0512 19:48:42.444452  103407 log.go:184] (0xc00073c780) (3) Data frame handling
21:48:42 # I0512 19:48:42.446297  103407 log.go:184] (0xc000555ef0) Data frame received for 1
21:48:42 # I0512 19:48:42.446314  103407 log.go:184] (0xc0008a28c0) (1) Data frame handling
21:48:42 # I0512 19:48:42.446333  103407 log.go:184] (0xc0008a28c0) (1) Data frame sent
21:48:42 # I0512 19:48:42.447630  103407 log.go:184] (0xc000555ef0) (0xc0008a28c0) Stream removed, broadcasting: 1
21:48:42 # I0512 19:48:42.447821  103407 log.go:184] (0xc000555ef0) (0xc0008a28c0) Stream removed, broadcasting: 1
21:48:42 # I0512 19:48:42.447829  103407 log.go:184] (0xc000555ef0) (0xc00073c780) Stream removed, broadcasting: 3
21:48:42 # I0512 19:48:42.447902  103407 log.go:184] (0xc000555ef0) (0xc0008a2000) Stream removed, broadcasting: 5
21:48:42 # KUBE_CONFIG_1=value-1
21:48:42 # I0512 19:48:42.572511  103426 log.go:184] (0xc0003eb600) (0xc000941f40) Create stream
21:48:42 # I0512 19:48:42.572564  103426 log.go:184] (0xc0003eb600) (0xc000941f40) Stream added, broadcasting: 1
21:48:42 # I0512 19:48:42.576762  103426 log.go:184] (0xc0003eb600) Reply frame received for 1
21:48:42 # I0512 19:48:42.576792  103426 log.go:184] (0xc0003eb600) (0xc0006592c0) Create stream
21:48:43 # I0512 19:48:42.576801  103426 log.go:184] (0xc0003eb600) (0xc0006592c0) Stream added, broadcasting: 3
21:48:43 # I0512 19:48:42.577680  103426 log.go:184] (0xc0003eb600) Reply frame received for 3
21:48:43 # I0512 19:48:42.577704  103426 log.go:184] (0xc0003eb600) (0xc000940960) Create stream
21:48:43 # I0512 19:48:42.577713  103426 log.go:184] (0xc0003eb600) (0xc000940960) Stream added, broadcasting: 5
21:48:43 # I0512 19:48:42.578348  103426 log.go:184] (0xc0003eb600) Reply frame received for 5
21:48:43 # I0512 19:48:42.605815  103426 log.go:184] (0xc0003eb600) Data frame received for 5
21:48:43 # I0512 19:48:42.605837  103426 log.go:184] (0xc000940960) (5) Data frame handling
21:48:43 # I0512 19:48:42.609258  103426 log.go:184] (0xc0003eb600) Data frame received for 3
21:48:43 # I0512 19:48:42.609276  103426 log.go:184] (0xc0006592c0) (3) Data frame handling
21:48:43 # I0512 19:48:42.611864  103426 log.go:184] (0xc0003eb600) Data frame received for 1
21:48:43 # I0512 19:48:42.611881  103426 log.go:184] (0xc000941f40) (1) Data frame handling
21:48:43 # I0512 19:48:42.611915  103426 log.go:184] (0xc000941f40) (1) Data frame sent
21:48:43 # I0512 19:48:42.612187  103426 log.go:184] (0xc0003eb600) (0xc000941f40) Stream removed, broadcasting: 1
21:48:43 # I0512 19:48:42.612427  103426 log.go:184] (0xc0003eb600) (0xc000941f40) Stream removed, broadcasting: 1
21:48:43 # I0512 19:48:42.612440  103426 log.go:184] (0xc0003eb600) (0xc0006592c0) Stream removed, broadcasting: 3
21:48:43 # I0512 19:48:42.612449  103426 log.go:184] (0xc0003eb600) (0xc000940960) Stream removed, broadcasting: 5
21:48:43 # Name:         config-env-test-pod
21:48:43 # Namespace:    default
21:48:43 # Priority:     0
21:48:43 # Node:         fedoradocker32-90dc90/10.0.0.5
21:48:43 # Start Time:   Wed, 12 May 2021 19:48:35 +0000
21:48:43 # Labels:       <none>
21:48:43 # Annotations:  <none>
21:48:43 # Status:       Running
21:48:43 # IP:           10.244.0.6
21:48:43 # IPs:
21:48:43 #   IP:  10.244.0.6
21:48:43 # Containers:
21:48:43 #   test-container:
21:48:43 #     Container ID:  cri-o://0cfedbaf37fed2802671c966a1e63b0852f23cbbdddeee8de80130daefba34f5
21:48:43 #     Image:         quay.io/prometheus/busybox:latest
21:48:43 #     Image ID:      quay.io/prometheus/busybox@sha256:a56e11cce1c09f50a71290d65733ebe976adc8654395091d5379c7f294cc891e
21:48:43 #     Port:          <none>
21:48:43 #     Host Port:     <none>
21:48:43 #     Command:
21:48:43 #       tail
21:48:43 #       -f
21:48:43 #       /dev/null
21:48:43 #     State:          Running
21:48:43 #       Started:      Wed, 12 May 2021 19:48:41 +0000
21:48:43 #     Ready:          True
21:48:43 #     Restart Count:  0
21:48:43 #     Environment:
21:48:43 #       KUBE_CONFIG_1:  <set to the key 'data-1' of config map 'test-configmap'>  Optional: false
21:48:43 #       KUBE_CONFIG_2:  <set to the key 'data-2' of config map 'test-configmap'>  Optional: false
21:48:43 #     Mounts:
21:48:43 #       /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-q8srx (ro)
21:48:43 # Conditions:
21:48:43 #   Type              Status
21:48:43 #   Initialized       True 
21:48:43 #   Ready             True 
21:48:43 #   ContainersReady   True 
21:48:43 #   PodScheduled      True 
21:48:43 # Volumes:
21:48:43 #   kube-api-access-q8srx:
21:48:43 #     Type:                    Projected (a volume that contains injected data from multiple sources)
21:48:43 #     TokenExpirationSeconds:  3607
21:48:43 #     ConfigMapName:           kube-root-ca.crt
21:48:43 #     ConfigMapOptional:       <nil>
21:48:43 #     DownwardAPI:             true
21:48:43 # QoS Class:                   BestEffort
21:48:43 # Node-Selectors:              <none>
21:48:43 # Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
21:48:43 #                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
21:48:43 # Events:
21:48:43 #   Type    Reason     Age   From               Message
21:48:43 #   ----    ------     ----  ----               -------
21:48:43 #   Normal  Scheduled  7s    default-scheduler  Successfully assigned default/config-env-test-pod to fedoradocker32-90dc90
21:48:43 #   Normal  Pulling    3s    kubelet            Pulling image "quay.io/prometheus/busybox:latest"
21:48:43 #   Normal  Pulled     1s    kubelet            Successfully pulled image "quay.io/prometheus/busybox:latest" in 2.572072549s
21:48:43 #   Normal  Created    1s    kubelet            Created container test-container
21:48:43 #   Normal  Started    1s    kubelet            Started container test-container
21:48:43 # pod "config-env-test-pod" deleted
21:48:43 # configmap "test-configmap" deleted
21:48:43 Failed at 81: bats "${K8S_TEST_ENTRY}"
```

Is this coming from kata or from CRI-O?

**Pull request merged**
