### PR TITLE
CC: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by Megan-Wright**
Merge remote-tracking branch 'upstream/main' into CCv0
    
Fixes: #5327
Depends-on: github.com/kata-containers/kata-containers#5906
    
Signed-off-by: Megan Wright <megan.wright@ibm.com>

### CODE REVIEW

**Comment by Megan-Wright** [comment]
```
git diff --stat upstream/main -- . ':!*/vendor/*'
 .ci/ci_job_flags.sh                                                           |  78 ++++++-
 .ci/install_cloud_hypervisor.sh                                               |  15 +-
 .ci/install_cni_plugins.sh                                                    |   2 +-
 .ci/install_cri_containerd.sh                                                 |  34 ++-
 .ci/install_kata.sh                                                           |   8 +
 .ci/install_kata_image.sh                                                     |  42 +++-
 .ci/install_kata_kernel.sh                                                    |  37 ++-
 .ci/install_ovmf_sev.sh                                                       |  28 +++
 .ci/install_qemu.sh                                                           |  34 ++-
 .ci/install_runtime.sh                                                        |  51 ++--
 .ci/install_td_shim.sh                                                        |  25 ++
 .ci/install_tdvf.sh                                                           |  24 ++
 .ci/install_virtiofsd.sh                                                      |  12 +-
 .ci/jenkins_job_build.sh                                                      |  10 +
 .ci/lib.sh                                                                    |  42 +++-
 .ci/resolve-kata-dependencies.sh                                              |  44 ++--
 .ci/run.sh                                                                    |  24 +-
 .ci/setup.sh                                                                  |   1 +
 .ci/setup_env_ubuntu.sh                                                       |   4 +-
 .ci/static-checks.sh                                                          |  10 +-
 .github/workflows/commit-message-check.yaml                                   |   4 +-
 Makefile                                                                      |  19 +-
 README.md                                                                     |  10 +-
 cmd/check-spelling/data/projects.txt                                          |   1 +
 cmd/github-labels/labels.yaml.in                                              |   4 +-
 cmd/pmemctl/pmemctl.sh                                                        |   2 +-
 functional/kata-monitor/run.sh                                                |   1 +
 functional/sev/fixtures/agent-config.toml                                     |  44 ++++
 functional/sev/run.sh                                                         | 233 +++++++++++++++++++
 .../fixtures/cosign/offline-fs-kbc/aa-offline_fs_kbc-resources.json           |   4 +
 .../confidential/fixtures/offline-fs-kbc/aa-offline_fs_kbc-resources.json.in  |   7 +
 integration/confidential/fixtures/offline-fs-kbc/auth.json.in                 |   7 +
 .../fixtures/offline-fs-kbc/s390x/aa-offline_fs_kbc-resources.json            |   5 +
 .../fixtures/offline-fs-kbc/x86_64/aa-offline_fs_kbc-resources.json           |   5 +
 integration/confidential/fixtures/quay_verification/s390x/public.gpg          |  41 ++++
 integration/confidential/fixtures/quay_verification/s390x/quay_policy.json    |  18 ++
 integration/confidential/fixtures/quay_verification/s390x/signatures.tar      | Bin 0 -> 1930 bytes
 integration/confidential/fixtures/quay_verification/x86_64/public.gpg         |  30 +++
 integration/confidential/fixtures/quay_verification/x86_64/quay_policy.json   |  18 ++
 integration/confidential/fixtures/quay_verification/x86_64/signatures.tar     | Bin 0 -> 2157 bytes
 integration/confidential/fixtures/registries.d/quay.io.yaml                   |   4 +
 integration/confidential/lib.sh                                               | 354 ++++++++++++++++++++++++++++
 integration/containerd/confidential/agent_api.bats                            |  82 +++++++
 integration/containerd/confidential/agent_image.bats                          | 176 ++++++++++++++
 integration/containerd/confidential/asserts.sh                                |  77 +++++++
 integration/containerd/confidential/fixtures/agent-configuration-no-exec.toml |  46 ++++
 integration/containerd/confidential/fixtures/container-config.yaml            |  11 +
 .../containerd/confidential/fixtures/container-config_authenticated.yaml      |   9 +
 .../containerd/confidential/fixtures/container-config_cosigned-other.yaml     |  11 +
 integration/containerd/confidential/fixtures/container-config_cosigned.yaml   |  11 +
 .../confidential/fixtures/container-config_signed-protected-other.yaml        |  11 +
 .../containerd/confidential/fixtures/container-config_unsigned-protected.yaml |  11 +
 .../confidential/fixtures/container-config_unsigned-unprotected.yaml          |  11 +
 integration/containerd/confidential/fixtures/pod-config.yaml.in               |  12 +
 integration/containerd/confidential/lib.sh                                    | 163 +++++++++++++
 integration/containerd/confidential/run_tests.sh                              |  21 ++
 integration/containerd/confidential/tests_common.sh                           | 106 +++++++++
 integration/containerd/cri/integration-tests.sh                               |  12 +-
 integration/kubernetes/confidential/agent_image.bats                          | 255 ++++++++++++++++++++
 integration/kubernetes/confidential/agent_image_encrypted.bats                |  79 +++++++
 integration/kubernetes/confidential/fixtures/encrypted-image-tests.yaml       |  28 +++
 integration/kubernetes/confidential/fixtures/pod-config.yaml.in               |  14 ++
 integration/kubernetes/confidential/fixtures/unencrypted-image-tests.yaml     |  28 +++
 integration/kubernetes/confidential/lib.sh                                    | 125 ++++++++++
 integration/kubernetes/confidential/sev.bats                                  | 447 ++++++++++++++++++++++++++++++++++++
 integration/kubernetes/e2e_conformance/setup.sh                               |   2 +-
 integration/nydus/nydus-sandbox.yaml                                          |   1 +
 integration/nydus/nydus_tests.sh                                              |   2 +
 lib/common.bash                                                               | 127 ++++++++++
 versions.yaml                                                                 |   7 +-
 70 files changed, 3116 insertions(+), 105 deletions(-)
```

**Review by GabyCT — APPROVED** [review]

**Comment by stevenhorsman** [comment]
@UnmeshDeodhar @RyanSavino 
I'm seeing an SEV failure that doesn't seem to be due to the network issues, so you might want to take a look:
```
17:21:57 [0;31mKATA CC SEV TEST - FAIL: SEV is NOT Enabled[0m
17:21:57 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
17:21:57 [0;31mERROR Encountered with Exit Code: 1[0m
17:21:57 ###############################################################################
```

**Comment by UnmeshDeodhar** [comment]
Observed some hardware errors in the dmesg. I have restarted the build.

**Comment by stevenhorsman** [comment]
@UnmeshDeodhar - FYI we are still seeing the failure
```
20:44:55 ssh: Could not resolve hostname <none>: Name or service not known
20:44:55 [0;31mKATA CC SEV TEST - FAIL: SEV is NOT Enabled[0m
20:44:55 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
20:44:55 [0;31mERROR Encountered with Exit Code: 1[0m
20:44:55 ###############################################################################
```

**Comment by fidencio** [comment]
I retriggered the TDX test, as the results I see here were still from a not up-to-date version of the kata-containers counterpart of this PR.

**Comment by stevenhorsman** [comment]
@UnmeshDeodhar - as per slack - I attempted to push https://github.com/kata-containers/tests/pull/5329/commits/eb724d78139d7bf926a6459d0c357b10d1cecf88 to fix these issues, but we're hitting a familiar problem, so I'm not sure if it helped yet, so more re-building:
```
09:44:02 Reading package lists...
09:44:02 
09:44:02 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
09:44:02 
09:44:02 E: The repository 'https://download.docker.com/linux/ubuntu focal Release' no longer has a Release file.
09:44:02 [install_kubernetes.sh:33] ERROR: chronic sudo -E apt update
09:44:02 [jenkins_job_build.sh:251] ERROR: .ci/setup.sh
```

**Comment by stevenhorsman** [comment]
@UnmeshDeodhar - Same networking issues on the re-build:
```
10:41:29 Set up environment (default)
10:41:29 Update apt repositories
10:41:29 
10:41:29 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
10:41:29 
10:41:29 Ign:1 https://download.docker.com/linux/ubuntu focal InRelease
10:41:29 Err:2 https://download.docker.com/linux/ubuntu focal Release
10:41:29   Could not handshake: Error in the pull function. [IP: 65.8.158.64 443]
10:41:29 Hit:4 http://us.archive.ubuntu.com/ubuntu focal InRelease
10:41:29 Hit:3 https://packages.cloud.google.com/apt kubernetes-xenial-unstable InRelease
10:41:29 Get:5 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
10:41:30 Get:6 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
10:41:30 Get:7 http://us.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
10:41:30 Reading package lists...
10:41:31 E: The repository 'https://download.docker.com/linux/ubuntu focal Release' no longer has a Release file.
10:41:31 [setup_env_ubuntu.sh:15] ERROR: sudo -E apt update
```
I'll run it again, but given that we've run the SEV tests > 13 times on this PR I'm getting fed up

**Comment by stevenhorsman** [comment]
@UnmeshDeodhar - still failing with networking problems:
```
12:04:40 Warning: apt-key output should not be parsed (stdout is not a terminal)
12:04:40 OK
12:04:42 Ign:1 https://download.docker.com/linux/ubuntu focal InRelease
12:04:42 Err:2 https://download.docker.com/linux/ubuntu focal Release
12:04:42   Could not handshake: Error in the pull function. [IP: 65.8.158.64 443]
12:04:42 Hit:4 http://us.archive.ubuntu.com/ubuntu focal InRelease
12:04:42 Get:5 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
12:04:42 Hit:3 https://packages.cloud.google.com/apt kubernetes-xenial-unstable InRelease
12:04:42 Get:6 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
12:04:42 Get:7 http://us.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
12:04:42 Reading package lists...
12:04:42 
12:04:42 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
12:04:42 
12:04:42 E: The repository 'https://download.docker.com/linux/ubuntu focal Release' no longer has a Release file.
12:04:42 [install_kubernetes.sh:33] ERROR: chronic sudo -E apt update
12:04:42 [jenkins_job_build.sh:251] ERROR: .ci/setup.sh
```

Can you confirm that the fix I attempted works please, so we can get this merged as the SEV tests clearly aren't stable enough to rely on.

**Comment by fidencio** [comment]
14, same error as before.

**Comment by stevenhorsman** [comment]
The next run has failed with:
```
15:38:37 Events:
15:38:37   Type     Reason                  Age               From               Message
15:38:37   ----     ------                  ----              ----               -------
15:38:37   Normal   Scheduled               21s               default-scheduler  Successfully assigned default/encrypted-image-tests-6dcdbcbc84-zc5k8 to amd-coco-ci-ubuntu2004-001
15:38:37   Warning  FailedCreatePodSandBox  4s (x2 over 19s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: Unable to acquire launch secret from KBS: rpc error: code = Internal desc = Policy validation failed: fw digest not valid: unknown
15:38:37 -------------------------------------------------------------------------------
15:38:37 Pseudo-terminal will not be allocated because stdin is not a terminal.
15:38:37 ssh: Could not resolve hostname <none>: Name or service not known
15:38:37 KATA CC SEV TEST - FAIL: SEV is NOT Enabled
15:38:37 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
15:38:37 ERROR Encountered with Exit Code: 1
15:38:37 ###############################################################################
```
so I guess that means the fix I attempted didn't work?

**Comment by ryansavino** [comment]
I pulled the exact cmdline needed:
```
tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k cryptomgr.notests net.ifnames=0 pci=lastbus=0 console=hvc0 console=hvc1 quiet panic=1 nr_cpus=1 selinux=0 agent.config_file=/etc/agent-config.toml agent.enable_signature_verification=false
```

Can you add it to this PR?

**Comment by ryansavino** [comment]
> @UnmeshDeodhar - still failing with networking problems:
> 
> ```
> 12:04:40 Warning: apt-key output should not be parsed (stdout is not a terminal)
> 12:04:40 OK
> 12:04:42 Ign:1 https://download.docker.com/linux/ubuntu focal InRelease
> 12:04:42 Err:2 https://download.docker.com/linux/ubuntu focal Release
> 12:04:42   Could not handshake: Error in the pull function. [IP: 65.8.158.64 443]
> 12:04:42 Hit:4 http://us.archive.ubuntu.com/ubuntu focal InRelease
> 12:04:42 Get:5 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
> 12:04:42 Hit:3 https://packages.cloud.google.com/apt kubernetes-xenial-unstable InRelease
> 12:04:42 Get:6 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
> 12:04:42 Get:7 http://us.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
> 12:04:42 Reading package lists...
> 12:04:42 
> 12:04:42 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 12:04:42 
> 12:04:42 E: The repository 'https://download.docker.com/linux/ubuntu focal Release' no longer has a Release file.
> 12:04:42 [install_kubernetes.sh:33] ERROR: chronic sudo -E apt update
> 12:04:42 [jenkins_job_build.sh:251] ERROR: .ci/setup.sh
> ```
> 
> Can you confirm that the fix I attempted works please, so we can get this merged as the SEV tests clearly aren't stable enough to rely on.

I've debugged this error, and I know what the issue is. During the setup, adding the k8s apt repo fails due to an issue with a bad google mirror (I think). The ssl cert cannot be verified and causes `apt update` calls to fail in subsequent CI builds. It's intermittent (mirror) and super annoying. I haven't figured out a good solution yet. Still looking into it.

**Comment by stevenhorsman** [comment]
> I pulled the exact cmdline needed:
> 
> ```
> tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k cryptomgr.notests net.ifnames=0 pci=lastbus=0 console=hvc0 console=hvc1 quiet panic=1 nr_cpus=1 selinux=0 agent.config_file=/etc/agent-config.toml agent.enable_signature_verification=false
> ```
> 
> Can you add it to this PR?

Thanks Ryan - it should be correct in https://github.com/kata-containers/tests/pull/5329/commits/4f04e96e7cdfe3c451764e177613207720217947 now.

**Review by stevenhorsman — APPROVED** [review]
Now SEV is working, LGTM

**Pull request merged**
