### PR TITLE
ci: Add containerd+k8s+initrd CI job

### LINKED ISSUE #3676: ci: Creates an CI job configuration for the kata-containers-2.0-ubuntu-initrd-PR jenkins job
The [kata-containers-2.0-ubuntu-initrd-PR](http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-initrd-PR) Jenkins job executes the following script:

```bash
#!/bin/bash

set -e

export ghprbPullId
export ghprbTargetBranch
export DEBUG=true
export CI="true"
export CI_JOB="CRI_CONTAINERD_K8S"
export SHIMV2_TEST="true"

export AGENT_INIT=yes
export TEST_INITRD=yes

export GOPATH=${WORKSPACE}/go
export PATH=${GOPATH}/bin:/usr/local/go/bin:/usr/sbin:${PATH}
export GOROOT="/usr/local/go"

# TEST
kata_repo="github.com/kata-containers/kata-containers"
kata_repo_dir="${GOPATH}/src/${kata_repo}"
mkdir -p "${kata_repo_dir}"

git clone "https://${kata_repo}.git" "${kata_repo_dir}"
cd "${kata_repo_dir}"
# Checkout to main
git checkout "$ghprbTargetBranch"
# END TEST

tests_repo="github.com/kata-containers/tests"
tests_repo_dir="${GOPATH}/src/${tests_repo}"
mkdir -p "${tests_repo_dir}"

git clone "https://${tests_repo}.git" "${tests_repo_dir}"
cd "${tests_repo_dir}"
# Checkout to Target Branch, which should be main
git checkout "$ghprbTargetBranch"
.ci/jenkins_job_build.sh "github.com/kata-containers/kata-containers"
```

Notice it is essentially the `CRI_CONTAINERD_K8S` job configuration plus the `SHIMV2_TEST`, `AGENT_INIT`, `TEST_INITRD` variables exported. To follow the standard way, let's add that job configuration in `.ci/jenkins_job_build.sh` and just export `CI_JOB` properly in the Jenkins job.

### PR DESCRIPTION
**Pull request by wainersm**
Added an CI job configuration to test an initrd image with containerd
and Kubernetes.

Fixes #3676
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @wainersm.

lgtm

**Review by chavafg — APPROVED** [review]

**Comment by fidencio** [comment]
Howdy!

I'd like to ask you to rebase your PR atop of current main, as #3668 has been merged and it has a fix that unblocks the CI.

Please, do the rebase and feel free to `@fidencio` in case you do not have the powers to run `/test`.

Sorry for the inconvenience and happy hacking!

**Comment by wainersm** [comment]
Just rebased this PR.

**Review by chavafg — APPROVED** [review]

**Pull request merged**
