### PR TITLE
tests: Wait to pods to be ready

### LINKED ISSUE #3490: wait to pods to be ready
I have seen random failures in CentOS and Debian CI in the credentials-secrets and volume tests where it seems that we need a timeout to see if a pod is ready
```
15:04:39 not ok 1 Create Persistent Volume
15:05:12 # (in test file k8s-volume.bats, line 57)
15:05:12 #   `kubectl wait --for=condition=Ready pod "$pod_name"' failed
15:05:12 # INFO: k8s configured to use runtimeclass
15:05:12 # persistentvolume/pv-volume created
15:05:12 # pv-volume   10Gi       RWO            Retain           Available           manual                  1s
15:05:12 # persistentvolumeclaim/pv-claim created
15:05:12 # pv-claim   Bound    pv-volume   10Gi       RWO            manual         0s
15:05:12 # pod/pv-pod created
15:05:12 # error: timed out waiting for the condition on pods/pv-pod
15:05:12 # Name:         pv-pod
15:05:12 # Namespace:    default
15:05:12 # Priority:     0
15:05:12 # Node:         centos8-780bc0/10.0.0.7
15:05:12 # Start Time:   Tue, 04 May 2021 20:04:41 +0000
15:05:12 # Labels:       <none>
15:05:12 # Annotations:  <none>
15:05:12 # Status:       Pending
15:05:12 # IP:           
15:05:12 # IPs:          <none>
15:05:12 # Containers:
15:05:12 #   pv-container:
15:05:12 #     Container ID:  
15:05:12 #     Image:         quay.io/prometheus/busybox:latest
15:05:12 #     Image ID:      
15:05:12 #     Port:          <none>
15:05:12 #     Host Port:     <none>
15:05:12 #     Command:
15:05:12 #       sleep
15:05:12 #       120
15:05:12 #     State:          Waiting
15:05:12 #       Reason:       ContainerCreating
15:05:12 #     Ready:          False
15:05:12 #     Restart Count:  0
15:05:12 #     Environment:    <none>
15:05:12 #     Mounts:
15:05:12 #       /mnt/ from pv-storage (rw)
15:05:12 #       /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vlv54 (ro)
15:05:12 # Conditions:
15:05:12 #   Type              Status
15:05:12 #   Initialized       True 
15:05:12 #   Ready             False 
15:05:12 #   ContainersReady   False 
15:05:12 #   PodScheduled      True 
15:05:12 # Volumes:
15:05:12 #   pv-storage:
15:05:12 #     Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
15:05:12 #     ClaimName:  pv-claim
15:05:12 #     ReadOnly:   false
15:05:12 #   kube-api-access-vlv54:
15:05:12 #     Type:                    Projected (a volume that contains injected data from multiple sources)
15:05:12 #     TokenExpirationSeconds:  3607
15:05:12 #     ConfigMapName:           kube-root-ca.crt
15:05:12 #     ConfigMapOptional:       <nil>
15:05:12 #     DownwardAPI:             true
15:05:12 # QoS Class:                   BestEffort
15:05:12 # Node-Selectors:              <none>
15:05:12 # Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
15:05:12 #                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
15:05:12 # Events:
15:05:12 #   Type    Reason     Age   From               Message
15:05:12 #   ----    ------     ----  ----               -------
15:05:12 #   Normal  Scheduled  30s   default-scheduler  Successfully assigned default/pv-pod to centos8-780bc0
15:05:12 #   Normal  Pulling    26s   kubelet            Pulling image "quay.io/prometheus/busybox:latest"
15:05:12 #   Normal  Pulled     25s   kubelet            Successfully pulled image "quay.io/prometheus/busybox:latest" in 317.906895ms
15:05:12 #   Normal  Created    25s   kubelet            Created container pv-container
15:05:12 #   Normal  Started    25s   kubelet            Started container pv-container
15:05:12 # pod "pv-pod" deleted
15:05:12 # persistentvolumeclaim "pv-claim" deleted
```
see http://jenkins.katacontainers.io/view/Kata%202.0/job/kata-containers-2.0-tests-centos-PR/

### PR DESCRIPTION
**Pull request by GabyCT**
This PR puts a timeout in waiting to the pods to be ready as we
have random failures in these tests.

Fixes #3490

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Review by devimc — APPROVED** [review]
thanks @GabyCT

**Pull request merged**
