### PR TITLE
ci: Reenable OOM and sysctl tests when using clh

### PR DESCRIPTION
**Pull request by fidencio**
Fixes: #2864

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Comment by fidencio** [comment]
Here's one successful run: http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/664/console

**Review by jcvenegas — APPROVED** [review]

**Comment by fidencio** [comment]
@GabyCT, may I bother you for an ack here? :-)

**Review by GabyCT — APPROVED** [review]

**Comment by likebreath** [comment]
@fidencio Sorry to miss the PR (was taking off last week). It is great to see those issues have been fixed. Do you have any pointers to what changes (may from runtime/agent) that fixed these two test failures? Thank you.

**Pull request merged**
