### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by Megan-Wright**
Merge remote-tracking branch 'upstream/main' into CCv0
    
Fixes: #4611
Depends-on: github.com/kata-containers/kata-containers#3932

Signed-off-by: Megan Wright <megan.wright@ibm.com>

### CODE REVIEW

**Comment by Megan-Wright** [comment]
```
.ci/ci_job_flags.sh                                                                       |  31 +++++++-
 .ci/configure_cni.sh                                                                      |   2 +-
 .ci/install_cri_containerd.sh                                                             |  31 +++++++-
 .ci/install_kata_image.sh                                                                 |  12 ++-
 .ci/jenkins_job_build.sh                                                                  |   6 ++
 .ci/lib.sh                                                                                |   8 ++
 .ci/resolve-kata-dependencies.sh                                                          |  42 ++++++-----
 .ci/run.sh                                                                                |   4 +
 .ci/setup_env_ubuntu.sh                                                                   |   1 +
 .ci/static-checks.sh                                                                      |  13 +++-
 Makefile                                                                                  |   4 +
 README.md                                                                                 |  12 +--
 cmd/github-labels/labels.yaml.in                                                          |   4 +-
 cmd/pmemctl/pmemctl.sh                                                                    |   2 +-
 integration/containerd/confidential/agent_image.bats                                      | 207 +++++++++++++++++++++++++++++++++++++++++++++++++++
 integration/containerd/confidential/fixtures/container-config.yaml                        |  11 +++
 integration/containerd/confidential/fixtures/container-config_signed-protected-other.yaml |  11 +++
 integration/containerd/confidential/fixtures/container-config_unsigned-protected.yaml     |  11 +++
 integration/containerd/confidential/fixtures/container-config_unsigned-unprotected.yaml   |  11 +++
 integration/containerd/confidential/fixtures/pod-config.yaml                              |  10 +++
 integration/containerd/confidential/lib.sh                                                | 359 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 integration/containerd/confidential/run_tests.sh                                          |  20 +++++
 integration/containerd/cri/integration-tests.sh                                           |  12 ++-
 integration/kubernetes/e2e_conformance/setup.sh                                           |   2 +-
 versions.yaml                                                                             |   2 +-
 25 files changed, 782 insertions(+), 46 deletions(-)
```

**Review by wainersm — APPROVED** [review]
Thanks for working with the merges as well @Megan-Wright ! LGTM.

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
