### PR TITLE
1.x | Use SELinux in the permissive mode for Fedora32 & older

### PR DESCRIPTION
**Pull request by fidencio**

### CODE REVIEW

**Comment by fidencio** [comment]
@GabyCT, this should work the issue around based on tests done previously.  Please, take a look.

**Review by GabyCT — APPROVED** [review]

**Comment by GabyCT** [comment]
thank you @fidencio

**Comment by fidencio** [comment]
```
12:28:24 Error: error checking path "/tmp/jenkins/workspace/kata-containers-tests-podman-clh-fedora-31-PR/go/src/github.com/kata-containers/osbuilder/rootfs": stat /tmp/jenkins/workspace/kata-containers-tests-podman-clh-fedora-31-PR/go/src/github.com/kata-containers/osbuilder/rootfs: no such file or directory
12:28:24 Failed at 187: sudo AGENT_INIT="${AGENT_INIT}" DOCKER_RUNTIME="crun" USE_PODMAN=true ./image-builder/image_builder.sh "$ROOTFS_DIR"
12:28:24 Failed at 27: "${cidir}/install_kata_image.sh" "${tag}"
12:28:24 ++ handle_error 69
12:28:24 ++ local exit_code=125
12:28:24 ++ local line_number=69
12:28:24 ++ echo 'Failed at /tmp/jenkins/workspace/kata-containers-tests-podman-clh-fedora-31-PR/ci_entry_point.sh +69: .ci/jenkins_job_build.sh "${repo_to_test}"'
12:28:24 Failed at /tmp/jenkins/workspace/kata-containers-tests-podman-clh-fedora-31-PR/ci_entry_point.sh +69: .ci/jenkins_job_build.sh "${repo_to_test}"
12:28:24 ++ exit 125
```

This comes from the **jenkins-ci-podman-clh-fedora-31**.  I'll open an issue about that, I have the feeling we have the problem with 2.x and someone else from Red Hat could take a look at this.  @pmores, as you played with osbuilder in the past, could you take a stab at this one?

**Comment by fidencio** [comment]
https://github.com/kata-containers/tests/issues/3439 has been opened to track the **jenkins-ci-podman-clh-fedora-31** failure.

**Review by c3d — APPROVED** [review]
Looks good.

**Comment by fidencio** [comment]
**jenkins-ci-ubuntu-1804-firecracker** is failing because it's CRI-O underneath, and due to instabilities on the device mapper support (on CRI-O side) we removed it here as part of https://github.com/kata-containers/tests/pull/3334

With this in mind, I changed the jenkins job definition to:
```
# Set TEST_CRIO="false" because of https://github.com/kata-containers/tests/pull/3334
export TEST_CRIO="false"
```

**Comment by fidencio** [comment]
I'm merging this one as we have issues opened for the failures and, AFAIU, Power and ARM CI are not online right now.

**Pull request merged**
