### PR TITLE
backport tests for stable 1.5

### PR DESCRIPTION
**Pull request by GabyCT**
0956d03 test: Skip netmon test on q35.
1d124d2 tests: skip netmon test when running with nemu
35ce055 test: Fix ci for RHEL
8bc1c60 tests: Skip unit tests on RHEL
18be952 test: shimv2 test not working on RHEL
0420d91 ci: Fix RHEL script
180c357 test: Fix swarm test instability on RHEL
a5b8311 test: Skip ipvlan test for RHEL
e1e6dbe test: Skip macvlan tests for RHEL
fbfc5fc ci: Add q35 setup
b87b817 tests: Skip shimv2 tests on SLES
265ef78 test: Skip shimv2 on openSUSE Leap
353d93c ci: Add sudo while adding the repository
93c7a03 ci: containerd: add config for runtimeclass
241df3f cri-o: skip new tests introduced in cri-o repo
d63b1a4 ci: Add installation RHEL scripts.
3b07c55 ci: Fix that the docker installation sometimes fails in opensuse
d587064 cri-o: fix name of skipped test
81fc47d integration: cri-o: Skip 'ctr stats'
e245289 test: Add CRI-O dependencies for SLES setup
7628e69 ci: Add installation script for SLES

### CODE REVIEW

**Comment by jcvenegas** [comment]
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-18-04-PR/386/console
```
15:03:33 Summarizing 1 Failure:
15:03:33 
15:03:33 [Fail] Check read-only cgroup filesystem write anything in the cgroup files [It] should fail because of cgroup filesystem MUST BE read-only 
15:03:33 /tmp/jenkins/workspace/kata-containers-tests-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests/integration/docker/run_test.go:231
15:03:33 
15:03:33 Ran 225 of 234 Specs in 2070.827 seconds
15:03:33 FAIL! -- 224 Passed | 1 Failed | 0 Pending | 9 Skipped --- FAIL: TestIntegration (2093.39s)
```

http://jenkins.katacontainers.io/job/kata-containers-tests-centos-7-4-PR-firecracker/438/console
```
14:50:29 Checking 0 containers have all relevant components
14:50:29 Disabling netmon at the configuration file
14:50:29 cd integration/stability && ./bind_mount_linux.sh
14:50:29 Starting stability test: bind_mount_linux.sh
14:50:30 8d1748b3cb07c9673d839f2af6f3357f31f26238619410c3e753336336206e3a
14:51:01 docker: Error response from daemon: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown.
```

**Comment by ganeshmaharaj** [comment]
@GabyCT i am guessing these will also be candidates to make to 1.6 right?

**Comment by jcvenegas** [comment]
@ganeshmaharaj for 1.6 it was already merged

**Comment by jcvenegas** [comment]
https://github.com/kata-containers/tests/issues/1477

**Comment by jcvenegas** [comment]
@chavafg  this sounds familiar, I think you fixed in master ? 
```
18:30:08 not ok 1 Create Persistent Volume
18:30:08 # (in test file k8s-volume.bats, line 42)
18:30:08 #   `sudo -E kubectl get pv $volume_name | grep Available' failed
18:30:08 # kata   5m
18:30:08 # persistentvolume/pv-volume created
18:30:08 # Error from server (NotFound): pods "pv-pod" not found
18:30:08 # Error from server (NotFound): persistentvolumeclaims "pv-claim" not found
18:30:08 # persistentvolume "pv-volume" deleted
18:30:08 Makefile:73: recipe for target 'kubernetes' failed
18:30:08 make: *** [kubernetes] Error 1
18:30:08 Build step 'Execute shell' marked build as failure
18:30:15 Performing Post build task...
18:30:15 Match found for :.* : True
18:30:15 Logical operation result is TRUE
18:30:15 Running script  : #!/bin/bash
18:30:15 
18:30:15 export GOPATH=$WORKSPACE/go
18:30:15 export GOROOT="/usr/local/go"
18:30:15 export PATH=${GOPATH}/bin:/usr/local/go/bin:/usr/sbin:/usr/local/bin:${PATH}
1
```

**Comment by jcvenegas** [comment]
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-nemu/293/console
@sboeuf @chavafg  is this a nemu issue? 
```
18:19:19 Summarizing 2 Failures:
18:19:19 
18:19:19 [Fail] port [AfterEach] port with docker specify a port in a container should return assigned port 
18:19:19 /tmp/jenkins/workspace/kata-containers-tests-ubuntu-nemu/go/src/github.com/kata-containers/tests/integration/docker/port_test.go:25
18:19:19 
18:19:19 [Fail] docker kill killing container [It] with '6'(aborted) signal 
18:19:19 /tmp/jenkins/workspace/kata-containers-tests-ubuntu-nemu/go/src/github.com/kata-containers/tests/integration/docker/kill_test.go:144
18:19:19 
18:19:19 Ran 225 of 234 Specs in 2449.886 seconds
18:19:19 FAIL! -- 223 Passed | 2 Failed | 0 Pending | 9 Skipped --- FAIL: TestIntegration (2474.30s)
```

**Comment by jcvenegas** [comment]
@GabyCT lets ignore nemu as it was not integrated in 1.5
Now ubuntu failing with:
http://jenkins.katacontainers.io/job/kata-containers-tests-ubuntu-18-04-PR/389/consoleFull
```
21:50:06 docker env check that required env variables are set 
21:50:06   should have path, hostname, home
21:50:06   /tmp/jenkins/workspace/kata-containers-tests-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests/integration/docker/env_test.go:30
21:50:06 Running command '/usr/bin/docker [docker run --cidfile /tmp/cid276122564/DfzmeCH4c0a0q4EsvEDPUC07mPprGz --runtime kata-runtime --name DfzmeCH4c0a0q4EsvEDPUC07mPprGz -h container busybox env]'
21:51:06 Killing process timeout reached '60' seconds
21:51:06 Running command '/usr/bin/docker [docker rm -f DfzmeCH4c0a0q4EsvEDPUC07mPprGz]'
21:51:06 [docker rm -f DfzmeCH4c0a0q4EsvEDPUC07mPprGz]
21:51:06 Timeout: 60 seconds
21:51:06 Exit Code: 0
21:51:06 Stdout: DfzmeCH4c0a0q4EsvEDPUC07mPprGz
21:51:06 
21:51:06 Stderr: 
21:51:06 Running command '/usr/bin/docker [docker ps -a -f name=DfzmeCH4c0a0q4EsvEDPUC07mPprGz --format {{.Status}}]'
```

**Comment by jcvenegas** [comment]
Ubuntu passed now, seems that there are still stability issues, merging now.

**Pull request merged**
