### PR TITLE
test: just a test PR for debuting test case

### PR DESCRIPTION
**Pull request by lifupan**
just a test case debug

Fixes:#1047

Signed-off-by: Fupan Li <lifupan@gmail.com>

### CODE REVIEW

**Comment by chavafg** [comment]
I see that #1184 is similar to what's been done here? both PRs fixes #1047, can we close this and continue all work in #1184

**Comment by amshinde** [comment]
@lifupan As @chavafg pointed out, you have two identical PRs open to resolve the same issue. Can one of them be closed?

**Comment by lifupan** [comment]
Yeah, I will close this PR.

**Pull request closed without merging**
