### PR TITLE
ci: qemu_experimental: enable DAX

### PR DESCRIPTION
**Pull request by jcvenegas**
Enable DAX for experimental job.

Fixes: #3377

Signed-off-by: Carlos Venegas <jos.c.venegas.munoz@intel.com>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by likebreath — APPROVED** [review]

**Comment by likebreath** [comment]
Please don't forget the failure on the `jenkins-ci-fedora-32-crio`.

**Pull request merged**
