### PR TITLE
fw/arm64: speed up installation of UEFI image

### PR DESCRIPTION
**Pull request by jongwu**
Building UEFI image from source take at least 5 min. We can build it
once and save it as backup then copy the UEFI image there to cancel the
build in the following UEFI image installation.

Fixes: #5022
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@jongwu, another possible approach would be to cache the UEFI as we do for the kernel / QEMU, and download the cached binary as part of the CI.

As the ARM CI is running on baremetal machines, your approach will do, but if we ever happen to have ARM VMs running, having it "downloadable" would be better.

**Comment by jongwu** [comment]
> @jongwu, another possible approach would be to cache the UEFI as we do for the kernel / QEMU, and download the cached binary as part of the CI.
> 
> As the ARM CI is running on baremetal machines, your approach will do, but if we ever happen to have ARM VMs running, having it "downloadable" would be better.

Yes, cache UEFI at somewhere of net site is better. But I have nowhere to place it.

**Comment by jongwu** [comment]
Help TAL @fidencio @GabyCT. Thanks!

**Review by GabyCT — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jongwu!

**Pull request merged**
