### PR TITLE
qemu: using script to apply qemu patch

### PR DESCRIPTION
**Pull request by jongwu**
remove this ugly way of applying patch in qemu build for arm64.

Fixes: #3994
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jongwu!

**Comment by fidencio** [comment]
This one would be good to be backported to the stable-2.2 branch.

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
