### PR TITLE
docs: Update network metrics document

### LINKED ISSUE #5016: update network metrics document

### PR DESCRIPTION
**Pull request by GabyCT**
This PR updates the network metrics document with the measurements
that we have available in our kata CI.

Fixes #5016

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by cmaf — APPROVED** [review]
thanks @GabyCT

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Pull request merged**
