### PR TITLE
kubernetes: Do not build custom stress image for metrics CI

### LINKED ISSUE #4827: k8s: Do not build custom stress image for metrics CI

### PR DESCRIPTION
**Pull request by GabyCT**
This PR avoids building the custom stress image which is being used
in the integration kubernetes tests in order to avoid delays while
we start kubernetes.

Fixes #4827

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by cmaf — APPROVED** [review]
thanks @GabyCT

**Review by snir911 — APPROVED** [review]

**Pull request merged**
