### PR TITLE
k8s: disable host cache empty dir test

### LINKED ISSUE #1432: Update Kubernetes emptyDir tests
The Kubernetes emptyDir tests need updating for https://github.com/kata-containers/runtime/pull/1485

The tests ensure that the host emptyDir is of type 9p, this will need to be changed to match the new type of mount.

### PR DESCRIPTION
**Pull request by awprice**
Depends-on: github.com/kata-containers/runtime#1485

Fixes #1432

Signed-off-by: Alex Price <aprice@atlassian.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@egernst @chavafg ptal

**Comment by awprice** [comment]
> Looks good. Will we be adding a new test soon it’s place?

Yep, I'd be happy to add a new test.

**Comment by awprice** [comment]
@egernst / @chavafg / @amshinde Apologies for commenting on a closed PR, but correct me if I'm wrong, but I don't think removing the test in this PR was needed in the end, as https://github.com/kata-containers/runtime/pull/1485 was passing without this PR being merged. 

Is it possible to revert/add this test back in?

**Comment by amshinde** [comment]
@awprice This test was checking if the empty-dir was mounted as 9p with `grep "/host/cache type 9p"` and hence was required to be removed as with the runtime PR, this is no longer the case.
The test needs to be modified to check for the correct mount type now.

**Pull request merged**
