### PR TITLE
cri: Remove container_restart_test.go.patch

### PR DESCRIPTION
**Pull request by amshinde**
See issue #5622 for detailed explanation.
This test has long been upstreamed in the containerd repo. More-over this test no longer works for newer container versions(1.7.0) due to changes made upstream.
We should make use of the upstream test.

Fixes: #5622

### CODE REVIEW

**Review by cmaf — APPROVED** [review]
thanks @amshinde

**Review by fengwang666 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
