### PR TITLE
cni: Update the script called for newer version of cni repo

### LINKED ISSUE #1983: Updating the CNI plugin version, needs updating the script called for building plugins.
See : https://github.com/kata-containers/runtime/issues/2111

### PR DESCRIPTION
**Pull request by amshinde**
Depends-on: github.com/kata-containers/runtime#2112

Fixes #1983

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@amshinde , I see the following error
```
15:50:54      BUILD    /tmp/jenkins/workspace/kata-containers-tests-debian-10-PR/go/src/github.com/kata-containers/runtime/kata-runtime
15:51:07 # github.com/kata-containers/runtime/virtcontainers
15:51:07 ../virtcontainers/network.go:1073:12: undefined: ns.NewNS
```

**Comment by amshinde** [comment]
@GabyCT Yeah, Fixed that. Rerunning,
/test

**Comment by GabyCT** [comment]
thanks @amshinde

**Comment by chavafg** [comment]
@amshinde as this depends on the runtime PR: github.com/kata-containers/runtime#2112, I'm adding a DNM flag until we can merge both at the same time.

**Pull request merged**
