### PR TITLE
ci: remove the PodOverhead feature gate for kubernetes 1.26

### PR DESCRIPTION
**Pull request by littlejawa**
Depends-on: github.com/kata-containers/kata-containers#5989 Fixes: #5365

Signed-off-by: Julien Ropé <jrope@redhat.com>

### CODE REVIEW

**Comment by littlejawa** [comment]
@fidencio @liubin 
I'm not confident about the change, and how to make a PR dependent to another.
As you've looked at the original PR, can you get a look here?

**Comment by liubin** [comment]
/test

@littlejawa I think this will work.

**Comment by littlejawa** [comment]
Running the test shows two kind of error:

With containerd, I get the following:
```
11:38:26 error: resource mapping not found for name: "psp.flannel.unprivileged" namespace: "" from "https://raw.githubusercontent.com/coreos/flannel/v0.14.0/Documentation/kube-flannel.yml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

It looks similar to what is described in #5264, which is why I cherry-picked the commits from this PR. Let's see if it goes further. 

With cri-o, I get the following:
```
11:50:38 [preflight] Running pre-flight checks
11:50:38 error execution phase preflight: [preflight] Some fatal errors occurred:
11:50:39 	[ERROR CRI]: container runtime is not running: output: time="2023-01-09T10:50:38Z" level=fatal msg="getting status of runtime: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
11:50:39 , error: exit status 1
11:50:39 [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

I am not sure yet how to address that. The error message is referenced here and there with different cause. I tried to fix the warning about "unix://" prefix on the URL hoping it would help, but it didn't.
Still searching.

**Pull request closed without merging**
