### PR TITLE
ci: Fix vfio CI for stable-2.0

### LINKED ISSUE #3261: vfio and metrics not working on stable-2.0
The metrics CI is not working on stable-2.0, the job gets disconnected while running the tests
```
14:43:36 + git rebase origin/stable-2.0
14:43:36 Current branch PR_3239 is up to date.
14:43:36 + '[' METRICS == VFIO ']'
14:43:36 + .ci/jenkins_job_build.sh github.com/kata-containers/tests
14:43:36 Setup env for kata repository: github.com/kata-containers/tests
14:43:36 Looking for baremetal cleanup script for arch x86_64
14:43:36 Running baremetal cleanup script for arch x86_64
14:43:36 panic: reflect: indirection through nil pointer to embedded struct [recovered]
14:43:36 	panic: reflect: indirection through nil pointer to embedded struct
14:43:36 
14:43:36 goroutine 1 [running]:
14:43:36 text/template.errRecover(0xc0005932a8)
14:43:36 	/usr/local/go/src/text/template/exec.go:170 +0x1b5
14:43:36 panic(0x556272148f40, 0x55627248a400)
14:43:36 	/usr/local/go/src/runtime/panic.go:679 +0x1b6
14:43:36 reflect.Value.FieldByIndex(0x556272302240, 0xc0002bd080, 0x99, 0xc0001a0710, 0x2, 0x2, 0x0, 0x5562725415c0, 0x556272148f40)
14:43:36 	/usr/local/go/src/reflect/value.go:883 +0x39e
14:43:36 text/template.(*state).evalField(0xc000593228, 0x556272302240, 0xc0002bd080, 0x99, 0x7fff107fdd4e, 0x6, 0x556272512480, 0xc0005cdfb0, 0xc0002d3b50, 0x1, ...)
14:43:36 	/usr/local/go/src/text/template/exec.go:605 +0x475
14:43:36 text/template.(*state).evalFieldChain(0xc000593228, 0x556272302240, 0xc0002bd080, 0x99, 0x556272302240, 0xc0002bd080, 0x99, 0x556272512480, 0xc0005cdfb0, 0xc0002d3b40, ...)
14:43:36 	/usr/local/go/src/text/template/exec.go:558 +0x222
14:43:36 text/template.(*state).evalFieldNode(0xc000593228, 0x556272302240, 0xc0002bd080, 0x99, 0xc0005cdfb0, 0xc0002d3b50, 0x1, 0x1, 0x5562721edec0, 0x5562735474c8, ...)
14:43:36 	/usr/local/go/src/text/template/exec.go:522 +0x115
14:43:36 text/template.(*state).evalCommand(0xc000593228, 0x556272302240, 0xc0002bd080, 0x99, 0xc0005cdf80, 0x5562721edec0, 0x5562735474c8, 0x99, 0xd0, 0x5562722e1e20, ...)
14:43:36 	/usr/local/go/src/text/template/exec.go:460 +0x79c
14:43:36 text/template.(*state).evalPipeline(0xc000593228, 0x556272302240, 0xc0002bd080, 0x99, 0xc00022e780, 0xc00016e538, 0xc000034f70, 0xc0005930e0)
14:43:36 	/usr/local/go/src/text/template/exec.go:434 +0x11c
14:43:36 text/template.(*state).walk(0xc000593228, 0x556272302240, 0xc0002bd080, 0x99, 0x556272512300, 0xc0003ec000)
14:43:36 	/usr/local/go/src/text/template/exec.go:258 +0x49d
14:43:36 text/template.(*state).walk(0xc000593228, 0x556272302240, 0xc0002bd080, 0x99, 0x556272512540, 0xc0005cdf50)
14:43:36 	/usr/local/go/src/text/template/exec.go:266 +0x144
14:43:36 text/template.(*Template).execute(0xc0002bd000, 0x5562724abd80, 0xc0002c5b60, 0x556272302240, 0xc0002bd080, 0x0, 0x0)
14:43:36 	/usr/local/go/src/text/template/exec.go:221 +0x20c
14:43:36 text/template.(*Template).Execute(...)
14:43:36 	/usr/local/go/src/text/template/exec.go:204
14:43:36 github.com/docker/cli/cli/command/system.formatInfo(0x55627253c2e0, 0xc000312680, 0x0, 0xc0002d3a70, 0x1, 0x1, 0xc0002d44b0, 0x0, 0x0, 0x0, ...)
14:43:36 	/go/src/github.com/docker/cli/cli/command/system/info.go:490 +0x1f5
14:43:36 github.com/docker/cli/cli/command/system.runInfo(0xc00001eb00, 0x55627253c2e0, 0xc000312680, 0xc0002d3440, 0x0, 0x0)
14:43:36 	/go/src/github.com/docker/cli/cli/command/system/info.go:87 +0x37c
14:43:36 github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc00001eb00, 0xc0002d3900, 0x0, 0x1, 0x0, 0x0)
14:43:36 	/go/src/github.com/docker/cli/cli/command/system/info.go:53 +0x48
14:43:36 github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00001eb00, 0xc000314e10, 0x1, 0x1, 0xc00001eb00, 0xc000314e10)
14:43:36 	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
14:43:36 github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000103b80, 0xc000314e00, 0x2, 0x2)
14:43:36 	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
14:43:36 github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
14:43:36 	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
14:43:36 main.runDocker(0xc000312680, 0x5562724ae3a0, 0xc000010020)
14:43:36 	/go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
14:43:36 main.main()
14:43:36 	/go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3
14:43:36 INFO: kill stale process
14:43:36 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
14:43:37 FATAL: command execution failed
14:43:37 java.io.EOFException
14:43:37 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2799)
14:43:37 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3274)
14:43:37 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:934)
14:43:37 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:396)
14:43:37 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
14:43:37 	at hudson.remoting.Command.readFrom(Command.java:142)
14:43:37 	at hudson.remoting.Command.readFrom(Command.java:128)
14:43:37 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
14:43:37 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
14:43:37 Caused: java.io.IOException: Unexpected termination of the channel
14:43:37 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
14:43:37 Caused: java.io.IOException: Backing channel 'x86_packet_metrics4' is disconnected.
14:43:37 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:216)
14:43:37 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:286)
```
On the other hand the vfio CI is not working on stable-2.0, the failure that we got is
```
15:21:40 ++ mkdir -p /home/jenkins/workspace/workspace/kata-containers-2.0-tests-vfio-PR/go/src/github.com/kata-containers
15:21:40 ++ git clone --quiet https://github.com/kata-containers/kata-containers.git /home/jenkins/workspace/workspace/kata-containers-2.0-tests-vfio-PR/go/src/github.com/kata-containers/kata-containers
15:21:43 ++ cd /home/jenkins/workspace/workspace/kata-containers-2.0-tests-vfio-PR/go/src/github.com/kata-containers/kata-containers
15:21:43 ++ git checkout 2.0-dev
15:21:43 error: pathspec '2.0-dev' did not match any file(s) known to git.
15:21:43 +++ handle_error 155
15:21:43 +++ local exit_code=1
15:21:43 +++ local line_number=155
15:21:43 +++ echo 'Failed at 155: git checkout "$kata_default_branch" 1>&2'
```

### PR DESCRIPTION
**Pull request by GabyCT**
This PR fixes the vfio CI for stable-2.0

Fixes #3261

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
The clh+k8s+containerd CI failure is related with https://github.com/kata-containers/tests/issues/3403

**Comment by GabyCT** [comment]
@devimc and @chavafg could you please take a look ? thanks

**Review by devimc — APPROVED** [review]
thanks @GabyCT 

nit: looks issue 22211 not exist :confused:

**Comment by GabyCT** [comment]
> thanks @GabyCT
> 
> nit: looks issue 22211 not exist 😕

Thanks @devimc fixed the issue :)

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Pull request merged**
