### PR TITLE
ci: Update permissions of containerd install

### PR DESCRIPTION
**Pull request by stevenhorsman**
- Ensure directory we are checking out to is deleted
- Attempt to build containerd with sudo permission

Fixes: #WIP
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by UnmeshDeodhar** [comment]
I am aware that kata main branch builds it without sudo. So, if we want to be consistent, we can probably add `export GOCACHE=/tmp/` as this person has done it for some other repo: https://github.com/sauterp/nix-go-hello-world/pull/1/files
Issue I found with similar results: https://github.com/openshift/release/issues/9748

**Comment by stevenhorsman** [comment]
> I am aware that kata main branch builds it without sudo. So, if we want to be consistent, we can probably add export GOCACHE=/tmp/ as this person has done it for some other repo: https://github.com/sauterp/nix-go-hello-world/pull/1/files
Issue I found with similar results: https://github.com/openshift/release/issues/9748

Thanks for sharing unmesh. Do you want me to try that in this PR, or are you working on the fix somewhere else?

**Comment by stevenhorsman** [comment]
@UnmeshDeodhar - given that SEV fails during one of your tests here, do you think this PR is helpful to merge?

**Comment by UnmeshDeodhar** [comment]
@stevenhorsman I have manually added `export GOCACHE=/tmp/` on the node for now. As this might be "the thing" that is different on our node from other nodes. Now, I am running my job again make sure the CI job is stable. If that is stable, then we might not need to add the `sudo` back in.

**Comment by stevenhorsman** [comment]
> @stevenhorsman I have manually added `export GOCACHE=/tmp/` on the node for now. As this might be "the thing" that is different on our node from other nodes. Now, I am running my job again make sure the CI job is stable. If that is stable, then we might not need to add the `sudo` back in.

Thanks, that's good to know. Let me know when I should stop investigating this and close the PR then please.

**Comment by UnmeshDeodhar** [comment]
Thanks! I will let you know as soon as my job finishes.

**Comment by UnmeshDeodhar** [comment]
@stevenhorsman after I manually exported the GOACHE variable, it is getting reset by the CI job. So yes, it will be helpful to get this PR merged so that we can get past the cri BUILD_TAGS error.

**Comment by stevenhorsman** [comment]
> @stevenhorsman after I manually exported the GOACHE variable, it is getting reset by the CI job. So yes, it will be helpful to get this PR merged so that we can get past the cri BUILD_TAGS error.

Can you make sure there is an issue describing the problem that I can link this PR to please?

**Comment by UnmeshDeodhar** [comment]
This is the issue that I had created a day ago: https://github.com/kata-containers/kata-containers/issues/5801
So, the details have changed. I will add the details in comments.

**Comment by fidencio** [comment]
> This is the issue that I had created a day ago: #5300 So, the details have changed. I will add the details in comments.

@stevenhorsman, I transferred that issue to the tests repo: https://github.com/kata-containers/tests/issues/5300

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Comment by fidencio** [comment]
@UnmeshDeodhar, http://jenkins.katacontainers.io/job/tests-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S-PR/104/console, something is not right with the SEV CI.
```
9:21:21 Set up environment (default)
19:21:21 Update apt repositories
19:21:21 
19:21:21 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
19:21:21 
19:21:21 Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
19:21:21 Hit:2 https://packages.cloud.google.com/apt kubernetes-xenial-unstable InRelease
19:21:21 Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease
19:21:21 Err:4 http://archive.ubuntu.com/ubuntu focal InRelease
19:21:21   403  Forbidden [IP: 2620:2d:4000:1::19 80]
19:21:21 Err:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
19:21:21   403  Forbidden [IP: 2620:2d:4000:1::19 80]
19:21:22 Err:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
19:21:22   403  Forbidden [IP: 2620:2d:4000:1::19 80]
19:21:22 Reading package lists...
19:21:23 W: Target CNF (stable/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:11 and /etc/apt/sources.list.d/docker.list:1
19:21:23 W: Target CNF (stable/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:11 and /etc/apt/sources.list.d/docker.list:1
19:21:23 W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:11 and /etc/apt/sources.list.d/docker.list:1
19:21:23 W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:11 and /etc/apt/sources.list.d/docker.list:1
19:21:23 W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:11 and /etc/apt/sources.list.d/docker.list:1
19:21:23 E: The repository 'http://archive.ubuntu.com/ubuntu focal InRelease' is no longer signed.
19:21:23 E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  403  Forbidden [IP: 2620:2d:4000:1::19 80]
19:21:23 E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  403  Forbidden [IP: 2620:2d:4000:1::19 80]
19:21:23 E: The repository 'http://archive.ubuntu.com/ubuntu focal-updates InRelease' is no longer signed.
19:21:23 E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  403  Forbidden [IP: 2620:2d:4000:1::19 80]
19:21:23 E: The repository 'http://archive.ubuntu.com/ubuntu focal-backports InRelease' is no longer signed.
19:21:23 W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:11 and /etc/apt/sources.list.d/docker.list:1
19:21:23 W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:11 and /etc/apt/sources.list.d/docker.list:1
19:21:23 W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:11 and /etc/apt/sources.list.d/docker.list:1
19:21:23 W: Target CNF (stable/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:11 and /etc/apt/sources.list.d/docker.list:1
19:21:23 W: Target CNF (stable/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:11 and /etc/apt/sources.list.d/docker.list:1
19:21:23 [setup_env_ubuntu.sh:15] ERROR: sudo -E apt update
19:21:23 [jenkins_job_build.sh:247] ERROR: .ci/setup.sh
19:21:23 ++ handle_error 91
19:21:23 ++ local exit_code=100
19:21:23 ++ local line_number=91
19:21:23 ++ echo 'Failed at /home/jenkins/workspace/tests-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S-PR/ci_entry_point.sh +91: .ci/jenkins_job_build.sh "${repo_to_test}"'
19:21:23 Failed at /home/jenkins/workspace/tests-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S-PR/ci_entry_point.sh +91: .ci/jenkins_job_build.sh "${repo_to_test}"
19:21:23 ++ exit 100
19:21:23 Build step 'Execute shell' marked build as failure
19:21:23 Performing Post build task...
19:21:23 Match found for :.* : True
19:21:23 Logical operation result is TRUE
19:21:23 Running script  : #!/bin/bash
```

**Comment by fidencio** [comment]
Interesting, seems to be an issue with Ubuntu mirrors, also affecting other CIs: http://jenkins.katacontainers.io/job/kata-containers-CCv0-tests-ubuntu-20.04-PR/429/console

**Comment by UnmeshDeodhar** [comment]
Yes, I see the same thing in the operator CI as well.

**Comment by fidencio** [comment]
@UnmeshDeodhar, it seems a different error is happening now:
```
[1BCreating simple-kbs_server_1 ... 
20:58:30 [1A[2K
Creating simple-kbs_server_1 ... [32mdone[0m
[1Bfunctional/sev/run.sh: line 70: /home/jenkins/.local/bin/sev-snp-measure: No such file or directory
20:58:35 [0;31mERROR Encountered with Exit Code: 127[0m
20:58:35 ###############################################################################
```

**Comment by UnmeshDeodhar** [comment]
Yes, saw that. Trying to fix it now.

**Comment by UnmeshDeodhar** [comment]
I have added the correct path in .profile now. So next run should be good.

**Pull request merged**
