### PR TITLE
More fixes to stable 2.0.0

### PR DESCRIPTION
**Pull request by wainersm**
Mostly fixes for testing on CentOS.

Cherry-picked the following commits:
c13dc04  .ci/setup_env_centos.sh: Ensure yum-config-manager is installed
644224a  .ci/setup_env_centos.sh: Install bc package
7855005  .ci/setup_env_centos.sh: Install packaged GNU Parallel
c13385c  centos: PowerTools repo got renamed to powertools
a341d7b  integration/kubernetes: Strength the k8s-block-volume test
6821ce1  tests/cri-containerd: Set default value to KATA_HYPERVISOR
b6a94de  tests/cri-containerd: Skip test failing with QEMU

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @wainersm!

**Comment by fidencio** [comment]
@wainersm, looks like CentOS may not be configured to run on stable-2.* branches

**Comment by fidencio** [comment]
@wainersm. actually no, CentOS CI was disabled entirely because it was failing a lot due to the image used & the recent 8.3 release.
Since then it was not brought back.  I'd like to go through the rest of my tests, to come up with changes in the script so we could use an image on Azure based on the official released one (with less modifications than the non-official ones provided by Azure).

**Comment by wainersm** [comment]
@fidencio I am okay to drop this PR if it won't be CI job for CentOS. Although merging it won't hurt either :)

**Comment by fidencio** [comment]
@wainersm, I think it should be merged. :-). My previous message was just to explain why the CentOS 8 CI is not in the list here,.

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `stable-2.0` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Comment by fidencio** [comment]
@wainersm, sorry, but my previous message was incorrect.  During the migration process we can't simply rename a branch that's not the default one and we decided to simply delete the `stable-2.0.0` in favour of creating a new `stable-2.0`.

I'd need to ask you to re-open your PR against the newly created `stable-2.0` branch.

Sorry for the inconvenience.

**Pull request closed without merging**
