### PR TITLE
test: Enable package manager test for virtiofs

### LINKED ISSUE #2008: package manager update test failing on virtiofs CI
Currently the docker integration test for package manager update is failing on virtiofs CI
See
http://jenkins.katacontainers.io/job/kata-containers-agent-ubuntu-18-04-virtiofs-PR/9/console

/cc @chavafg

### PR DESCRIPTION
**Pull request by GabyCT**
This PR enables the package manager test for virtiofs CI.

Fixes #2008

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @GabyCT.

**Review by devimc — APPROVED** [review]
thanks @GabyCT

**Comment by GabyCT** [comment]
@jodh-intel not sure why it is failing at "move issues to in progress in backlog" when the issue is in progress

**Pull request merged**
