### PR TITLE
k8s: add test to check capabilities of pod

### PR DESCRIPTION
**Pull request by egernst**
Check default  capabilities of a given container process, as well as
from exec.

Fixes: #4081

Signed-off-by: Eric Ernst <eric_ernst@apple.com>

### CODE REVIEW

**Comment by egernst** [comment]
/test

Repushed to ensure we have good debug information. I expect this to fail...

**Comment by egernst** [comment]
Thanks for the review @wainersm. I updated to address, PTAL!

**Comment by fidencio** [comment]
@egernst, please, raise a backport for this when possible.

**Pull request merged**
