### PR TITLE
ci: Get package dependencies in alphabetical order

### LINKED ISSUE #2477: get packages dependencies in alphabetical order

### PR DESCRIPTION
**Pull request by GabyCT**
This PR orders the package dependencies for the different distros in alphabetical order
in order to make easier to add or remove packages.

Fixes #2477

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
7 CI fails. I'm sure some of those are known flakes, but 7 is a lot.... better check them I guess?

**Comment by GabyCT** [comment]
@grahamwhaley the reason of why the were failing was the bats issue

**Pull request merged**
