### PR TITLE
stable-2.1 | containerd: Adapt to the new tarball URL

### PR DESCRIPTION
**Pull request by fidencio**
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

lgtm

**Comment by snir911** [comment]
@fidencio note that depends-on is wrong here i guess, as it required since 1.3.x no?

**Review by snir911 — APPROVED** [review]

**Comment by fidencio** [comment]
@snir911, I the majority of the tests will fail as the dependency order is wrong. I should have made this one depending on the one from kata-containers one, but I'll do it after I get green tests there (one CI is still broken).

**Comment by snir911** [comment]
closing, continues in #3744

**Pull request closed without merging**
