### PR TITLE
Backports stable 2.0

### PR DESCRIPTION
**Pull request by bergwolf**
6eab9eb1 ci: fix scripts for centos 8
e62e4492 ci: add make as dependency
9804446a tests: Remove GNU Parallel installation
b4cac932 .ci/setup_env_centos.sh: Fix "too many arguments" error
06ebe787 centos: PowerTools repo got renamed to powertools
57c629e3 .ci/setup_env_centos.sh: Install packaged GNU Parallel
bdb159cf .ci/setup_env_centos.sh: Install bc package
6996289e .ci/setup_env_centos.sh: Ensure yum-config-manager is installed

### CODE REVIEW

**Comment by GabyCT** [comment]
The `vfio` failure is known so we can ignore it for stable-2.0

**Review by GabyCT — APPROVED** [review]

**Comment by GabyCT** [comment]
@bergwolf for the CentOS 8 CI  you need to backport the fix https://github.com/kata-containers/tests/commit/a4dd6e252c3122f796d24d5adf1a999ee8fb5d36

**Comment by bergwolf** [comment]
Thanks @GabyCT !

**Comment by fidencio** [comment]
**jenkins-ci-fedora-32-crio-k8s-e2e-minimal**:
```
09:23:43     - name: '[sig-storage] ConfigMap should be consumable from pods in volume as non-root
09:23:43         [NodeConformance] [Conformance]'
09:23:43       status: failed
09:23:43       details:
09:23:43         failure: "/workspace/anago-v1.18.9-rc.0.79+8147d851af540a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:703\nMar
09:23:43           22 08:22:38.828: Unexpected error:\n    <*errors.errorString | 0xc0017ce050>:
09:23:43           {\n        s: \"expected \\\"content of file \\\\\\\"/etc/configmap-volume/data-1\\\\\\\":
09:23:43           value-1\\\" in container output: Expected\\n    <string>: \\nto match regular
09:23:43           expression\\n    <string>: content of file \\\"/etc/configmap-volume/data-1\\\":
09:23:43           value-1\",\n    }\n    expected \"content of file \\\"/etc/configmap-volume/data-1\\\":
09:23:43           value-1\" in container output: Expected\n        <string>: \n    to match
09:23:43           regular expression\n        <string>: content of file \"/etc/configmap-volume/data-1\":
09:23:43           value-1\noccurred\n/workspace/anago-v1.18.9-rc.0.79+8147d851af540a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:782"
```

This is weird, as it seems that the output format is slightly different than the expected one, but the content seems the same.

**Comment by bergwolf** [comment]
@fidencio Looks like there is no container output:
```
16:23:43       expected "content of file \"/etc/configmap-volume/path/to/data-2\": value-2" in container output: Expected
16:23:43           <string>: 
16:23:43       to match regular expression
16:23:43           <string>: content of file "/etc/configmap-volume/path/to/data-2": value-2
```

**Comment by fidencio** [comment]
@bergwolf, we need those two patches as part of the `kata-containers` repo:
* https://github.com/kata-containers/kata-containers/commit/21801a11a7c8bf3fbed3e7be82170ef68b36b657
* https://github.com/kata-containers/kata-containers/commit/61fccef643492be6a0e354a1a22989f4644c2d06

**Comment by bergwolf** [comment]
Thanks @fidencio! I've included these commits and restarted the tests. Let's see how it goes.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Pull request merged**
