### PR TITLE
# Kata Containers 2.3.2

### PR DESCRIPTION
**Pull request by snir911**
- stable-2.3: backports
- ci: Switch to virtio-9p on s390x
- stable-2.3 | ci: force-skip-ci check before static checks
- stable-2.3 | ci: Run static checks --only-arch

07a46826 ci: fix install_rom_aarch64.sh on non-ubuntu/debian os
209def11 k8s: ensure capability test container logs are available before checking
c3c9f292 ci: Switch to virtio-9p on s390x
50a60777 ci: force-skip-ci check before static checks
ee878115 ci: Run static checks --only-arch

### CODE REVIEW

**Comment by snir911** [comment]
dnm until [test-kata-deploy](https://github.com/kata-containers/kata-containers/actions/runs/1778586983) passes 
/test

**Comment by wainersm** [comment]
> dnm until [test-kata-deploy](https://github.com/kata-containers/kata-containers/actions/runs/1778586983) passes /test

Fingers crossed!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @snir911!

**Review by egernst — APPROVED** [review]

**Pull request merged**
