### PR TITLE
metrics: Rename checkmetrics results to current node for metrics CI

### LINKED ISSUE #4209: rename checkmetrics results for metrics CI

### PR DESCRIPTION
**Pull request by GabyCT**
This PR renames the checkmetrics results as we need it to change the metrics
CI node to a different one due to network connectivity issues.

Fixes #4209

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @GabyCT

**Review by dborquez — APPROVED** [review]
LGTM, thanks @GabyCT

**Pull request merged**
