### PR TITLE
k8s: run CPU test on firecracker

### PR DESCRIPTION
**Pull request by egernst**
With static sandbox resource management, this test should pass.

Fixes: #xxxx
Depends-on: github.com/kata-containers/kata-containers#2941
Signed-off-by: Eric Ernst <eric_ernst@apple.com>

### CODE REVIEW

**Comment by egernst** [comment]
The Firecracker job is the only "interesting one" here -- I'll want to see it pass, then perhaps drop the "depends on" to verify it fails without the runtime fix. 🤞🏻

**Comment by egernst** [comment]
Actually, this will require migrating to K8S 1.23 and container 1.6 -- will put this into draft for now

**Review by jodh-intel — APPROVED** [review]
lgtm.

Now all we need is https://github.com/kata-containers/kata-containers/issues/3555 :smile:

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Comment by jodh-intel** [comment]
@egernst - Can this PR leave "draft mode" yet?

**Comment by jodh-intel** [comment]
Ping @egernst _et al_ - we need another review and to decide if this can leave draft mode.

**Review by amshinde — APPROVED** [review]

**Comment by fidencio** [comment]
As we're in the process (a still long process) of moving tests from this repo to the kata-containers one, we're closing PRs that are either stale for too long.

Please, if you think this has been mistakenly closed, open it agains the `kata-containers` repo as in the coming months this repo will be archived.

**Pull request closed without merging**
