### PR TITLE
metrics: Add script to run FIO in metrics CI

### LINKED ISSUE #4965: add FIO script to run on metrics CI

### PR DESCRIPTION
**Pull request by GabyCT**
This PR adds a script that will be used in our kata metrics CI
so we can collect FIO measurements.

Fixes #4965

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by dborquez — APPROVED** [review]
lgtm

**Review by amshinde — APPROVED** [review]
lgtm, would be good to add latency as well going forward.

**Pull request merged**
