### PR TITLE
Ci improve url checker

### LINKED ISSUE #407: CI URL checker should uniq the file list
The URL checker added on #398 does not `uniq` the file list, leading to duplicate entries in the output.

### PR DESCRIPTION
**Pull request by jodh-intel**
When invalid URLs are found, ensure the list of files that contain such URLs are sorted uniquely to avoid duplication.

Also, improve the error message.

Fixes #407.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
`-u`? :)

**Comment by chavafg** [comment]
lgtm

@jodh-intel can you repush to trigger the CI jobs? Thanks.

**Comment by jodh-intel** [comment]
Re-pushed.

**Comment by jodh-intel** [comment]
Sigh. Two CI checks are failing due to crio and the Ubuntu 17.10 crash - both unrelated to this PR so I'm going to channel @egernst and merge this trivial PR ... :smile:

**Pull request merged**
