### PR TITLE
docs: Moving from EOT to EOF

### PR DESCRIPTION
**Pull request by wzshiming**
uniformly changed to EOF to avoid confusion

Fixes: #4237

Signed-off-by: Shiming Zhang <wzshiming@foxmail.com>

### CODE REVIEW

**Review by jodh-intel — COMMENTED** [review]
Thanks @wzshiming. There are two other files that we should change (`EOC`, `SHELL`):

```bash
$ rg -s "<< *-*[A-Z][A-Z]*\b"|egrep -vi "eot|eof|vendor"
tests/Vagrantfile:  config.vm.provision "shell", env: {"CI_JOB" => job}, inline: <<-SHELL
tests/Vagrantfile:    fedora.vm.provision "shell", reboot: true, inline: <<-SHELL
tests/Vagrantfile:    fedora.vm.provision "shell", inline: <<-SHELL
tests/Vagrantfile:      ubuntu.vm.provision "shell", reboot: true, inline: <<-SHELL
tests/Vagrantfile:    ubuntu.vm.provision "shell", inline: <<-SHELL
tests/integration/kubernetes/k8s-exec.bats:     kubectl exec -i "$pod_name" -- sh <<EOC
tests/integration/kubernetes/k8s-exec.bats:     run bash -c "kubectl exec -i $pod_name -- sh <<EOC
```

I'm assuming we *can* change that Vagrantfile, but @wainersm can probably tell us.

Note the vendor exclude in the command above. There are a few files that "don't confirm" but we need to ensure the static checks don't fail due to vendored code.

**Comment by wzshiming** [comment]
https://github.com/kata-containers/tests/blob/main/Vagrantfile#L68-L97
There may be exceptions here, <<-EOF is nested in <<-SHELL

**Review by jodh-intel — APPROVED** [review]
Thanks @wzshiming.

lgtm, but you might need to update the checker to ignore `Vagrantfile`'s (or include `SHELL` as a valid here-document marker (wdyt @wainersm?)

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/tests/pull/3937.

**Review by liubin — APPROVED** [review]

**Pull request merged**
