### PR TITLE
docs: Update unit test doc for rust

### PR DESCRIPTION
**Pull request by jodh-intel**
Add advice for writing unit tests in rust.

Fixes: #2038.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
travis failure:
```
ERROR: Invalid URL 'file::tempdir' found in the following files:
Unit-Test-Advice.md
```

**Comment by jodh-intel** [comment]
@chavafg - eek! Fixed by https://github.com/kata-containers/tests/pull/2041.

**Comment by jodh-intel** [comment]
Ping @kata-containers/tests. I don't think we need a doc team review as this is mostly a "code change" but it would be good to get this landed.

**Pull request merged**
