### PR TITLE
tests: Add docker search, privileges and restart.

### LINKED ISSUE #57: Add docker integration test for restart, privileges and search
Add docker integration tests for docker restart, docker search and docker run with privileges flag.

### PR DESCRIPTION
**Pull request by GabyCT**
Add docker integration tests for docker search, docker run with privileges flag,
and docker restart.

Fixes #57

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

@GabyCT - Travis is complaining due to some of the static checks failing though:

```
$ bash -c 'KATA_DEV_MODE=true .ci/static-checks.sh'
```

**Comment by GabyCT** [comment]
@jodh-intel thanks I fixed it

**Comment by jodh-intel** [comment]
lgtm

**Comment by jcvenegas** [comment]
lgtm

**Comment by chavafg** [comment]
lgtm

**Pull request merged**
