### PR TITLE
DEBUG: Test Debian kata 2.0

### PR DESCRIPTION
**Pull request by GabyCT**
This is only to test debian.

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@fidencio so debian is not working with kernel 4.19.0-11-cloud-amd64 and centos (I updated to use 8.2) is not working with kernel 4.18.0-80.11.2.el8_0.x86_64

**Comment by fidencio** [comment]
> @fidencio so debian is not working with kernel 4.19.0-11-cloud-amd64 and centos (I updated to use 8.2) is not working with kernel 4.18.0-80.11.2.el8_0.x86_64

@GabyCT, thanks a lot for helping me testing with newer versions of Debian & CentOS.
I've added a comment  in the issue Eric opened, so I can continue debugging Tomorrow: https://github.com/kata-containers/kata-containers/issues/868#issuecomment-705204932.

**Pull request closed without merging**
