### PR TITLE
docs: Fix markdown

### LINKED ISSUE #1486: Fix markdown
Resolve issues in the markdown files in this repo.

### PR DESCRIPTION
**Pull request by jodh-intel**
Resolve issues in the markdown files in this repo.

Fixes #1486.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Ugh - some of these links are now not working with GitHub. Adding dnm...

**Comment by egernst** [comment]
seems fine, minus the broken link.

**Comment by jodh-intel** [comment]
I've got to update my tool to deal with the original (weird but valid) links so let's leave the dnm on this for now.

**Comment by jodh-intel** [comment]
Closing as the links *are* valid - my tool needed to learn more about gfm... ;)

**Pull request closed without merging**
