### PR TITLE
ci: install virtiofsd when installing qemu

### PR DESCRIPTION
**Pull request by bergwolf**
So that we can use it to test virtio-fs.

Depends-on: github.com/kata-containers/kata-containers#936
Fixes: #2950

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
Either that, or get kata pointing to the right directory when building under CentOS.
@wainersm, maybe this is something we can improve in the future.

In any case, for now, just linking is fine lgtm!

**Comment by bergwolf** [comment]
```
11:03:40 INFO: The following package will be installed: crudini
11:03:41 Install os-tree
11:03:42 Job for docker.service failed because the control process exited with error code.
11:03:42 See "systemctl status docker.service" and "journalctl -xe" for details.
11:03:43 Build step 'Execute shell' marked build as failure
11:03:43 Performing Post build task...
11:03:43 Match found for :.* : True
11:03:43 Logical operation result is TRUE
11:03:43 Running script  : #!/bin/bash
```
ARM CI failed on installing `os-tree`. Disk is full?

**Pull request merged**
