### PR TITLE
backport: Changes for stable-2.0

### PR DESCRIPTION
**Pull request by GabyCT**
6ae704da tests: Update instructions for running tests for kata 2.0
9e583fbb integration,k8s: Rely on quay.io images instead of dockerhub ones
6e121816 integration/kubernetes: Strength the k8s-block-volume test
09259b03 k8s: Change pod spec used in k8s-copy-file.bats
4cbcde98 k8s: Skip "k8s-copy-file" tests with CRI-O
f34717aa tests/cri-containerd: Set default value to KATA_HYPERVISOR
2111bc77 kata-webhook: simplify building kata-webhook container
1a4f4f99 CI: Fix xurls url
c16e0a72 lib/common.bash: Fix overwrite of KATA_TESTS_BASEDIR
da6593b5 ci: Init and document SHIMV2_TEST envvar.
3850b74f ci: Not use experimental kernel and qemu
1aa06ca3 ubuntu: Preemptively do an 'apt --fix-broken install'
22acc49e tests: Remove unused build_install_musl function
8e97469a tests: Enable hypervisor stability kill test
3992a628 ci/install_runtime: export PATH on sudo env properly

### CODE REVIEW

**Comment by GabyCT** [comment]
@devimc something strange is happening in the metrics job...with the current backports that I have the CI is being triggered...but if I start adding the metrics tests the connection is being broken

**Comment by GabyCT** [comment]
@devimc do you have any idea why the vfio job is failing what I am missing to backport http://jenkins.katacontainers.io/view/Kata%202.0/job/kata-containers-2.0-tests-vfio-PR/227/console?

**Comment by GabyCT** [comment]
@chavafg , @jcvenegas , @devimc currently the status of this PR is working for the stable-2.0, this PR is bringing tests fixes, ci fixes and so on to stable-2.0. However, metrics and vfio CI are failing and I am not sure how to fix the failure in stable-2.0 and if we should ignore that failure and not enable those CIs for stable-2.0 and merge this PR

**Comment by chavafg** [comment]
I would recommend to remove the Required in metrics and VFIO CIs if we are still in the process of stabilizing these jobs in the stable branches.

**Review by chavafg — APPROVED** [review]

**Review by devimc — APPROVED** [review]

**Review by likebreath — APPROVED** [review]

**Pull request merged**
