### PR TITLE
ci: Enable clh+containerd k8s e2e testing

### LINKED ISSUE #2989: Enable clh+containerd k8s e2e k8s testing for kata 2.x

### PR DESCRIPTION
**Pull request by GabyCT**
This PR enables the clh+containerd full k8s e2e testing.

Fixes #2989

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @GabyCT

**Review by likebreath — APPROVED** [review]
Thanks, @GabyCT.

**Pull request merged**
