### PR TITLE
tracing: Enable agent tracing in test

### LINKED ISSUE #4634: tracing: enable agent tracing in tracing test
Current tracing test only tests runtime; add agent tracing.

### PR DESCRIPTION
**Pull request by cmaf**
Use trace forwarder in tracing test to forward agent spans in order to
include agent tracing in test.

Fixes #4634

Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>

### CODE REVIEW

**Comment by cmaf** [comment]
@jodh-intel could you PTAL? It uses some of the logic from the agent shutdown test. 

Since the agent shutdown test is testing proper agent shutdown, I assumed we don't need anything more than using the trace forwarder and counting additional spans. Do you agree?

**Review by jodh-intel — APPROVED** [review]
Thanks @cmaf.

lgtm

**Comment by cmaf** [comment]
@jodh-intel could you please re-review?

**Review by jodh-intel — APPROVED** [review]
Thanks @cmaf.

lgtm

**Review by amshinde — APPROVED** [review]

**Comment by cmaf** [comment]
@amshinde @jodh-intel could you please review one more time? I added a check for trace forwarder output that uses `waitForProcess`. Adding DNM until re-reviewed because it's otherwise passing. 

/test-ubuntu

**Review by jodh-intel — APPROVED** [review]
Thanks @cmaf.

lgtm

**Comment by cmaf** [comment]
ping @amshinde, could you review a final time?

**Review by chavafg — APPROVED** [review]

**Pull request merged**
