### PR TITLE
SEV Test Fixes

### PR DESCRIPTION
**Pull request by fitzthum**
One minor fix to make things more clear and one bigger fix to make things actually work.

Hopefull will resolve https://github.com/kata-containers/kata-containers/pull/6360
Maybe also https://github.com/kata-containers/kata-containers/pull/5665

@ryansavino 
@stevenhorsman 
@jepio

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks @fitzthum

**Comment by fidencio** [comment]
@fitzthum, we'd appreciate if the commit message could bring any kind of information about the fix you provided.  Usually someone would just go through the commit message and, without having to open the issue it fixes or the PR, be able to get the context of why the previous code had an issue, and how the changes done are able to fix it.

**Pull request merged**
