### PR TITLE
ci: ignore files within kernel/configs directory

### PR DESCRIPTION
**Pull request by egernst**
Make sure we include subdirectories...

Fixes: #2960

Signed-off-by: Eric Ernst <eric.g.ernst@gmail.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
lgtm - thanks @egernst

**Review by likebreath — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Comment by egernst** [comment]
Looks like maybe a new failure, unrelated to this PR? http://jenkins.katacontainers.io/blue/organizations/jenkins/kata-containers-2.0-tests-ubuntu-PR-containerd-k8s-minimal/detail/kata-containers-2.0-tests-ubuntu-PR-containerd-k8s-minimal/127/pipeline#log-3346

```
10:44:35 ./run.sh: line 155: e2e_result_dir: unbound variable
```

Are you aware of this, @chavafg @GabyCT ?

**Comment by chavafg** [comment]
failed before on:
```
time="2020-10-15T17:44:35Z" level=error msg="error attempting to run sonobuoy: waiting for run to finish: failed to get status: failed to get namespace sonobuoy: etcdserver: request timed out"
```
I've seen this before, but not really sure why, not related to this change, so restarted job

Anyway we can also fix that unbound variable.

**Pull request merged**
