### PR TITLE
Fix functional and integration tests tu support golang 1.13

### PR DESCRIPTION
**Pull request by devimc**
cc @chavafg @saschagrunert

### CODE REVIEW

**Comment by chavafg** [comment]
@devimc can you please check,
on travis:
```
integration/docker/main_test.go:72:1: SA3000: TestMain should call os.Exit to set exit code (staticcheck)
func TestMain(m *testing.M) {
^
The command "bash .ci/static-checks.sh github.com/kata-containers/tests" exited with 1.
```


and seems like we will need to update our cri-containerd version as it is now failing there:
```
13:55:19 go test -c github.com/containerd/cri/integration -o _output/integration.test
13:55:48 🇩 _output/containerd
13:55:48 go build -o _output/containerd \
13:55:48 	-tags 'seccomp apparmor' \
13:55:48 	-ldflags '-X github.com/containerd/cri/vendor/github.com/containerd/containerd/version.Version=5d49e7e5-TEST' \
13:55:48 	-gcflags '' \
13:55:48 	github.com/containerd/cri/cmd/containerd
13:56:06 🇩 binaries
13:56:06 🇩 test-integration
13:56:06 flag provided but not defined: -test.run
```

**Comment by saschagrunert** [comment]
Thank you @devimc :pray:

**Pull request merged**
