### PR TITLE
integration/kubernetes: Improve the resource quota test

### PR DESCRIPTION
**Pull request by wainersm**
Improves the resource quota test as discussed in #3857

### CODE REVIEW

**Review by devimc — APPROVED** [review]

**Comment by GabyCT** [comment]
@wainersm please put the label if this PR needs or not a backport and in case that yes, please do it thanks

**Comment by wainersm** [comment]
The resource quota test is failing, I will debug it.

**Review by jodh-intel — APPROVED** [review]

**Pull request merged**
