### PR TITLE
stable-2.3 backports

### PR DESCRIPTION
**Pull request by snir911**
512277055bd9445821e78ede05d2ac1ad7f40772 k8s: cleanup environment before retrying init.sh
70265cafa04b0c94e9787ba67086a3ab0aa4ff14 ci: add backoff sleep
e400f12ac295412e07745ae37d8acef5e7961a62 ci: turn off zram swap
5141a31e36f20ae26eb43596c194ce3b59cb80a9 ci: skip unit tests on ppc64le
2cc8d97bd0e1d1939c1c5cbd4a0e914996cb60d4 env: install runc before podman
a8b6e4aaa594531f7139cb44da335bf0c0582af8 static-checks: Check for the `force-skip-ci` label on each step
cfadec47 ci/static-checks: skip dockerfiles checker if not in x86_64
2e438a7e ci/static-checks: update dockerfiles checker for the kata-containers repo
98d6cf2e ci/static-checks: handle hadolint install
3a743977 ci/static-checks: add a checker for dockerfiles
69348744 ci/openshift-ci: delint dockerfiles (adapted)
c44eb74b conformance/posixfs: delint dockerfiles
f09ad38f metrics: delint dockerfiles
af0492a7 integration/kubernetes: delint dockerfiles
27ec22ee kata-webhook: delint the Dockerfile
98db058b63122fa12d3a691380744d5629aef029 tests: Remove docker integration tests 
ed0da6ad5e4ad304c0c9c692778d1479e1d44a0d ci: Remove docker stability from Makefile

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @snir911!

**Comment by fidencio** [comment]
Please, see https://github.com/kata-containers/kata-containers/pull/3368#issuecomment-1003921668.
```
And it seems that oin ARM / s390x we may be running the static checks based on main rather than on the branch used, as the static checks on the dockerfiles was only added as part of kata-containers/tests#4194.

For the sake of consistency, we better backport it there, or ensure we're running the tests with the correct branch (I'd do both, but mainly ensure the latter).
```

**Review by c3d — APPROVED** [review]
Thanks @snir911, looks good to me.

**Comment by snir911** [comment]
/test
pointed depend-on to https://github.com/kata-containers/kata-containers/pull/3368

**Comment by snir911** [comment]
s390x job is failing with `error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster` which AFAICT it's not related

**Review by bergwolf — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @snir911.

lgtm

**Review by amshinde — APPROVED** [review]

**Pull request merged**
