### PR TITLE
ci: Enable clh+virtiofs CI

### LINKED ISSUE #2788: enable clh+virtiofs kata 2.0

### PR DESCRIPTION
**Pull request by GabyCT**
This PR will allow us to enable a jenkins job for the clh+virtiofs CI.

Depends-on: github.com/kata-containers/kata-containers#533

Fixes #2788

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by likebreath** [comment]
@GabyCT It is great to see the first CI covering clh in kata 2.0. This aligns with what @jcvenegas and I discussed earlier today. Few quick questions: Have you added the corresponding jenkins job? If yes, are we ready to run it?

**Comment by GabyCT** [comment]
@likebreath , I am going to add the jenkins job

**Comment by GabyCT** [comment]
@likebreath @jcvenegas the error that I got is 
```
10:53:36 INFO: Applying patch /tmp/jenkins/workspace/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/go/src/github.com/kata-containers/kata-containers/tools/packaging/kernel/patches//virtio-fs-dev.virtio-fs-dev.x/0001-net-virtio_vsock-Fix-race-condition-between-bind-and.patch
10:53:36 patching file net/vmw_vsock/virtio_transport_common.c
10:53:36 Reversed (or previously applied) patch detected!  Assume -R? [n] 
```
any idea?

**Comment by jcvenegas** [comment]
Seem that this patch is needed: https://github.com/kata-containers/packaging/pull/1098/commits/0549c8dacefd77c4f8000859b2f4f2cc16b74474

**Comment by jcvenegas** [comment]
and this other PR https://github.com/kata-containers/runtime/commit/b8238ce0f25e04105788518956535accf82676bf#diff-811794ac085edc8c084d789655b66452

**Comment by jcvenegas** [comment]
I am not sure who the "backports" are managed in 2.0 as source trees are different?
is this using `git format-patch --relative ` + `git am --directory`[1]
@bergwolf  what is the strategy you are following here ? 
[1] https://stackoverflow.com/questions/16526321/how-to-apply-a-git-patch-to-a-file-with-a-different-name-and-path

**Comment by GabyCT** [comment]
@jcvenegas and @likebreath so it seems that the CI setup is working, the tests are failing mainly because it is trying to run functional or integration (which are not working on 2.0), for running k8s tests, first I thing that we should see if they are working with CLH + kata 2.0, but right now I think that we can merge this and later enable the tests http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/3/console

**Comment by GabyCT** [comment]
This PR needs https://github.com/kata-containers/kata-containers/pull/533

**Comment by likebreath** [comment]
@GabyCT Thanks a lot for helping out here. It looks great to have a running CI. 👍 

I am assuming we are going to merge your PR kata-containers/kata-containers#533 first, from where I can take over to debug on the failing tests and start the back-porting process in 2.0. I am planning to keep this PR open and reuse it for my debugging/back-porting process in kata-containers/kata-containers. We can adjust this PR on the way, and merge it when this CI is passing for all the expected tests. Mainly my thoughts for now. Any advises or comments, please don't hesitate to share. @GabyCT @jcvenegas

**Comment by likebreath** [comment]
> but right now I think that we can merge this and later enable the tests http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/3/console

@GabyCT Oh, I missed this comment. I thought we were planning on having a fully-working CI before we want to land this PR. I am fine with merging the PR right now so that we have a running  CLH CI job that is not running any tests. Either way works for me.

**Pull request merged**
