### PR TITLE
CCv0 | ci: Cherry pick ignore-depends-on from `main`

### PR DESCRIPTION
**Pull request by stevenhorsman**
We need the function from https://github.com/kata-containers/tests/pull/4363 into CCv0 to help with the merge of main into CCv0

Fixes: #4457

### CODE REVIEW

**Comment by stevenhorsman** [comment]
Testing without the label worked [e.g.](http://jenkins.katacontainers.io/job/kata-containers-CCv0-tests-ubuntu-20.04-PR/110/consoleFull) shows:
```
20:27:02 INFO: No ignore_depends_on label found
```

**Comment by stevenhorsman** [comment]
With the `ignore-depends-on` label added, the test run worked successfully [e.g.](http://jenkins.katacontainers.io/job/kata-containers-CCv0-tests-ubuntu-20.04-PR/111/consoleFull):
```
21:20:07 INFO: label 'ignore-depends-on' found
21:20:07 INFO: Ignoring all 'Depends-on' labels
21:20:07 INFO: Not applying depends on due to 'ignore-depends-on' label
```

**Review by wainersm — APPROVED** [review]

**Pull request merged**
