### PR TITLE
ci: enable initrd testing support

### PR DESCRIPTION
**Pull request by bergwolf**
We can set TEST_INITRD=yes to enalbe it.

Fixes: #172

ref: kata-containers/runtime#98

### CODE REVIEW

**Comment by bergwolf** [comment]
```
Repository  was already defined in a 'Depends-on:' tag.
Only one repository per tag is allowed.
Build step 'Execute shell' marked build as failure
```

It seems `Depends-on` is not working as expected? I'm removing the tag from commit message...

**Comment by jodh-intel** [comment]
lgtm

**Comment by sboeuf** [comment]
@bergwolf please fix the Travis issue.

**Comment by bergwolf** [comment]
Both Travis and Jenkins are green now. PTAL.

**Comment by bergwolf** [comment]
CI all green. PTAL @kata-containers/tests

**Comment by bergwolf** [comment]
@grahamwhaley yes, I guess we can configure Jenkins to have sub-jobs to test different environment setups?

**Comment by grahamwhaley** [comment]
Definitely possible I believe.
Either we add sub-jobs, or more parallel jobs for different configs (like we do for different distros).
Sub-jobs is probably the better and right way (it will keep all distro related bits together, and not bloat the number of jobs feeding back ack/nack into github) - but, at the cost of PR processing runtime - presuming we will run the complete set of checks on each sub-job type.
/cc @chavafg

**Comment by bergwolf** [comment]
Yeah, parallel jobs are ok to me as well. Please note that the dependent runtime PR kata-containers/runtime/pull/98 is not merged yet though (waiting Jenkins to pass after this one got merged).

And I suggest we at least test following two environment setups in Jenkins:
```
- AGENT_INIT=yes TEST_INITRD=yes OSBUILDER_DISTRO=alpine
- AGENT_INIT=no TEST_INITRD=no OSBUILDER_DISTRO=clearlinux
```

**Pull request merged**
