### PR TITLE
k8s: enable skipped crio tests for kata 2.0

### PR DESCRIPTION
**Pull request by bergwolf**
We should pass them.

Fixes: #2865

### CODE REVIEW

**Comment by likebreath** [comment]
FYI: the clh CI is failing on installing clh, which should be fixed by the outstanding PR (https://github.com/kata-containers/kata-containers/pull/762). Quote from the [CI log](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/36/console):

```
04:39:10 INFO: current cloud hypervisor : v0.10.0
04:39:10 INFO: cached cloud hypervisor  : v0.9.0
04:39:12 package github.com/cloud-hypervisor/cloud-hypervisor: no Go files in /tmp/jenkins/workspace/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/go/src/github.com/cloud-hypervisor/cloud-hypervisor
04:39:12 /tmp/jenkins/workspace/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/go/src/github.com/cloud-hypervisor /tmp/jenkins/workspace/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/go/src/github.com/kata-containers/tests
04:39:12 INFO: Download cloud-hypervisor version: v0.10.0
04:39:12   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
04:39:12                                  Dload  Upload   Total   Spent    Left  Speed
04:39:12 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   649  100   649    0     0   4133      0 --:--:-- --:--:-- --:--:--  4133
04:39:13 Warning: Failed to create the file cloud-hypervisor: Is a directory
04:39:13 
  0 4221k    0 16360    0     0  47836      0  0:01:30 --:--:--  0:01:30 47836
04:39:13 curl: (23) Failed writing body (0 != 16360)
04:39:13 Failed at 41: "${kata_repo_dir}/tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh"
04:39:13 Failed at 42: "${cidir}/install_cloud_hypervisor.sh"
04:39:13 Build step 'Execute shell' marked build as failure
04:39:20 Performing Post build task...
```

You can add a line in the commit message `Depends-on: github.com/kata-containers/kata-containers#762` to use that fix and see how it goes. This is what's done in the PR https://github.com/kata-containers/tests/pull/2862.

**Review by liubin — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
\o/. Thanks @bergwolf! I :heart: seeing PRs like this :smile:

**Pull request merged**
