### PR TITLE
ci: fix scripts for centos 8

### PR DESCRIPTION
**Pull request by alicefr**
Fix various issues to be able to run `jenkins_job_build.sh` on centos 8. Right now, I hardcoded the docker version, until we decide which is the right one to pick. For more details check  #3245

cc @fidencio

### CODE REVIEW

**Comment by chavafg** [comment]
@alicefr can you please address conflicts? Just merged #3272 from @fidencio to not use a specific old docker version, so that part may be fixed for centos.

**Comment by alicefr** [comment]
Done! After @fidencio it  turned out to be one line fix :)

**Review by fidencio — APPROVED** [review]
thanks, @alicefr!

**Comment by fidencio** [comment]
@chavafg, I re-enabled the CentOS CI via jenkins, but I still can't trigger it here.
If you happen to have some cycles later Today, let me know and I can learn what I've done wrong there.

**Review by c3d — APPROVED** [review]
/lgtm

**Comment by chavafg** [comment]
let's try to run centos CI

/test-centos

@fidencio, looked at the configuration and it seems correct.

**Comment by chavafg** [comment]
triggered for now, let's see how this runs. @fidencio later, you can try again and see if you are now able to trigger the job,

**Comment by alicefr** [comment]
so the Centos job is running until the k8s tests and then fails: http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-centos-PR/301/console. I could reproduce that locally

**Review by GabyCT — APPROVED** [review]

**Comment by GabyCT** [comment]
@fidencio, @alicefr it seems that CentOS CI is still failing in a k8s test, maybe you can skip the test and create an issue in order to avoid other PRs to be failing due to the CentOS CI

**Comment by fidencio** [comment]
@GabyCT, the failures are really non deterministic.  It seems the machine is just slow and we're failing on different tests because of that.

**Comment by GabyCT** [comment]
> @GabyCT, the failures are really non deterministic. It seems the machine is just slow and we're failing on different tests because of that.

so maybe we can merge this change and see how it behaves the CentOS CI (how stable it is) and if it continues to be failing then we should disable it in order to have the CI failing in each PR, wdyt @chavafg @fidencio  @alicefr

**Comment by fidencio** [comment]
@GabyCT, I've increased the only timeout I was able to see as part of the configurations:
Captura de pantalla de 2021-03-17 21-33-30

Is that the right thing?  In any case, CI passed now.

**Comment by GabyCT** [comment]
ok thanks @fidencio , let's merge this and see how it behaves with the modifications

**Pull request merged**
