### PR TITLE
versions: Update cni plugins version

### LINKED ISSUE #5087: update cni plugins version

### PR DESCRIPTION
**Pull request by GabyCT**
This PR updates the cni plugins version that is being used in the
kata CI.

Fixes #5087
Depends-on: https://github.com/kata-containers/kata-containers/pull/5040

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Review by cmaf — APPROVED** [review]

**Pull request merged**
