### PR TITLE
CCv0: Merge main into CCv0 branch 

### PR DESCRIPTION
**Pull request by stevenhorsman**
Merge remote-tracking branch 'upstream/main' into CCv0

Fixes: #4312
Depends-on: github.com/kata-containers/kata-containers#3377

Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
```bash
$ git diff --stat upstream/main -- . ':!*/vendor/*'
 .ci/configure_cni.sh                            |  2 +-
 .ci/install_cri_containerd.sh                   | 31 +++++++++++++++++++++++++++----
 .ci/install_kata_image.sh                       | 12 +++++++++---
 .ci/jenkins_job_build.sh                        |  6 ++++++
 .ci/lib.sh                                      |  8 ++++++++
 .ci/static-checks.sh                            | 13 ++++++++++---
 README.md                                       | 12 ++++++------
 cmd/github-labels/labels.yaml.in                |  4 ++--
 cmd/pmemctl/pmemctl.sh                          |  2 +-
 integration/containerd/cri/integration-tests.sh | 12 +++++++++---
 integration/kubernetes/e2e_conformance/setup.sh |  2 +-
 versions.yaml                                   |  2 +-
 12 files changed, 81 insertions(+), 25 deletions(-)
```

**Comment by jodh-intel** [comment]
@stevenhorsman - looks like there is an issue with the merge:

```
10:48:47 Fetching pull request: 3109 for repository: github.com/kata-containers/kata-containers
10:48:47 From https://github.com/kata-containers/kata-containers
10:48:47  * [new ref]           refs/pull/3109/head -> p3109
10:48:47 Switched to branch 'p3109'
10:48:48 Auto-merging tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
10:48:48 CONFLICT (content): Merge conflict in tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
```

**Comment by stevenhorsman** [comment]
> @stevenhorsman - looks like there is an issue with the merge:
> 
> ```
> 10:48:47 Fetching pull request: 3109 for repository: github.com/kata-containers/kata-containers
> 10:48:47 From https://github.com/kata-containers/kata-containers
> 10:48:47  * [new ref]           refs/pull/3109/head -> p3109
> 10:48:47 Switched to branch 'p3109'
> 10:48:48 Auto-merging tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
> 10:48:48 CONFLICT (content): Merge conflict in tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
> ```

Hi @jodh-intel - thanks for looking. I think this issue is the same as the problem we had with https://github.com/kata-containers/tests/pull/4282. Because we are merging across https://github.com/kata-containers/tests/pull/4313/commits/37e3637f70a0e63e7f87bd9ef08ce394c50b99df from `main` to `CCv0` and that commit has `Depends-on: github.com/kata-containers/kata-containers#3109` then the test code is hitting that then trying to apply that PR, which is already merged and hitting problems, whereas I want to actually test against PR kata-containers/kata-containers#3377. Last time we took a pragmatic decision and just did a force push off the merge to the CCv0 branch. Like then there haven't been any CCv0 changes in the tests repo since the last merge, so it shouldn't cause too many issues to anyone's `CCv0` commit history, but if this is going to happen more regularly then it's probably something we'd like to get resolved once and for all.

**Comment by fidencio** [comment]
Okay, I found the issue, it's been reported at https://github.com/kata-containers/tests/issues/4329 and https://github.com/kata-containers/tests/pull/4330 is the fix for the issue.

**Comment by stevenhorsman** [comment]
@fidencio - I think these will still fail as there are multiple depends-on, but now that they have the correct first dependency the first fix in https://github.com/kata-containers/tests/pull/4320 should be sufficient. I'll clean up that PR on Monday to remove the debugging then test it out again.

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Comment by stevenhorsman** [comment]
Now the [ocicrypt-rs issue](https://github.com/containers/ocicrypt-rs/issues/16) has been solved (with thanks to @sameo), the tests are now all passing. It is work noting that due to the long blockers, the version of `main` this is merging is from 4th Jan, so after it's merged my intention is to immediately do another merge of the latest `main` in, but I want to do them as separate PRs to avoid doubling up on merge complexities.

**Review by wainersm — APPROVED** [review]

**Pull request merged**
