### PR TITLE
CI: Fix branch management when using Depends-on tag

### LINKED ISSUE #707: ci: do not checkout to a stable/master branch when already on a branch created by the depends-on tag
A bug to the CI flow was introduced when we started to support stable branches. 
We are checking out to stable/master branches of the repositories, even when there is a `Depends-on` tag.

### PR DESCRIPTION
**Pull request by chavafg**
This change now verifies if a repository is already
checked-out to the correct branch when there is a
Depends-on tag.

Fixes #707.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
cc @lifupan

**Comment by devimc** [comment]
might be related to https://github.com/kata-containers/tests/issues/679

**Comment by chavafg** [comment]
correct, #679 is being fixed by this.

**Comment by GabyCT** [comment]
lgtm

**Comment by jcvenegas** [comment]
lgtm

**Pull request merged**
