### PR TITLE
cache: fix clh path

### PR DESCRIPTION
**Pull request by jcvenegas**
- Remove extra clh directory path
- Copy binary to assets directory
- Fix install function

Fixes: #2266

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
I pointed the job to my PR for testing, now it works. 
http://jenkins.katacontainers.io/job/cloud-hypervisor-nightly-x86_64/151/

**Comment by GabyCT** [comment]
lgtm

**Pull request merged**
