### PR TITLE
ci: install_qemu: improve script

### LINKED ISSUE #4477: ci: support different qemu types in install_qemu.sh
make install_qemu.sh script more flexible to support different types of qemu, like vanilla and tdx

### PR DESCRIPTION
**Pull request by devimc**
Add options to enable bash debug and build/install different
qemu types, such as tdx and vanilla

fixes #4477

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by jodh-intel — DISMISSED** [review]
Thanks @devimc.

lgtm

**Review by GabyCT — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @devimc!

**Pull request merged**
