### PR TITLE
backport 1.8 tests improvements

### PR DESCRIPTION
**Pull request by GabyCT**
efe44db spellcheck: add minikube
a38e336 ci: metrics: run metrics script using full tests repo path
ccef774 ci: jenkins: metrics: add metrics call direct to jenkins script
ef5b03b ci: Allow travis to use go install script
87caf2a ci: fast-path: install yq before use
f9ca367 ci: Set the complete path for the ci-fast-return.sh
7c39ca0 spellcheck: add macOS
c6a4c1b ci: move pr file list funcs out to library file

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Ooh, OK - are we backporting to 1.8 for convenience, or did we (probably I) actually break something back there that needs fixing?
Prolly lgtm given it is a needed thing..

**Comment by GabyCT** [comment]
@grahamwhaley we are doing the backporting mainly because the ci-fastpath was not working properly in other repositories when we were doing it so I am submitting all the changes to make sure it is working

**Comment by GabyCT** [comment]
This backport includes the fixes for the ci-fastpath as well as general ci improvements

**Comment by chavafg** [comment]
seems that this is not working as expected:
```
14:02:30 INFO: Checking for any changed files that will prevent CI fastpath return
14:02:30 /tmp/jenkins/workspace/kata-containers-tests-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests/.ci/ci-fast-return.sh: line 110: get_pr_changed_file_details: command not found
14:02:30 INFO: No files found
14:02:30 INFO: Checking labels for PR kata-containers/tests/1845
14:02:30 /tmp/jenkins/workspace/kata-containers-tests-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests/.ci/ci-fast-return.sh: line 243: jq: command not found
14:02:30 INFO: No forcing label found
14:02:30 Short circuit fast path skipping the rest of the CI.
14:02:36 Performing Post build task...
```

**Comment by GabyCT** [comment]
@chavafg thanks, changes applied (included the missing PR)

**Comment by chavafg** [comment]
thanks @GabyCT

**Pull request merged**
