### PR TITLE
ci: skip pmem test

### LINKED ISSUE #3224: ci: skip pmem test
see issue https://github.com/kata-containers/tests/issues/3223

### PR DESCRIPTION
**Pull request by devimc**
Pmem test is failing randomly, let's disable to unblock the PRs

fixes #3224

cc @fidencio @GabyCT 

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @devimc!

**Comment by fidencio** [comment]
@dgibson, this should unblock you.

**Comment by fidencio** [comment]
@wainersm, could you take a look here?

**Review by wainersm — APPROVED** [review]
Skipt it, fix then put back. makes sense to me. Thanks @devimc

**Pull request merged**
