### PR TITLE
metrics: Enable latency network measurement

### LINKED ISSUE #4993: enable network latency measurements

### PR DESCRIPTION
**Pull request by GabyCT**
This PR enables the latency network measurements in our kata metrics
CI.

Fixes #4993

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Review by dborquez — APPROVED** [review]
lgtm, thank you @GabyCT

**Pull request merged**
