### PR TITLE
rust-agent: use --release build for rust agent

### PR DESCRIPTION
**Pull request by yyyeerbo**
Fixes: #2276

Signed-off-by: Yang Bo <bo@hyper.sh>

### CODE REVIEW

**Comment by GabyCT** [comment]
Currently we do not have a CI at tests to build the kata-agent in rust.

**Comment by yyyeerbo** [comment]
https://github.com/kata-containers/kata-containers/pull/129
we have

**Comment by GabyCT** [comment]
@yyyeerbo so it looks that it needs some modifications as it is failing
```
+ local rootfs_file=/var/lib/osbuilder/osbuilder.yaml
+ info 'Created summary file '\''/var/lib/osbuilder/osbuilder.yaml'\'' inside rootfs'
+ local 'msg=Created summary file '\''/var/lib/osbuilder/osbuilder.yaml'\'' inside rootfs'
+ echo 'INFO: Created summary file '\''/var/lib/osbuilder/osbuilder.yaml'\'' inside rootfs'
INFO: Created summary file '/var/lib/osbuilder/osbuilder.yaml' inside rootfs
+ exit 0
install: cannot stat '/tmp/jenkins/workspace/kata-containers-rust-agent-ubuntu-18-04-PR/go/src/github.com/kata-containers/kata-containers/src/agent/target/x86_64-unknown-linux-musl/debug/kata-agent': No such file or directory
Failed at 23: "${cidir}/install_kata_image_rust.sh"
```

**Comment by yyyeerbo** [comment]
That is what this pr does

**Pull request merged**
