### PR TITLE
CI: Make here document checker die on error

### PR DESCRIPTION
**Pull request by jodh-intel**
Fix the shell here document static check added on #3937 which detects
problems perfectly, but doesn't actually exit on error.

Fixes: #4568.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Added dnm label since to minimise problems, this PR should not be merged until the following has been:

- https://github.com/kata-containers/kata-containers/pull/3865

**Review by liubin — APPROVED** [review]

**Review by devimc — APPROVED** [review]
thanks @jodh-intel

**Pull request merged**
