### PR TITLE
[stable-2.1] ci: Reenable OOM and sysctl tests when using clh

### PR DESCRIPTION
**Pull request by fidencio**
Fixes: #2864

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@pmores, here's a good example of the CLH CI constantly failing due to https://github.com/kata-containers/tests/issues/3515

**Review by GabyCT — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Review by jcvenegas — APPROVED** [review]

**Pull request merged**
