### PR TITLE
CI: Simplify kata dependencies management

### PR DESCRIPTION
**Pull request by chavafg**
This refactor simplifies the management of the kata
components. The clones and checkouts of them are now managed
in a single script called `resolve-kata-dependencies.sh`,
which is executed before running the `setup.sh`. This new
script manages the branches (stable or master) and any
`Depends-on` tag that may be used in a commit message.

Fixes: #798.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
I know this is WIP, but I fancied a read through to see the direction. OOI, what is the ultimate goal - might we reduce some startup time?, or is this a refactor so we can more easily test out a Jenkins pipeline build maybe?

CIs blew. To save you hunting, a 16.04 fragment below. I will note, there is a potential typo there popped out at me s/Clonning/Cloning/ :-)

```
/tmp/jenkins/workspace/kata-containers-tests-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests
Clonning github.com/kata-containers/runtime
can't load package: package github.com/kata-containers/runtime: no Go files in /tmp/jenkins/workspace/kata-containers-tests-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime
/tmp/jenkins/workspace/kata-containers-tests-ubuntu-16-04-PR/go/src/github.com/kata-containers/runtime /tmp/jenkins/workspace/kata-containers-tests-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests
Checking out to master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
/tmp/jenkins/workspace/kata-containers-tests-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests
Clonning github.com/kata-containers/shim
/tmp/jenkins/workspace/kata-containers-tests-ubuntu-16-04-PR/go/src/github.com/kata-containers/shim /tmp/jenkins/workspace/kata-containers-tests-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests
Checking out to master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
/tmp/jenkins/workspace/kata-containers-tests-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests
Clonning github.com/kata-containers/tests
/tmp/jenkins/workspace/kata-containers-tests-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests /tmp/jenkins/workspace/kata-containers-tests-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests
fatal: Refusing to fetch into current branch refs/heads/PR_799 of non-bare repository
Build step 'Execute shell' marked build as failure
```

**Comment by chavafg** [comment]
@grahamwhaley, 
It has 2 main purposes:
- Use a single script to reduce the complexity of managing the kata components. Having it on different stages of the process is not ideal as it is harder to maintain. Not sure if this is gonna save time (but maybe).
- This will help to better integrate with zuul and maybe later with pipelines. E.g. some of the variables that we are using when cloning and checking out to the correct branch do not have a value on Zuul as those values are taken from jenkins. So we end up having errors in the zuul CI. 

And fixed the typo.

Thanks.

**Comment by jodh-intel** [comment]
lgtm

**Comment by chavafg** [comment]
I've made some local testing with this to make sure I don't brake anything. Seems to work fine. DNM and wip labels removed.

**Pull request merged**
