### PR TITLE
tests: Enable qos k8s test on x86_64

### LINKED ISSUE #4725: enable k8s qos test

### PR DESCRIPTION
**Pull request by GabyCT**
This PR enables the qos k8s test on x86_64.

Fixes #4725

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]

**Review by dborquez — APPROVED** [review]
LGTM, thank you @GabyCT

**Pull request merged**
