### PR TITLE
k8s: fix a problem on flannel installation

### LINKED ISSUE #4381: kubernetes: init sometimes fail to bring up flannel
The baseline job [kata-containers-2.0-ubuntu-20.04-CLOUD-HYPERVISOR-K8S-CRIO-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-ubuntu-20.04-CLOUD-HYPERVISOR-K8S-CRIO-main-baseline/) has failed very often with the error shown below. Not only that job but I've noticed the same failure on [kata-containers-2.0-fedora-32-CRIO_K8S-main-baseline](http://jenkins.katacontainers.io/view/Daily%20baseline/job/kata-containers-2.0-fedora-32-CRIO_K8S-main-baseline) (although it is more rare).

The `integration/kubernetes/init.sh` script installs [flannel](https://github.com/flannel-io/flannel) on the cluster then it waits all the system's pod to start. Happens that sometimes the flannel pod doesn't start and coredns consequently then it bails out with the error we have noticed.

An preliminary investigation pointed me out to https://github.com/cri-o/cri-o/issues/4276 . Maybe that bug on cri-o has hit us....

I opened the issue https://github.com/kata-containers/ci/issues/416 while ago recommending to disable kata-containers-2.0-ubuntu-20.04-CLOUD-HYPERVISOR-K8S-CRIO-main-baseline while we investigate that problem.
 
Cc @GabyCT @ariel-adam @fidencio @jcvenega @likebreath

### Additional information

Typical error message:
```
21:40:20 [init.sh:298] INFO: Wait for system's pods be ready and running
21:40:31 kube-system   kube-apiserver-ubuntu20-bd4df0            1/1     Running   0          11s
21:40:31 kube-system   kube-controller-manager-ubuntu20-bd4df0   1/1     Running   0          13s
21:40:31 kube-system   etcd-ubuntu20-bd4df0                      1/1     Running   0          13s
21:40:31 kube-system   kube-scheduler-ubuntu20-bd4df0            1/1     Running   0          10s
21:42:33 [init.sh:60] INFO: Some expected Pods aren't running after 120 seconds.
21:42:33 NAMESPACE     NAME                                      READY   STATUS              RESTARTS      AGE
21:42:33 kube-system   coredns-78fcd69978-qfprv                  0/1     ContainerCreating   0             2m
21:42:33 kube-system   coredns-78fcd69978-zpwj9                  0/1     ContainerCreating   0             2m
21:42:33 kube-system   etcd-ubuntu20-bd4df0                      1/1     Running             0             2m15s
21:42:33 kube-system   kube-apiserver-ubuntu20-bd4df0            1/1     Running             0             2m13s
21:42:33 kube-system   kube-controller-manager-ubuntu20-bd4df0   1/1     Running             0             2m15s
21:42:33 kube-system   kube-flannel-ds-h5v7x                     0/1     Error               2 (55s ago)   2m
21:42:33 kube-system   kube-proxy-5wwgh                          0/1     ContainerCreating   0             2m
21:42:33 kube-system   kube-scheduler-ubuntu20-bd4df0            1/1     Running             0             2m12s
21:42:33 [DEBUG] Pod coredns-78fcd69978-qfprv:
21:42:33 Name:                 coredns-78fcd69978-qfprv
21:42:33 Namespace:            kube-system
21:42:33 Priority:             2000000000
21:42:33 Priority Class Name:  system-cluster-critical
21:42:33 Node:                 ubuntu20-bd4df0/10.0.0.13
21:42:33 Start Time:           Tue, 18 Jan 2022 00:40:50 +0000
21:42:33 Labels:               k8s-app=kube-dns
21:42:33                       pod-template-hash=78fcd69978
21:42:33 Annotations:          <none>
21:42:33 Status:               Pending
21:42:33 IP:                   
21:42:33 IPs:                  <none>
21:42:33 Controlled By:        ReplicaSet/coredns-78fcd69978
21:42:33 Containers:
21:42:33   coredns:
21:42:33     Container ID:  
21:42:33     Image:         k8s.gcr.io/coredns/coredns:v1.8.4
21:42:33     Image ID:      
21:42:33     Ports:         53/UDP, 53/TCP, 9153/TCP
21:42:33     Host Ports:    0/UDP, 0/TCP, 0/TCP
21:42:33     Args:
21:42:33       -conf
21:42:33       /etc/coredns/Corefile
21:42:33     State:          Waiting
21:42:33       Reason:       ContainerCreating
21:42:33     Ready:          False
21:42:33     Restart Count:  0
21:42:33     Limits:
21:42:33       memory:  170Mi
21:42:33     Requests:
21:42:33       cpu:        100m
21:42:33       memory:     70Mi
21:42:33     Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
21:42:33     Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
21:42:33     Environment:  <none>
21:42:33     Mounts:
21:42:33       /etc/coredns from config-volume (ro)
21:42:33       /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vs6fs (ro)
21:42:33 Conditions:
21:42:33   Type              Status
21:42:33   Initialized       True 
21:42:33   Ready             False 
21:42:33   ContainersReady   False 
21:42:33   PodScheduled      True 
21:42:33 Volumes:
21:42:33   config-volume:
21:42:33     Type:      ConfigMap (a volume populated by a ConfigMap)
21:42:33     Name:      coredns
21:42:33     Optional:  false
21:42:33   kube-api-access-vs6fs:
21:42:33     Type:                    Projected (a volume that contains injected data from multiple sources)
21:42:33     TokenExpirationSeconds:  3607
21:42:33     ConfigMapName:           kube-root-ca.crt
21:42:33     ConfigMapOptional:       <nil>
21:42:33     DownwardAPI:             true
21:42:33 QoS Class:                   Burstable
21:42:33 Node-Selectors:              kubernetes.io/os=linux
21:42:33 Tolerations:                 CriticalAddonsOnly op=Exists
21:42:33                              node-role.kubernetes.io/control-plane:NoSchedule
21:42:33                              node-role.kubernetes.io/master:NoSchedule
21:42:33                              node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
21:42:33                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
21:42:33 Events:
21:42:33   Type     Reason                  Age   From               Message
21:42:33   ----     ------                  ----  ----               -------
21:42:33   Warning  FailedScheduling        2m    default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
21:42:33   Normal   Scheduled               103s  default-scheduler  Successfully assigned kube-system/coredns-78fcd69978-qfprv to ubuntu20-bd4df0
21:42:33   Warning  FailedCreatePodSandBox  102s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-qfprv_kube-system_34868c32-fc68-48fc-a76b-a3f80500f062_0(2cff8637c794b9d23a6f891b656be0d2967e82a4f665b05a5c3fc8158148a606): error adding pod kube-system_coredns-78fcd69978-qfprv to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  89s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-qfprv_kube-system_34868c32-fc68-48fc-a76b-a3f80500f062_0(b42c68580d9fc38c65101d106e3947c7e0a0abb8a32fd01f65ac35f3e722ac7a): error adding pod kube-system_coredns-78fcd69978-qfprv to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  76s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-qfprv_kube-system_34868c32-fc68-48fc-a76b-a3f80500f062_0(61a57287310334b375e5f52bfd6bc2f5504d858ad0ebe386413104a9775a776a): error adding pod kube-system_coredns-78fcd69978-qfprv to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  61s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-qfprv_kube-system_34868c32-fc68-48fc-a76b-a3f80500f062_0(5acf1fcdc192056921f4b258c78ce39491dccb2ceedc4945e8e6a606f5d34ae8): error adding pod kube-system_coredns-78fcd69978-qfprv to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  49s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-qfprv_kube-system_34868c32-fc68-48fc-a76b-a3f80500f062_0(e486afd9b3e4f1760f59a12c660600d1dbb2f4654ea3cf11fbcfe66cc2f0df0d): error adding pod kube-system_coredns-78fcd69978-qfprv to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  38s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-qfprv_kube-system_34868c32-fc68-48fc-a76b-a3f80500f062_0(ac278bb32d503a2b4543960ed481ba07adcd84e841ff2bfc5a9a993d9f6f9424): error adding pod kube-system_coredns-78fcd69978-qfprv to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  24s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-qfprv_kube-system_34868c32-fc68-48fc-a76b-a3f80500f062_0(c5c91af8e397f8f11a2d5aef6aa3727c6018932d12912e9dfdde8e23c5edd4d6): error adding pod kube-system_coredns-78fcd69978-qfprv to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  12s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-qfprv_kube-system_34868c32-fc68-48fc-a76b-a3f80500f062_0(7ee96392ebd5ea9efc1bd0eb29ea80c9d3e67d5e70291cd17791d94812f96982): error adding pod kube-system_coredns-78fcd69978-qfprv to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33 [DEBUG] Pod coredns-78fcd69978-zpwj9:
21:42:33 Name:                 coredns-78fcd69978-zpwj9
21:42:33 Namespace:            kube-system
21:42:33 Priority:             2000000000
21:42:33 Priority Class Name:  system-cluster-critical
21:42:33 Node:                 ubuntu20-bd4df0/10.0.0.13
21:42:33 Start Time:           Tue, 18 Jan 2022 00:40:50 +0000
21:42:33 Labels:               k8s-app=kube-dns
21:42:33                       pod-template-hash=78fcd69978
21:42:33 Annotations:          <none>
21:42:33 Status:               Pending
21:42:33 IP:                   
21:42:33 IPs:                  <none>
21:42:33 Controlled By:        ReplicaSet/coredns-78fcd69978
21:42:33 Containers:
21:42:33   coredns:
21:42:33     Container ID:  
21:42:33     Image:         k8s.gcr.io/coredns/coredns:v1.8.4
21:42:33     Image ID:      
21:42:33     Ports:         53/UDP, 53/TCP, 9153/TCP
21:42:33     Host Ports:    0/UDP, 0/TCP, 0/TCP
21:42:33     Args:
21:42:33       -conf
21:42:33       /etc/coredns/Corefile
21:42:33     State:          Waiting
21:42:33       Reason:       ContainerCreating
21:42:33     Ready:          False
21:42:33     Restart Count:  0
21:42:33     Limits:
21:42:33       memory:  170Mi
21:42:33     Requests:
21:42:33       cpu:        100m
21:42:33       memory:     70Mi
21:42:33     Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
21:42:33     Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
21:42:33     Environment:  <none>
21:42:33     Mounts:
21:42:33       /etc/coredns from config-volume (ro)
21:42:33       /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8ldv7 (ro)
21:42:33 Conditions:
21:42:33   Type              Status
21:42:33   Initialized       True 
21:42:33   Ready             False 
21:42:33   ContainersReady   False 
21:42:33   PodScheduled      True 
21:42:33 Volumes:
21:42:33   config-volume:
21:42:33     Type:      ConfigMap (a volume populated by a ConfigMap)
21:42:33     Name:      coredns
21:42:33     Optional:  false
21:42:33   kube-api-access-8ldv7:
21:42:33     Type:                    Projected (a volume that contains injected data from multiple sources)
21:42:33     TokenExpirationSeconds:  3607
21:42:33     ConfigMapName:           kube-root-ca.crt
21:42:33     ConfigMapOptional:       <nil>
21:42:33     DownwardAPI:             true
21:42:33 QoS Class:                   Burstable
21:42:33 Node-Selectors:              kubernetes.io/os=linux
21:42:33 Tolerations:                 CriticalAddonsOnly op=Exists
21:42:33                              node-role.kubernetes.io/control-plane:NoSchedule
21:42:33                              node-role.kubernetes.io/master:NoSchedule
21:42:33                              node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
21:42:33                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
21:42:33 Events:
21:42:33   Type     Reason                  Age   From               Message
21:42:33   ----     ------                  ----  ----               -------
21:42:33   Warning  FailedScheduling        2m    default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
21:42:33   Normal   Scheduled               103s  default-scheduler  Successfully assigned kube-system/coredns-78fcd69978-zpwj9 to ubuntu20-bd4df0
21:42:33   Warning  FailedCreatePodSandBox  102s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-zpwj9_kube-system_59857ea2-9f15-4fb3-9d68-45a730c9374c_0(cb24d496b49588d45f92a1010bd500f86250a64c4a0a39df2573f593c87fcd7f): error adding pod kube-system_coredns-78fcd69978-zpwj9 to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  88s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-zpwj9_kube-system_59857ea2-9f15-4fb3-9d68-45a730c9374c_0(d9e67acc9ad441cd52f6d5cf39efb80cb8000b7b9aa816e463e2b771d886f070): error adding pod kube-system_coredns-78fcd69978-zpwj9 to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  77s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-zpwj9_kube-system_59857ea2-9f15-4fb3-9d68-45a730c9374c_0(2781425464e7a3cf37da0bd9c33a7de754297d86fac0fb6e8003a522e6403c89): error adding pod kube-system_coredns-78fcd69978-zpwj9 to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  63s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-zpwj9_kube-system_59857ea2-9f15-4fb3-9d68-45a730c9374c_0(69f0c097826888de8be8a947cc49fa1b7df255f8cbc95bb0e0657b41b7cfc6bd): error adding pod kube-system_coredns-78fcd69978-zpwj9 to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  52s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-zpwj9_kube-system_59857ea2-9f15-4fb3-9d68-45a730c9374c_0(574a95ae3c1b4eae3cff2290e0b0044583642c59fab9b7c7cb9914b6bed96fc0): error adding pod kube-system_coredns-78fcd69978-zpwj9 to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  40s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-zpwj9_kube-system_59857ea2-9f15-4fb3-9d68-45a730c9374c_0(b65a7195741671d7139e298cb0a87c2cae15546fd3b56162df9f69d7bfba9979): error adding pod kube-system_coredns-78fcd69978-zpwj9 to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  27s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-zpwj9_kube-system_59857ea2-9f15-4fb3-9d68-45a730c9374c_0(6f9b340dbbe5a73933c63a7abeaa4b8d9110cf9c59e757995592af980ff2084a): error adding pod kube-system_coredns-78fcd69978-zpwj9 to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  15s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-zpwj9_kube-system_59857ea2-9f15-4fb3-9d68-45a730c9374c_0(ae5bec5600d8c8f30fe25e10d7b0d261cf1a418bf1fd2265407db310935112a3): error adding pod kube-system_coredns-78fcd69978-zpwj9 to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33   Warning  FailedCreatePodSandBox  2s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-78fcd69978-zpwj9_kube-system_59857ea2-9f15-4fb3-9d68-45a730c9374c_0(710908c73e8c2a2d6ee6c2d9df41c70edd00a5be6de83bf75a59f38d15280991): error adding pod kube-system_coredns-78fcd69978-zpwj9 to CNI network "cbr0": open /run/flannel/subnet.env: no such file or directory
21:42:33 [init.sh:71] ERROR: Kubernetes is not fully ready. Bailing out...
```

Cc @GabyCT @ariel-adam @fidencio @jcvenega @likebreath

### PR DESCRIPTION
**Pull request by wainersm**
Tentative to fix a problem with CRI-O. Apparently it can sometimes not realize a new CNI configuration was installed as a result the deployed flannel pods fail to start up. 

Fixes #4381
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

### CODE REVIEW

**Comment by wainersm** [comment]
I created this PR to debug the issue https://github.com/kata-containers/tests/issues/4381 as I couldn't reproduce locally.

/test-ubuntu-clh

**Comment by wainersm** [comment]
I'm sending a fix for this problem but I failed miserably to reproduce it either locally or in CI. So I am kind of blindly proposing a fix.

I will be running the jobs a couple of times to see how it goes.

**Comment by wainersm** [comment]
Hi @GabyCT !

FYI, it's a tentative to fix the problem with cri-o...

**Review by GabyCT — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @wainersm.

lgtm

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Pull request merged**
