### PR TITLE
ci: Kill tasks by whole word in clean_env_ctr

### PR DESCRIPTION
**Pull request by GabyCT**
- grep container for whole word in tasks. Otherwise, e.g. `test1` can be
  caught when `test` is to be removed, and `test1` won't find anything.
- cut name out -- no point in killing `[PID] RUNNING`
- Rename this variable from `tasks` to `task` to avoid confusion. There
  will be no more than one task associated with the container name.

Fixes: #3961
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]

**Review by cmaf — COMMENTED** [review]
@GabyCT does this PR encompass more than one backport? It has more changes than the [original commit ](https://github.com/kata-containers/tests/pull/3970/commits/ddcd2265734680e400af8e459457cfa79e3b7032)

**Comment by GabyCT** [comment]
> @GabyCT does this PR encompass more than one backport? It has more changes than the [original commit ](https://github.com/kata-containers/tests/pull/3970/commits/ddcd2265734680e400af8e459457cfa79e3b7032)

yes it does

**Comment by GabyCT** [comment]
The main reason is because other commits are related with metrics changes which are not backported and this function is not metrics specific @cmaf

**Review by cmaf — APPROVED** [review]

**Pull request merged**
