### PR TITLE
docs: Update readme for metrics

### LINKED ISSUE #3710: update readme for metrics

### PR DESCRIPTION
**Pull request by GabyCT**
This PR updates the documentation for metrics with the current
implementation for kata 2.x metrics CI and tests. This PR removes
the master branch trending topics as they are not implemented in
kata 2.x metrics CI and also the master tracking as for kata 2.x
all metrics tests are being run.

Fixes #3710

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by jodh-intel — COMMENTED** [review]
Hi @GabyCT - the change looks ok, but I'm not clear _why_ the change is being made :)

Could you add some details to the issue/commit to help explain?

**Comment by GabyCT** [comment]
@jodh-intel changes applied

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Review by jodh-intel — APPROVED** [review]
Thanks @GabyCT.

lgtm

**Pull request merged**
