### PR TITLE
Add kata-monitor tests in CI jobs

### LINKED ISSUE #4506: ci: run kata-monitor tests
We have added some basic tests to check kata-monitor functionality (PR #4461).
Wee need now to include them in the tests run by our CI jobs .

### PR DESCRIPTION
**Pull request by fgiudici**
Include kata-monitor testing in our CI jobs.
Namely: add to CI_JOBs "CRIO_K8S" and  "CRI_CONTAINERD|CRI_CONTAINERD_K8S".
Since the current kata-monitor tests are quite basic and quick (less than one minute) shouldn't affect the CI pipeline that much.
Fixes #4506

### CODE REVIEW

**Comment by fgiudici** [comment]
Commit breaks ARM-ubuntu CI job. Set "do not merge" label till not resolved.

**Review by Jakob-Naucke — APPROVED** [review]

**Review by cmaf — APPROVED** [review]
@fgiudici lgtm

**Pull request merged**
