### PR TITLE
backport 3.2 | tracing: ensure reproducible builds

### PR DESCRIPTION
**Pull request by alex-matei**
Fixes: #5756

Signed-off-by: Alexandru Matei <alexandru.matei@uipath.com>
(cherry picked from commit 0faaa56)

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @alex-matei!

**Comment by stevenhorsman** [comment]
Should this be targeted at `stable-3.2` rather than `main`, or have I misunderstood something?

**Review by stevenhorsman — APPROVED** [review]
LGTM now it's against stable-3.2. Thanks!

**Pull request merged**
