### PR TITLE
CI: Fix handling of sub-modules in static checks script

### LINKED ISSUE #136: Fix handling of submodules in static checks script
The `.ci/static-checks.sh` script currently ignores a repository if it contains sub-modules.

Now that the following PRs have landed in the runtime repo:

- https://github.com/kata-containers/runtime/pull/41
- https://github.com/kata-containers/runtime/pull/59

... the runtime repo is not purely comprised of submodules so the check script needs to be modified to ignore submodule packages, but check any remaining code.

### PR DESCRIPTION
**Pull request by jodh-intel**
Don't ignore a repository just because it contains sub-modules - filter
the packages those sub-modules provide out of the list of all packages
and run the static checks on the remaining packages.

This is specifically for the https://github.com/kata-containers/runtime
repo. It used to contain simply submodule references to other
repositories. However, now it contains actual code content (`cli/` and
`virtcontainers/`) but the original check script logic was ignoring
*all* packages below runtime. This is incorrect since (now) both the
`cli` and `virtcontainers` packages should be checked when a runtime PR
is raised.

Fixes #136.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Commit detail and description above updated for clarity.

**Comment by jodh-intel** [comment]
Blocked on #139.

**Comment by jodh-intel** [comment]
Blocked on #148.

**Comment by jodh-intel** [comment]
Build now passing so ready for review ;)

**Comment by chavafg** [comment]
lgtm

**Comment by GabyCT** [comment]
lgtm

**Pull request merged**
