### PR TITLE
CI: use virtio-blk device driver

### PR DESCRIPTION
**Pull request by chavafg**
Modify kata-runtime configuration to set:
block_device_driver = "virtio-blk"

Fixes: #107

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
Adding do-not-merge label as https://github.com/clearcontainers/runtime/pull/1044 needs to be merged and then we need to update the `runtime` version

**Comment by sboeuf** [comment]
This is temporary since we'll need scsi for reliable testing when we'll have moved to Qemu >= 2.9, but for now:
LGTM

**Comment by jodh-intel** [comment]
lgtm

**Comment by chavafg** [comment]
This can be merged now, but I see that using `virtio-scsi` is also working correctly. 
@sboeuf do you think we need this change?

**Comment by chavafg** [comment]
Talking with @sboeuf we need this change to test device passthrough

**Comment by GabyCT** [comment]
lgtm

**Pull request merged**
