### PR TITLE
2.x | webhook: Check whether Privileged is nil before accessing its value

### PR DESCRIPTION
**Pull request by fidencio**
Otherwise we'll just crash.

Fixes: #3111

Signed-off-by: Adel Zaalouk <azaalouk@redhat.com>
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Review by snir911 — APPROVED** [review]
lgtm

Thanks, tested and fixed the issue for me.

**Review by liubin — APPROVED** [review]

**Review by wainersm — APPROVED** [review]
Likewise for 2.x.

**Pull request merged**
