### PR TITLE
CI: Hide libcontainer logs from log-parser

### PR DESCRIPTION
**Pull request by jodh-intel**
Filter out libcontainer log messages (which get logged by the agent) as they trigger errors from the the log-parser that runs in the CI. The reason for the errors is that the log-parser expects all log entries to provide a standard set of fields, but libcontainer does not provide a way to pass a logger object into it, so it logs in its own format, which does not include mandatory fields like "pid".

See: https://github.com/kata-containers/tests/tree/master/cmd/log-parser#logfile-requirements

Fixes: #2470.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
You've missed the SoB on the whitepace commit :-)
We should also correlate this with #2467 , if you have not already - I'm presuming they don't clash?

**Comment by jodh-intel** [comment]
Updated. Well, the diffs look different to me, but presumably we want to land this PR before yours anyhow?

**Comment by grahamwhaley** [comment]
What I mean is that we check that this patch does not filter out the shimv2 containerd `kata` logs completely - I'll have a stare at the two to check.

**Comment by jodh-intel** [comment]
Oh ugh. Right. It's a shame the libcontainer API doesn't allow a logger to be passed in to avoid "polluting" our logs with "malformed" logs so we could avoid hacks like this.

**Comment by grahamwhaley** [comment]
Checked what the `kata` journal lines look like - afaict, they will not get filtered by this PR - they don't seem to container a `name=` field... they look like:

```
Apr 20 14:18:54 ubuntu1804-azure82cdc0 kata[79595]: time="2020-04-20T14:18:54.372435579Z" level=info msg="loaded configuration" ID=73227e3f9daf5b0faf17b6a1af72b657dfcd4b5e58afa112d9ea9d46be52e887 file=/etc/kata-containers/configuration.toml format=TOML source=katautils
```

You can see them in the `kata-shimv2*` artifacts attached to the Jenkins CI run of the other PR if you need etc.

**Comment by chavafg** [comment]
took a look at the log fragments and most of the job prints similar (few) entries as before. The one that printed a lot of log entries was initrd job, but with this PR it got reduced and now it looks similar to the other jobs, so I think the PR works. Anyway I'll let @jodh-intel or @grahamwhaley review before merging.

**Comment by grahamwhaley** [comment]
ack, that initrd log looks sane to me. You might need to ack @chavafg

**Comment by jodh-intel** [comment]
Yep. And in fact the errors being reported by the log parser now are real bugs. I'll raise PRs...

**Comment by jodh-intel** [comment]
Raised https://github.com/kata-containers/runtime/pull/2645 to fix one of the offenders and https://github.com/kata-containers/runtime/issues/2643 to highlight the need for a fix for the other one ;)

**Pull request merged**
