### PR TITLE
vendor: Update dep lock file for new format

### LINKED ISSUE #614: Update dep lock file format
The format of the `dep Gopkg.lock` file has changed, so do an NOP change to update it.

See also: https://github.com/kata-containers/runtime/issues/573

### PR DESCRIPTION
**Pull request by jodh-intel**
NOP update that simply updates the file format of the `dep` `Gopkg.lock`
file to the latest format.

Note: `dep ensure` run using `dep` at commit golang/dep@6b79ccc.

Fixes #614.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Those failures seem to be caused by `dep` removing `vendor/github.com/onsi/ginkgo/ginkgo`, even though `vendor/github.com/onsi/ginkgo` has been retained.

@devimc - any ideas?

**Comment by chavafg** [comment]
I see: 
`vendor/github.com/onsi/ginkgo/ginkgo/main.go` being removed. 

I remember I had this issue (https://github.com/kata-containers/tests/pull/27#issuecomment-359456302) when we added ginkgo to the vendor directory and then run `dep prune`. Needed to re-add the ginkgo files manually.

**Comment by amshinde** [comment]
@jodh-intel Wondering if including `github.com/onsi/ginkgo/ginkgo` alongwith `github.com/onsi/ginkgo` in our Gopkg.toml fixes this issue.

**Comment by jodh-intel** [comment]
Branch updated. This time I used the following approach to unbreak `dep`:

```
$ dep ensure
$ git checkout -f vendor/github.com/onsi/ginkgo/ginkgo
```

**Comment by jodh-intel** [comment]
Ping @chavafg, @devimc, @jcvenegas.

**Comment by jodh-intel** [comment]
krik1y! A k8s failure. Spinning the wheel again...

**Comment by grahamwhaley** [comment]
@jodh-intel do you still have details of the failure? if so, pls paste here, just in case that is the same as the one I saw earlier today - in which case maybe we have a repeating glitch to chase...

**Comment by jodh-intel** [comment]
@grahamwhaley - sorry, that was 2 weeks ago :) But the CI fell over in a very obvious way since as @chavafg said, `dep ensure` had simply deleted `vendor/github.com/onsi/ginkgo/ginkgo/main.go`.

What error are you seeing / referring to?

**Comment by chavafg** [comment]
I think @grahamwhaley was referring to the k8s failure on the CI:
```
not ok 2 Running within memory constraints
# (from function `waitForProcess' in file ../../.ci/lib.sh, line 164,
#  in test file k8s-memory.bats, line 47)
#   `waitForProcess "$wait_time" "$sleep_time" "$pod_status_cmd"' failed
# pod "memory-test" created
```

I already saw that it happened some times during the week. Opened #680 to investigate

**Comment by grahamwhaley** [comment]
yep, that one. thx @chavafg

**Comment by jodh-intel** [comment]
I'm getting pretty hacked off with this PR now :(

Restarting the 16.04 CI *again*....

**Pull request merged**
