### PR TITLE
CCv0: Merge main into CCv0 branch     

### PR DESCRIPTION
**Pull request by Megan-Wright**
Merge remote-tracking branch 'upstream/main' into CCv0
    
Fixes: #5538
Depends-on: github.com/kata-containers/kata-containers#6506
    
Signed-off-by: Megan Wright <megan.wright@ibm.com>

### CODE REVIEW

**Comment by Megan-Wright** [comment]
```
it diff --stat upstream/main -- . ':!*/vendor/*'
 .ci/ci_job_flags.sh                                                           |  63 ++++-
 .ci/configure_containerd_for_kata.sh                                          |   1 +
 .ci/install_cloud_hypervisor.sh                                               |  15 +-
 .ci/install_cni_plugins.sh                                                    |   2 +-
 .ci/install_kata.sh                                                           |  20 ++
 .ci/install_kata_image.sh                                                     |  44 +++-
 .ci/install_kata_kernel.sh                                                    |  37 ++-
 .ci/install_ovmf_sev.sh                                                       |  28 ++
 .ci/install_qemu.sh                                                           |  34 ++-
 .ci/install_runtime.sh                                                        |  77 ++++--
 .ci/install_td_shim.sh                                                        |  25 ++
 integration/confidential/fixtures/quay_verification/s390x/public.gpg          |  41 +++
 integration/confidential/fixtures/quay_verification/s390x/signatures.tar      | Bin 0 -> 1930 bytes
 integration/confidential/fixtures/quay_verification/x86_64/public.gpg         |  30 +++
 integration/confidential/fixtures/quay_verification/x86_64/signatures.tar     | Bin 0 -> 2157 bytes
 integration/confidential/fixtures/registries.d/quay.io.yaml                   |   4 +
 integration/confidential/lib.sh                                               | 357 +++++++++++++++++++++++++
 integration/containerd/confidential/agent_api.bats                            |  82 ++++++
 integration/containerd/confidential/agent_image.bats                          | 148 +++++++++++
 integration/containerd/confidential/asserts.sh                                |  77 ++++++
 integration/containerd/confidential/fixtures/agent-configuration-no-exec.toml |  46 ++++
 integration/containerd/confidential/fixtures/container-config.yaml            |  11 +
 .../containerd/confidential/fixtures/container-config_authenticated.yaml      |   9 +
 .../containerd/confidential/fixtures/container-config_cosigned-other.yaml     |  11 +
 integration/containerd/confidential/fixtures/container-config_cosigned.yaml   |  11 +
 .../confidential/fixtures/container-config_signed-protected-other.yaml        |  11 +
 .../containerd/confidential/fixtures/container-config_unsigned-protected.yaml |  11 +
 .../confidential/fixtures/container-config_unsigned-unprotected.yaml          |  11 +
 integration/containerd/confidential/fixtures/pod-config.yaml.in               |  12 +
 integration/containerd/confidential/lib.sh                                    | 163 ++++++++++++
 integration/containerd/confidential/run_tests.sh                              |  21 ++
 integration/containerd/confidential/tests_common.sh                           | 106 ++++++++
 integration/containerd/cri/integration-tests.sh                               |  12 +-
 integration/kubernetes/cleanup_bare_metal_env.sh                              |   0
 integration/kubernetes/confidential/agent_image.bats                          | 239 +++++++++++++++++
 integration/kubernetes/confidential/agent_image_encrypted.bats                |  79 ++++++
 integration/kubernetes/confidential/fixtures/pod-config.yaml.in               |  14 +
 integration/kubernetes/confidential/fixtures/service.yaml.in                  |  34 +++
 integration/kubernetes/confidential/lib.sh                                    | 125 +++++++++
 integration/kubernetes/confidential/sev.bats                                  | 510 ++++++++++++++++++++++++++++++++++++
 integration/kubernetes/e2e_conformance/setup.sh                               |   2 +-
 integration/kubernetes/tests_common.sh                                        |   0
 integration/nydus/nydus-sandbox.yaml                                          |   1 +
 integration/nydus/nydus_tests.sh                                              |   2 +
 lib/common.bash                                                               | 158 +++++++++++
 versions.yaml                                                                 |   7 +-
 67 files changed, 2844 insertions(+), 111 deletions(-)
```

**Comment by stevenhorsman** [comment]
Tests passing after I bumped the CC jobs to run on the 22.04 node, apart from the TDX known issue, so this can be merged.

**Pull request merged**
