### PR TITLE
stable-2.1: fix no build target issue in containerd installation

### PR DESCRIPTION
**Pull request by jongwu**
There is no "cri-cni-release" targe in makefile before containerd 1.5.0,
and change it to "release".

Fixes: #3830
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
seems that the environment is not clean
```
13:36:04 [init] Using Kubernetes version: v1.21.1
13:36:12 [preflight] Running pre-flight checks
13:36:12 error execution phase preflight: [preflight] Some fatal errors occurred:
13:36:12 	[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
```

**Comment by jongwu** [comment]
All green!
take a look at this @fidencio @GabyCT @lifupan

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jongwu!
/cc @snir911

**Review by snir911 — APPROVED** [review]
LGTM thanks!

**Pull request merged**
