### PR TITLE
[DNM] integration/docker: check devices cgroup

### LINKED ISSUE #665: integration/docker: add tests to check devices constraint
Apply and check devices cgroup

### PR DESCRIPTION
**Pull request by devimc**
Modify hotplug block devices test to check loop devices and check that these
loop devices are part of the devices cgroup.
    
Depends-on: github.com/kata-containers/runtime#657

fixes #665

### CODE REVIEW

**Comment by devimc** [comment]
oh my.... the number of the beast :metal:

**Comment by grahamwhaley** [comment]
😈

**Comment by devimc** [comment]
Depends-on: https://github.com/kata-containers/runtime/pull/657

**Comment by jodh-intel** [comment]
lgtm

:japanese_ogre:

**Pull request closed without merging**
