### PR TITLE
backport fixes for 1.10 for sles, centos, fedora and opensuse

### PR DESCRIPTION
**Pull request by GabyCT**
e878226 ci: Skip vsock_test for firecracker
70fd2df ci: Set kata-runtime as Docker runtime when using cloud-hypervisor
9529951 containerd-shimv2: do not run under opensuse 15
465f340 containerd: be able to build from source when version is a commit
c801eb1 integration/docker: pull fedora 30 image before using it
2e82e76 test: Update package manager test for Fedora
6ef2f29 tests: don't call to flag.Parse() from init()
51d7086 test:docker: Use the right hypervisor when reading from KataConfig
9077fdc functional: fix functional tests to support golang 1.13
b73b5b0 integration/docker: fix docker integration tests to support golang 1.13
be1d895 travis: specify go version with the latest v1.13.x
6d1f4e7 golangci-lint: fix `invalid pseudo-version` error
83f1a46 ci: Fix cloud hypervisor script
af866c6 ci: Add patch as a dependency
5cf802b ci: add libpmem as build dependency
9e2c50d ci: Add patch package
d1f77f4 debian: Install libbtrfs-dev package
ed55c8f ci: Enable repo for perl-IPC-Run
734f3cd ci: Add PREFIX variable
21b78e6 ci: Add FORCE_BUILD_QEMU variable
4b9ed65 ci: Fix SLES CI
102f9ba  ci: Do not install and run kubernetes on Fedora
6c92f02 ci: Enable ci for CentOS8
d6a895a ci: Remove smem package
38b9c25 ci: Remove alien package
376a6a6 ci: Update python for CentOS 8
c01f3ca ci: Enable priority for CentOS base repository
d69d58c ci: Enable PowerTools repository for CentOS 8
958b12e ci: Fix kubernetes installation for Fedora 31
ac63c13 ci: Update build tools package dependency for openSUSE Leap
afc16d9 ci: Update docker version for openSUSE and SLES
733f052 ci: Enable openSUSE Leap 15.1 CI
d77639f ci: Update setup script for SLES

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @GabyCT - I think this PR is blocked on the following:

- https://github.com/kata-containers/packaging/pull/1005
- https://github.com/kata-containers/packaging/pull/1016

We'll need those fixes backported into the 1.10 packaging branch before this PR will reliably build I think.

**Comment by GabyCT** [comment]
@chavafg so it seems something is missing with ginkgo
```
10:24:36 GOPATH=/tmp/jenkins/workspace/kata-containers-tests-debian-10-PR/go/src/github.com/kata-containers/tests/vendor go build ./vendor/github.com/onsi/ginkgo/ginkgo
10:24:39 unlink vendor/src
10:24:39 ./ginkgo -failFast -v -focus "" -skip "" \
10:24:39 	functional/ -- -runtime=kata-runtime -timeout=120
10:24:41 flag provided but not defined: -test.timeout
10:24:41 Usage of /tmp/ginkgo916301424/functional.test:
10:24:41   -ginkgo.debug
10:24:41     	If set, ginkgo will emit node output to files when running in parallel.
10:24:41   -ginkgo.dryRun
```

**Pull request merged**
