### PR TITLE
test: Fix stability test

### LINKED ISSUE #609: Docker stability test is failing
Currently we have issues in the CI mainly because the docker stability test is failing. I tried it to run it in an ubuntu machine by itself and is showing me the error that is been seen in our CI.

```
$ export ITERATIONS=2 && export MAX_CONTAINERS=20 && chronic ./soak_parallel_rm.sh
Checking Kata runtime kata-runtime
Start iteration 1 of 2
Running...
Checking 0 containers have all relevant components
Run kata-runtime: nginx:
f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad
Checking 1 containers have all relevant components
Wrong number of qemus running (1 != 0) - stopping
Showing system state:
 --Docker ps--
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS               NAMES
f35f28321624        nginx               "nginx -g 'daemon of…"   3 seconds ago       Up Less than a second   80/tcp              festive_allen
 --kata-runtime list--
ID                                                                 PID         STATUS      BUNDLE                                                                                                                               CREATED                          OWNER
f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad   7253        running     /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad   2018-08-14T20:07:27.998881292Z   #0
 --pgrep kata-proxy--
7207 /usr/libexec/kata-containers/kata-proxy -listen-socket unix:///run/vc/sbs/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/proxy.sock -mux-socket /run/vc/vm/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/kata.sock -sandbox f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad -log debug -agent-logs-socket /run/vc/vm/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/console.sock
 --pgrep kata-shim--
7253 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/proxy.sock -container f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad -exec-id f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad -terminal -log debug
 --pgrep kata-runtime--
 --pgrep qemu--
7193 /usr/local/bin/qemu-system-x86_64 -name sandbox-f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad -uuid 9550ee0c-4466-4c64-b06f-d3513314b4b1 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host,pmu=off -qmp unix:/run/vc/vm/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/qmp.sock,server,nowait -m 2048M,slots=2,maxmem=17065M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2 -device virtio-serial-pci,disable-modern=true,id=serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/usr/share/kata-containers/kata-containers-image_clearlinux_1.2.0_agent_fcfa054a757.img,size=536870912 -device virtio-scsi-pci,id=scsi0,disable-modern=true -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad/kata.sock,server,nowait -device virtio-9p-pci,disable-modern=true,fsdev=extra-9p-kataShared,mount_tag=kataShared -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/f35f28321624591140e5fd5b81276fb58417bbe068c0a6478a0f4bc6c27983ad,security_model=none -netdev tap,id=network-0,vhost=on,vhostfds=3:4:5:6:7:8:9:10,fds=11:12:13:14:15:16:17:18 -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:02,disable-modern=true,mq=on,vectors=18 -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -kernel /usr/share/kata-containers/vmlinuz-4.14.51.7-133.container -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug panic=1 nr_cpus=4 init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket agent.log=debug -smp 1,cores=1,threads=1,sockets=1,maxcpus=4
 --pgrep ksm-throttler--
ERROR: Got 1 errors, quitting
```

### PR DESCRIPTION
**Pull request by GabyCT**
Instead of looking for qemu-lite-system look for qemu-system.

Fixes #609

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
lgtm.

**Comment by jcvenegas** [comment]
I think we were using qemu-lite in the CI. @chavafg  @jodh-intel

**Comment by amshinde** [comment]
@GabyCT This looks like our CI has started using qemu-system instead of qemu-lite. I think we need to fix that, instead of introducing this change.

**Comment by jcvenegas** [comment]
Yes, just to confirm qemu-lite is being installed in the CI. So the fix need to be different

**Comment by jcvenegas** [comment]
```
	destination install path (DESTDIR)    : /
	binary installation path (BINDIR)     : /usr/local/bin
	binaries to install                   :
	 - /usr/local/bin/kata-runtime
	 - /usr/local/bin/data/kata-collect-data.sh
	config to install (CONFIG)            : cli/config/configuration.toml
	install path (CONFIG_PATH)            : /usr/share/defaults/kata-containers/configuration.toml
	alternate config path (SYSCONFIG)     : /etc/kata-containers/configuration.toml
	hypervisor path (QEMUPATH)            : /usr/bin/qemu-lite-system-x86_64
	assets path (PKGDATADIR)              : /usr/share/kata-containers
	proxy+shim path (PKGLIBEXECDIR)       : /usr/libexec/kata-containers
```

**Comment by amshinde** [comment]
It looks like we are always installing qemu from source instead of the packages for some reason now:
https://github.com/kata-containers/tests/blob/master/.ci/install_qemu.sh#L99

With this, I see we then do this linking:
```
sudo ln -sf $(command -v qemu-system-${QEMU_ARCH}) "/usr/bin/qemu-lite-system-${QEMU_ARCH}"
```
However the soak test is checking for qemu-lite-system-x86_64 always with pgrep. Obviously pgrep  output would not contain  qemu-lite-system-x86_64. 

We need to figure out why we are not installing from the packages first. (I'll raise a test PR to check some of the env variables)

But depending on whether we are installing from source/packages, the soak test needs to check for the correct qemu binary name.
@GabyCT @grahamwhaley Can you take a look at this?
I also think we need to include ${QEMU_ARCH} in the qemu binary check so that this will work for all architectures in the future.

**Comment by amshinde** [comment]
Raised this : https://github.com/kata-containers/runtime/issues/582

**Comment by grahamwhaley** [comment]
Thanks for the quick workaround.
I think the correct fix is to use the `HYPERVISOR_PATH` var that has been extracted from the `kata-env` over in https://github.com/kata-containers/tests/blob/master/metrics/lib/common.bash#L34 - that is the right thing to do - ask the runtime itself which QEMU it will be using, and then check for that. That is also pretty true for the shim and proxy, although their names change less ;-)

@GabyCT - if you could do that, that would be great. You might need to check that `pgrep` is happy with the full path, or you may need to do some bash `%%` type path magic to just use the filename. iirc, `pkill` I think it was had some different semantics depending on if you used a full path or not - hopefully `pgrep` is fine with it.

It's interesting that the test sort of picked up an 'anomoly' - that we'd switched how we built/installed qemu, and we seem not to have been fully aware.
@jcvenegas @chavafg @jcvenegas I also want to ask - if that qemu build change could get in without triggering this CI failure - then should we think about if we can improve how we check changes to the CI or build infra itself - as @jodh-intel would say (except my Latin is, well, non-existent) .... 'Who checks the checkers?'.

One final note - with the introduction of `vsock`, we no longer have the proxy, so I would also expect this test to fail - and need modifying to spot when we have vsock and if we should check for the proxy count or not. @GabyCT , if you are in the code, you might want to consider adding that ability as well to the test?

**Pull request closed without merging**
