### PR TITLE
ci: add exec bit for s390x scripts

### PR DESCRIPTION
**Pull request by tuan-hoang1**
Fix https://github.com/kata-containers/tests/issues/1169

Signed-off-by: Tuan Hoang <tmhoang@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
/test

Jenkins was complaining there was no Fixes, but I think you have already fixed that, so I've re-nudged one of the jenkins jobs as well - let's keep an eye on that.

**Comment by grahamwhaley** [comment]
That is most odd - jenkins still complaining about the 'fixes' - let me check into that a little...
(I'm wondering if we mandate a `:`, but I don't think we do..)

**Comment by tuan-hoang1** [comment]
Yep I must have missed the : https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md. Reading now ...

**Comment by grahamwhaley** [comment]
Yeah, I think we need `Fixes` with a capital. Code that does the check is over at https://github.com/kata-containers/tests/blob/master/cmd/checkcommits/checkcommits.go#L56 if you are really curious ;-)
Yeah, we only handle a very small specific subset of the github phrases: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by chavafg** [comment]
I think we dont need to run the whole jenkins jobs for this, should we merge?

**Comment by grahamwhaley** [comment]
wfm - go ahead @chavafg :-)

**Pull request merged**
