### PR TITLE
Backports - stable-1.10 

### PR DESCRIPTION
**Pull request by chavafg**
Backports from master:

- integration: fix cpuset test
- integration: remove, update cpuset tests
- ci: compress virtiofsd logs
- ci: Fix docker installation centos 8
- ci: Fix docker installation for rhel 8
- .ci/setup_env_centos.sh: Ensure yum-config-manager is installed
- .ci/setup_env_centos.sh: Install bc package
- .ci/setup_env_centos.sh: Install packaged GNU Parallel

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, considering happy tests!

**Comment by fidencio** [comment]
Thanks @chavafg and @jcvenegas!

**Review by GabyCT — APPROVED** [review]

**Comment by jcvenegas** [comment]
some CI errors, restarting

sles:

```
14:37:29 [3] • Failure [5.442 seconds]
14:37:29 [3] Update CPU constraints
14:37:29 [3] /tmp/jenkins/workspace/kata-containers-tests-opensuse-15-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:392
14:37:29 [3]   Update CPU set
14:37:29 [3]   /tmp/jenkins/workspace/kata-containers-tests-opensuse-15-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
14:37:29 [3]     cpuset should be equal to 0 [It]
14:37:29 [3]     /tmp/jenkins/workspace/kata-containers-tests-opensuse-15-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
14:37:29 [3] 
14:37:29 [3]     Expected
14:37:29 [3]         <string>: 0
14:37:29 [3]     to equal
14:37:29 [3]         <string>: 0-3
14:37:29 [3] 
14:37:29 [3]     /tmp/jenkins/workspace/kata-containers-tests-opensuse-15-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:463
14:37:29 [3] ------------------------------
14:37:29 [3] SSSSSSSSSSSSSSSSSSSSSSS
14:37:29 [3] 
14:37:29 [3] Summarizing 1 Failure:
14:37:29 [3] 
14:37:29 [3] [Fail] Update CPU constraints Update CPU set [It] cpuset should be equal to 0 
14:37:29 [3] /tmp/jenkins/workspace/kata-containers-tests-opensuse-15-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:463
14:37:29 [3] 
14:37:29 [3] Ran 53 of 81 Specs in 330.791 seconds
14:37:29 [3] FAIL! -- 52 Passed | 1 Failed | 0 Pending | 28 Skipped
```
centos
```
14:30:03 1..2
14:30:26 not ok 1 Disable_new_netns equal to false
14:30:26 # (in test file integration/network/disable_net/net_none.bats, line 36)
14:30:26 #   `docker run -d --runtime=${RUNTIME} --name=${NAME} --net=none ${IMAGE} ${PAYLOAD}' failed with status 125
14:30:26 # 
14:30:26 # 8b2bc3e84c72c79184eac7302a168b8b9fc20ef388a98a3c7d7e1ffeb5fee58d
14:30:26 # docker: Error response from daemon: OCI runtime create failed: Failed to check if grpc server is working: rpc error: code = Unavailable desc = transport is closing: unknown.
14:30:26 # 
14:30:27 not ok 2 Disable net
14:30:27 # (in test file integration/network/disable_net/net_none.bats, line 69)
14:30:27 #   `docker run -d --runtime=${RUNTIME} --name=${NAME} --net=none ${IMAGE} ${PAYLOAD}' failed with status 125
14:30:27 # 
14:30:27 # docker: Error response from daemon: Conflict. The container name "/test" is already in use by container "8b2bc3e84c72c79184eac7302a168b8b9fc20ef388a98a3c7d7e1ffeb5fee58d". You have to remove (or rename) that container to be able to reuse that name.
14:30:27 # See 'docker run --help'.
```

**Review by jodh-intel — APPROVED** [review]

**Comment by GabyCT** [comment]
@chavafg can we close this issue?

**Comment by chavafg** [comment]
yeah, lets close this.

**Pull request closed without merging**
