### PR TITLE
backport patches to stable-2.0.0

### PR DESCRIPTION
**Pull request by chavafg**
34d2451  ci: Fix git error in crio installation
b6f661c ci: vfio: unskip cloud-hypervisor tests
ac081af ci: vfio: workaround virtiofs bug
d36f238 ci: Fix cri-o drop-in configuration file
f9e5884 ci: Remove duplication of kubernetes installation
6d5349b ci: ignore files within kernel/configs directory
b98f027 vfio: skip cloud-hypervisor
7326a45 ci: vfio: fix VFIO CI
066c6cd CI: ignore license header check for drawio files
e697148 CI: Don't license check kernel config files
5438de0 ci: update the way we get crio version
62a4242 ci: Update network namespace flag for CRIO install
3af1284 versions: update Sonobuoy version to match k8s version
805fcf6 ci: Try to skip CI only on PR jobs
4e97850 CI: Really enable fast return for 2.0-dev
8e57555 k8s: enable memroy tests
f9b1601 k8s: skip k8s-block-volume on aarch64
5b53060 k8s: skip oom test for aarch64
6c5a296 ci: add VFIO CI for kata 2.0
00437e0 spellcheck: Add "musl" to dictionary
22f7c88 versions: Update flannel version to v0.13.0-rc2
1af123c ci: change qemu patch path for qemu build on arm64
e095ccd ci: skip k8s-oom test on arm64.

### CODE REVIEW

**Comment by chavafg** [comment]
@devimc any idea of why this commit https://github.com/kata-containers/tests/commit/28147bbb2874cedb66819c866f270ebd72393526 says that is authored by @katacontainersbot ?
Now SoB check is failing because it expects the bot's email... lol. 

@jodh-intel any idea of how we can overpass this issue?

**Review by jodh-intel — APPROVED** [review]
Thanks @chavafg.

lgtm, but the branch is now conflicted so may be a PR or two missing.

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Comment by fidencio** [comment]
@chavafg, sorry, but my previous message was incorrect.  During the migration process we can't simply rename a branch that's not the default one and we decided to simply delete the `stable-2.0.0` in favour of creating a new `stable-2.0`.

I'd need to ask you to re-open your PR against the newly created `stable-2.0` branch.

Sorry for the inconvenience.

**Pull request closed without merging**
