### PR TITLE
# Kata Containers 2.4.0-rc0

### PR DESCRIPTION
**Pull request by egernst**
- metrics: Remove network common script
- ci: Fixed: convert nodename to lower case to match kubectl
- ci: Remove some jenkins_job_build.sh cruft
- docs: fix vm setup instructions
- metrics: Update lower limit for boot time
- Add kata-monitor tests in CI jobs
- tests: unify runtime type to io.containerd.kata.v2
- tess: enable TestContainerMemoryUpdate test
- ci: Remove unused metrics experimental flag
- nydus: install nydus-snapshotter from tarball
- integration/containerd: Remove Kata config
- golangci-ling: disable unconverted until it can support -- all flag
- ci: Update lib script to use clean env for ctr
- static-checks: Exclude Dockerfile.template
- metrics: Use clean env for ctr for blogbench metrics
- ci: fix Iperf bench
- metrics: Update boot time for qemu
- metrics: Update blogbench limits for qemu
- k8s: check $number_cpus before using it
- ci: Set qemu_repo after QEMU_REPO_URL
- tests: add test for nydus with clh
- metrics: Remove unused code for run metrics script
- ci: ci_cache_components: fix cloud-hypervisor support
- clh: Use kata-containers' static build script
- ci: add basic tests for kata-monitor
- ci: add k8s uninstallation to metrics tests
- ci/static-checks: Treat Dockerfile.template
- ci: install_qemu: improve script
- tests: temporarily disable hugepage sandbox cgroup only case
- stability: Kill _all_ containers
- tests: Remove conformance tests
- test: cri: enable containerd debug logs
- integration/containerd: Do not override config
- k8s: enable case for hugepages
- ci: make it possible to use multiple test files
- improve install_kata_kernel.sh script
- ci: install podman-docker when using podman
- metrics: Remove unused network metrics
- Add test for translation of PCIDEVICE_ environment variables
- tests: remove RUST_AGENTs variable
- tests: add case for nydus
- ci: -Wl,--s390-pgste for s390x
- ci: Add ignore_depends_on label
- ci: Rename checkmetrics tomls for metrics CI
- tests: Remove ctr runtime duplicate definition

7dc18294 metrics: Remove network common script
f0665283 ci: Fixed: convert nodename to lower case to match kubectl
15456e60 metrics: Update lower limit for boot time
93d0d4a7 kata-monitor: skip test on BAREMETAL CI jobs
fff7eb71 tests: unify runtime type to io.containerd.kata.v2
bc1ed142 ci: Remove unused metrics experimental flag
ecc6450e tess: enable TestContainerMemoryUpdate test
5d13c52b docs: fix vm setup instructions
1f3b2c69 unconvert: disable unconvert static check
d971367a ci: Update lib script to use clean env for ctr
175c6fee integration/containerd: Remove Kata config
cc14f38c metrics: Use clean env for ctr for blogbench metrics
ee572656 kata-monitor: add CRICTL_RUNTIME
37d89f28 kata-monitor: enable automatic testing on CRI_CONTAINERD and CRIO_K8S
ba8b22aa kata-monitor: allow to start the test via make
56790d13 kata-monitor: fix cases in which vars can be unset
24687a8a static-checks: Exclude Dockerfile.template
05224686 ci: fix Iperf bench
e54398b3 metrics: Update boot time for qemu
1c91dfef metrics: Update blogbench limits for qemu
9aa752c9 metrics: Remove unused code for run metrics script
a70c9e8f ci: ci_cache_components: fix cloud-hypervisor support
de2b4b58 ci: Set qemu_repo after QEMU_REPO_URL
e05447a9 clh: Use kata-containers's static build script
3b0547f4 vfio: Enforce docker usage inside the Fedora VM
f46c3700 ci: Enable Iperf bench
fca617cf ci: add basic tests for kata-monitor
07c4cff1 nydus: install nydus-snapshotter from tarball
88d993fd tests: add test for nydus with clh
46bdb8c2 ci: install_qemu: improve script
30d9b8a5 tests: temporarily disable hugepage sandbox cgroup case
473745b3 ci: Remove some jenkins_job_build.sh cruft
aad5e846 tests: Remove conformance tests
2ea4dc3a ci/static-checks: Treat Dockerfile.template
55119100 ci: install_kata_kernel: check arguments are not empty
f24489b2 ci: install_kata_kernel: add workaround for fedora 35
319a050c ci: install_kata_kernel: add support for tdx kernel type
072bb539 ci: install_kata_kernel: add support for experimental kernel type
37c91413 ci: error handling and bugfix
b001aaba ci: install podman-docker when using podman
53331c1f ci: install_kata_kernel: add cmdline options
0d372e44 ci: install_kata_kernel: fix build kernel when release is different
168ef97f ci: install_kata_kernel: improve script
01ff3973 metrics: Remove unused network metrics
19f7a952 integration/containerd: Do not override config
ac4acd1d stability: Fix counter scope
ee671796 stability: Kill _all_ containers
62c863f3 ci: Log default cri-o version used for skipping tests.
38de71ec ci: separate skipped tests for each bats file
493dbc3c tests: remove RUST_AGENTs variable
cbf40f14 tests: add case for nydus
d6ba7ce1 vfio: Verify translation of PCIDEVICE_* environment variables
d728078d vfio: Add check on size of IOMMU group
ebdd6a80 vfio: Rename get_eth_addr function
81dbf51d ci: Rename checkmetrics tomls for metrics CI
2133de5a ci: make it possible to use multiple test files
9ee2ddcc tests: Remove ctr runtime duplicate definition
138c61b8 ci: Rename kata_repo variables
31ae832f ci: Add ignore_depends_on label
d22bad8b ci: -Wl,--s390-pgste for s390x
7c533776 k8s: enable case for hugepages
7a12ce6d debug: Skip tests for PR debug
c51bc51a cri: set -x on DEBUG=!""
75014cf2 test: cri: enable containerd debug logs
24413b67 k8s: check $number_cpus before using it

### CODE REVIEW

**Review by fidencio — DISMISSED** [review]
lgtm, thanks @egernst!

**Review by Jakob-Naucke — COMMENTED** [review]
I'd love #4548 to be in, but maybe it doesn't _really_ matter for the tests until we actually cut. @egernst tell me what you think.

**Review by GabyCT — APPROVED** [review]

**Review by cmaf — APPROVED** [review]

**Review by fengwang666 — APPROVED** [review]

**Pull request merged**
