### PR TITLE
ci: Remove installation from OBS

### LINKED ISSUE #1790: Remove installation from OBS
We are not longer using the installation from the OBS repository, we need to remove it from the ci

### PR DESCRIPTION
**Pull request by GabyCT**
We are not longer using the installation from the OBS repository,
this will remove the unnecesary steps.

Fixes #1790

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
As we presumably now either pull items from the CI fragment cache if we can, or build from source if we cannot?
Does this lose us anything, like implicitly testing of OBS images?

**Comment by chavafg** [comment]
I think this is fine, we are no longer installing kata assets using the package manager, so doesn't make sense to install the obs repos.

**Pull request merged**
