### PR TITLE
cri-o: Stop using devicemapper with CRI-O

### PR DESCRIPTION
**Pull request by fidencio**
CRI-O tests have been constantly failing on 1.x, and it seems to be due
to using devicemapper as the storage driver.

Fixes: #3330

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
(cherry picked from commit cde3c0c590351f38d50d1d563126c92887be808b)

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by wainersm — APPROVED** [review]
LGTM

**Comment by GabyCT** [comment]
Centos CI is failing with
```
11:09:47 make: *** [Makefile:166: bin/crio] Error 2
11:10:35 Failed at 86: make BUILDTAGS='exclude_graphdriver_devicemapper libdm_no_deferred_remove'
```

**Pull request merged**
