### PR TITLE
metrics: Add cassandra k8s + tdx

### LINKED ISSUE #4730: add cassandra k8s + tdx test

### PR DESCRIPTION
**Pull request by GabyCT**
This PR adds the cassandra benchmark with tdx configuration.

Fixes #4730

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Review by devimc — APPROVED** [review]

**Pull request merged**
