### PR TITLE
CI: Create GHA to add PR sizing label

### PR DESCRIPTION
**Pull request by jodh-intel**
Created a new GitHub Action workflow file that adds a sizing label to
each PR.

Fixes: #4550.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
dnm - blocked on https://github.com/kata-containers/.github/pull/42.

**Review by liubin — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jodh-intel!

**Pull request merged**
