### PR TITLE
arch: Remove s390x-options.mk

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
obsolete and define a removed config

Fixes: #3863
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

also using this for general s390x CI tests (https://github.com/kata-containers/kata-containers/issues/2465)

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @Jakob-Naucke

**Comment by Jakob-Naucke** [comment]
Seems that went well -- /test all the things

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
