### PR TITLE
integration/openshift: Update test cases for 4.6

### LINKED ISSUE #3062: ci/openshift-ci: Use OpenShift 4.6
The OpenShift 4.6 is the latest GA version: https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-release-notes

The Kata Containers daily job on Openshift CI is still using 4.5 however. Likewise the e2e integration tests wrapper scripts (https://github.com/kata-containers/tests/tree/master/integration/openshift/e2e).

Let's bump to 4.6. Needs to:
1. Update github.com/kata-containers/runtime/versions.yaml
2. Re-generate the list of test cases (github.com/kata-containers/tests/tree/master/integration/openshift/e2e)

### PR DESCRIPTION
**Pull request by wainersm**
Re-generate the list of tests cases for the openshift-tests
4.6.

Depends-on: github.com/kata-containers/runtime#3081

Fixes #3062

Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

### CODE REVIEW

**Comment by wainersm** [comment]
@chavafg @fidencio  Mind to review this?

Not much to review actually...I only re-generated the list of tests by using openshift-tests 4.6.

**Review by chavafg — APPROVED** [review]
Thanks @wainersm

**Comment by wainersm** [comment]
@cpmeadors Mind to review it?

**Review by cpmeadors — APPROVED** [review]
Changes look good.

**Review by c3d — APPROVED** [review]
Looks good to me.

**Pull request merged**
