### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by Megan-Wright**
Merge remote-tracking branch 'upstream/main' into CCv0
    
Fixes: #5514
Depends-on: github.com/kata-containers/kata-containers#6440
    
Signed-off-by: Megan Wright <megan.wright@ibm.com>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Comment by wainersm** [comment]
@stevenhorsman I suspect the trigger for the job has an extra space on the begin now. Let's see:
 /test

**Comment by stevenhorsman** [comment]
> @stevenhorsman I suspect the trigger for the job has an extra space on the begin now. Let's see: /test

The trigger in the config: http://jenkins.katacontainers.io/view/CCv0/job/kata-containers-CCv0-ubuntu-20.04-x86_64-CC_CRI_CONTAINERD-PR/configure looks okay to me, but I might have glossed over something like that

**Comment by wainersm** [comment]
Merged a fix https://github.com/kata-containers/ci/pull/536

Let's see if it works

/test

**Review by wainersm — APPROVED** [review]

**Comment by stevenhorsman** [comment]
The next SEV run hit the same problem:
```
Update apt repositories
16:51:58 
16:51:58 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
16:51:58 
16:51:58 Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
16:51:58 Hit:3 http://us.archive.ubuntu.com/ubuntu focal InRelease
16:51:58 Get:4 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
16:51:58 Ign:2 https://packages.cloud.google.com/apt kubernetes-xenial-unstable InRelease
16:51:58 Err:5 https://packages.cloud.google.com/apt kubernetes-xenial-unstable Release
16:51:58   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 142.251.32.46 443]
```
/test-sev

**Comment by stevenhorsman** [comment]
Another SEV failure, but different this time:
```
17:38:50 INFO: build static CC virtiofsd
17:38:51 Error response from daemon: Get "https://quay.io/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
17:39:24 #1 [internal] load .dockerignore
17:39:24 #1 transferring context: 2B done
17:39:24 #1 DONE 0.0s
17:39:24 
17:39:24 #2 [internal] load build definition from Dockerfile
17:39:24 #2 transferring dockerfile: 463B done
17:39:24 #2 DONE 0.0s
17:39:24 
17:39:24 #3 [internal] load metadata for docker.io/library/alpine:3.16.2
17:39:24 #3 ERROR: failed to do request: Head "https://registry-1.docker.io/v2/library/alpine/manifests/3.16.2": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution
17:39:27 ------
17:39:27  > [internal] load metadata for docker.io/library/alpine:3.16.2:
17:39:27 ------
17:39:27 Dockerfile:5
17:39:27 --------------------
17:39:27    3 |     # SPDX-License-Identifier: Apache-2.0
17:39:27    4 |     
17:39:27    5 | >>> FROM alpine:3.16.2
17:39:27    6 |     ARG RUST_TOOLCHAIN
17:39:27    7 |     
17:39:27 --------------------
17:39:27 ERROR: failed to solve: alpine:3.16.2: failed to do request: Head "https://registry-1.docker.io/v2/library/alpine/manifests/3.16.2": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution
```
Re-running for the last time!

**Comment by stevenhorsman** [comment]
sev failed again - back to:
```
18:11:17 Ign:3 https://packages.cloud.google.com/apt kubernetes-xenial-unstable InRelease
18:11:17 Err:7 https://packages.cloud.google.com/apt kubernetes-xenial-unstable Release
18:11:17   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 142.250.188.14 443]
18:11:18 Reading package lists...
```
@UnmeshDeodhar @ryansavino - can you confirm that this is an existing error, so we can proceed with this PR?

**Comment by stevenhorsman** [comment]
@fidencio @arronwy - Can you check if the TDX failures are just network related issues and let us know if they should block this PR. Thanks!

**Comment by fidencio** [comment]
Cloud Hypervisor TDX:
```
20:03:18 /home/jenkins/workspace/tests-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/go/src/github.com/kata-containers/kata-containers/tools/packaging/static-build/kernel/build.sh: line 19: BUILDER_REGISTRY: unbound variable
```

If this was solved already, I can just rerun the job.

**Comment by fidencio** [comment]
QEMU job failed due to something wrong with the libseccomp repo.  let me rerun both,

**Comment by UnmeshDeodhar** [comment]
@stevenhorsman sev test is passing now.

**Comment by fidencio** [comment]
We're hitting a legit error on QEMU TDX with those changes, but we, as Intel, do not want to block the development upstream.

With this said, I've discussed with @arronwy and we agreed on having the rebase merged as soon as possible and we'll take the bullet to fix this on our side sooner than later.

**Pull request merged**
