### PR TITLE
ci: Enable podman cloud hypervisor CI

### LINKED ISSUE #2547: clh: enable Podman CI tesing
**Which feature do you think can be improved?**

Podman CI has to enable to improve integration parity with qemu.

### PR DESCRIPTION
**Pull request by GabyCT**
This PR enables the posiblity to run a podman cloud hypervisor CI.

Fixes #2547

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@jcvenegas yes, I already made the changes thanks

**Comment by jcvenegas** [comment]
@gaby one more request could you change the regex to trigger from `/test-podmanclh` to `/test-clh-podman`. And allow the regex detect:
`/test`
`/test-clh`
`/test-clh-podman`

**Comment by jodh-intel** [comment]
... and update https://github.com/kata-containers/community/wiki/Controlling-the-CI when you do :smile:

**Comment by GabyCT** [comment]
@jcvenegas and @jodh-intel sure i will do that :)

**Pull request merged**
