### PR TITLE
nydus: upgrade nydus version

### PR DESCRIPTION
**Pull request by liubin**
Enable all debug flags to show more log for nydus test

Fixes: #4947

Signed-off-by: liubin <liubin0329@gmail.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@liubin I will triggered ubuntu 22 CI as the failure of nydus was present there

**Review by GabyCT — APPROVED** [review]

**Comment by liubin** [comment]
> @liubin I will need to triggered ubuntu 22 CI as the failure of nydus was present there, however, the cgroupsv2 support has not been merged, so should we merge this and test later?

I'd prefer to merge this first, and then fix the group v2 issue.

**Review by Tim-Zhang — APPROVED** [review]

**Pull request merged**
