### PR TITLE
work with containerd 1.6.x

### PR DESCRIPTION
**Pull request by wllenyj**
- fix: Shell syntax error. 
- fix: support containerd 1.6.x

Depends-on: https://github.com/kata-containers/kata-containers/pull/2733

Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
@sameo DYT we should use root here? https://github.com/kata-containers/tests/blob/b7529c42d7227be25c9d488e968555c38cf0e01f/.ci/install_cri_containerd.sh#L46

**Comment by wllenyj** [comment]
> @sameo DYT we should use root here?
> 
> https://github.com/kata-containers/tests/blob/b7529c42d7227be25c9d488e968555c38cf0e01f/.ci/install_cri_containerd.sh#L46

@Jakob-Naucke Why don't the ci on 2377 have this problem. 
I'll try changing it.

**Comment by Jakob-Naucke** [comment]
@wllenyj I don't know :/ /test

**Comment by Jakob-Naucke** [comment]
@wllenyj exactly. /test

**Comment by Jakob-Naucke** [comment]
Success on Ubuntu & Firecracker! @snir911 how much storage are we provisioning these Fedora instances with?

**Review by sameo — APPROVED** [review]

**Review by Jakob-Naucke — APPROVED** [review]

**Pull request merged**
