### PR TITLE
Vagrantfile: add support to Centos Stream 8

### PR DESCRIPTION
**Pull request by snir911**
This allows to set a local Centos Stream 8 vm and run the
CI jobs within it.

Fixes: #4577
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>

### CODE REVIEW

**Comment by wainersm** [comment]
@snir911 thanks! let me test it locally.

**Comment by wainersm** [comment]
Hi @snir911 ,

> @snir911 thanks! let me test it locally.

The setup phase (`export CI_JOB=CRIO_K8S & vagrant up vagrant up centos8stream`) apparently worked out. However the very first k8s test fails (I ran twice to be sure):

```
[vagrant@localhost tests]$ .ci/run.sh 
INFO: Running kubernetes tests
bash -f .ci/install_bats.sh
/bin/bats
bash -f integration/kubernetes/run_kubernetes_tests.sh
/home/vagrant/go/src/github.com/kata-containers/tests/integration/kubernetes /home/vagrant/go/src/github.com/kata-containers/tests
INFO: Initialize the test environment
[init.sh:300] INFO: Check there aren't dangling processes from previous tests
[init.sh:78] INFO: Build custom stress image
/home/vagrant/go/src/github.com/kata-containers/tests/integration/kubernetes/runtimeclass_workloads/stress /home/vagrant/go/src/github.com/kata-containers/tests/integration/kubernetes
STEP 1/2: FROM quay.io/libpod/ubuntu:latest
STEP 2/2: RUN apt-get -y update &&     apt-get -y upgrade &&     apt-get -y --no-install-recommends install stress &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
--> Using cache 4e86b0b4869071d93fd4d9365ec9567cc0f4077c793a89cb11a0e728edc1fc2e
COMMIT localhost/stress-kata:latest
--> 4e86b0b4869
Successfully tagged localhost/stress-kata:latest
4e86b0b4869071d93fd4d9365ec9567cc0f4077c793a89cb11a0e728edc1fc2e
/home/vagrant/go/src/github.com/kata-containers/tests/integration/kubernetes
[init.sh:306] INFO: Clean up any leftover CNI configuration
Device "cni0" does not exist.
[init.sh:309] INFO: Start crio service
● crio.service - Container Runtime Interface for OCI (CRI-O)
   Loaded: loaded (/usr/local/lib/systemd/system/crio.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-03-14 17:46:03 UTC; 5s ago
     Docs: https://github.com/cri-o/cri-o
 Main PID: 15003 (crio)
    Tasks: 10
   Memory: 13.1M
   CGroup: /system.slice/crio.service
           └─15003 /usr/local/bin/crio

Mar 14 17:46:03 localhost.localdomain crio[15003]: time="2022-03-14 17:46:03.552446082Z" level=info msg="No blockio config file…o.go:37"
Mar 14 17:46:03 localhost.localdomain crio[15003]: time="2022-03-14 17:46:03.552459433Z" level=info msg="RDT not available in t…t.go:57"
Mar 14 17:46:03 localhost.localdomain crio[15003]: time="2022-03-14 17:46:03.552530525Z" level=info msg="Updated default CNI ne….go:371"
Mar 14 17:46:03 localhost.localdomain crio[15003]: time="2022-03-14 17:46:03.552793547Z" level=debug msg="reading hooks from /u…d.go:65"
Mar 14 17:46:03 localhost.localdomain crio[15003]: time="2022-03-14 17:46:03.558436778Z" level=debug msg="Golang's threads limi….go:349"
Mar 14 17:46:03 localhost.localdomain crio[15003]: time="2022-03-14 17:46:03.558732482Z" level=debug msg="Sandboxes: []" file="….go:499"
Mar 14 17:46:03 localhost.localdomain crio[15003]: time="2022-03-14 17:46:03.558844529Z" level=debug msg="Registered SIGHUP wat…d.go:32"
Mar 14 17:46:03 localhost.localdomain crio[15003]: time="2022-03-14 17:46:03.558873020Z" level=debug msg="Metrics are disabled"….go:510"
Mar 14 17:46:03 localhost.localdomain crio[15003]: time="2022-03-14 17:46:03.577576418Z" level=debug msg="monitoring \"/usr/sha…r.go:43"
Mar 14 17:46:03 localhost.localdomain systemd[1]: Started Container Runtime Interface for OCI (CRI-O).
Hint: Some lines were ellipsized, use -l to show in full.
[init.sh:312] INFO: Start Kubernetes
[init.sh:202] INFO: Init cluster using /var/run/crio/crio.sock
[init] Using Kubernetes version: v1.23.1
[preflight] Running pre-flight checks
	[WARNING FileExisting-tc]: tc not found in system path
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local localhost.localdomain] and IPs [10.96.0.1 192.168.122.185]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [localhost localhost.localdomain] and IPs [192.168.122.185 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [localhost localhost.localdomain] and IPs [192.168.122.185 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[apiclient] All control plane components are healthy after 10.504473 seconds
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config-1.23" in namespace kube-system with the configuration for the kubelets in the cluster
NOTE: The "kubelet-config-1.23" naming of the kubelet ConfigMap is deprecated. Once the UnversionedKubeletConfigMap feature gate graduates to Beta the default name will become just "kubelet-config". Kubeadm upgrade will handle this transition transparently.
[upload-certs] Skipping phase. Please see --upload-certs
[mark-control-plane] Marking the node localhost.localdomain as control-plane by adding the labels: [node-role.kubernetes.io/master(deprecated) node-role.kubernetes.io/control-plane node.kubernetes.io/exclude-from-external-load-balancers]
[mark-control-plane] Marking the node localhost.localdomain as control-plane by adding the taints [node-role.kubernetes.io/master:NoSchedule]
[bootstrap-token] Using token: 2ko7ue.i1xvv4482ev1hoqp
[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
[bootstrap-token] configured RBAC rules to allow Node Bootstrap tokens to get nodes
[bootstrap-token] configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[kubelet-finalize] Updating "/etc/kubernetes/kubelet.conf" to point to a rotatable kubelet client certificate and key
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

Alternatively, if you are the root user, you can run:

  export KUBECONFIG=/etc/kubernetes/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join 192.168.122.185:6443 --token 2ko7ue.i1xvv4482ev1hoqp \
	--discovery-token-ca-cert-hash sha256:31671f853d22a3c18d47802b48922cf62559fd552487a76dbc55b9d4378aa9b9 
[init.sh:230] INFO: Probing kubelet (timeout=240s)
NAME                    STATUS     ROLES                  AGE   VERSION
localhost.localdomain   NotReady   control-plane,master   4s    v1.23.1
[init.sh:315] INFO: Configure the cluster network
[init.sh:133] INFO: Use flannel v0.14.0
[init.sh:136] INFO: Use configuration file from https://raw.githubusercontent.com/coreos/flannel/v0.14.0/Documentation/kube-flannel.yml
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
podsecuritypolicy.policy/psp.flannel.unprivileged created
clusterrole.rbac.authorization.k8s.io/flannel created
clusterrolebinding.rbac.authorization.k8s.io/flannel created
serviceaccount/flannel created
configmap/kube-flannel-cfg created
daemonset.apps/kube-flannel-ds created
[init.sh:145] INFO: Restart the CRI-O service due to https://github.com/kata-containers/tests/issues/4381
[init.sh:149] INFO: Wait for Flannel pods to show up
[init.sh:155] INFO: Wait for pod kube-flannel-ds-d5msl be ready
pod/kube-flannel-ds-d5msl condition met
[init.sh:319] INFO: Wait for system's pods be ready and running
kube-system   kube-apiserver-localhost.localdomain            1/1     Running   2          22s
kube-system   kube-controller-manager-localhost.localdomain   1/1     Running   2          14s
kube-system   etcd-localhost.localdomain                      1/1     Running   2          14s
kube-system   kube-scheduler-localhost.localdomain            1/1     Running   2          20s
kube-system   coredns-64897985d-7tmdh                         1/1     Running   0          7s
kube-system   coredns-64897985d-98cxc                         1/1     Running   0          7s
[init.sh:322] INFO: Create kata RuntimeClass resource
runtimeclass.node.k8s.io/kata created
[init.sh:33] INFO: Taint 'NoSchedule' is found. Untaint the node so pods can be scheduled.
node/localhost.localdomain untainted
INFO: Run tests
1..1
not ok 1 Running with postStart and preStop handlers
# (in test file k8s-attach-handlers.bats, line 29)
#   `kubectl wait --for=condition=Ready --timeout=$timeout pod $pod_name' failed
# INFO: k8s configured to use runtimeclass
# pod/handlers created
# error: timed out waiting for the condition on pods/handlers
# Name:         handlers
# Namespace:    default
# Priority:     0
# Node:         localhost.localdomain/192.168.122.185
# Start Time:   Mon, 14 Mar 2022 17:46:43 +0000
# Labels:       <none>
# Annotations:  <none>
# Status:       Pending
# IP:
# IPs:          <none>
# Containers:
#   handlers-container:
#     Container ID:
#     Image:          quay.io/sjenning/nginx:1.15-alpine
#     Image ID:
#     Port:           <none>
#     Host Port:      <none>
#     State:          Waiting
#       Reason:       ContainerCreating
#     Ready:          False
#     Restart Count:  0
#     Environment:    <none>
#     Mounts:
#       /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-rhcrd (ro)
# Conditions:
#   Type              Status
#   Initialized       True
#   Ready             False
#   ContainersReady   False
#   PodScheduled      True
# Volumes:
#   kube-api-access-rhcrd:
#     Type:                    Projected (a volume that contains injected data from multiple sources)
#     TokenExpirationSeconds:  3607
#     ConfigMapName:           kube-root-ca.crt
#     ConfigMapOptional:       <nil>
#     DownwardAPI:             true
# QoS Class:                   BestEffort
# Node-Selectors:              <none>
# Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
#                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
# Events:
#   Type     Reason                  Age               From               Message
#   ----     ------                  ----              ----               -------
#   Normal   Scheduled               90s               default-scheduler  Successfully assigned default/handlers to localhost.localdomain
#   Warning  FailedCreatePodSandBox  9s (x7 over 90s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = CreateContainer failed: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-x86_64: Error while loading elf kernel
# : unknown
# pod "handlers" deleted
[run_kubernetes_tests.sh:109] ERROR: bats k8s-attach-handlers.bats
INFO: Run the cleanup routine
[cleanup_env.sh:31] INFO: Reset Kubernetes
[reset] Reading configuration from the cluster...
[reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[preflight] Running pre-flight checks
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
[reset] Deleting contents of stateful directories: [/var/lib/etcd /var/lib/kubelet /var/lib/dockershim /var/run/kubernetes /var/lib/cni]

The reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d

The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually by using the "iptables" command.

If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.

The reset process does not clean your kubeconfig files and you must remove them manually.
Please, check the contents of the $HOME/.kube/config file.
[cleanup_env.sh:35] INFO: Teardown the registry server
[cleanup_env.sh:39] INFO: Stop crio service
[cleanup_env.sh:42] INFO: Remove network devices
[cleanup_env.sh:44] INFO: remove device: cni0
[cleanup_env.sh:44] INFO: remove device: flannel.1
[cleanup_env.sh:54] INFO: Check no kata processes are left behind after reseting kubernetes
[cleanup_env.sh:57] INFO: Checks that pods were not left
make: *** [Makefile:57: kubernetes] Error 1
[run.sh:62] ERROR: sudo -E PATH=/usr/local/go/bin:/home/vagrant/go/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin bash -c make kubernetes

```

**Comment by snir911** [comment]
@wainersm this is fishy, when i run it it passes this point (for me it fails on loop device permissions in other test), also the CI centos stream jobs are passing.
Any idea how could it be so inconsistent, my first guess would be it uses different qemu versions.. could you share kata-collect-data.sh ?
Is it possible the VM vagrant is creating is somehow different?

**Comment by wainersm** [comment]
@snir911 now it is failing with `no space left on device` :(

**Comment by snir911** [comment]
@wainersm disk size increased

**Review by c3d — APPROVED** [review]
Looks good to me.

Not entirely sure about the use case, though.

**Review by jodh-intel — APPROVED** [review]
Thanks @snir911.

lgtm

**Comment by jodh-intel** [comment]
@snir911 - if you remove the wip label, this can land.

**Comment by snir911** [comment]
@jodh-intel actually let's close this one as it's anyhow planned to drop centos in favor of other similar distribution (and it's already disabled by CI)
cc @wainersm

**Pull request closed without merging**
