### PR TITLE
CI: test adding codecov

### LINKED ISSUE #132: Add codecov to jenkins script
We need to update the CI script to allow us to move away from Travis.

See: https://github.com/kata-containers/tests/pull/103#issuecomment-369625173

Related: #104.

### PR DESCRIPTION
**Pull request by jodh-intel**
Test to see if codecov.io works without a token with Jenkins.

Fixes #132.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
lgtm

**Comment by grahamwhaley** [comment]
You hit the dreaded Travis range revision dea(r)th...
You'll have to say if the codecov on Jenkins worked or not - here is the output:
```
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-8b76995


==> Jenkins CI detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
```

**Comment by jodh-intel** [comment]
Hi @chavafg - is the `CODECOV_TOKEN` variable being set in the environment now? The docs for the codecov script I added on this PR show that it should automatically read that envvar:

- https://docs.codecov.io/docs/about-the-codecov-bash-uploader

So, as long as the CI sets `CODECOV_TOKEN` to the correct token value for a particular kata repo (they will all have different values), it should all "just work" (TM).

**Comment by chavafg** [comment]
Hi @jodh-intel, 

Yes, I have added `CODECOV_TOKEN` as an environment variable to this Job. 
I'll add other tokens to the other repos.

**Comment by chavafg** [comment]
I've just added the token to the other repositories.

**Comment by jodh-intel** [comment]
```
 _  __     _           ____            _        _                     
| |/ /__ _| |_ __ _   / ___|___  _ __ | |_ __ _(_)_ __   ___ _ __ ___ 
| ' // _` | __/ _` | | |   / _ \| '_ \| __/ _` | | '_ \ / _ \ '__/ __|
| . \ (_| | || (_| | | |__| (_) | | | | || (_| | | | | |  __/ |  \__ \
|_|\_\__,_|\__\__,_|  \____\___/|_| |_|\__\__,_|_|_| |_|\___|_|  |___/
                                                                      
  ____ ___                                _   _ 
 / ___|_ _|  _ __   __ _ ___ ___  ___  __| | | |
| |    | |  | '_ \ / _` / __/ __|/ _ \/ _` | | |
| |___ | |  | |_) | (_| \__ \__ \  __/ (_| | |_|
 \____|___| | .__/ \__,_|___/___/\___|\__,_| (_)
            |_|
```

Soz - couldn't resist it.

Well, clearly codecov is doing "something". However, we're not going to get much more on tests as we don't have tests for the tests...

Before we get into the [Quis custodiet ipsos custodes](https://en.wikipedia.org/wiki/Quis_custodiet_ipsos_custodes%3F) debate, I say we merge this and keep an eye on it once we've added the codecov tokens for the other repos.

**Comment by chavafg** [comment]
lgtm

**Comment by jcvenegas** [comment]
lgtm

**Pull request merged**
