### PR TITLE
CI: pin go linter version to avoid new lints failing PRs

### LINKED ISSUE #299: Pin gometalinter to avoid breakages
Currently, the static checks script `go get`'s `gometalinter`. The problem is, that project is constantly being updated and we're seeing a few PRs that are being failed due to newly introduced lint checks (that potentially were not present when the developer ran `static-checks.sh`).

Pin `gometalinter` to a known good version. Note that we'll need a process to ratchet up this version by pulling the latest code and running against all the kata repos.

### PR DESCRIPTION
**Pull request by jodh-intel**
Run a known version of `gometalinter` to avoid new lint tests from
breaking valid PRs.

Fixes #299.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
This is expected to fail the CI tests at this stage ;)

**Comment by jodh-intel** [comment]
Blocked on https://github.com/kata-containers/runtime/pull/305.

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/runtime/pull/301#issuecomment-388775526

**Comment by WeiZhang555** [comment]
This makes a lot of sense to me! Thanks!

Though CI is failed :-(

**Comment by jodh-intel** [comment]
Hi @WeiZhang555 - yes, the CI will fail until https://github.com/kata-containers/runtime/pull/305 lands since the tests CI cannot find the correct entry in the `versions.yaml` file for `gometalinter`.

**Comment by jodh-intel** [comment]
Hi @chavafg - ptal.

**Comment by chavafg** [comment]
lgtm

**Pull request merged**
