### PR TITLE
# Kata Containers 1.11.0-alpha1

### PR DESCRIPTION
**Pull request by bergwolf**
- clh: docker: Skip CPU hotplug test
- ci: Update setup script for SLES
- ci: Enable openSUSE Leap 15.1 CI
- ci: Bring back docker integration tests since yq v3.1
- ci: Set noninteractive on Ubuntu and Debian
- integration/docker: pull fedora 30 image before using it
- ci: Enable CPU hot-plug tests for cloud-hypervisor
- tests: e2e: Update Sonobuoy to 0.17.2
- spellcheck: Add master dict rebuild note
- Makefile: Run docker tests sequentially in CentOS 7
- test: Update package manager test for Fedora
- static_checks: fix `skip_paths` function
- test: Skip state functional test for Debian 10
- ci: static: markdown: make list var func local
- ci: Update build tools package dependency for openSUSE Leap
- ci: Update docker version for openSUSE and SLES
- ci: add libpmem as build dependency
- cri-o: fix netns mount point leaking from cri-o
- test: metrics: add virtiofsd to memory measure list
- versions: Update podman version to 1.8.0 and remove port nginx test
- spellcheck: add project works for EFK stack etc.
- test: enable k8s for clh
- ci: Do not install and run kubernetes on Fedora
- test: Enable more e2e podman tests

1e7fcc0 clh: docker: Skip CPU hotplug test
3e2ddd9 ci: Update setup script for SLES
93a29ca ci: Set noninteractive on Ubuntu and Debian
332b8aa ci: Bring back docker integration tests since yq v3.1
f296579 integration/docker: pull fedora 30 image before using it
575773b ci: Enable CPU hot-plug tests for cloud-hypervisor
a60ca3b spellcheck: Add master dict rebuild note
f5d8e3d ci: Enable openSUSE Leap 15.1 CI
4c18604 Makefile: Run docker tests sequentially in CentOS 7
9019fcf tests: e2e: Update Sonobuoy to 0.17.2
2d86678 test: Update package manager test for Fedora
bad3afc static_checks: fix skip_paths function
c289559 test: Skip state functional test for Debian 10
e1150e5 ci: Update build tools package dependency for openSUSE Leap
4ad1c2b ci: add libpmem as build dependency
4f42d4d ci: Update docker version for openSUSE and SLES
c34ea54 ci: static: markdown: make list var func local
2d28956 test: metrics: add virtiofsd to memory measure list
d1d0320 versions: Update podman version to 1.8.0 and remove port nginx test
38ef580 spellcheck: add project works for EFK stack etc.
fa5b6af test: cri: skip failing test for clh
1980cc6 test: k8s: skip faling test for clh.
41b7912 test: enable k8s for clh
ebf3909 cgroupfs: set cri-o cgroup manager with cgroupfs
8d8f979 test: Enable more e2e podman tests
4d3bf99 coredns: checking whether dns pod is ready
7d11c67 cri-o-runc: add BUILDTAGS
7ed6027 k8s: update kubeadm config to version v1beta2
6db55e4 ci: Do not install and run kubernetes on Fedora

### CODE REVIEW

**Comment by jodh-intel** [comment]
Another awkward one - the podman CI is failing:

```
14:51:39 No match for argument: podman-1.8.0
14:51:40 Error: Unable to find a match: podman-1.8.0
14:51:40 Failed at 21: sudo -E dnf -y install podman-"${version}"
```

It looks like the problem is that F31 is now using 1.8.1 so we need to update:

- https://github.com/kata-containers/tests/blob/master/versions.yaml#L68

/cc @chavafg, @GabyCT.

Also, I spotted the following error in the same log:

```
14:51:28 /tmp/jenkins/workspace/kata-containers-tests-podman-fedora-31-PR/go/src/github.com/kata-containers/tests/.ci/ci-fast-return.sh: line 447: exit: Last: numeric argument required
```

/cc @grahamwhaley

**Comment by GabyCT** [comment]
@bergwolf and @jodh-intel here it is the update of podman version
https://github.com/kata-containers/tests/pull/2390

**Comment by bergwolf** [comment]
`ARM-ubuntu-18-04` seems constantly failing. @Pennyzct any clue?

```
15:23:12 Install os-tree
15:23:13 Job for docker.service failed because the control process exited with error code.
15:23:13 See "systemctl status docker.service" and "journalctl -xe" for details.
15:23:13 Build step 'Execute shell' marked build as failure
15:23:13 Performing Post build task...
15:23:13 Match found for :.* : True
15:23:13 Logical operation result is TRUE
15:23:13 Running script  : #!/bin/bash
15:23:13 
```

**Comment by bergwolf** [comment]
well, per http://jenkins.katacontainers.io/job/kata-containers-tests-ARM-18.04-PR-firecracker/
`jenkins-ci-ARM-ubuntu-18-04` seems newly added yesterday. Is it expected to fail?

**Comment by Pennyzct** [comment]
yep, I add this new jenkins job http://jenkins.katacontainers.io/job/kata-containers-tests-ARM-18.04-PR-firecracker/ to test FC related tests on ARM. For now, it expects to fail other than PR https://github.com/kata-containers/tests/pull/2388
Emmmm, I don't know how to trigger it properly. here, it should trigeer http://jenkins.katacontainers.io/job/kata-containers-tests-ARM-18.04-PR.
And for the error, original installing fc method tried to modify `/etc/docker/daemon.json`, not systemd service file,  and will leave two configuration files on bare metal CI, which causing above error.

**Comment by bergwolf** [comment]
@Pennyzct Thanks for confirming! Then this PR can be merged IMO ignoring the ARM FC failure.

**Pull request merged**
