### PR TITLE
tracing: Fix or skip on s390x

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
tracing: Remove Jaeger container before starting

can be left over on permanent instances

---

tracing: Skip agent shutdown test on s390x

is unstable, see https://github.com/kata-containers/tests/issues/4597

Fixes: #4598

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
> thanks @Jakob-Naucke, could you please move all the disabled tests/conditions to the same section? There are others disabled in `setup` in `test-agent-shutdown.sh`.

Ah, thanks for the heads-up -- I'd missed those. Done.

> Also could you skip s390x in `tracing-test.sh` too?
> 
> (Unless you can fix it)

`tracing-test.sh` appears to work with the minor fix already given.

> /test-s390x
> 
> actually...does this trigger still work?

s390x has been disabled, but this is hopefully the last step. The keyword is `/debug-s390x`, but it didn't pull in the changes from the PR last time I checked.

**Review by cmaf — APPROVED** [review]

**Pull request merged**
