### PR TITLE
Checkcommits ignore release prs

### LINKED ISSUE #28: Sync checkcommits from Clear Containers repo
Once https://github.com/clearcontainers/tests/pull/861 lands, sync the `checkcommits` code in this repo.

### PR DESCRIPTION
**Pull request by jodh-intel**
Change the `checkcommits` config to not require an issue for release                       
PRs.                                       
                                               
Fixes #28.

### CODE REVIEW

**Comment by jodh-intel** [comment]
Well, that's good - Travis is failing due to one of the static tests `gocyclo` detecting an issue :)

Blocked on https://github.com/clearcontainers/tests/pull/869.

**Comment by chavafg** [comment]
clearcontainers/tests#869 now merged ;)

**Comment by jodh-intel** [comment]
Thanks @chavafg - branch updated, so this should now pass under Travis...

**Comment by jodh-intel** [comment]
Travis is happy. Just need 2 acks from @kata-containers/tests now ;)

**Comment by chavafg** [comment]
lgtm

**Pull request merged**
