### PR TITLE
Follow ups on the golang bump

### PR DESCRIPTION
**Pull request by fidencio**
Please, check each commit for more details.

### CODE REVIEW

**Comment by bergwolf** [comment]
`jenkins-ci-dragonball-ubuntu-20-04` has passed but it does not show up here.
http://jenkins.katacontainers.io/job/kata-containers-dragonball-tests-ubuntu-20.04-PR/191/

**Comment by liubin** [comment]
Hi @fidencio @bergwolf Now there is a hardcoded golangci-lint in static-checks.sh, so we need these patches too:

- https://github.com/kata-containers/tests/commit/026b3ae78db85c4865e466766d2bd2d29ca1d278
- https://github.com/kata-containers/tests/commit/54279ae424187261dc128348d5b2f0893277c230

**Comment by bergwolf** [comment]
@liubin Could you push the additional commits to `fidencio:topic/update-golangci-lint` to include them in the PR?

**Comment by fidencio** [comment]
> Hi @fidencio @bergwolf Now there is a hardcoded golangci-lint in static-checks.sh, so we need these patches too:
> 
> * [026b3ae](https://github.com/kata-containers/tests/commit/026b3ae78db85c4865e466766d2bd2d29ca1d278)
> * [54279ae](https://github.com/kata-containers/tests/commit/54279ae424187261dc128348d5b2f0893277c230)

Thanks @liubin, those have been added.

**Review by liubin — APPROVED** [review]

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
