### PR TITLE
CCv0: Merge `main` into `CCv0` branch

### PR DESCRIPTION
**Pull request by stevenhorsman**
Weekly merge of new commits in `main` into `CCv0`

Fixes: #4255

### CODE REVIEW

**Comment by stevenhorsman** [comment]
```
$ git diff --stat upstream/main -- . ':!*/vendor/*'
 .ci/configure_cni.sh                            |  2 +-
 .ci/install_cri_containerd.sh                   | 31 +++++++++++++++++++++++++++----
 .ci/install_kata_image.sh                       | 12 +++++++++---
 .ci/jenkins_job_build.sh                        |  6 ++++++
 .ci/lib.sh                                      |  8 ++++++++
 .ci/static-checks.sh                            | 13 ++++++++++---
 README.md                                       | 12 ++++++------
 cmd/github-labels/labels.yaml.in                |  4 ++--
 cmd/pmemctl/pmemctl.sh                          |  2 +-
 integration/containerd/cri/integration-tests.sh | 12 +++++++++---
 integration/kubernetes/e2e_conformance/setup.sh |  2 +-
 versions.yaml                                   |  2 +-
 12 files changed, 81 insertions(+), 25 deletions(-)
 ```

**Review by fidencio — APPROVED** [review]
lgtm, assuming the CI is happy!
thanks @stevenhorsman!

**Comment by stevenhorsman** [comment]
I believe the CI is failing as it requires the changes in https://github.com/kata-containers/kata-containers/pull/3210. You can see in that PR (which depends on this) that the CI passes with them both.
My understanding is that if both PRs depend on each other you get circular dependencies, so I didn't make the tests PR depend on kata-containers PR. Assuming this is correct, then I think in order to get the tests passing here I need to merge the kata-containers PR and then re-run the tests here. I hope that makes some sense?

**Comment by fidencio** [comment]
> I believe the CI is failing as it requires the changes in [kata-containers/kata-containers#3210](https://github.com/kata-containers/kata-containers/pull/3210). You can see in that PR (which depends on this) that the CI passes with them both. My understanding is that if both PRs depend on each other you get circular dependencies, so I didn't make the tests PR depend on kata-containers PR. Assuming this is correct, then I think in order to get the tests passing here I need to merge the kata-containers PR and then re-run the tests here. I hope that makes some sense?

It does make sense!  Let me merge the other one and retrigger the CI here.

**Comment by stevenhorsman** [comment]
@fidencio - thank you very much. You're a star as always!

**Pull request merged**
