### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by GeorginaKin**
Merge remote-tracking branch 'upstream/main' into CCv0

Fixes: #4970
Depends-on: github.com/kata-containers/kata-containers#4751

Signed-off-by: Georgina Kinge <georgina.kinge@ibm.com>

### CODE REVIEW

**Comment by GeorginaKin** [comment]
```
git diff --stat upstream/main -- . ':!*/vendor/*'
 .ci/ci_job_flags.sh                                                                       |  38 +++++++++----
 .ci/configure_cni.sh                                                                      |   2 +-
 .ci/install_cri_containerd.sh                                                             |  26 ++++++++-
 .ci/install_kata_image.sh                                                                 |  12 +++-
 .ci/jenkins_job_build.sh                                                                  |   6 ++
 .ci/lib.sh                                                                                |   8 +++
 .ci/resolve-kata-dependencies.sh                                                          |  42 +++++++-------
 .ci/run.sh                                                                                |  24 +++++---
 .ci/static-checks.sh                                                                      |   8 ++-
 .github/workflows/commit-message-check.yaml                                               |   2 +-
 Makefile                                                                                  |  15 +++--
 README.md                                                                                 |  10 ++--
 cmd/github-labels/labels.yaml.in                                                          |   4 +-
 cmd/pmemctl/pmemctl.sh                                                                    |   2 +-
 functional/kata-monitor/run.sh                                                            |   1 +
 integration/confidential/fixtures/quay_verification/public.gpg                            |  30 ++++++++++
 integration/confidential/fixtures/quay_verification/quay_policy.json                      |  18 ++++++
 integration/confidential/fixtures/quay_verification/signatures.tar                        | Bin 0 -> 2157 bytes
 integration/confidential/fixtures/registries.d/quay.io.yaml                               |   4 ++
 integration/confidential/lib.sh                                                           | 191 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 integration/containerd/confidential/agent_api.bats                                        |  72 ++++++++++++++++++++++++
 integration/containerd/confidential/agent_image.bats                                      | 103 ++++++++++++++++++++++++++++++++++
 integration/containerd/confidential/asserts.sh                                            |  68 +++++++++++++++++++++++
 integration/containerd/confidential/fixtures/agent-configuration-no-exec.toml             |  46 +++++++++++++++
 integration/containerd/confidential/fixtures/container-config.yaml                        |  11 ++++
 integration/containerd/confidential/fixtures/container-config_signed-protected-other.yaml |  11 ++++
 integration/containerd/confidential/fixtures/container-config_unsigned-protected.yaml     |  11 ++++
 integration/containerd/confidential/fixtures/container-config_unsigned-unprotected.yaml   |  11 ++++
 integration/containerd/confidential/fixtures/pod-config.yaml.in                           |  12 ++++
 integration/containerd/confidential/lib.sh                                                | 163 +++++++++++++++++++++++++++++++++++++++++++++++++++++
 integration/containerd/confidential/run_tests.sh                                          |  21 +++++++
 integration/containerd/confidential/tests_common.sh                                       | 105 +++++++++++++++++++++++++++++++++++
 integration/containerd/cri/integration-tests.sh                                           |  14 ++++-
 integration/kubernetes/confidential/agent_image.bats                                      | 130 +++++++++++++++++++++++++++++++++++++++++++
 integration/kubernetes/confidential/agent_image_encrypted.bats                            |  65 ++++++++++++++++++++++
 integration/kubernetes/confidential/fixtures/pod-config.yaml                              |  14 +++++
 integration/kubernetes/confidential/fixtures/pod-config_signed-protected-other.yaml       |  14 +++++
 integration/kubernetes/confidential/fixtures/pod-config_unsigned-protected.yaml           |  14 +++++
 integration/kubernetes/confidential/fixtures/pod-config_unsigned-unprotected.yaml         |  14 +++++
 integration/kubernetes/confidential/lib.sh                                                | 161 +++++++++++++++++++++++++++++++++++++++++++++++++++++
 integration/kubernetes/e2e_conformance/setup.sh                                           |   2 +-
 integration/nydus/nydus-sandbox.yaml                                                      |   1 +
 integration/nydus/nydus_tests.sh                                                          |   2 +
 lib/common.bash                                                                           | 127 ++++++++++++++++++++++++++++++++++++++++++
 versions.yaml                                                                             |   2 +-
 45 files changed, 1574 insertions(+), 63 deletions(-)
```

**Comment by GeorginaKin** [comment]
We’re seeing failures with both Kubernetes integration tests with the error: 
```
11:43:32 Failed at 672: CC= cargo build --release --target "${target}" --no-default-features --features "${AA_KBC}"
11:43:32 ++ echo 'Failed at 672: CC= cargo build --release --target "${target}" --no-default-features --features "${AA_KBC}"'
11:43:32 ++ exit 101
11:43:32 ++ error_handler
11:43:33 ++ '[' 101 -eq 0 ']'
11:43:33 ++ '[' -n '' ']'
11:43:33 + after_stopping_container
11:43:33 + return 0
11:43:33 make: *** [Makefile:93: /tmp/jenkins/workspace/kata-containers-CCv0-ubuntu-20.04-x86_64-CC_CRI_CONTAINERD_K8S-PR/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/.ubuntu_rootfs.done] Error 101
11:43:33 [install_kata_image.sh:52] ERROR: sudo -E USE_DOCKER=1 DISTRO=ubuntu AA_KBC=offline_fs_kbc UMOCI=yes make -e image
11:43:33 [install_kata.sh:34] ERROR: .ci/install_kata_image.sh 
11:43:33 [jenkins_job_build.sh:223] ERROR: ci/setup.sh
```

Unsure of why this is at the moment but there are only a handful of commits that have gone in with this week’s merge.

**Comment by wainersm** [comment]
> Hi @GeorginaKin !
> 
> Ryan Savino (AMD) told about that build problem yesterday. I turns out to be the attestation-agent which fails to be built with Rust 1.58.1. According to him the version 1.62 builds attestation-agent just fine, he is working on the bump of version on main branch then we can pick it to CCv0.

The issue: https://github.com/kata-containers/kata-containers/issues/4764

**Review by stevenhorsman — APPROVED** [review]
The code changes look good to me and I can see that the tests are all passing now that the rust bump as been added to the dependant PR. Thanks!

**Pull request merged**
