### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by Megan-Wright**
Merge remote-tracking branch 'upstream/main' into CCv0
    
Fixes: #4853
Depends-on: github.com/kata-containers/kata-containers#4461
    
Signed-off-by: Megan Wright <megan.wright@ibm.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Megan-Wright!

**Comment by fidencio** [comment]
@Megan-Wright, you better wait till https://github.com/kata-containers/tests/pull/4852 gets merged then you do the rebase, as it'll ensure we have merged in a fix that is currently blocking the `kata-containers` PR.

**Comment by Megan-Wright** [comment]
@fidencio I think I've merged the snap fix in now so I think we are ready to merge this PR once the tests have passed?

**Comment by fidencio** [comment]
> @fidencio I think I've merged the snap fix in now so I think we are ready to merge this PR once the tests have passed?

Yep, we can go ahead and merge this one as soon as we have green tests.
We need to merge this one before merging the one in the kata-containers repo then.

Thanks for the work here, @Megan-Wright!

**Comment by fidencio** [comment]
Ah, also, please, rebase the kata-containers PR as that also depends on a snap fix in order to have the CI green.

**Pull request merged**
