### PR TITLE
ci: Fix SLES CI

### LINKED ISSUE #2380: fix sles ci

### PR DESCRIPTION
**Pull request by GabyCT**
This PR performs modifications in order to fix the SLES
CI setup scripts.

Fixes #2380

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @GabyCT - please can you update and this branch is now conflicted.

**Comment by GabyCT** [comment]
@jodh-intel rebase applied :)

**Pull request merged**
