### PR TITLE
ci: don't setup kata environment for unit test and snap test

### PR DESCRIPTION
**Pull request by jongwu**
setup.sh will do lots of work, including install runtime kata-image, which
take a long time. But it isn't needed in unit test and snap build test,
thus, move it into "run_main_test".

Fixes: #5024
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Comment by GabyCT** [comment]
@jongwu ARM is failing with
```
14:55:07 Install rust 1.62.0
14:55:07 info: downloading installer
14:55:07 error: could not amend shell profile: '/home/jenkins/.profile': could not write rcfile file: '/home/jenkins/.profile': Permission denied (os error 13)
14:55:08 [install_rust.sh:23] ERROR: sh -s -- -y --default-toolchain 1.62.0
14:55:08 ~/workspace/kata-containers-2.0-tests-ubuntu-ARM-PR/go/src/github.com/kata-containers/kata-containers/src/tools/agent-ctl ~/workspace/kata-containers-2.0-tests-ubuntu-ARM-PR/go/src/github.com/kata-containers/tests
14:55:08 ../../../utils.mk:160: "WARNING: aarch64-musl needs extra symbols from libgcc"
14:55:08 /bin/sh: 1: cargo: not found
```

**Review by cmaf — APPROVED** [review]

**Comment by jongwu** [comment]
Thanks @GabyCT -, I think that grant the R+W permission to Jenkins user will fix it.

**Pull request merged**
