### PR TITLE
ci: do not run docker/cri-o tests if TEST_DOCKER/TEST_CRIO are not true 

### PR DESCRIPTION
**Pull request by chavafg**
do not run `cri-o` tests if `TEST_CRIO` is not true
do not run `docker` tests if `TEST_DOCKER` is not true

This behavior will only be valid when running under CI.
When running `make test` without `CI=true`, docker and
cri-o will always run.

Fixes: #1686.

### CODE REVIEW

**Comment by chavafg** [comment]
btw, I've added the envars on each of the jenkins jobs (tired...), so the executions here should already reflect the changes...

**Comment by grahamwhaley** [comment]
Great. silly question - did we/do we/sometime need to update the CI test matrix table to reflect the changes?

**Comment by chavafg** [comment]
@grahamwhaley yeah we need to, I'll do that, thanks for the reminder.

**Pull request merged**
