### PR TITLE
golangci-lint: fix `invalid pseudo-version` error on ARM CI

### PR DESCRIPTION
**Pull request by Pennyzct**
With golang updated to v1.13, we found golangci-lint build error on ARM CI.
```
08:55:44 go build -o golangci-lint ./cmd/golangci-lint
08:55:49 go: github.com/go-critic/go-critic@v0.0.0-20181204210945-ee9bf5809ead: invalid pseudo-version: does not match version-control timestamp (2019-02-10T22:04:43Z)
```
Taking advices here(https://github.com/filecoin-project/go-filecoin/issues/3486#issuecomment-534858459), we need to update `golangci-lint` to `v1.18.0` to get Go `1.13` support.

Fixes: #2434

Signed-off-by: Penny Zheng <penny.zheng@arm.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Theory l g t m - Travis not happy though:
```
go: finding gopkg.in/gemnasium/logrus-airbrake-hook.v2 v2.1.2
go: error loading module requirements
Makefile:107: recipe for target 'go.mod' failed
make: *** [go.mod] Error 1
The command "bash .ci/static-checks.sh github.com/kata-containers/tests" exited with 2.
```

**Comment by GabyCT** [comment]
@Pennyzct there is an issue with travis

**Comment by Pennyzct** [comment]
Hi~~ guys @grahamwhaley @jodh-intel @chavafg @GabyCT 
I've found the reason why travis ci failed. 
Since we updated go to `v1.13.x`, the go in travis ci testing environment should also follow this update. 
I see, originally, we use script `bash .ci/install_go.sh -p -f` to forcefully update the go version in travis. But this method definitely missed something somewhere, and led travis failed before.
I've tried another method, just specifying go version in `.travis.yml` and the travis is happy now~~~

**Comment by jodh-intel** [comment]
Thanks for investigating @Pennyzct !

Looking at the raw Travis log, it is installing go1.13.9 whereas `.ci/install_go.sh` would be installing version 1.13.8:

- https://github.com/kata-containers/runtime/blob/master/versions.yaml#L305

Unfortunately, it's isn't very obvious what changed between those two revisions:

- https://github.com/golang/go/releases

@GabyCT, @chavafg, @jcvenegas - We could try updating `versions.yaml` to `1.13.9` to see if that unbreaks `.ci/install_go.sh` maybe? Or maybe updated to 1.41.1 which is now out :smile:

**Comment by grahamwhaley** [comment]
@chavafg @Pennyzct - so, is this a DNM, or a good to go, or ? :-)

**Comment by Pennyzct** [comment]
Hi guys @grahamwhaley @chavafg @jodh-intel you may misunderstand what I said before.
Sorry for the ambiguous explanation. 
I'm saying that in previous `travis.yml`, we only defined the language with `golang`, not giving it a specific version number.
```
language: go
```
So it would use `go 1.11.x` as default option, you could see following job log in any other travis run
https://travis-ci.org/github/kata-containers/tests/jobs/671941103#L185
```
$ travis_setup_go
go version go1.11.13 linux/amd64
```
And with kata updating golang to `v1.13.x`, we may need to update the go compiler in travis to the same version too.
Originally, we used script `.ci/install_go.sh -p -f` in travis to do the work. 
```
before_install:
  - bash .ci/install_go.sh -p -f	
```
But this method definitely missed something somewhere(I dunno😂), and led travis failed before.
```
go: finding gopkg.in/gemnasium/logrus-airbrake-hook.v2 v2.1.2
go: error loading module requirements
Makefile:107: recipe for target 'go.mod' failed
make: *** [go.mod] Error 1
The command "bash .ci/static-checks.sh github.com/kata-containers/tests" exited with 2.
```
So I switch to just define go version in `travis.yaml` to do the update. See, 
```
language: go
go:
  - 1.13.x
```

**Comment by Pennyzct** [comment]
Hi @chavafg 
If you guys agree with my new go version update method, we need to update `tavis.yml` in other repoes. ;)

**Comment by chavafg** [comment]
@Pennyzct I'll open a PR in runtime following @jodh-intel suggestion to update our versions.yaml to 1.13.9 and see if that fixes the issue without changing the travis.yaml. If this do not help, I think that yes, we would need to go and update travis files in all other repos.

I remember that we removed the go version from travis and use our `.ci/install_go.sh -p -f` to reduce the maintenance in the travis files across all repos.

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/agent/pull/752#issuecomment-610397937.

In summary, I think we need to update the go lint version.

**Comment by chavafg** [comment]
Added a `Depends-on` on my runtimes' PR that updates golang to 1.13.9 making reference to this, but in travis this does not have any effect, so we really don't know if we will be fine. 

@jodh-intel to unlock arm CI, I think we can merge this change and then take a look at if we need to really update all travis files or if updating golang in our versions.yaml will be enough, wdyt?

**Comment by jodh-intel** [comment]
@chavafg - agreed.

**Pull request merged**
