### PR TITLE
tests: Remove leftovers of the docker integration tests

### LINKED ISSUE #4223: remove docker integration tests

### PR DESCRIPTION
**Pull request by wainersm**
On commit 98db058b it was removed the docker integration tests. There are some
files/configurations left behind which are removed on this commit.

Fixes #4223
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

### CODE REVIEW

**Comment by wainersm** [comment]
Hi @GabyCT ! While working on another PR I found what seems leftovers of https://github.com/kata-containers/tests/commit/98db058b63122fa12d3a691380744d5629aef029 . If they are still used somewhere then please close this PR and sorry :)

**Comment by GabyCT** [comment]
The failure is related with https://github.com/kata-containers/tests/issues/4285

**Review by fidencio — APPROVED** [review]
lgtm, thanks @wainersm!

**Pull request merged**
