### PR TITLE
data: add rpm packages public signing key

### PR DESCRIPTION
**Pull request by marcov**
The key shall be used during the automated installation of packages, to
enforce key verification without skipping the gpg checks.

Fixes: #824

Signed-off-by: Marco Vedovati <mvedovati@suse.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by marcov** [comment]
mmhh, what do?
```
INFO: Checking for SPDX license headers
ERROR: Required license identifier ('SPDX-License-Identifier: Apache-2.0') missing from following files:
```

**Comment by grahamwhaley** [comment]
arf!
well, apparently you could add a comment line starting with '#' and add the copyright in (although adding a copyright to a key feels somewhat odd....). The other option is to update the checking script to skip pub keys - it has a list of things not to check iirc.

**Comment by jodh-intel** [comment]
I'll update the checking script...

**Comment by jodh-intel** [comment]
Blocked on #827.

**Comment by jodh-intel** [comment]
@marcov - #827 is merged so if you re-push, this should work now...

**Comment by jodh-intel** [comment]
This PR adds a single file which has nothing to do with metrics, so merging...

**Pull request merged**
